function la(e){var h=0;return function(){return h<e.length?{done:!1,value:e[h++]}:{done:!0}}}var ma=typeof Object.defineProperties=="function"?Object.defineProperty:function(e,h,l){if(e==Array.prototype||e==Object.prototype)return e;e[h]=l.value;return e};
function Ua(e){e=["object"==typeof globalThis&&globalThis,e,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var h=0;h<e.length;++h){var l=e[h];if(l&&l.Math==Math)return l}throw Error("Cannot find global object");}var Va=Ua(this);function Wa(e,h){if(h)a:{var l=Va;e=e.split(".");for(var t=0;t<e.length-1;t++){var m=e[t];if(!(m in l))break a;l=l[m]}e=e[e.length-1];t=l[e];h=h(t);h!=t&&h!=null&&ma(l,e,{configurable:!0,writable:!0,value:h})}}
Wa("Symbol",function(e){function h(v){if(this instanceof h)throw new TypeError("Symbol is not a constructor");return new l(t+(v||"")+"_"+m++,v)}function l(v,S){this.i=v;ma(this,"description",{configurable:!0,writable:!0,value:S})}if(e)return e;l.prototype.toString=function(){return this.i};var t="jscomp_symbol_"+(Math.random()*1E9>>>0)+"_",m=0;return h});
Wa("Symbol.iterator",function(e){if(e)return e;e=Symbol("Symbol.iterator");ma(Array.prototype,e,{configurable:!0,writable:!0,value:function(){return Xa(la(this))}});return e});function Xa(e){e={next:e};e[Symbol.iterator]=function(){return this};return e}function Ya(e,h){e instanceof String&&(e+="");var l=0,t=!1,m={next:function(){if(!t&&l<e.length){var v=l++;return{value:h(v,e[v]),done:!1}}t=!0;return{done:!0,value:void 0}}};m[Symbol.iterator]=function(){return m};return m}
Wa("Array.prototype.values",function(e){return e?e:function(){return Ya(this,function(h,l){return l})}});
(function(){function e(a){try{return!(!a||a.IsValid&&!a.IsValid())}catch(b){}return!1}function h(){for(var a=$.GetContextPanel();a&&a.GetParent&&a.GetParent();)a=a.GetParent();a=a||null;a!==T&&(T=a,A=null,na=0,U=V=null,oa="",B=C=F=null,pa(),m("root",{id:qa(a)||"",j:!0}));return T}function l(){try{if(typeof GameUI!=="undefined"&&GameUI&&GameUI.CustomUIConfig)return GameUI.CustomUIConfig()}catch(a){}return null}function t(){var a=l();try{return!(!a||!a.__hpColorsPresetDebug)}catch(b){}return!1}function m(a,
b){if(t()){var c="";try{c=b?JSON.stringify(b):""}catch(d){c=String(b||"")}if(Ea[a]!==c){Ea[a]=c;a="[HP_COLORS_MINIMAL_PRESET] "+a+(c?" "+c:"");try{if(typeof $!=="undefined"&&$&&$.Msg){$.Msg(a);return}}catch(d){}try{typeof console!=="undefined"&&console&&console.log&&console.log(a)}catch(d){}}}}function v(a){return a?a.id+":"+a.heroMode+":"+(a.heroes&&a.heroes.length?a.heroes.join(","):"*"):""}function S(a,b){try{if(a&&a.FindChildrenWithClassTraverse){var c=a.FindChildrenWithClassTraverse(b)||[];if(c.length)return c[0]}}catch(d){}return null}
function Fa(){var a=G();if(!e(A)||a-na>1E3){if(!e(A)){var b=h(),c=Ga(b,"TopBar");A=S(c,"GameTime")||S(b,"GameTime")}na=a}if(!e(A))return-1;a="";try{a=A.text||A.GetAttributeString("text","")||""}catch(d){}a=(a=String(a||"").replace(/^\s+|\s+$/g,""))?(a=a.match(/\d+/g))&&a.length?a.length===1?Number(a[0])||0:(Number(a[0])||0)*60+(Number(a[1])||0):-1:-1;return a}function pa(){M=!1;ra=W=""}function Ha(){if(M||!X||Fa()<10)return!1;M=!0;W=X;ra=Y||"";x=!1;return!0}function G(){try{if(Date&&Date.now)return Date.now()}catch(a){}return+new Date}
function D(a,b,c,d,f,n){Z=a;X=b?b.id:"";Y=c||"";Ia=!!n;m("select",{reason:a,preset:v(b),hero:c||"",allow_unknown_fallback:!!d,u:f||0,m:!!n});return b}function Ja(a){return String(a||"").toLowerCase().replace(/[^a-z0-9_]+/g,"_").replace(/^_+|_+$/g,"")}function aa(a,b){(a=Ja(a))&&!Object.prototype.hasOwnProperty.call(H,a)&&(H[a]=b,N.push({g:a,hero:b,token:a.replace(/^hero_/,"")}))}function sa(a){var b=[];Array.isArray(a)?b=a:typeof a==="string"?b=a.split(/[,|;]/):a&&(b=[a]);a={};for(var c=[],d=0;d<
b.length;d+=1){var f;(f=(f=Ja(b[d]))?Object.prototype.hasOwnProperty.call(H,f)?H[f]:f.indexOf("hero_")!==0&&Object.prototype.hasOwnProperty.call(H,"hero_"+f)?H["hero_"+f]:"":"")&&!a[f]&&(a[f]=!0,c.push(f))}return c}function qa(a){try{return a&&a.id?String(a.id):""}catch(b){}return""}function Ga(a,b){try{return a&&a.FindChildTraverse?a.FindChildTraverse(b):null}catch(c){}return null}function ta(a,b,c){a:{try{var d=a&&a.Children?a.Children():[];break a}catch(k){}d=[]}a=null;for(var f=0;f<d.length;f+=
1){var n=d[f];if(qa(n)===b&&(a||(a=n),!c||c(n)))return n}return a}function ba(a){if(!e(a))return"";for(var b=0;b<N.length;b+=1){a:{try{var c=!!(a&&a.BHasClass&&a.BHasClass(N[b].g));break a}catch(d){}c=!1}if(c)return N[b].hero}return""}function Za(a){return!!ba(ta(a,"progress",ba))}function $a(){var a=h();if(!e(a))return null;e(F)||(F=Ga(a,"gameplay_hud_alive"),B=C=null);if(!e(F))return null;a=ta(F,"crosshair",Za);a!==C&&(C=a,B=null);if(!e(C))return null;a=ta(C,"progress",ba);a!==B&&(B=a);return e(B)?
B:null}function Ka(){var a=$a(),b=ba(a);m("detect",{hero:b||"",root:qa(T)||"",alive:e(F),crosshair:e(C),progress:e(a)});return b}function ca(a){try{return $.DispatchEvent("ClientUI_FireOutput",a),!0}catch(b){}return!1}function ua(a){if(!a)return!1;var b=!1,c=!1,d=l();if(d)try{d.__hpColorsCfgRaw!==a&&(d.__hpColorsCfgRaw=a),b=!0}catch(f){}d=h();try{e(d)&&d.SetAttributeString&&(d.GetAttributeString&&d.GetAttributeString("hp_colors_minimal_cfg_raw","")===a||d.SetAttributeString("hp_colors_minimal_cfg_raw",
a),c=!0)}catch(f){}b&&(O=!0);c&&(P=!0);(va=O||P)&&m("shared-write",{gameui:b,root_attr:c,gameui_ready:O,root_ready:P,raw_length:a.length});return b||c}function La(a){try{if(typeof a.text==="string")return a.text}catch(b){}try{if(a.GetAttributeString)return a.GetAttributeString("text","")}catch(b){}return""}function Ma(a){try{if(a&&a.id!==void 0)return String(a.id||"")}catch(b){}try{if(a&&a.GetAttributeString)return String(a.GetAttributeString("id","")||"")}catch(b){}return""}function ab(a){function b(g){if(g===
void 0||g==="")return 0;if(!Object.prototype.hasOwnProperty.call(c,g))throw Error("bad base64url");return c[g]}for(var c={},d=0;d<64;d+=1)c["ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_"[d]]=d;d=[];for(var f=0;f<a.length;f+=4){var n=b(a[f]),k=b(a[f+1]),q=a[f+2]!==void 0?b(a[f+2]):0,p=a[f+3]!==void 0?b(a[f+3]):0;d.push(n<<2|k>>4);a[f+2]!==void 0&&d.push((k&15)<<4|q>>2);a[f+3]!==void 0&&d.push((q&3)<<6|p)}a="";for(f=0;f<d.length;f+=1)n=d[f],n<128?a+=String.fromCharCode(n):n<224?
a+=String.fromCharCode((n&31)<<6|d[++f]&63):(k=d[++f],q=d[++f],a+=String.fromCharCode((n&15)<<12|(k&63)<<6|q&63));return a}function Na(){var a=h();if(!a||!a.FindChildTraverse)return[];var b=e(V)?V:null;if(!b){try{b=a.FindChildTraverse("HPColorsPresetStore")}catch(Oa){}V=e(b)?b:null}if(!b)return[];a=[];try{b.FindChildrenWithClassTraverse&&(a=b.FindChildrenWithClassTraverse("hp_colors_preset_entry")||[])}catch(Oa){}b=String(a.length);for(var c=0;c<a.length;c+=1)b+="|"+Ma(a[c])+":"+La(a[c]);if(U&&oa===
b)return U;c=[];for(var d=0;d<a.length;d+=1)try{var f=Ma(a[d]),n=La(a[d]);if(n){var k=JSON.parse(ab(n));if(k&&typeof k==="object"){var q=Number(k.version!==void 0?k.version:k.v);var p=void 0,g=k.values||k.vals||k.vs;if(g&&typeof g==="object"){var r={},w=!1;for(p in g)if(Object.prototype.hasOwnProperty.call(g,p)){var da=bb[p]||p;String(da).indexOf("hp_")===0&&(r[da]=g[p],w=!0)}var wa=w?r:null}else wa=null;if(q!==1&&q!==97||!wa)var y=null;else{var ea=sa(k.heroes||k.hs||k.hero||k.h);p=ea;var z=String(k.heroMode||
k.hm||"").toLowerCase();var fa=z==="off"||z==="disabled"||z==="none"?"off":z==="all"||z==="global"?"all":z==="selected"||z==="heroes"||z==="hero"?sa(p).length?"selected":"off":sa(p).length?"selected":"all";fa!=="selected"||ea.length||(fa="off");fa!=="selected"&&(ea=[]);y={values:wa,heroes:ea,heroMode:fa}}}else y=null;if(y){if(y.heroMode==="off")if(a.length===1&&f==="HPColorsPreset_001")y.heroMode="all",m("single-startup-off-compat",{id:f});else continue;c.push({id:f,values:y.values,heroes:y.heroes,
heroMode:y.heroMode})}}}catch(Oa){}oa=b;U=c;t()&&m("store",{entries:a.length,B:c.length,A:c.map(v)});return c}function xa(a,b){if(!a||!b||a.heroMode!=="selected"||!Array.isArray(a.heroes))return!1;for(var c=0;c<a.heroes.length;c+=1)if(a.heroes[c]===b)return!0;return!1}function cb(a){if(!a)return null;for(var b=Na(),c=0;c<b.length;c+=1)if(xa(b[c],a))return b[c];return null}function db(a){if(u)return!0;if(ha)var b=ha;else{b:{var c=!!a;var d=Na();if(d.length===1)c=D("single-valid-preset",d[0],"",c,d.length,
!1);else{var f=null,n=null;Fa()===0&&pa();for(var k=null,q=null,p=!1,g=0;g<d.length;g+=1){var r=d[g];n||(n=r);!k&&r&&r.heroMode==="all"&&(k=r);r.heroMode==="selected"&&(p=!0);r.id==="HPColorsPreset_001"&&(f=r)}if(M&&W){for(g=0;g<d.length;g+=1)if(d[g].id===W){c=D("locked-hero-selection",d[g],ra,c,d.length,p);break b}pa()}g=p?Ka():"";for(r=0;g&&r<d.length;r+=1)if(xa(d[r],g)){q=d[r];break}g&&q?c=D("selected-hero-match",q,g,c,d.length,p):!p||g||c?(!(q=!f)&&(q=g)&&(q=f,q=!(q&&q.heroMode==="all"||xa(q,
g))),c=q?k?D("first-global-fallback",k,g,c,d.length,p):D("first-enabled-fallback",n,g,c,d.length,p):D(g?"compatible-startup":"unknown-hero-startup-fallback",f,g,c,d.length,p)):c=D("wait-unknown-hero",null,"",c,d.length,p)}}if(c&&c.values){c=c.values;d={};for(b in c||{})Object.prototype.hasOwnProperty.call(c,b)&&(d[b]=c[b]);Object.prototype.hasOwnProperty.call(d,"hp_counter_visible")||(d.hp_counter_visible=!0);for(var w in ya)Object.prototype.hasOwnProperty.call(ya,w)&&(d[w]=ya[w]);b=ha=d}else b=null}if(!b)return!1;
w="";try{w=JSON.stringify(b)}catch(da){return!1}try{u=JSON.stringify({magic_word:"HP_COLORS_PRESET_SNAPSHOT",mod_title:"HP Colors",version:1,values_raw:w,values:b,update_source:"builder_static"})}catch(da){return u="",!1}Q=w;m("capture",{allow_unknown_fallback:!!a,raw_length:w.length,hp_team_colors:b.hp_team_colors,hp_color_low:b.hp_color_low,hp_mode:b.hp_mode,hp_skip_buildings:b.hp_skip_buildings,hp_counter_visible:b.hp_counter_visible,hp_friend_enabled:b.hp_friend_enabled,hp_friend_color_low:b.hp_friend_color_low,
hp_friend_color_mid:b.hp_friend_color_mid,hp_friend_color_high:b.hp_friend_color_high,hp_friend_pulse_enabled:b.hp_friend_pulse_enabled});Ha();return!0}function za(a){if(!db(a))return!1;a=ua(Q);!E&&u&&(E=!0,Aa());var b=ca(u);!Ia||Y||Z!=="unknown-hero-startup-fallback"&&Z!=="first-global-fallback"&&Z!=="first-enabled-fallback"||eb();return b||a}function Pa(a){return u&&O&&P?!0:u?(a=ua(Q),!E&&u&&(E=!0,Aa()),ca(u)||a||va):za(a)}function Aa(){var a=G();I=x||a<ia||R&&a-R<1500||J<3?1:J<12?3:8;(J<=1||I!==
Qa)&&m("replay",{l:J,interval:I,o:!!x});Qa=I;try{K=$.Schedule(I,fb)}catch(b){K=null,E=!1}}function fb(){K=null;u?(J+=1,ca(u),Aa()):E=!1}function gb(a){if(typeof a!=="string"||a.indexOf("HP_COLORS_PRESET_REQUEST")!==-1)try{var b=typeof a==="string"?JSON.parse(a):a;if(b&&b.magic_word==="HP_COLORS_PRESET_REQUEST"&&(!b.mod_title||b.mod_title==="HP Colors"))if(u){var c=G();R&&c-R<250||(R=c,ia=c+1500,ca(u),ua(Q))}else za(!0)}catch(d){}}function Ra(a){if(x)if(M||Ha())x=!1;else{var b=Ka(),c=cb(b);m("probe",
{index:a,hero:b||"",preset:v(c)});if(c){if(K)try{$.CancelScheduled&&$.CancelScheduled(K)}catch(d){}K=null;E=!1;ha=null;Q=u="";P=O=va=!1;J=0;I=1;ia=G()+1E4;if(za(!1)){x=!1;m("probe-stop",{reason:"selected-hero-match",hero:Y||b,preset:X||c.id});return}}b&&b===Ba?L+=1:(Ba=b||"",L=b?1:0);b||(L=0);if(b&&!c&&L>=2)x=!1,m("probe-stop",{reason:"known-hero-no-scoped-preset",hero:b,stable_count:L});else if(a+1>=ja.length)x=!1,m("probe-stop",{reason:"bounded-timeout",hero:b||""});else try{$.Schedule(ja[a+1],
function(){Ra(a+1)})}catch(d){}}}function eb(){if(!Sa&&!x){x=Sa=!0;Ba="";L=0;ia=G()+1E4;m("probe-start",{retries:ja.length});try{$.Schedule(ja[0],function(){Ra(0)})}catch(a){}}}var Ca=[.1,.5,1,2.5,5,8],ja=[2,4,6,8,12,16,20,24],ya={},Da={hp_enabled:"e",hp_mode:"m",hp_low_threshold:"l",hp_high_threshold:"h",hp_bg_visible:"b",hp_team_colors:"t",hp_info_health_margin_top:"ihmt",hp_healthbar_height:"hbh",hp_color_low:"cl",hp_color_mid:"cm",hp_color_high:"ch",hp_counter_visible:"cv",hp_counter_size:"s",
hp_counter_position:"p",hp_text_color_mode:"tm",hp_level_number_visible:"lnv",hp_pip_visible:"plv",hp_ult_color_enabled:"uce",hp_ult_color_custom:"ucc",hp_text_color_low:"tl",hp_text_color_mid:"ti",hp_text_color_high:"th",hp_pulse_bpm:"bp",hp_pulse_intensity:"pi",hp_pulse_enabled:"pe",hp_pulse_text_enabled:"pte",hp_pulse_text_scale:"pts",hp_pulse_text_position:"ptp",hp_pulse_hide_bar:"phb",hp_pulse_color_enabled:"pce",hp_pulse_color:"pc",hp_pulse_color_mode:"pcm",hp_skip_buildings:"sb",hp_pulse_threshold:"pt",
hp_friend_enabled:"fe",hp_friend_pulse_enabled:"fpe",hp_friend_pulse_bpm:"fpb",hp_friend_pulse_intensity:"fpi",hp_friend_pulse_threshold:"fpt",hp_friend_color_low:"fcl",hp_friend_color_mid:"fcm",hp_friend_color_high:"fch",hp_friend_pulse_color_enabled:"fpce",hp_friend_pulse_color:"fpc",hp_kill_zone_enabled:"kze",hp_kill_zone_threshold:"kzt",hp_kill_zone_color:"kzc",hp_kill_zone_width:"kzw",hp_counter_format:"cf"},bb=function(){var a={},b;for(b in Da)Object.prototype.hasOwnProperty.call(Da,b)&&(a[Da[b]]=
b);return a}(),Ta=[{id:"hero_inferno",name:"Infernus",aliases:["infernus","hero_infernus"]},{id:"hero_gigawatt",name:"Seven",aliases:["seven","hero_seven"]},{id:"hero_hornet",name:"Vindicta",aliases:["vindicta","hero_vindicta"]},{id:"hero_ghost",name:"Lady Geist",aliases:["geist","lady_geist","ladygeist","hero_lady_geist"]},{id:"hero_atlas",name:"Abrams",aliases:["abrams","bull","hero_abrams"]},{id:"hero_wraith",name:"Wraith",aliases:[]},{id:"hero_forge",name:"McGinnis",aliases:["mcginnis","mc_ginnis",
"engineer","hero_mcginnis"]},{id:"hero_chrono",name:"Paradox",aliases:["paradox","hero_paradox"]},{id:"hero_dynamo",name:"Dynamo",aliases:["sumo"]},{id:"hero_kelvin",name:"Kelvin",aliases:[]},{id:"hero_haze",name:"Haze",aliases:[]},{id:"hero_astro",name:"Ivy",aliases:["ivy","hero_ivy"]},{id:"hero_bebop",name:"Bebop",aliases:[]},{id:"hero_nano",name:"Nano",aliases:[]},{id:"hero_orion",name:"Grey Talon",aliases:["archer","grey_talon","gray_talon","greytalon","hero_grey_talon"]},{id:"hero_krill",name:"Mo & Krill",
aliases:["digger","mo_and_krill","mo_krill","hero_mo_and_krill"]},{id:"hero_shiv",name:"Shiv",aliases:[]},{id:"hero_tengu",name:"Tengu",aliases:[]},{id:"hero_warden",name:"Warden",aliases:[]},{id:"hero_yamato",name:"Yamato",aliases:[]},{id:"hero_lash",name:"Lash",aliases:[]},{id:"hero_viscous",name:"Viscous",aliases:[]},{id:"hero_synth",name:"Pocket",aliases:["pocket","hero_pocket"]},{id:"hero_mirage",name:"Mirage",aliases:[]},{id:"hero_viper",name:"Vyper",aliases:["viper","vyper","hero_vyper"]},
{id:"hero_magician",name:"Magician",aliases:["sinclair","hero_sinclair"]},{id:"hero_vampirebat",name:"Mina",aliases:["vampire_bat","vampirebat","mina","hero_mina"]},{id:"hero_drifter",name:"Drifter",aliases:[]},{id:"hero_priest",name:"Priest",aliases:[]},{id:"hero_frank",name:"Frank",aliases:[]},{id:"hero_bookworm",name:"Bookworm",aliases:["paige","hero_paige"]},{id:"hero_doorman",name:"Doorman",aliases:[]},{id:"hero_punkgoat",name:"Billy",aliases:["punkgoat","punk_goat","billy","hero_billy"]},{id:"hero_necro",
name:"Necro",aliases:[]},{id:"hero_fencer",name:"Apollo",aliases:["fencer","apollo","hero_apollo"]},{id:"hero_familiar",name:"Familiar",aliases:[]},{id:"hero_werewolf",name:"Werewolf",aliases:[]},{id:"hero_unicorn",name:"Unicorn",aliases:[]}],H={},N=[],T=null,V=null,F=null,C=null,B=null,A=null,na=0,U=null,oa="",ha=null,Q="",u="",va=!1,O=!1,P=!1,E=!1,K=null,Ea={},Z="",X="",Y="",Ia=!1,Sa=!1,x=!1,R=0,J=0,I=1,Qa=0,ia=G()+1E4,Ba="",L=0,M=!1,W="",ra="";try{$.RegisterForUnhandledEvent("ClientUI_FireOutput",
gb)}catch(a){}(function(){for(var a=0;a<Ta.length;a+=1){var b=Ta[a];aa(b.id,b.id);aa(b.id.replace(/^hero_/,""),b.id);aa(b.name,b.id);for(var c=0;c<b.aliases.length;c+=1)aa(b.aliases[c],b.id)}N.sort(function(d,f){return f.token.length-d.token.length})})();Pa(!1);for(var ka=0;ka<Ca.length;ka+=1)try{(function(a){$.Schedule(Ca[ka],function(){Pa(a)})})(ka===Ca.length-1)}catch(a){}})();
