function pa(f){var k=0;return function(){return k<f.length?{done:!1,value:f[k++]}:{done:!0}}}var Da=typeof Object.defineProperties=="function"?Object.defineProperty:function(f,k,m){if(f==Array.prototype||f==Object.prototype)return f;f[k]=m.value;return f};
function Sa(f){f=["object"==typeof globalThis&&globalThis,f,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var k=0;k<f.length;++k){var m=f[k];if(m&&m.Math==Math)return m}throw Error("Cannot find global object");}var Ta=Sa(this);function W(f,k){if(k)a:{var m=Ta;f=f.split(".");for(var q=0;q<f.length-1;q++){var w=f[q];if(!(w in m))break a;m=m[w]}f=f[f.length-1];q=m[f];k=k(q);k!=q&&k!=null&&Da(m,f,{configurable:!0,writable:!0,value:k})}}
W("Symbol",function(f){function k(x){if(this instanceof k)throw new TypeError("Symbol is not a constructor");return new m(q+(x||"")+"_"+w++,x)}function m(x,K){this.na=x;Da(this,"description",{configurable:!0,writable:!0,value:K})}if(f)return f;m.prototype.toString=function(){return this.na};var q="jscomp_symbol_"+(Math.random()*1E9>>>0)+"_",w=0;return k});
W("Symbol.iterator",function(f){if(f)return f;f=Symbol("Symbol.iterator");Da(Array.prototype,f,{configurable:!0,writable:!0,value:function(){return Ua(pa(this))}});return f});function Ua(f){f={next:f};f[Symbol.iterator]=function(){return this};return f}function Va(f,k){f instanceof String&&(f+="");var m=0,q=!1,w={next:function(){if(!q&&m<f.length){var x=m++;return{value:k(x,f[x]),done:!1}}q=!0;return{done:!0,value:void 0}}};w[Symbol.iterator]=function(){return w};return w}
W("Array.prototype.keys",function(f){return f?f:function(){return Va(this,function(k){return k})}});W("Array.prototype.values",function(f){return f?f:function(){return Va(this,function(k,m){return m})}});
(function(){function f(a){try{return!(!a||a.IsValid&&!a.IsValid())}catch(b){}return!1}function k(){if(!F.isActive())return null;for(var a=$.GetContextPanel();a&&a.GetParent&&a.GetParent();)a=a.GetParent();a=a||null;a!==X&&(X=a,z=null,Y=0,Z=L=null,qa="",B+=1,ra(),v=M=!1,N="",C=0,sa(),aa());return X}function m(){var a=k();if(!a||!a.GetAttributeString||!a.SetAttributeString)return!1;var b=null;try{b=a.FindChildTraverse?a.FindChildTraverse("Hud"):null}catch(p){}a=b&&b!==a?[a,b]:[a];for(var c="",d=b=0;d<
a.length;d+=1){var e=a[d],g="",h=0;try{g=String(e.GetAttributeString("Deadlock_Mod_Settings_v1","")||""),h=Number(e.GetAttributeString("QOL_USER_EDIT_REV","0")||"0")}catch(p){}if(!isFinite(h)||h<0)h=0;g&&(!c||h>=b)&&(c=g,b=h)}if(!c)return!1;e=null;try{e=JSON.parse(c)}catch(p){return!1}g=e&&typeof e==="object"&&e.data&&typeof e.data==="object"?e.data:e;if(!g||typeof g!=="object")return!1;d=!1;for(var l in ba)Object.prototype.hasOwnProperty.call(ba,l)&&g[l]!==ba[l]&&(g[l]=ba[l],d=!0);l=c;if(d){try{l=
JSON.stringify(e)}catch(p){return!1}b+=1}b=String(b);for(c=0;c<a.length;c+=1){e=a[c];try{e.GetAttributeString("Deadlock_Mod_Settings_v1","")!==l&&e.SetAttributeString("Deadlock_Mod_Settings_v1",l),e.GetAttributeString("QOL_USER_EDIT_REV","0")!==b&&e.SetAttributeString("QOL_USER_EDIT_REV",b)}catch(p){}}return d}function q(a,b){if(!F.isActive(a))return!1;var c=k();return!c||b&&c!==b?!1:F.isActive(a)}function w(a){a=String(a||"").replace(/^\s+|\s+$/g,"");if(!a)return-1;var b=a.match(/\d+/g);if(!b||!b.length)return-1;
if(b.length===1)return Number(b[0])||0;a=Number(b[b.length-2])||0;b=Number(b[b.length-1])||0;b>59&&(b%=60);return a*60+b}function x(a,b){try{if(a&&a.FindChildrenWithClassTraverse){var c=a.FindChildrenWithClassTraverse(b)||[];if(c.length)return c[0]}}catch(d){}return null}function K(){var a=y();if(!f(z)||a-Y>1E3){if(!f(z)){var b=k(),c=Ea(b,"TopBar");z=x(c,"GameTime")||x(b,"GameTime")}Y=a}if(!f(z))return-1;a="";try{a=z.text||z.GetAttributeString("text","")||""}catch(d){}return w(a)}function aa(){O=
!1;ta=ca=""}function Fa(){if(O||!da||K()<10)return!1;O=!0;ca=da;ta=ea||"";v=!1;return!0}function y(){try{if(Date&&Date.now)return Date.now()}catch(a){}return+new Date}function ua(a,b,c,d,e,g){P=a;da=b?b.id:"";ea=c||"";va=!!g;return b}function Ga(a){try{return a&&a.id?String(a.id):""}catch(b){}return""}function Ea(a,b){try{return a&&a.FindChildTraverse?a.FindChildTraverse(b):null}catch(c){}return null}function wa(a,b,c){a:{try{var d=a&&a.Children?a.Children():[];break a}catch(h){}d=[]}a=null;for(var e=
0;e<d.length;e+=1){var g=d[e];if(Ga(g)===b&&(a||(a=g),!c||c(g)))return g}return a}function fa(a){if(!f(a))return"";for(var b=0;b<Q.length;b+=1){a:{try{var c=!!(a&&a.BHasClass&&a.BHasClass(Q[b].id));break a}catch(d){}c=!1}if(c)return Q[b].id}return""}function Wa(a){return!!fa(wa(a,"progress",fa))}function sa(){A=D=G=null}function Xa(){var a=k();if(!f(a))return null;f(G)||(G=Ea(a,"gameplay_hud_alive"),A=D=null);if(!f(G))return null;a=wa(G,"crosshair",Wa);a!==D&&(D=a,A=null);if(!f(D))return null;a=wa(D,
"progress",fa);a!==A&&(A=a);return f(A)?A:null}function Ha(){var a=Xa();return fa(a)}function Ia(a){try{if(typeof a.text==="string")return a.text}catch(b){}try{if(a.GetAttributeString)return a.GetAttributeString("text","")}catch(b){}return""}function Ja(a){try{if(a&&a.id!==void 0)return String(a.id||"")}catch(b){}try{if(a&&a.GetAttributeString)return String(a.GetAttributeString("id","")||"")}catch(b){}return""}function Ka(){var a=k();if(!a||!a.FindChildTraverse)return[];var b=f(L)?L:null;if(!b){try{b=
a.FindChildTraverse(t.Ba)}catch(p){}L=f(b)?b:null}if(!b)return[];a=[];try{b.FindChildrenWithClassTraverse&&(a=b.FindChildrenWithClassTraverse(t.ka)||[])}catch(p){}b=String(a.length);for(var c=0;c<a.length;c+=1)b+="|"+Ja(a[c])+":"+Ia(a[c]);if(Z&&qa===b)return Z;c=[];for(var d=0;d<a.length;d+=1)try{var e=Ja(a[d]),g=Ia(a[d]);if(g){var h,l=JSON.parse(La.ia(g));if(h=La.ja(l,{U:"all"})){if(h.heroMode==="off")if(a.length===1&&e==="HPColorsPreset_001")h.heroMode="all";else continue;c.push({id:e,values:h.values,
M:h.M,heroes:h.heroes,heroMode:h.heroMode})}}}catch(p){}qa=b;return Z=c}function Ya(a){if(!a)return null;for(var b=Ka(),c=0;c<b.length;c+=1)if(R.P(b[c],a))return b[c];return null}function Ma(){if(H)try{$.CancelScheduled&&$.CancelScheduled(H)}catch(a){}H=null;I=!1}function ra(){Ma();S.stop();T=xa=U=null;E=n="";ha=ia=ya=!1;ja=0;za=1;ka=y()+1E4}function Za(a){if(n)return!0;if(T)var b=T;else{b:{a=!!a;var c=Ka();if(c.length===1)a=ua("single-valid-preset",c[0],"",a,c.length,!1);else{K()===0&&aa();var d=
R.u(c);if(O&&ca){var e=R.ma(c,ca);if(e){a=ua("locked-hero-selection",e,ta,a,c.length,d);break b}aa()}d=d?Ha():"";d=R.resolve(c,d,a);a=ua(d.reason,d.preset,d.g,a,c.length,d.u)}}if(a&&a.values){c=a.values;d={};for(b in c||{})Object.prototype.hasOwnProperty.call(c,b)&&(d[b]=c[b]);Object.prototype.hasOwnProperty.call(d,"hp_counter_visible")||(d.hp_counter_visible=!0);U=d;xa=a.M||{};S.Aa(xa);b=T=S.V(U)}else b=null}if(!b)return!1;a="";try{a=JSON.stringify(b)}catch(g){return!1}try{n=r.S(b,a,"builder_static")}catch(g){return n=
"",!1}E=a;Fa();return!0}function $a(a){if(!U||!n)return!1;var b=S.V(U),c="";try{if(c=JSON.stringify(b),c===E)return!1}catch(d){return!1}try{n=r.S(b,c,a||"signature_tier_changed")}catch(d){return!1}T=b;E=c;a=r.J(c);r.start();return t.D(n)||a}function la(a){m();return n&&ia&&ha?!0:n?(a=r.J(E),r.start(),t.D(n)||a||ya):r.O(a)}function Na(){za=r.ya(y());var a=B,b=k();if(b)try{H=$.Schedule(za,function(){q(a,b)&&I&&(m(),H=null,n?S.T()?(aa(),v=M=!1,N="",C=0,ea=da=P="",va=!1,sa(),ra(),la(!1)||la(!0)):(ja+=
1,t.D(n),Na()):I=!1)})}catch(c){H=null,I=!1}}function ab(a){if(F.isActive()&&(typeof a!=="string"||a.indexOf(t.aa)!==-1))try{var b=t.ua(a);if(r.fa(b))if(n){var c=y();J&&c-J<250||(r.Z(c),r.wa(b.reason))}else r.Z(y()),r.O(!0)}catch(d){}}function Oa(a,b){if(F.isActive(b)&&v)if(O||Fa())v=!1;else{var c=Ha(),d=Ya(c);if(d&&(ra(),r.O(!1))){v=!1;return}c&&c===N?C+=1:(N=c||"",C=c?1:0);c||(C=0);if(c&&!d&&C>=2)v=!1;else if(a+1>=Aa.length)v=!1;else try{$.Schedule(Aa[a+1],function(){Oa(a+1,b)})}catch(e){}}}function bb(){if(!M&&
!v){v=M=!0;N="";C=0;ka=y()+1E4;var a=B;try{$.Schedule(Aa[0],function(){Oa(0,a)})}catch(b){}}}var Ba=[.1,.5,1,2.5,5,8],Aa=[2,4,6,8,12,16,20,24],ba={Na:0,Ma:0,Ka:0,La:0,Oa:0,Pa:0,Sa:100,Ra:1,Ta:0,Ua:0,Qa:0,Ja:0,Fa:0,Ga:0,Ha:0,Ia:0},V={hp_enabled:"e",hp_mode:"m",hp_low_threshold:"l",hp_high_threshold:"h",hp_bg_visible:"b",hp_team_colors:"t",hp_info_health_margin_top:"ihmt",hp_healthbar_height:"hbh",hp_color_low:"cl",hp_color_mid:"cm",hp_color_high:"ch",hp_heal_color:"ehc",hp_delta_color:"edc",hp_bullet_shield_color:"ebsc",
hp_counter_visible:"cv",hp_counter_size:"s",hp_counter_position:"p",hp_text_color_mode:"tm",hp_level_number_visible:"lnv",hp_pip_visible:"plv",hp_precise_pips_enabled:"ppe",hp_ult_color_enabled:"uce",hp_ult_color_custom:"ucc",hp_text_color_low:"tl",hp_text_color_mid:"ti",hp_text_color_high:"th",hp_pulse_bpm:"bp",hp_pulse_intensity:"pi",hp_pulse_enabled:"pe",hp_pulse_text_enabled:"pte",hp_pulse_text_scale:"pts",hp_pulse_text_position:"ptp",hp_pulse_hide_bar:"phb",hp_pulse_color_enabled:"pce",hp_pulse_color:"pc",
hp_pulse_color_mode:"pcm",hp_skip_buildings:"sb",hp_pulse_threshold:"pt",hp_friend_enabled:"fe",hp_friend_pulse_enabled:"fpe",hp_friend_pulse_bpm:"fpb",hp_friend_pulse_intensity:"fpi",hp_friend_pulse_threshold:"fpt",hp_friend_color_low:"fcl",hp_friend_color_mid:"fcm",hp_friend_color_high:"fch",hp_friend_heal_color:"fhc",hp_friend_delta_color:"fdc",hp_friend_bullet_shield_color:"fbsc",hp_friend_pulse_color_enabled:"fpce",hp_friend_pulse_color:"fpc",hp_kill_zone_enabled:"kze",hp_kill_zone_threshold:"kzt",
hp_kill_zone_color:"kzc",hp_kill_zone_width:"kzw",hp_counter_format:"cf"},Pa=function(){var a={},b;for(b in V)Object.prototype.hasOwnProperty.call(V,b)&&(a[V[b]]=b);return a}(),ma=function(){var a={},b;for(b in V)Object.prototype.hasOwnProperty.call(V,b)&&(a[b]=!0);return a}(),Q=[{id:"hero_inferno",g:1,name:"Infernus"},{id:"hero_gigawatt",g:2,name:"Seven"},{id:"hero_hornet",g:3,name:"Vindicta"},{id:"hero_ghost",g:4,name:"Lady Geist"},{id:"hero_atlas",g:6,name:"Abrams"},{id:"hero_wraith",g:7,name:"Wraith"},
{id:"hero_forge",g:8,name:"McGinnis"},{id:"hero_chrono",g:10,name:"Paradox"},{id:"hero_dynamo",g:11,name:"Dynamo"},{id:"hero_kelvin",g:12,name:"Kelvin"},{id:"hero_haze",g:13,name:"Haze"},{id:"hero_astro",g:14,name:"Holliday"},{id:"hero_bebop",g:15,name:"Bebop"},{id:"hero_nano",g:16,name:"Calico"},{id:"hero_orion",g:17,name:"Grey Talon"},{id:"hero_krill",g:18,name:"Mo & Krill"},{id:"hero_shiv",g:19,name:"Shiv"},{id:"hero_tengu",g:20,name:"Ivy"},{id:"hero_warden",g:25,name:"Warden"},{id:"hero_yamato",
g:27,name:"Yamato"},{id:"hero_lash",g:31,name:"Lash"},{id:"hero_viscous",g:35,name:"Viscous"},{id:"hero_synth",g:50,name:"Pocket"},{id:"hero_mirage",g:52,name:"Mirage"},{id:"hero_viper",g:58,name:"Vyper"},{id:"hero_magician",g:60,name:"Sinclair"},{id:"hero_vampirebat",g:63,name:"Mina"},{id:"hero_drifter",g:64,name:"Drifter"},{id:"hero_priest",g:65,name:"Venator"},{id:"hero_frank",g:66,name:"Victor"},{id:"hero_bookworm",g:67,name:"Paige"},{id:"hero_doorman",g:69,name:"The Doorman"},{id:"hero_punkgoat",
g:72,name:"Billy"},{id:"hero_necro",g:76,name:"Graves"},{id:"hero_fencer",g:77,name:"Apollo"},{id:"hero_familiar",g:79,name:"Rem"},{id:"hero_werewolf",g:80,name:"Silver"},{id:"hero_unicorn",g:81,name:"Celeste"}],Qa={},Ra={},X=null,L=null,G=null,D=null,A=null,z=null,Y=0,Z=null,qa="",U=null,xa=null,T=null,E="",n="",ya=!1,ia=!1,ha=!1,I=!1,H=null,P="",da="",ea="",va=!1,M=!1,v=!1,J=0,ja=0,za=1,ka=y()+1E4,N="",C=0,O=!1,ca="",ta="",B=1,Ca=!1,na=null,F={isActive:function(a){if(Ca||a!==void 0&&a!==B)return!1;
a=null;try{a=$.GetContextPanel()}catch(b){}if(f(a))return!0;this.stop();return!1},stop:function(){if(Ca)return!1;Ca=!0;B+=1;Ma();M=v=!1;sa();z=A=D=G=L=X=null;Y=0;try{$.UnregisterForUnhandledEvent&&na!==null&&$.UnregisterForUnhandledEvent("ClientUI_FireOutput",na)}catch(a){}na=null;return!0}},t={W:"ClientUI_FireOutput",va:"HP_COLORS_PRESET_SNAPSHOT",aa:"HP_COLORS_PRESET_REQUEST",da:"__hpColorsCfgRaw",ba:"hp_colors_minimal_cfg_raw",Ba:"HPColorsPresetStore",Wa:"HPColorsPreset_001",ka:"hp_colors_preset_entry",
oa:function(){a:{try{if(typeof GameUI!=="undefined"&&GameUI&&GameUI.CustomUIConfig){var a=GameUI.CustomUIConfig();break a}}catch(b){}a=null}return a},D:function(a){if(!a)return!1;try{return $.DispatchEvent(this.W,a),!0}catch(b){}return!1},ua:function(a){try{return typeof a==="string"?JSON.parse(a):a}catch(b){}return null},pa:function(a){return!(!a||a.magic_word!==this.aa)},ea:function(a){return!(!this.pa(a)||a.mod_title&&a.mod_title!=="HP Colors")},ga:function(a,b,c){return{magic_word:this.va,mod_title:"HP Colors",
version:1,values_raw:b,values:a,update_source:String(c||"builder_static")}},Ca:function(a){var b=!1,c=!1,d=this.oa();if(d)try{d[this.da]!==a&&(d[this.da]=a),b=!0}catch(e){}d=k();try{f(d)&&d.SetAttributeString&&(d.GetAttributeString&&d.GetAttributeString(this.ba,"")===a||d.SetAttributeString(this.ba,a),c=!0)}catch(e){}return{ok:b||c,Ea:b,Da:c}}},R={L:function(a){var b=[];Array.isArray(a)?b=a:typeof a==="string"?b=a.split(/[,|;]/):a&&(b=[a]);a={};for(var c=[],d=0;d<b.length;d+=1){var e=b[d];e===null||
e===void 0?e="":(e=String(e),e=Object.prototype.hasOwnProperty.call(Qa,e)?e:/^\d+$/.test(e)?Ra[e]||"":"");e&&!a[e]&&(a[e]=!0,c.push(e))}return c},Va:function(a,b){a=String(a||"").toLowerCase();return a==="off"||a==="disabled"||a==="none"?"off":a==="all"||a==="global"?"all":a==="selected"||a==="heroes"||a==="hero"?this.L(b).length?"selected":"off":this.L(b).length?"selected":"all"},P:function(a,b){if(!a||!b||a.heroMode!=="selected"||!Array.isArray(a.heroes))return!1;for(var c=0;c<a.heroes.length;c+=
1)if(a.heroes[c]===b)return!0;return!1},u:function(a){for(var b=0;b<a.length;b+=1)if(a[b]&&a[b].heroMode==="selected")return!0;return!1},ma:function(a,b){for(var c=0;c<a.length;c+=1)if(a[c]&&a[c].id===b)return a[c];return null},resolve:function(a,b,c){for(var d=null,e=null,g=null,h=null,l=!1,p=0;p<a.length;p+=1){var u=a[p];u&&(e||(e=u),g||u.heroMode!=="all"||(g=u),u.heroMode==="selected"&&(l=!0),u.id==="HPColorsPreset_001"&&(d=u),b&&!h&&this.P(u,b)&&(h=u))}return b&&h?{preset:h,g:b,u:l,reason:"selected-hero-match",
source:"hero",I:!1}:!l||b||c?!d||b&&d.heroMode!=="all"&&!this.P(d,b)?g?{preset:g,g:b,u:l,reason:"first-global-fallback",source:"global",I:!0}:{preset:e,g:b,u:l,reason:"first-enabled-fallback",source:"first",I:!0}:{preset:d,g:b,u:l,reason:b?"compatible-startup":"unknown-hero-startup-fallback",source:"startup",I:!0}:{preset:null,g:"",u:l,reason:"wait-unknown-hero",source:"waiting_for_hero",I:!1}}},La={R:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_",j:function(a,b){return Object.prototype.hasOwnProperty.call(a||
{},b)},ia:function(a){function b(u){if(u===void 0)return 0;if(!Object.prototype.hasOwnProperty.call(d,u))throw Error("Invalid base64url");return d[u]}var c=String(a||"").replace(/^\s+|\s+$/g,"");if(!/^[A-Za-z0-9_-]*$/.test(c)||c.length%4===1)throw Error("Invalid base64url");var d={};for(a=0;a<this.R.length;a+=1)d[this.R[a]]=a;a=[];for(var e=0;e<c.length;e+=4){var g=b(c[e]),h=b(c[e+1]),l=c[e+2]!==void 0?b(c[e+2]):0,p=c[e+3]!==void 0?b(c[e+3]):0;a.push(g<<2|h>>4);c[e+2]!==void 0&&a.push((h&15)<<4|l>>
2);c[e+3]!==void 0&&a.push((l&3)<<6|p)}c="";for(e=0;e<a.length;e+=1)g=a[e],g<128?c+=String.fromCharCode(g):g<224?c+=String.fromCharCode((g&31)<<6|a[++e]&63):(h=a[++e],l=a[++e],c+=String.fromCharCode((g&15)<<12|(h&63)<<6|l&63));return c},la:function(a,b,c){if(!a||typeof a!=="object")return null;var d={},e=!1,g;for(g in a)if(this.j(a,g)){var h=g==="kzs"?"hp_kill_zone_color":b[g]||g;this.j(c,h)&&(d[h]=a[g],e=!0)}return e?d:null},sa:function(a){if(Array.isArray(a)){if(a.length!==3)return null;var b=a[0];
var c=a[1];a=a[2]}else if(a&&typeof a==="object"){if(!this.j(a,"slot")||!this.j(a,"minTier")||!this.j(a,"value"))return null;b=a.slot;c=a.minTier;a=a.value}else return null;return typeof b!=="number"||!isFinite(b)||Math.floor(b)!==b||b<1||b>4||typeof c!=="number"||!isFinite(c)||Math.floor(c)!==c||c<0||c>3?null:{slot:b,qa:c,value:a}},ta:function(a){if(!a||typeof a!=="object"||Array.isArray(a))return{};for(var b={},c={},d=Object.keys(a),e=0;e<d.length;e+=1){var g=d[e];this.j(ma,g)&&g!=="hp_precise_pips_enabled"&&
(b[g]=!0)}for(e=0;e<d.length;e+=1){var h=d[e],l=this.j(ma,h);(g=l?h:h==="kzs"?"hp_kill_zone_color":Pa[h]||"")&&this.j(ma,g)&&g!=="hp_precise_pips_enabled"&&(l||!this.j(b,g))&&(h=this.sa(a[h]))&&(c[g]=h)}return c},ra:function(a,b,c){b=R.L(b);a=String(a||"").toLowerCase();var d="";a==="off"||a==="disabled"||a==="none"?d="off":a==="all"||a==="global"?d="all":a==="selected"||a==="heroes"||a==="hero"?d=b.length?"selected":"off":b.length?d="selected":d=c&&c.U||"all";return{mode:d,heroes:d==="selected"?
b:[]}},ja:function(a,b){if(!a||typeof a!=="object")return null;var c=Number(a.version!==void 0?a.version:a.v);if(c!==1&&c!==97&&c!==98&&c!==99)return null;c=this.la(a.values&&typeof a.values==="object"?a.values:a.vals&&typeof a.vals==="object"?a.vals:a.vs&&typeof a.vs==="object"?a.vs:null,Pa,ma);if(!c)return null;b=this.ra(a.heroMode!==void 0?a.heroMode:a.hm,a.heroes!==void 0?a.heroes:a.hs!==void 0?a.hs:a.hero!==void 0?a.hero:a.h,b||{U:"all"});return{values:c,M:this.ta(a.o!==void 0?a.o:a.overrides),
heroes:b.heroes,heroMode:b.mode}}},S={root:null,A:null,m:null,l:[null,null,null,null],tiers:[-1,-1,-1,-1],B:[!1,!1,!1,!1],i:[-1,-1,-1,-1],retired:[!1,!1,!1,!1],rules:{},G:0,C:!1,handle:null,F:-1,stop:function(){if(this.handle)try{$.CancelScheduled&&$.CancelScheduled(this.handle)}catch(a){}this.handle=null;this.C=!1;this.G+=1;this.F=-1},za:function(){this.stop();this.m=this.A=this.root=null;this.l=[null,null,null,null];this.tiers=[-1,-1,-1,-1];this.i=[-1,-1,-1,-1];this.retired=[!1,!1,!1,!1]},T:function(){var a=
K();if(a<0)return!1;var b=this.F>=0&&a<this.F;this.F=a;if(!b)return!1;this.za();this.F=a;return!0},Aa:function(a){this.stop();this.rules=a||{};this.m=this.A=this.root=null;this.l=[null,null,null,null];this.tiers=[-1,-1,-1,-1];this.B=[!1,!1,!1,!1];this.i=[-1,-1,-1,-1];this.retired=[!1,!1,!1,!1];for(var b in this.rules)Object.prototype.hasOwnProperty.call(this.rules,b)&&(a=this.rules[b].slot,a>=1&&a<=4&&(this.B[a-1]=!0));this.H()&&this.ca()},H:function(){for(var a=0;a<4;a+=1)if(this.B[a]&&!this.retired[a])return!0;
return!1},N:function(a){try{return a&&a.GetParent?a.GetParent():null}catch(b){}return null},Y:function(a,b){for(;f(a);){if(a===b)return!0;a=this.N(a)}return!1},X:function(){for(var a=0;a<4;a+=1)if(this.B[a]&&(!f(this.l[a])||this.N(this.l[a])!==this.m))return!1;return!0},ha:function(a){return!!(a===this.root&&f(this.A)&&f(this.m)&&this.Y(this.A,a)&&this.Y(this.m,this.A)&&this.X())},K:function(){this.m=this.A=this.root=null;this.l=[null,null,null,null]},resolve:function(){var a=k();if(!a)return!1;if(this.ha(a))return!0;
var b=this.l;this.K();var c=null;try{c=a.FindChildTraverse("hud_signature")}catch(p){}if(!f(c))return!1;for(var d=null,e=0;e<4;e+=1)if(this.B[e]){try{d=c.FindChildTraverse("slot_signature_"+String(e+1))}catch(p){}if(f(d))break}if(!f(d))return!1;d=this.N(d);if(!f(d))return!1;this.root=a;this.A=c;this.m=d;this.l=[null,null,null,null];try{var g=d.GetChildCount?d.GetChildCount():0;for(a=0;a<g;a+=1){var h=d.GetChild(a),l=Ga(h);for(c=1;c<=4;c+=1)if(this.B[c-1]&&l==="slot_signature_"+String(c)){b[c-1]&&
b[c-1]!==h&&(this.tiers[c-1]=-1,this.i[c-1]=-1,this.retired[c-1]=!1);this.l[c-1]=h;break}}}catch(p){return this.K(),!1}return this.X()?!0:(this.K(),!1)},xa:function(a){if(!f(a))return-1;for(var b=3;b>=0;--b)try{if(a.BHasClass&&a.BHasClass("Tier"+String(b)))return b}catch(c){}return-1},refresh:function(){var a=!1;this.T();for(var b=this.H()&&this.resolve(),c=y(),d=0;d<4;d+=1){var e=-1;this.B[d]?this.retired[d]?e=3:b?(e=this.xa(this.l[d]),e===3?this.i[d]<0||c<this.i[d]?this.i[d]=c:c-this.i[d]>=5E3&&
(this.i[d]=-1,this.retired[d]=!0):this.i[d]=-1):this.i[d]=-1:this.i[d]=-1;e!==this.tiers[d]&&(a=!0);this.tiers[d]=e}return a},V:function(a){var b={},c;for(c in a||{})Object.prototype.hasOwnProperty.call(a,c)&&(b[c]=a[c]);for(var d in this.rules)Object.prototype.hasOwnProperty.call(this.rules,d)&&(a=this.rules[d],this.tiers[a.slot-1]>=a.qa&&(b[d]=a.value));return b},ca:function(){if(!this.C&&this.H()){var a=this.G,b=B,c=k();if(c){var d=this;this.C=!0;try{this.handle=$.Schedule(.1,function(){d.handle=
null;if(a===d.G&&F.isActive(b)&&k()===c){var e=d.refresh();d.C=!1;e&&$a("signature_tier_changed");d.H()&&d.ca()}else d.C=!1})}catch(e){this.handle=null,this.C=!1}}}}},r={S:function(a,b,c){return JSON.stringify(t.ga(a,b,c))},fa:function(a){return t.ea(a)},Z:function(a){J=a||y();ka=(a||J)+1500},ya:function(a){return v||a<ka||J&&a-J<1500||ja<3?1:ja<12?3:8},wa:function(){if(!n)return!1;var a=t.D(n),b=this.J(E);return a||b},J:function(a){if(!a)return!1;a=t.Ca(a);var b=!(!a||!a.Da);a&&a.Ea&&(ia=!0);b&&
(ha=!0);ya=ia||ha;return!(!a||!a.ok)},O:function(a){if(!Za(a))return!1;a=this.J(E);this.start();var b=t.D(n);!va||ea||P!=="unknown-hero-startup-fallback"&&P!=="first-global-fallback"&&P!=="first-enabled-fallback"||bb();return b||a},start:function(){!I&&n&&(I=!0,Na())}};try{na=$.RegisterForUnhandledEvent(t.W,ab)}catch(a){}(function(){for(var a=0;a<Q.length;a+=1){var b=Q[a];Qa[b.id]=b;Ra[String(b.g)]=b.id}})();la(!1);for(var oa=0;oa<Ba.length;oa+=1)try{(function(a){var b=B,c=k();c&&$.Schedule(Ba[oa],
function(){q(b,c)&&la(a)})})(oa===Ba.length-1)}catch(a){}})();
