function ja(e){var h=0;return function(){return h<e.length?{done:!1,value:e[h++]}:{done:!0}}}var ka=typeof Object.defineProperties=="function"?Object.defineProperty:function(e,h,l){if(e==Array.prototype||e==Object.prototype)return e;e[h]=l.value;return e};
function Sa(e){e=["object"==typeof globalThis&&globalThis,e,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var h=0;h<e.length;++h){var l=e[h];if(l&&l.Math==Math)return l}throw Error("Cannot find global object");}var Ta=Sa(this);function Ua(e,h){if(h)a:{var l=Ta;e=e.split(".");for(var t=0;t<e.length-1;t++){var m=e[t];if(!(m in l))break a;l=l[m]}e=e[e.length-1];t=l[e];h=h(t);h!=t&&h!=null&&ka(l,e,{configurable:!0,writable:!0,value:h})}}
Ua("Symbol",function(e){function h(v){if(this instanceof h)throw new TypeError("Symbol is not a constructor");return new l(t+(v||"")+"_"+m++,v)}function l(v,R){this.i=v;ka(this,"description",{configurable:!0,writable:!0,value:R})}if(e)return e;l.prototype.toString=function(){return this.i};var t="jscomp_symbol_"+(Math.random()*1E9>>>0)+"_",m=0;return h});
Ua("Symbol.iterator",function(e){if(e)return e;e=Symbol("Symbol.iterator");ka(Array.prototype,e,{configurable:!0,writable:!0,value:function(){return Va(ja(this))}});return e});function Va(e){e={next:e};e[Symbol.iterator]=function(){return this};return e}function Wa(e,h){e instanceof String&&(e+="");var l=0,t=!1,m={next:function(){if(!t&&l<e.length){var v=l++;return{value:h(v,e[v]),done:!1}}t=!0;return{done:!0,value:void 0}}};m[Symbol.iterator]=function(){return m};return m}
Ua("Array.prototype.values",function(e){return e?e:function(){return Wa(this,function(h,l){return l})}});
(function(){function e(a){try{return!(!a||a.IsValid&&!a.IsValid())}catch(b){}return!1}function h(){for(var a=$.GetContextPanel();a&&a.GetParent&&a.GetParent();)a=a.GetParent();a=a||null;a!==S&&(S=a,A=null,la=0,T=U=null,ma="",B=C=F=null,na(),m("root",{id:oa(a)||"",j:!0}));return S}function l(){try{if(typeof GameUI!=="undefined"&&GameUI&&GameUI.CustomUIConfig)return GameUI.CustomUIConfig()}catch(a){}return null}function t(){var a=l();try{return!(!a||!a.__hpColorsPresetDebug)}catch(b){}return!1}function m(a,
b){if(t()){var c="";try{c=b?JSON.stringify(b):""}catch(d){c=String(b||"")}if(Ca[a]!==c){Ca[a]=c;a="[HP_COLORS_MINIMAL_PRESET] "+a+(c?" "+c:"");try{if(typeof $!=="undefined"&&$&&$.Msg){$.Msg(a);return}}catch(d){}try{typeof console!=="undefined"&&console&&console.log&&console.log(a)}catch(d){}}}}function v(a){return a?a.id+":"+a.heroMode+":"+(a.heroes&&a.heroes.length?a.heroes.join(","):"*"):""}function R(a,b){try{if(a&&a.FindChildrenWithClassTraverse){var c=a.FindChildrenWithClassTraverse(b)||[];if(c.length)return c[0]}}catch(d){}return null}
function Da(){var a=G();if(!e(A)||a-la>1E3){if(!e(A)){var b=h(),c=Ea(b,"TopBar");A=R(c,"GameTime")||R(b,"GameTime")}la=a}if(!e(A))return-1;a="";try{a=A.text||A.GetAttributeString("text","")||""}catch(d){}a=(a=String(a||"").replace(/^\s+|\s+$/g,""))?(a=a.match(/\d+/g))&&a.length?a.length===1?Number(a[0])||0:(Number(a[0])||0)*60+(Number(a[1])||0):-1:-1;return a}function na(){L=!1;pa=V=""}function Fa(){if(L||!W||Da()<10)return!1;L=!0;V=W;pa=X||"";x=!1;return!0}function G(){try{if(Date&&Date.now)return Date.now()}catch(a){}return+new Date}
function D(a,b,c,d,f,n){Y=a;W=b?b.id:"";X=c||"";Ga=!!n;m("select",{reason:a,preset:v(b),hero:c||"",allow_unknown_fallback:!!d,u:f||0,m:!!n});return b}function qa(a){var b=[];Array.isArray(a)?b=a:typeof a==="string"?b=a.split(/[,|;]/):a&&(b=[a]);a={};for(var c=[],d=0;d<b.length;d+=1){var f=b[d];f===null||f===void 0?f="":(f=String(f),f=Object.prototype.hasOwnProperty.call(Ha,f)?f:/^\d+$/.test(f)?Ia[f]||"":"");f&&!a[f]&&(a[f]=!0,c.push(f))}return c}function oa(a){try{return a&&a.id?String(a.id):""}catch(b){}return""}
function Ea(a,b){try{return a&&a.FindChildTraverse?a.FindChildTraverse(b):null}catch(c){}return null}function ra(a,b,c){a:{try{var d=a&&a.Children?a.Children():[];break a}catch(k){}d=[]}a=null;for(var f=0;f<d.length;f+=1){var n=d[f];if(oa(n)===b&&(a||(a=n),!c||c(n)))return n}return a}function Z(a){if(!e(a))return"";for(var b=0;b<M.length;b+=1){a:{try{var c=!!(a&&a.BHasClass&&a.BHasClass(M[b].id));break a}catch(d){}c=!1}if(c)return M[b].id}return""}function Xa(a){return!!Z(ra(a,"progress",Z))}function Ya(){var a=
h();if(!e(a))return null;e(F)||(F=Ea(a,"gameplay_hud_alive"),B=C=null);if(!e(F))return null;a=ra(F,"crosshair",Xa);a!==C&&(C=a,B=null);if(!e(C))return null;a=ra(C,"progress",Z);a!==B&&(B=a);return e(B)?B:null}function Ja(){var a=Ya(),b=Z(a);m("detect",{hero:b||"",root:oa(S)||"",alive:e(F),crosshair:e(C),progress:e(a)});return b}function aa(a){try{return $.DispatchEvent("ClientUI_FireOutput",a),!0}catch(b){}return!1}function sa(a){if(!a)return!1;var b=!1,c=!1,d=l();if(d)try{d.__hpColorsCfgRaw!==a&&
(d.__hpColorsCfgRaw=a),b=!0}catch(f){}d=h();try{e(d)&&d.SetAttributeString&&(d.GetAttributeString&&d.GetAttributeString("hp_colors_minimal_cfg_raw","")===a||d.SetAttributeString("hp_colors_minimal_cfg_raw",a),c=!0)}catch(f){}b&&(N=!0);c&&(O=!0);(ta=N||O)&&m("shared-write",{gameui:b,root_attr:c,gameui_ready:N,root_ready:O,raw_length:a.length});return b||c}function Ka(a){try{if(typeof a.text==="string")return a.text}catch(b){}try{if(a.GetAttributeString)return a.GetAttributeString("text","")}catch(b){}return""}
function La(a){try{if(a&&a.id!==void 0)return String(a.id||"")}catch(b){}try{if(a&&a.GetAttributeString)return String(a.GetAttributeString("id","")||"")}catch(b){}return""}function Za(a){function b(g){if(g===void 0||g==="")return 0;if(!Object.prototype.hasOwnProperty.call(c,g))throw Error("bad base64url");return c[g]}for(var c={},d=0;d<64;d+=1)c["ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_"[d]]=d;d=[];for(var f=0;f<a.length;f+=4){var n=b(a[f]),k=b(a[f+1]),q=a[f+2]!==void 0?b(a[f+
2]):0,p=a[f+3]!==void 0?b(a[f+3]):0;d.push(n<<2|k>>4);a[f+2]!==void 0&&d.push((k&15)<<4|q>>2);a[f+3]!==void 0&&d.push((q&3)<<6|p)}a="";for(f=0;f<d.length;f+=1)n=d[f],n<128?a+=String.fromCharCode(n):n<224?a+=String.fromCharCode((n&31)<<6|d[++f]&63):(k=d[++f],q=d[++f],a+=String.fromCharCode((n&15)<<12|(k&63)<<6|q&63));return a}function Ma(){var a=h();if(!a||!a.FindChildTraverse)return[];var b=e(U)?U:null;if(!b){try{b=a.FindChildTraverse("HPColorsPresetStore")}catch(Na){}U=e(b)?b:null}if(!b)return[];
a=[];try{b.FindChildrenWithClassTraverse&&(a=b.FindChildrenWithClassTraverse("hp_colors_preset_entry")||[])}catch(Na){}b=String(a.length);for(var c=0;c<a.length;c+=1)b+="|"+La(a[c])+":"+Ka(a[c]);if(T&&ma===b)return T;c=[];for(var d=0;d<a.length;d+=1)try{var f=La(a[d]),n=Ka(a[d]);if(n){var k=JSON.parse(Za(n));if(k&&typeof k==="object"){var q=Number(k.version!==void 0?k.version:k.v);var p=void 0,g=k.values||k.vals||k.vs;if(g&&typeof g==="object"){var r={},w=!1;for(p in g)if(Object.prototype.hasOwnProperty.call(g,
p)){var ba=$a[p]||p;String(ba).indexOf("hp_")===0&&(r[ba]=g[p],w=!0)}var ua=w?r:null}else ua=null;if(q!==1&&q!==97||!ua)var y=null;else{var ca=qa(k.heroes||k.hs||k.hero||k.h);p=ca;var z=String(k.heroMode||k.hm||"").toLowerCase();var da=z==="off"||z==="disabled"||z==="none"?"off":z==="all"||z==="global"?"all":z==="selected"||z==="heroes"||z==="hero"?qa(p).length?"selected":"off":qa(p).length?"selected":"all";da!=="selected"||ca.length||(da="off");da!=="selected"&&(ca=[]);y={values:ua,heroes:ca,heroMode:da}}}else y=
null;if(y){if(y.heroMode==="off")if(a.length===1&&f==="HPColorsPreset_001")y.heroMode="all",m("single-startup-off-compat",{id:f});else continue;c.push({id:f,values:y.values,heroes:y.heroes,heroMode:y.heroMode})}}}catch(Na){}ma=b;T=c;t()&&m("store",{entries:a.length,B:c.length,A:c.map(v)});return c}function va(a,b){if(!a||!b||a.heroMode!=="selected"||!Array.isArray(a.heroes))return!1;for(var c=0;c<a.heroes.length;c+=1)if(a.heroes[c]===b)return!0;return!1}function ab(a){if(!a)return null;for(var b=
Ma(),c=0;c<b.length;c+=1)if(va(b[c],a))return b[c];return null}function bb(a){if(u)return!0;if(ea)var b=ea;else{b:{var c=!!a;var d=Ma();if(d.length===1)c=D("single-valid-preset",d[0],"",c,d.length,!1);else{var f=null,n=null;Da()===0&&na();for(var k=null,q=null,p=!1,g=0;g<d.length;g+=1){var r=d[g];n||(n=r);!k&&r&&r.heroMode==="all"&&(k=r);r.heroMode==="selected"&&(p=!0);r.id==="HPColorsPreset_001"&&(f=r)}if(L&&V){for(g=0;g<d.length;g+=1)if(d[g].id===V){c=D("locked-hero-selection",d[g],pa,c,d.length,
p);break b}na()}g=p?Ja():"";for(r=0;g&&r<d.length;r+=1)if(va(d[r],g)){q=d[r];break}g&&q?c=D("selected-hero-match",q,g,c,d.length,p):!p||g||c?(!(q=!f)&&(q=g)&&(q=f,q=!(q&&q.heroMode==="all"||va(q,g))),c=q?k?D("first-global-fallback",k,g,c,d.length,p):D("first-enabled-fallback",n,g,c,d.length,p):D(g?"compatible-startup":"unknown-hero-startup-fallback",f,g,c,d.length,p)):c=D("wait-unknown-hero",null,"",c,d.length,p)}}if(c&&c.values){c=c.values;d={};for(b in c||{})Object.prototype.hasOwnProperty.call(c,
b)&&(d[b]=c[b]);Object.prototype.hasOwnProperty.call(d,"hp_counter_visible")||(d.hp_counter_visible=!0);for(var w in wa)Object.prototype.hasOwnProperty.call(wa,w)&&(d[w]=wa[w]);b=ea=d}else b=null}if(!b)return!1;w="";try{w=JSON.stringify(b)}catch(ba){return!1}try{u=JSON.stringify({magic_word:"HP_COLORS_PRESET_SNAPSHOT",mod_title:"HP Colors",version:1,values_raw:w,values:b,update_source:"builder_static"})}catch(ba){return u="",!1}P=w;m("capture",{allow_unknown_fallback:!!a,raw_length:w.length,hp_team_colors:b.hp_team_colors,
hp_color_low:b.hp_color_low,hp_mode:b.hp_mode,hp_skip_buildings:b.hp_skip_buildings,hp_counter_visible:b.hp_counter_visible,hp_friend_enabled:b.hp_friend_enabled,hp_friend_color_low:b.hp_friend_color_low,hp_friend_color_mid:b.hp_friend_color_mid,hp_friend_color_high:b.hp_friend_color_high,hp_friend_pulse_enabled:b.hp_friend_pulse_enabled});Fa();return!0}function xa(a){if(!bb(a))return!1;a=sa(P);!E&&u&&(E=!0,ya());var b=aa(u);!Ga||X||Y!=="unknown-hero-startup-fallback"&&Y!=="first-global-fallback"&&
Y!=="first-enabled-fallback"||cb();return b||a}function Oa(a){return u&&N&&O?!0:u?(a=sa(P),!E&&u&&(E=!0,ya()),aa(u)||a||ta):xa(a)}function ya(){var a=G();H=x||a<fa||Q&&a-Q<1500||I<3?1:I<12?3:8;(I<=1||H!==Pa)&&m("replay",{l:I,interval:H,o:!!x});Pa=H;try{J=$.Schedule(H,db)}catch(b){J=null,E=!1}}function db(){J=null;u?(I+=1,aa(u),ya()):E=!1}function eb(a){if(typeof a!=="string"||a.indexOf("HP_COLORS_PRESET_REQUEST")!==-1)try{var b=typeof a==="string"?JSON.parse(a):a;if(b&&b.magic_word==="HP_COLORS_PRESET_REQUEST"&&
(!b.mod_title||b.mod_title==="HP Colors"))if(u){var c=G();Q&&c-Q<250||(Q=c,fa=c+1500,aa(u),sa(P))}else xa(!0)}catch(d){}}function Qa(a){if(x)if(L||Fa())x=!1;else{var b=Ja(),c=ab(b);m("probe",{index:a,hero:b||"",preset:v(c)});if(c){if(J)try{$.CancelScheduled&&$.CancelScheduled(J)}catch(d){}J=null;E=!1;ea=null;P=u="";O=N=ta=!1;I=0;H=1;fa=G()+1E4;if(xa(!1)){x=!1;m("probe-stop",{reason:"selected-hero-match",hero:X||b,preset:W||c.id});return}}b&&b===za?K+=1:(za=b||"",K=b?1:0);b||(K=0);if(b&&!c&&K>=2)x=
!1,m("probe-stop",{reason:"known-hero-no-scoped-preset",hero:b,stable_count:K});else if(a+1>=ha.length)x=!1,m("probe-stop",{reason:"bounded-timeout",hero:b||""});else try{$.Schedule(ha[a+1],function(){Qa(a+1)})}catch(d){}}}function cb(){if(!Ra&&!x){x=Ra=!0;za="";K=0;fa=G()+1E4;m("probe-start",{retries:ha.length});try{$.Schedule(ha[0],function(){Qa(0)})}catch(a){}}}var Aa=[.1,.5,1,2.5,5,8],ha=[2,4,6,8,12,16,20,24],wa={},Ba={hp_enabled:"e",hp_mode:"m",hp_low_threshold:"l",hp_high_threshold:"h",hp_bg_visible:"b",
hp_team_colors:"t",hp_info_health_margin_top:"ihmt",hp_healthbar_height:"hbh",hp_color_low:"cl",hp_color_mid:"cm",hp_color_high:"ch",hp_counter_visible:"cv",hp_counter_size:"s",hp_counter_position:"p",hp_text_color_mode:"tm",hp_level_number_visible:"lnv",hp_pip_visible:"plv",hp_ult_color_enabled:"uce",hp_ult_color_custom:"ucc",hp_text_color_low:"tl",hp_text_color_mid:"ti",hp_text_color_high:"th",hp_pulse_bpm:"bp",hp_pulse_intensity:"pi",hp_pulse_enabled:"pe",hp_pulse_text_enabled:"pte",hp_pulse_text_scale:"pts",
hp_pulse_text_position:"ptp",hp_pulse_hide_bar:"phb",hp_pulse_color_enabled:"pce",hp_pulse_color:"pc",hp_pulse_color_mode:"pcm",hp_skip_buildings:"sb",hp_pulse_threshold:"pt",hp_friend_enabled:"fe",hp_friend_pulse_enabled:"fpe",hp_friend_pulse_bpm:"fpb",hp_friend_pulse_intensity:"fpi",hp_friend_pulse_threshold:"fpt",hp_friend_color_low:"fcl",hp_friend_color_mid:"fcm",hp_friend_color_high:"fch",hp_friend_pulse_color_enabled:"fpce",hp_friend_pulse_color:"fpc",hp_kill_zone_enabled:"kze",hp_kill_zone_threshold:"kzt",
hp_kill_zone_color:"kzc",hp_kill_zone_width:"kzw",hp_counter_format:"cf"},$a=function(){var a={},b;for(b in Ba)Object.prototype.hasOwnProperty.call(Ba,b)&&(a[Ba[b]]=b);return a}(),M=[{id:"hero_inferno",g:1,name:"Infernus"},{id:"hero_gigawatt",g:2,name:"Seven"},{id:"hero_hornet",g:3,name:"Vindicta"},{id:"hero_ghost",g:4,name:"Lady Geist"},{id:"hero_atlas",g:6,name:"Abrams"},{id:"hero_wraith",g:7,name:"Wraith"},{id:"hero_forge",g:8,name:"McGinnis"},{id:"hero_chrono",g:10,name:"Paradox"},{id:"hero_dynamo",
g:11,name:"Dynamo"},{id:"hero_kelvin",g:12,name:"Kelvin"},{id:"hero_haze",g:13,name:"Haze"},{id:"hero_astro",g:14,name:"Holliday"},{id:"hero_bebop",g:15,name:"Bebop"},{id:"hero_nano",g:16,name:"Calico"},{id:"hero_orion",g:17,name:"Grey Talon"},{id:"hero_krill",g:18,name:"Mo & Krill"},{id:"hero_shiv",g:19,name:"Shiv"},{id:"hero_tengu",g:20,name:"Ivy"},{id:"hero_warden",g:25,name:"Warden"},{id:"hero_yamato",g:27,name:"Yamato"},{id:"hero_lash",g:31,name:"Lash"},{id:"hero_viscous",g:35,name:"Viscous"},
{id:"hero_synth",g:50,name:"Pocket"},{id:"hero_mirage",g:52,name:"Mirage"},{id:"hero_viper",g:58,name:"Vyper"},{id:"hero_magician",g:60,name:"Sinclair"},{id:"hero_vampirebat",g:63,name:"Mina"},{id:"hero_drifter",g:64,name:"Drifter"},{id:"hero_priest",g:65,name:"Venator"},{id:"hero_frank",g:66,name:"Victor"},{id:"hero_bookworm",g:67,name:"Paige"},{id:"hero_doorman",g:69,name:"The Doorman"},{id:"hero_punkgoat",g:72,name:"Billy"},{id:"hero_necro",g:76,name:"Graves"},{id:"hero_fencer",g:77,name:"Apollo"},
{id:"hero_familiar",g:79,name:"Rem"},{id:"hero_werewolf",g:80,name:"Silver"},{id:"hero_unicorn",g:81,name:"Celeste"}],Ha={},Ia={},S=null,U=null,F=null,C=null,B=null,A=null,la=0,T=null,ma="",ea=null,P="",u="",ta=!1,N=!1,O=!1,E=!1,J=null,Ca={},Y="",W="",X="",Ga=!1,Ra=!1,x=!1,Q=0,I=0,H=1,Pa=0,fa=G()+1E4,za="",K=0,L=!1,V="",pa="";try{$.RegisterForUnhandledEvent("ClientUI_FireOutput",eb)}catch(a){}(function(){for(var a=0;a<M.length;a+=1){var b=M[a];Ha[b.id]=b;Ia[String(b.g)]=b.id}})();Oa(!1);for(var ia=
0;ia<Aa.length;ia+=1)try{(function(a){$.Schedule(Aa[ia],function(){Oa(a)})})(ia===Aa.length-1)}catch(a){}})();
