function pd(l){var x=0;return function(){return x<l.length?{done:!1,value:l[x++]}:{done:!0}}}var qd=typeof Object.defineProperties=="function"?Object.defineProperty:function(l,x,y){if(l==Array.prototype||l==Object.prototype)return l;l[x]=y.value;return l};
function re(l){l=["object"==typeof globalThis&&globalThis,l,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var x=0;x<l.length;++x){var y=l[x];if(y&&y.Math==Math)return y}throw Error("Cannot find global object");}var se=re(this);function te(l,x){if(x)a:{var y=se;l=l.split(".");for(var K=0;K<l.length-1;K++){var S=l[K];if(!(S in y))break a;y=y[S]}l=l[l.length-1];K=y[l];x=x(K);x!=K&&x!=null&&qd(y,l,{configurable:!0,writable:!0,value:x})}}
te("Symbol",function(l){function x(ja){if(this instanceof x)throw new TypeError("Symbol is not a constructor");return new y(K+(ja||"")+"_"+S++,ja)}function y(ja,$b){this.jb=ja;qd(this,"description",{configurable:!0,writable:!0,value:$b})}if(l)return l;y.prototype.toString=function(){return this.jb};var K="jscomp_symbol_"+(Math.random()*1E9>>>0)+"_",S=0;return x});
te("Symbol.iterator",function(l){if(l)return l;l=Symbol("Symbol.iterator");qd(Array.prototype,l,{configurable:!0,writable:!0,value:function(){return ue(pd(this))}});return l});function ue(l){l={next:l};l[Symbol.iterator]=function(){return this};return l}function ve(l,x){l instanceof String&&(l+="");var y=0,K=!1,S={next:function(){if(!K&&y<l.length){var ja=y++;return{value:x(ja,l[ja]),done:!1}}K=!0;return{done:!0,value:void 0}}};S[Symbol.iterator]=function(){return S};return S}
te("Array.prototype.values",function(l){return l?l:function(){return ve(this,function(x,y){return y})}});
(function(){var l,x,y,K,S,ja,$b,rd,sd,td,ud,vd,wd,xb;function Td(){if(!(fb||ac||na(0)||na(1)||na(2))){ac=!0;var a=++xd,b=bc;try{$.Schedule(5,function(){ac=!1;a===xd&&Mc.isActive(b)&&(na(0)||na(1)||na(2)||Td())})}catch(c){ac=!1}}}function Sa(){if(Z||yb!==null||!(Aa<0)||zb!==null){for(var a=Aa>=0?Ab[Aa]:"",b=[q,n,p],c=0;c<b.length;c++){var d=b[c];if(d)try{d.RemoveClass("low_hp_pulsing"),a&&d.RemoveClass(a),d.style&&(d.style.animationDuration="",d.style.brightness="")}catch(g){}}Z=0;yb=null;Aa=-1;gb=
oa=Ta=ka=Q=pa=zb=null}}function Ud(a,b){a=yd.G(a,b,zd);if(a.stop)return Sa(),!1;if(!a.g)return!1;if(a.start){Z=1;gb=oa=Ta=ka=Q=pa=null;try{q&&q.AddClass("low_hp_pulsing")}catch(d){}try{p&&p.AddClass("low_hp_pulsing")}catch(d){}}if(yb!==a.duration)try{q&&q.IsValid&&q.IsValid()&&(q.style.animationDuration=a.duration),p&&p.IsValid&&p.IsValid()&&(p.style.animationDuration=a.duration),yb=a.duration}catch(d){yb=null}if(Aa!==a.i){b=Aa>=0?Ab[Aa]:"";var c=Ab[a.i];if(b){try{q&&q.IsValid&&q.IsValid()&&q.RemoveClass(b)}catch(d){}try{p&&
p.IsValid&&p.IsValid()&&p.RemoveClass(b)}catch(d){}}if(c){try{q&&q.IsValid&&q.IsValid()&&q.AddClass(c)}catch(d){}try{p&&p.IsValid&&p.IsValid()&&p.AddClass(c)}catch(d){}}Aa=a.i}if(a.va){try{n&&n.style&&(n.style.animationDuration="",n.style.brightness="")}catch(d){}zb=null;return!1}if(!a.ea||!n||!n.style)return!1;if(zb!==a.U)try{zb=n.style.brightness=a.U}catch(d){zb=null}return a.ja}function Nc(a,b){a=a||I;b=yd.fa(b,Vd);if(b.stop){b=Ua>=0?Ab[Ua]:"";if(a)try{a.RemoveClass("low_hp_pulsing"),b&&a.RemoveClass(b),
a.style&&(a.style.animationDuration="",a.style.brightness="")}catch(g){}Va=0;Ua=-1;N=Oc=null;return!1}if(!b.g)return!1;if(b.start){Va=1;Ua=-1;N=null;try{a&&a.AddClass("low_hp_pulsing")}catch(g){}}if(Ua!==b.i){var c=Ua>=0?Ab[Ua]:"",d=Ab[b.i];try{a&&c&&a.RemoveClass(c),a&&d&&a.AddClass(d)}catch(g){}Ua=b.i}if(Oc!==b.duration)try{a&&a.style&&(a.style.animationDuration=b.duration),Oc=b.duration}catch(g){Oc=null}return b.start}function we(a,b){if(a===!0||a===!1)return a;if(a===1||a==="1")return!0;if(a===
0||a==="0")return!1;if(typeof a==="string"){a=a.toLowerCase();if(a==="true")return!0;if(a==="false")return!1}return!!b}function xe(){if(!cc||!m(cc)){var a=la;for(var b=null,c=0;a&&c<24;){m(a)&&(b=a);var d=null;try{d=a.GetParent?a.GetParent():null}catch(g){d=null}if(!d||d===a)break;a=d;c+=1}cc=b||la||null}a=cc;if(!m(a)||!a.GetAttributeString)return"";try{return String(a.GetAttributeString("hp_colors_minimal_cfg_raw","")||"")}catch(g){}return""}function na(a){return a===0?!!e.hp_enabled:a===1?!!e.hp_friend_enabled:
!!e.hp_level_number_visible}function Bb(a){return!(!Ba[a]||!qa[a])}function ye(a,b){a=Number(a);return!isFinite(a)||a<0?b:a}function v(a,b){return Wa.Xa(a,b)}function Wd(a){if(!a)return!1;var b=!!e.hp_precise_pips_enabled,c=0,d;for(d in a)if(Object.prototype.hasOwnProperty.call(a,d)&&Object.prototype.hasOwnProperty.call(Cb,d)){var g=d;var h=d,k=a[d];if(Object.prototype.hasOwnProperty.call(Cb,h)){var f=Cb[h];if(h==="hp_counter_position"||h==="hp_pulse_text_position")b:if(f=k,h=0,k=200,f&&typeof f===
"object")Array.isArray(f)?(f.length>0&&(h=u(f[0],0,400,0)),f.length>1&&(k=u(f[1],-50,400,200))):(Object.prototype.hasOwnProperty.call(f,"x")&&(h=u(f.x,0,400,0)),Object.prototype.hasOwnProperty.call(f,"y")&&(k=u(f.y,-50,400,200))),f=Math.round(h)+","+Math.round(k);else{if(typeof f==="string"){var z=f.match(/-?\d+(?:\.\d+)?/g);if(z&&z.length>0){h=u(z[0],0,400,0);z.length>1&&(k=u(z[1],-50,400,200));f=Math.round(h)+","+Math.round(k);break b}}typeof f==="number"&&(k=u(f,-50,400,200));f=Math.round(h)+","+
Math.round(k)}else typeof f==="boolean"?f=we(k,f):typeof f==="number"?(h=Number(k),f=isFinite(h)?Math.round(h):f):f=typeof f==="string"?typeof k==="string"&&k.length>0?k:f:k}else f=k;e[g]=f;c+=1}if(!c)return!1;b!==!!e.hp_precise_pips_enabled&&(Pc=null,Qc=0);Rc();try{Sc()}catch(J){}try{r.C()}catch(J){}Db();Tc+=1;Eb=!1;hb=!0;Ca++;Da=da=!0;ib=ra=0;Ea=null;jb=Fb=-1;dc();Xd();Wa.D(0,.01);Wa.D(1,.01);Wa.D(2,.01);return!0}function Yd(){var a=kb.zb();if(!a)return!1;if(a===Uc&&hb)return Ad.Aa("shared_same_raw"),
!0;var b=null;try{b=JSON.parse(a)}catch(c){return!1}b=b&&typeof b==="object"?b.values||b:null;if(!b||typeof b!=="object"||!Wd(b))return!1;Uc=a;return!0}function Zd(){if(fb||hb)Eb=!1;else if(!Eb&&!Yd()){Gb+=1;var a=Gb<=8,b=Gb>20,c=Gb===1?"overlay_startup":"overlay_retry",d=!0;!a&&b&&(d=Gb===21||(Gb-20-1)%6===0)&&(c="overlay_late_retry");d&&kb.ib(c);var g=++Tc,h=bc;Eb=!0;$.Schedule(a?.5:b?10:3,function(){Mc.isActive(h)&&g===Tc&&(Eb=!1,Zd())})}}function ze(a){function b(c){c=+c|0;return c<0?0:c>255?
255:c}return"#"+(16777216|b(a[0])<<16|b(a[1])<<8|b(a[2])).toString(16).slice(1)}function Fa(a,b,c){a=a.slice(1);a.length===3&&(a=a[0]+a[0]+a[1]+a[1]+a[2]+a[2]);b=b.slice(1);b.length===3&&(b=b[0]+b[0]+b[1]+b[1]+b[2]+b[2]);a=parseInt(a,16);b=parseInt(b,16);return"#"+(16777216|((a>>16&255)+((b>>16&255)-(a>>16&255))*c|0)<<16|((a>>8&255)+((b>>8&255)-(a>>8&255))*c|0)<<8|(a&255)+((b&255)-(a&255))*c|0).toString(16).slice(1)}function A(a){if(typeof a!=="string")return"";a=a.trim();if(!a)return"";if(a.charAt(0)===
"#")return a.length===4?("#"+a.charAt(1)+a.charAt(1)+a.charAt(2)+a.charAt(2)+a.charAt(3)+a.charAt(3)).toLowerCase():a.length>=7?a.slice(0,7).toLowerCase():a;var b=a.match(/^rgba?\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)/i);return b?ze([b[1],b[2],b[3]]):a}function ec(){return e.hp_team_colors?Xa===2?"#6485FC":"#FFC961":e.hp_color_high}function Bd(a,b,c){return e.hp_text_color_mode?a<=b?e.hp_text_color_low:a<=c?e.hp_text_color_mid:e.hp_text_color_high:a<=b?e.hp_color_low:a<=c?e.hp_color_mid:ec()}function m(a){try{return!(!a||
a.IsValid&&!a.IsValid())}catch(b){}return!1}function dc(){Hb=null;fc="";hc=ic=0}function Vc(a){a=a||"any";hc=0;var b=R(),c;if(c=fc===a&&m(Hb)){c=b-ic;var d=a,g=R();c=c<=(T&&g<=T?80:d==="friend"?160:Ya>=8||Ga>=8?300:120)}if(c)return Hb;c=la.FindChildTraverse("unit_healthbar_lagging");if(Ib.Va(c,a)||m(w)&&(c=w.FindChildTraverse("unit_healthbar_lagging"),Ib.Va(c,a)))return Hb=c,fc=a,ic=b,c;Hb=null;fc=a;ic=b;return null}function O(a){try{return!(!a||!a.IsValid||a.IsValid())}catch(b){}return!1}function Wc(a){try{return a&&
a.actuallayoutwidth!==void 0?a.actuallayoutwidth|0:0}catch(b){}return 0}function Cd(a){try{return a&&a.GetParent?a.GetParent():null}catch(b){}return null}function $d(){return Ga>=8?2500:Ga>=3?1800:Ya>=8?2500:Ya>=3?1800:1200}function Ae(a,b){if(!b){if(jc&&a<jc)return!1;b=T&&a<=T?180:$d();jc=a+b}if(!ea||!ea.Children)return!1;try{var c=ea.Children()}catch(k){return!1}a=q;b=ae(q,-1);for(var d=0;d<c.length;d++){var g=c[d];if(m(g)){var h="";try{h=String(g.id||"")}catch(k){h=""}h==="unit_healthbar_lagging"&&
(h=ae(g,d),h>b&&(a=g,b=h))}}return a&&a!==q?be(a):!1}function Dd(a,b){var c=0,d=0,g=0;for(b=b||Xc;a&&g<b&&!(a.BHasClass&&(c||(a.BHasClass("team2")?c=2:a.BHasClass("team1")&&(c=1)),d&1||!a.BHasClass("enemy")||(d|=1),d&2||!a.BHasClass("team_neutral")||(d|=2),d&4||!(a.BHasClass("building")||a.BHasClass("destroyable_building")||a.BHasClass("guardian")||a.BHasClass("boss_tier1")||a.BHasClass("boss_tier2")||a.BHasClass("boss_tier_01")||a.BHasClass("boss_tier_02")||a.BHasClass("boss_tier_01_brazier_guardian")||
a.BHasClass("boss_barracks"))||(d|=4),d&8||!a.BHasClass("friend")||(d|=8),c&&d&15))&&a.GetParent;)a=a.GetParent(),g++;return c<<8|d}function ae(a,b){if(!m(a))return-1;var c=Wc(a),d=Wc(Cd(a)),g=d>0,h=g?120:-200,k=Dd(a,Xc)&255;k&1&&!(k&2)?h+=g?700:120:k&8?h-=160:k&2?h-=120:k&15||(h-=40);h=a===q?h+(g?80:-40):h+100;c>0&&(h+=40);d>0&&(h+=Math.min(d,400)/20);b>=0&&(h+=Math.min(b,20));return h}function be(a){E=ea=(aa=q=a)&&a.GetParent?a.GetParent():null;ba=Ha=Za=0;dc();kc=lb=Xa=0;lc=null;Sc();sa=Jb=$a=-1;
Ya=0;mc=-1;r.R();return!0}function Db(){var a=R(),b=a+1600;T&&a<=T?b>T&&(T=b):(T=b,jc=nc=0)}function ce(a){return T&&a<=T||Ga||fa&&fa<4||ta&&ta<4?!0:lb&2?fa<4:lb&4?e.hp_skip_buildings?ta<4:fa<4:lb&1?!1:fa<4}function Kb(a,b){var c=(a=a||I)&&a.IsValid&&a.IsValid()?de(a):0;oc=!1;mb=0;Ia=Ja=Ka=nb=N=null;ab=ob=pb=-1;Ed=U=0;Lb=null;Mb=Nb=0;Nc(a,!1);if(b&&a&&a===I&&Ib.P(c)&&a.style){b=c&4?"#ffffff":"#FFEFD7";try{a.style.washColor=b,N=A(b),nb=b}catch(d){nb=N=null}if(V&&V.style)try{V.style.washColor=""}catch(d){}if(W&&
W.style)try{W.style.washColor=""}catch(d){}if(X&&X.style)try{X.style.backgroundColor=""}catch(d){}}}function de(a){var b=R();if(a===Lb&&b-Nb<Be)return Mb;var c=Dd(a,Xc)&255;Lb=a;Nb=b;return Mb=c}function Fd(a,b){if(!a||!a.Children)return null;try{var c=a.Children();for(a=0;a<c.length;a++){var d=c[a];if(d&&d.id===b)return d}}catch(g){}return null}function u(a,b,c,d){a=Number(a);isFinite(a)||(a=Number(d));isFinite(a)||(a=0);isFinite(b)&&a<b&&(a=b);isFinite(c)&&a>c&&(a=c);return a}function pc(a){return u(a,
0,100,0)|0}function Rc(){var a=pc(e.hp_low_threshold),b=pc(e.hp_high_threshold);b<a&&(b=a);var c=e.hp_kill_zone_width|0;c<1&&(c=1);c>100&&(c=100);var d=u(e.hp_counter_size,72,400,145);l=a;x=b;y=Math.max(1,b-a);K=Math.max(1,100-b);S=pc(e.hp_pulse_threshold);ja=pc(e.hp_friend_pulse_threshold);$b=d;rd=u(e.hp_pulse_text_scale,72,320,d);sd=ee(e.hp_counter_position,!0);td=ee(e.hp_pulse_text_position,!1);ud=Math.round(u(e.hp_healthbar_height,0,230,130));vd=pc(e.hp_kill_zone_threshold);wd=c;xb=e.hp_kill_zone_color||
"#FF2222";fe=A(xb)}function Ce(a){a:{if(a&&a.style&&N)try{var b=A(String(a.style.washColor||""))!==N;break a}catch(c){}b=!1}if(b)return!0;if(V&&V.style&&Ka)try{if(A(String(V.style.washColor||""))!==Ka)return!0}catch(c){}if(W&&W.style&&Ja)try{if(A(String(W.style.washColor||""))!==Ja)return!0}catch(c){}if(X&&X.style&&Ia)try{if(A(String(X.style.backgroundColor||""))!==Ia)return!0}catch(c){}return!1}function bb(a,b){if((!B||!m(B))&&a&&e.hp_kill_zone_enabled&&w&&w.FindChildTraverse)try{B=w.FindChildTraverse("hp_kill_zone_marker")}catch(k){}if(B&&
B.style){var c=!L||!L.style||La!=="visible"||Ma!=="1.0";if(!a||!e.hp_kill_zone_enabled||b<=0||c){if(Yc=null,Na!=="collapse"&&(Na=B.style.visibility="collapse"),ua!=="0")try{ua=B.style.opacity="0"}catch(k){ua=null}}else{a=vd;c=wd;var d=Math.round(b*a/100-c/2);d<0&&(d=0);d>b-c&&(d=Math.max(0,b-c));d+="px";var g=c+"px";Zc!==xb&&(Zc=xb,Gd=fe);var h=Gd;b=b+"|"+a+"|"+c+"|"+xb+"|"+h+"|"+La+"|"+Ma;if(Yc!==b||Na!=="visible"||ua!=="0.95"||qc!=="1000"||$c!==d||ad!==g||rc!==h){Yc=b;Na!=="visible"&&(Na=B.style.visibility=
"visible");if(ua!=="0.95")try{ua=B.style.opacity="0.95"}catch(k){ua=null}if(qc!=="1000")try{qc=B.style.zIndex="1000"}catch(k){qc=null}$c!==d&&($c=B.style.marginLeft=d);ad!==g&&(ad=B.style.width=g);if(rc!==h)try{rc=B.style.backgroundColor=h}catch(k){rc=null}}}}}function ee(a,b){var c=0,d=200;b=b?-200:0;if(a&&typeof a==="object")return Array.isArray(a)?(a.length>0&&(c=u(a[0],0,400,0)),a.length>1&&(d=u(a[1],b,400,200))):(Object.prototype.hasOwnProperty.call(a,"x")&&(c=u(a.x,0,400,0)),Object.prototype.hasOwnProperty.call(a,
"y")&&(d=u(a.y,b,400,200))),{x:c,y:d};if(typeof a==="string"){var g=a.match(/-?\d+(?:\.\d+)?/g);if(g&&g.length>0)return c=u(g[0],0,400,0),g.length>1&&(d=u(g[1],b,400,200)),{x:c,y:d}}typeof a==="number"&&(d=u(a,b,400,200));return{x:c,y:d}}function Hd(a){if(n&&n.style){a=!!(a&&e.hp_pulse_enabled&&e.hp_pulse_text_enabled);var b=$b||u(e.hp_counter_size,72,400,145);b=a?rd||u(e.hp_pulse_text_scale,72,320,b):b;var c=a?td:sd,d=u(c.x,0,400,0),g=u(c.y,-50,400,200);c=b+"px";var h="100%";if(a){a=130;try{var k=
n.GetParent?n.GetParent():null;k&&k.actuallayoutheight>0&&(a=k.actuallayoutheight)}catch(f){}h=Math.max(a,Math.round(b*1.85))+"px"}k="translate3d("+Math.round(d)+"px, "+Math.round(Math.max(g-150,-200))+"px, 0px)";qb!==c&&(qb=n.style.fontSize=c);rb!==h&&(rb=n.style.height=h);M&&M.style&&sb!==k&&(sb=M.style.transform=k)}}function Ob(a){if(n&&n.style){var b=a?"visible":"collapse";if(cb!==b)try{cb=n.style.visibility=b}catch(c){cb=null}a||(Pb=Qb=-1,Oa=!1)}}function bd(a,b){if(cd!==String(a||"")+"|"+(b?
"clear":"set")+"|"+cb+"|"+Na+"|"+ua+"|"+La+"|"+Ma+"|"+Z||Z)Sa(),r.hb(),Ob(!1),bb(!1,0),r.T(a||""),b?r.Ca():r.ba(a||""),r.xa("#ffffff"),r.S(!0),cd=String(a||"")+"|"+(b?"clear":"set")+"|"+cb+"|"+Na+"|"+ua+"|"+La+"|"+Ma+"|"+Z}function ge(){Sa();Ob(!1);bb(!1,0);r.S(!0);r.Ca()}function Sc(){var a="";try{Pa&&(a=Pa.text||Pa.GetAttributeString("text","")||"")}catch(b){a=""}if(q!==sc||ea!==tc||E!==uc||n!==vc||L!==wc||B!==xc||C!==yc||F!==zc||G!==Ac||H!==Bc||a!==Cc)sc=q,tc=ea,uc=E,vc=n,wc=L,xc=B,yc=C,zc=F,Ac=
G,Bc=H,Cc=a,va++,jb=Fb=mc=-1,Dc=Id=R(),r.C(),Sa(),oc=!1,Ia=Ja=Ka=N=X=W=V=ha=D=Y=dd=I=null,ab=ob=pb=-1,tb=mb=U=0,Ea=null,sa=Jb=$a=-1,Pc=null,Qc=0,ed=-1,Ya=ta=Rb=fa=Ga=Sb=0,Oa=!1,Ec=Fc=null,Da=da=!0,ib=ra=0,Db()}function Jd(a,b){na(a)&&!Ba[a]&&(Ba[a]=!0,v(a,b||.05,a===0?"enemy_paint":a===1?"ally_paint":"level_poll"))}function Gc(a,b){if(b)if(a===0){Sa();if(q&&q.style)try{q.style.washColor=""}catch(c){}if(p&&p.style)try{p.style.washColor=""}catch(c){}if(n&&n.style)try{n.style.washColor=""}catch(c){}Ta=
pa=oa=Q=gb=ka=null;bb(!1,0);L&&L.style&&(La!=="collapse"&&(La=L.style.visibility="collapse"),Ma!=="0"&&(Ma=L.style.opacity="0"));if(n&&n.style){try{n.style.fontSize="",n.style.height="",n.style.washColor=""}catch(c){}Ta=pa=rb=qb=null}if(F&&F.style)try{F.style.washColor=""}catch(c){}if(G&&G.style)try{G.style.washColor=""}catch(c){}if(H&&H.style)try{H.style.backgroundColor=""}catch(c){}Tb=Ub=Vb=wa=xa=ya=null;M&&M.style&&(M.style.transform="",sb=null);ed=sa=Jb=$a=-1;Ya=ta=Rb=fa=Ga=Sb=0;r.R()}else if(a===
1)Kb(I,!0),I=null;else{if(!P||!P.IsValid())if(ia&&ia.IsValid()||(ia=la.FindChildTraverse("UnitStatus")),ia)for(b=ia;b;){if(b.BHasClass&&b.BHasClass("enemy")){P=b;break}if(!b.GetParent)break;b=b.GetParent()}if(P&&P.IsValid&&P.IsValid()){try{P.RemoveClass(Kd)}catch(c){}for(b=0;b<4;b++)try{P.RemoveClass(Wb[b].F)}catch(c){}}Ea=!1;fd=-1;Hc=0}Ba[a]=!1;Xb[a]=!1;qa[a]=0;Yb[a]++}function Xd(){Rc();e.hp_enabled?Jd(0):Gc(0,!0);e.hp_friend_enabled?Jd(1):Gc(1,!0);e.hp_level_number_visible?Jd(2):Gc(2,!0);e.hp_counter_visible||
(Ob(!1),Pb=Qb=-1);!e.hp_pulse_enabled&&Z&&Sa();Z?(yb=null,Aa=-1,Ud(!0,R())):e.hp_pulse_text_enabled||(Oa=!1,Hd(!1));!e.hp_friend_pulse_enabled&&Va&&Nc(D,!1);e.hp_kill_zone_enabled||bb(!1,0);if(C&&C.style&&!e.hp_pip_visible&&db!=="collapse")try{db=C.style.visibility="collapse"}catch(a){db=null}Td()}function De(){Ba[0]=!0;try{if(e.hp_enabled){var a=R(),b=!1;if(Za||q)if(O(w)||O(n)||O(M)||O(L)||O(C)||O(aa)||O(E)||O(q)||O(ea)||O(F)||O(G)||O(H)||O(p)||O(B)||O(Y)||O(ca)||O(Pa))w=n=M=L=C=aa=E=q=ea=F=G=H=
p=B=Y=ca=Pa=null,ba=Ha=Za=0,sc=tc=uc=zc=Ac=Bc=vc=wc=xc=yc=null,Cc="",r.C(),Da=da=!0,dc(),Db();if(m(q))ce(a)&&(b=r.Ab(a,!1));else{if(!gd||a>=gd)gd=(q=Vc("any"))?0:a+150;if(!q){v(0,.15,"enemy_probe_missing_bar");return}}var c;if(!(c=Za))a:{if(Za){var d=!e.hp_counter_visible||m(n);if(!(!(m(w)&&d&&m(L)&&m(C)&&m(aa)&&m(E))||M&&!m(M)||F&&!m(F)||G&&!m(G)||H&&!m(H)||p&&!m(p)||B&&!m(B)||Y&&!m(Y)||ca&&!m(ca))&&m(Pa)){c=1;break a}ba=Za=0}var g=R();if(ba&&g<ba)var h=0;else Ha++,m(w)||(w=la.FindChildTraverse("UnitStatus")),
w?(m(n)||!e.hp_counter_visible&&cb==="collapse"||(n=w.FindChildTraverse("hp_counter")),e.hp_counter_visible&&!m(M)&&(M=w.FindChildTraverse("hp_counter_anchor")),m(L)||(L=w.FindChildTraverse("unit_healthbar_bg")),m(C)||(C=w.FindChildTraverse("unit_healthbar_pip_label")),m(aa)||(aa=w.FindChildTraverse("unit_healthbar_lagging")),e.hp_kill_zone_enabled&&!m(B)&&(B=w.FindChildTraverse("hp_kill_zone_marker")),m(p)||(p=w.FindChildTraverse("unit_ult_ready_icon")),m(Y)||(Y=w.FindChildTraverse("InfoHealthContainer")),
m(ca)||(ca=w.FindChildTraverse("UnitHealthbarContainer")),m(Pa)||(Pa=la.FindChildTraverse("name")),m(p)&&(Qa=0),aa&&!m(E)&&(E=aa.GetParent()),!m(F)&&E&&E.FindChildTraverse&&(F=E.FindChildTraverse("unit_healthbar_healing")),!m(G)&&E&&E.FindChildTraverse&&(G=E.FindChildTraverse("unit_healthbar_delta")),!m(H)&&E&&E.FindChildTraverse&&(H=E.FindChildTraverse("unit_healthbar_bullet_shield")),C&&aa&&E?(Za=1,ba=Ha=0,h=1):(ba=g+(Ha<8?150:Ha<24?500:1500),h=0)):(ba=g+(Ha<8?150:Ha<24?500:1500),h=0);c=h}if(c){if(q.GetParent){var k=
q.GetParent();ea!==k&&(ea=k)}!b&&ce(a)&&Ae(a,!1);Sc();var f=Ib.fb(q,ea,he),z=f.Y;b=ie;Fb!==Ca&&(Fb=Ca,da=!0,ra=0,r.C());if(f.da!==Ec||f.flags!==Fc)Ec=f.da,Fc=f.flags,r.C(),da=!0,ra=a,Da=!0,ib=a,Ea=null,Db();if(e.hp_skip_buildings&&f.X)t.ya=!!e.hp_skip_buildings,t.W=!!e.hp_friend_enabled,t.ha=ta+1,b=Ic.O(f,a,t,b),ta++,fa=0,f.K||f.L?(bd("#ffffff",!0),e.hp_friend_enabled&&ge()):bd(f.I,!1),v(0,b.delay,b.reason);else if(c=da,z&&a-Dc>=5E3&&(Dc=a,r.Ha()&&(r.C(),da=!0,ra=a,c=!0)),f.Z)t.Oa=Rb+1,b=Ic.O(f,a,
t,b),Sa(),Rb++,ta=fa=0,r.S(!0),bb(!1,0),Ob(!1),r.T(f.I),r.ba(f.I),hd=a,v(0,b.delay,b.reason);else if(z){ta=Rb=fa=0;if(da){if(a<ra){v(0,.05,"enemy_dirty_hold");return}Rc();r.S(!z||!!e.hp_bg_visible);e.hp_counter_visible?Hd(Oa):Ob(!1);r.bb();Dc=R();r.R();sa=$a=-1;da=!1;ra=0}if(hb){var J=f.u,ma=f.o;t.ya=!!e.hp_skip_buildings;t.W=!!e.hp_friend_enabled;t.Ya=!!da;t.Za=a<ra;t.ra=!!hb;t.ca=!1;t.u=J;t.o=ma;t.La=$a;t.Ma=Jb;t.Na=hd;t.low=l;t.na=sa;t.sa=!!Z;t.ta=!!e.hp_pulse_text_enabled;t.Sa=!!e.hp_pulse_enabled;
t.Ta=S;t.Ba=!!c;t.Da=mc;t.Qa=va;t.aa=Ga+(ma<=0?1:0);b=Ic.O(f,a,t,b);var eb=!(!Z||!e.hp_pulse_text_enabled);if(J!==$a||ma!==Jb||eb||c||mc!==va)if(Ya=0,$a=J,Jb=ma,hd=a,ma<=0)Ga++,r.T(ec()),bb(!1,0),v(0,b.delay,b.reason);else{Ga=0;e.hp_kill_zone_enabled?bb(!0,ma):Na!=="collapse"&&bb(!1,0);f=J/ma*100|0;z=l;J=S;var Ra=!!(e.hp_pulse_enabled&&f<=J);if(!(Math.abs(f-sa)<3&&f>z&&sa>z)||e.hp_pulse_text_enabled&&(Z||Ra)||c){z=sa;f===ed?Sb++:(Sb=0,ed=f);sa=f;var Jc=!!e.hp_counter_visible,je=e.hp_counter_format|
0;J="";if(ma=!!C)try{Jc&&je!==1&&(J=C.text||C.GetAttributeString("text","")||"")}catch(Ee){J="",db=null}Jc=!!(Jc&&aa&&E);var id=eb=0;Jc&&je!==1&&(eb=aa.actuallayoutwidth||0,id=E.actuallayoutwidth||0);var Fe=yd.G(Ra,R(),zd),ub=Ge.G(f,Fe,ma,J,Jc,eb,id,ke);ub.ka&&r.cb(ub.qa);ub.N===1?r.ab(ub.current,ub.max,ub.oa):ub.N===2&&r.wa(!1);var za=He.G(f,z,a,Ra,le);r.S(za.ga);za.ia&&Sa();r.T(za.M);r.Db(za.l,za.j,za.A);r.ba(za.M);r.xa(za.V);var Ld=za.za?-1:za.m;if(Ld<0)v(0,.05,"enemy_dirty_hold");else{var me=
Ud(Ra,a);me&&(Ld=.1);mc=va;v(0,Ld,me?"enemy_pulse":"enemy_paint")}}else v(0,b.delay,b.reason)}else{Ya++;if(z&&a>=Md){Md=a+(jd>=8?950:jd>=3?700:350);if(r.Ga()){r.R();r.C();da=!0;ra=a;sa=$a=-1;v(0,.05,"enemy_style_drift");return}jd++}v(0,b.delay,b.reason)}}else r.T("#E16161"),r.ba("#E16161"),r.xa("#ffffff"),t.ra=!1,b=Ic.O(f,a,t,b),v(0,b.delay,b.reason)}else{fa++;ta=Rb=0;id=!(!f.K&&!f.L||!e.hp_friend_enabled);t.W=!!e.hp_friend_enabled;t.pa=fa;b=Ic.O(f,a,t,b);if(f.K||f.L){if(bd("#ffffff",!0),id)a:if(ge(),
e.hp_friend_enabled){if(oc&&qa[1]&&qa[1]>a){if(qa[1]-a<=250)break a;if(I&&m(I)){if(Nd&&a-Nd<3E3)break a;Nd=a;break a}}Od&&a-Od<2500||(Od=a,Wa.D(1,.01))}}else bd(f.I,!1);hd=a;v(0,b.delay,b.reason)}}else v(0,ba&&ba>a?Math.max(.15,(ba-a)/1E3):.15,"enemy_cache_missing")}else Gc(0,!0)}catch(Ee){v(0,.5,"enemy_error")}finally{}}function Ie(){vb&&vb.IsValid()||(vb=la.FindChildTraverse("unit_level_label"));ia&&ia.IsValid()||(ia=la.FindChildTraverse("UnitStatus"));if(ia&&(!P||!P.IsValid()))for(var a=ia;a;){if(a.BHasClass&&
a.BHasClass("enemy")){P=a;break}if(!a.GetParent)break;a=a.GetParent()}if(!vb||!ia||!P)return!1;a=!!e.hp_level_number_visible;Ea!==a&&(a?P.AddClass(Kd):P.RemoveClass(Kd),Ea=a);if(!a)return!1;a="";try{a=vb.text||vb.GetAttributeString("text","")||""}catch(c){a=""}a=ne.parse(a);if(a===fd||!a)return!1;fd=a;for(var b=0;b<Wb.length;b++)P.RemoveClass(Wb[b].F);(a=ne.eb(a))&&P.AddClass(a);return!0}function Je(){Ba[1]=!0;try{if(e.hp_friend_enabled){var a=R();if(!D||!D.IsValid()){Kb(I,!1);ha=D=I=null;D=Vc("friend");
if(!D){Pd++;if(hc&4){v(1,2.5,"ally_missing_building");return}if(hc){v(1,1.2,"ally_missing_rejected");return}v(1,Pd>75?3:.2,"ally_missing_bar");return}Lb=null;Mb=Nb=0}Pd=0;if(D.GetParent){var b=D.GetParent();ha!==b&&(ha=b,Ia=Ja=Ka=X=W=V=null)}D!==dd&&(dd=D,jb=-1,Da=!0,ib=0,N=null,ab=ob=pb=-1);if(b=jb!==Ca)Da=!0,ib=0,N=null,ab=ob=pb=-1,U=0;if(Da){if(a<ib){v(1,.05,"ally_dirty_hold");return}Da=!1;Kb(I,!1)}var c=Ib.gb(D,oe).flags;if(Ib.P(c)){b&&(jb=Ca);tb=0;var d=D.actuallayoutwidth|0,g=ha&&ha.actuallayoutwidth!==
void 0?ha.actuallayoutwidth|0:0;if(g<=0)mb++,v(1,mb<4?.2:mb<12?.4:.8,"ally_no_parent_width");else{mb=0;if((c=d===pb&&g===ob)&&!Va)if(a>=Ed)if(Ed=a+(U>=3?2500:1200),Ce(D))N=null;else{U++;v(1,kd[Math.min(Math.floor(U/3),4)],"ally_stable");return}else{U++;v(1,kd[Math.min(Math.floor(U/3),4)],"ally_stable");return}pb=d;ob=g;a=d/g*100|0;d=ab;Qd.H=a;var h=Ke.fa(Qd,wb);m(V)||(V=Fd(ha,"unit_healthbar_healing"));m(W)||(W=Fd(ha,"unit_healthbar_delta"));m(X)||(X=Fd(ha,"unit_healthbar_bullet_shield"));var k=h.washColor,
f=h.J;if(nb===k&&N){var z=N;var J=!1}else z=A(k),J=N!==z;if(J&&D)try{N=D.style.washColor=z,nb=k,oc=!0,I=D}catch(Ra){nb=N=null}if(Ka!==h.l&&V&&V.style)try{Ka=V.style.washColor=h.l}catch(Ra){Ka=null}if(Ja!==h.j&&W&&W.style)try{Ja=W.style.washColor=h.j}catch(Ra){Ja=null}if(Ia!==h.A&&X&&X.style)try{Ia=X.style.backgroundColor=h.A}catch(Ra){Ia=null}k=!!Va;var ma=Nc(D,f);k=!f&&k;var eb=h.m;f&&!ma&&!J&&a===d&&c?(U++,eb=kd[Math.min(Math.floor(U/3),4)]):f||J||k||a!==d?U=0:(U++,eb=kd[Math.min(Math.floor(U/3),
4)]);ab=a;v(1,eb,"ally_paint")}}else I===D?(Kb(I,!1),I=null):Va&&Nc(D,!1),U=0,ab=-1,mb=0,tb++,tb===4||tb===12?(Kb(I,!1),Lb=ha=D=I=null,Mb=Nb=0,dc(),v(1,.1,"ally_rebind")):v(1,tb<4?1.2:tb<12?2:3,"ally_unconfirmed")}else Kb(I,!0),I=null,Ba[1]=!1}catch(Ra){v(1,.5,"ally_error")}finally{}}var Cb={hp_enabled:!0,hp_mode:1,hp_low_threshold:25,hp_high_threshold:65,hp_bg_visible:!0,hp_team_colors:!1,hp_info_health_margin_top:23,hp_healthbar_height:130,hp_color_low:"#E16161",hp_color_mid:"#FF7B00",hp_color_high:"#00FF00",
hp_heal_color:"#5fff80",hp_delta_color:"#ffe55b",hp_bullet_shield_color:"#ffffff",hp_counter_visible:!0,hp_counter_size:145,hp_counter_position:"27,20",hp_text_color_mode:0,hp_text_color_low:"#E16161",hp_text_color_mid:"#FF7B00",hp_text_color_high:"#FFFFFF",hp_pulse_bpm:75,hp_pulse_intensity:1,hp_pulse_enabled:!0,hp_pulse_text_enabled:!1,hp_pulse_text_scale:120,hp_pulse_text_position:"20,196",hp_pulse_hide_bar:!1,hp_pulse_color_enabled:!1,hp_pulse_color:"#FF2222",hp_pulse_color_mode:0,hp_skip_buildings:!1,
hp_pulse_threshold:25,hp_counter_format:0,hp_friend_enabled:!1,hp_friend_pulse_enabled:!1,hp_friend_pulse_bpm:75,hp_friend_pulse_intensity:1,hp_friend_pulse_threshold:25,hp_friend_color_low:"#E16161",hp_friend_color_mid:"#FF7B00",hp_friend_color_high:"#00FF00",hp_friend_heal_color:"#5fff80",hp_friend_delta_color:"#504c47",hp_friend_bullet_shield_color:"#ffffff",hp_friend_pulse_color_enabled:!1,hp_friend_pulse_color:"#FF2222",hp_level_number_visible:!0,hp_pip_visible:!0,hp_precise_pips_enabled:!1,
hp_ult_color_enabled:!0,hp_ult_color_custom:"#E16161",hp_kill_zone_enabled:!1,hp_kill_zone_threshold:25,hp_kill_zone_color:"#FF2222",hp_kill_zone_width:3},e={};var fe=xb=wd=vd=ud=td=sd=rd=$b=ja=S=K=y=x=l=void 0;var R=Date.now?Date.now.bind(Date):function(){return+new Date},Ab=["pulse_subtle","","pulse_intense"],Le=[.35,.8,1.5,2.5],kd=[.35,.9,1.8,3,3],Ba=[!1,!1,!1],Xb=[!1,!1,!1],Yb=[0,0,0],qa=[0,0,0],ld=null,bc=1,fb=!1,xd=0,ac=!1,Mc={isActive:function(a){if(fb||a!==void 0&&a!==bc)return!1;if(m(la))return!0;
this.stop();return!1},stop:function(){if(fb)return!1;fb=!0;xd+=1;ac=!1;bc+=1;for(var a=0;a<Yb.length;a+=1)Yb[a]+=1,qa[a]=0,Xb[a]=!1,Ba[a]=!1;Tc+=1;Eb=!1;kc=T=jc=nc=gd=ba=0;Ec=Fc=lc=null;dc();try{$.UnregisterForUnhandledEvent&&ld!==null&&$.UnregisterForUnhandledEvent(pe,ld)}catch(b){}ld=null;try{r.ob()}catch(b){}D=ha=V=W=X=I=dd=cc=Lb=vb=ia=P=null;kc=Mb=Nb=0;sc=tc=uc=vc=wc=xc=yc=zc=Ac=Bc=lc=null;Cc="";fd=-1;Ec=Fc=Ea=null;cd="";N=nb=Ka=Ja=Ia=ka=Q=pa=ya=xa=wa=gb=oa=Ta=Zc=Vb=Ub=Tb=null;pb=ob=ab=-1;oc=
!1;Qb=Pb=-1;Ea=Kc=md=nd=od=cb=null;Lc=-1;Zb=0;Qd.H=0;wb.washColor="";wb.J=!1;wb.l="";wb.j="";wb.A="";wb.m=.35}},t={ya:!1,W:!1,Ya:!1,Za:!1,ra:!0,Ib:!1,ca:!1,u:0,o:0,La:-1,Ma:-1,Na:0,low:0,na:-1,sa:!1,ta:!1,Sa:!1,Ta:0,Ba:!1,Da:0,Qa:0,pa:0,Oa:0,ha:0,aa:0,B:!1},ie={action:0,delay:.25,reason:"enemy_paint",H:0,g:!1,xb:!1,B:!1},Z=0,yb=null,Aa=-1,zb=null,D=null,ha=null,V=null,W=null,X=null,I=null,N=null,nb=null,Ka=null,Ja=null,Ia=null,pb=-1,ob=-1,ab=-1,U=0,oc=!1,Nd=0,mb=0,tb=0,Od=0,Ed=0,Va=0,Ua=-1,Oc=null,
Pd=0,Hb=null,fc="",ic=0,hc=0,zd={g:!1,start:!1,stop:!1,duration:"",i:-1,ea:!1,U:"",va:!1,ja:!1},Vd={g:!1,start:!1,stop:!1,duration:"",i:-1},yd={ua:function(a){a.g=!1;a.start=!1;a.stop=!1;a.duration="";a.i=-1;a.ea=!1;a.U="";a.va=!1;a.ja=!1;return a},G:function(a,b,c){c=this.ua(c||zd);if(!a)return c.stop=Z?!0:!1,c;c.g=!0;c.start=Z?!1:!0;a=u(e.hp_pulse_bpm,30,300,75);c.duration=(60/a).toFixed(3)+"s";c.i=u(e.hp_pulse_intensity,0,2,1)|0;if(!e.hp_pulse_text_enabled)return c.va=!0,c;a=Math.max(1,6E4/a);
b=b%a/a;a=c.i;var d=a===2?.55:a===0?.85:.65;c.ea=!0;c.U=(d+((a===2?2:a===0?1.15:1.5)-d)*(b<.5?b*2:(1-b)*2)).toFixed(2);c.ja=!0;return c},Bb:function(a){a.g=!1;a.start=!1;a.stop=!1;a.duration="";a.i=-1;return a},fa:function(a,b){b=this.Bb(b||Vd);if(!a)return b.stop=Va?!0:!1,b;b.g=!0;b.start=Va?!1:!0;a=u(e.hp_friend_pulse_bpm,30,300,75);b.duration=(60/a).toFixed(3)+"s";b.i=u(e.hp_friend_pulse_intensity,0,2,1)|0;return b}};(function(){for(var a in Cb)Object.prototype.hasOwnProperty.call(Cb,a)&&(e[a]=
Cb[a])})();Rc();var Tc=0,Eb=!1,pe="ClientUI_FireOutput",hb=!1,Gb=0,da=!0,ra=0,Da=!0,ib=0,Dc=0,Uc="",Rd=0,Qa=0,cc=null,Sd="",Ca=0,Fb=-1,jb=-1,dd=null,Lc=-1,Zb=0,Qd={H:0},wb={washColor:"",J:!1,l:"",j:"",A:"",m:.35},kb={Ea:pe,Ra:"HP_COLORS_PRESET_SNAPSHOT",wb:"HP_COLORS_PRESET_REQUEST",Eb:"__hpColorsCfgRaw",Jb:"hp_colors_minimal_cfg_raw",nb:function(){a:{try{if(typeof GameUI!=="undefined"&&GameUI&&GameUI.CustomUIConfig){var a=GameUI.CustomUIConfig();break a}}catch(b){}a=null}return a},yb:function(){return xe()},
zb:function(){var a=this.nb(),b="";try{b=a?String(a[this.Eb]||""):""}catch(c){b=""}return b||this.yb()},ib:function(a){try{return $.DispatchEvent(this.Ea,JSON.stringify({magic_word:this.wb,mod_title:"HP Colors",reason:String(a||"overlay_request")})),!0}catch(b){}return!1},Fb:function(a){return typeof a!=="string"||a.indexOf(this.Ra)!==-1},ub:function(a){try{return typeof a==="string"?JSON.parse(a):a}catch(b){}return null},$a:function(a){return!(!a||a.magic_word!==this.Ra||a.mod_title&&a.mod_title!==
"HP Colors"||!a.values||typeof a.values!=="object")},mb:function(a){var b=typeof a.values_raw==="string"?a.values_raw:"";if(b)return b;try{return JSON.stringify(a.values)}catch(c){}return""}},Ic={Cb:function(a){a.action=0;a.delay=.25;a.reason="enemy_paint";a.H=0;a.g=!1;a.xb=!1;a.B=!1;return a},O:function(a,b,c,d){d=this.Cb(d||ie);var g=!(!a||!a.Y);c.B=!(!a||!a.K&&!a.L||!c.W);if(c.ya&&a&&a.X)return d.action=1,d.reason="enemy_skip_building",d.delay=c.ha<4?.3:c.ha<12?.6:1.5,d;if(a&&a.Z)return d.action=
2,d.reason="enemy_neutral",d.delay=c.Oa<4?.75:1.5,d;if(!g)return d.action=3,d.B=c.B,d.reason=c.B?"enemy_friend_target":"enemy_not_enemy",d.delay=c.B?c.pa<4?.2:2:c.pa<4?.2:1.25,d;if(c.Ya&&c.Za)return d.action=4,d.reason="enemy_dirty_hold",d.delay=.05,d;if(!c.ra)return d.action=5,d.reason="enemy_preset_wait",d.delay=.05,d;if(c.ca)return d.action=7,d.reason="enemy_style_drift",d.delay=.05,d;if(c.o<=0)return d.action=6,d.reason="enemy_no_parent_width",d.delay=c.aa<3?.18:c.aa<6?.75:c.aa<10?1.5:2.5,d;a=
!(!c.sa||!c.ta);if(c.u===c.La&&c.o===c.Ma&&!a&&!c.Ba&&c.Da===c.Qa)return d.action=7,d.reason="enemy_stable",d.delay=b-c.Na>2E3?1.5:.25,d;b=c.o>0?c.u/c.o*100|0:0;d.H=b;d.g=!!(c.Sa&&b<=c.Ta);if(Math.abs(b-c.na)<3&&b>c.low&&c.na>c.low&&(!c.ta||!c.sa&&!d.g)&&!c.Ba)return d.action=8,d.reason="enemy_small_delta",d.delay=.25,d;d.action=9;d.reason=d.g?"enemy_pulse":"enemy_paint";d.delay=.15;return d}},Ad={Gb:function(a,b){return b?b.Hb?!1:!!(b.rb||b.sb||b.kb||b.pb||b.ca):!0},qb:function(a,b){Rd=b;Lc=va;Zb=
b},Aa:function(a){var b=R();if(Zb){b-Zb>=5E3&&(Zb=b);var c=Lc!==va||e.hp_enabled&&Fb!==Ca||e.hp_friend_enabled&&jb!==Ca||e.hp_enabled&&!Bb(0)||e.hp_friend_enabled&&!Bb(1)||e.hp_level_number_visible&&!Bb(2)?!1:!0}else c=!1;if(!c){Zb=b;c=va;try{Sc()}catch(d){}c=va!==c?"panel_changed":Lc!==va?"panel_unseen":e.hp_enabled&&Fb!==Ca||e.hp_friend_enabled&&jb!==Ca?"generation_pending":e.hp_enabled&&!Bb(0)||e.hp_friend_enabled&&!Bb(1)||e.hp_level_number_visible&&!Bb(2)?"loop_stopped":b-Dc>=5E3&&r.Ha()?"style_drift":
"";this.Gb(a,{rb:c==="panel_changed",sb:c==="panel_unseen",kb:c==="generation_pending",pb:c==="loop_stopped",ca:c==="style_drift",Hb:!c})?Rd&&b-Rd<250||(this.qb(a,b),Da=da=!0,ib=ra=0,Ea=null,Db(),Wa.D(0,.01),Wa.D(1,.01),Wa.D(2,.01)):c||(Lc=va)}}},Wa={Xa:function(a,b,c){if(!na(a)||fb)return!1;b=ye(b,.05);var d=R()+b*1E3;if(qa[a]&&qa[a]<=d)return!1;qa[a]=d;var g=++Yb[a],h=bc;$.Schedule(b,function(){Mc.isActive(h)&&g===Yb[a]&&(qa[a]=0,c&&c(),na(a)&&(a===0?De():a===1?Je():e.hp_level_number_visible?(Ba[2]=
!0,Hc=Ie()?0:Hc+1,v(2,Hc>10?5:.5,Hc>10?"level_backoff":"level_poll")):Gc(2,!0)))});return!0},D:function(a,b){!na(a)||Xb[a]||fb||(Xb[a]=!0,this.Xa(a,b===void 0?.01:b,function(){Xb[a]=!1})||(Xb[a]=!1))}};try{ld=$.RegisterForUnhandledEvent(kb.Ea,function(a){if(Mc.isActive()&&kb.Fb(a))try{if(hb&&typeof a==="string"&&a===Sd)Ad.Aa("event_duplicate_payload");else{var b=kb.ub(a);if(kb.$a(b)){var c=kb.mb(b);c&&c===Uc&&hb?(typeof a==="string"&&(Sd=a),Ad.Aa("event_payload_same_raw")):Wd(b.values)&&(c&&(Uc=c),
typeof a==="string"&&(Sd=a))}}}catch(d){}})}catch(a){}var la=$.GetContextPanel(),w=null,n=null,M=null,L=null,C=null,aa=null,E=null,q=null,ea=null,F=null,G=null,H=null,p=null,B=null,Y=null,ca=null,Pa=null,Za=0,Ha=0,ba=0,gd=0,nc=0,jc=0,T=0,Md=0,jd=0,La=null,Ma=null,qb=null,rb=null,sb=null,Kc=null,md=null,nd=null,od=null,db=null,he={Pa:null,parent:null,da:0,flags:0,Y:!1,Z:!1,X:!1,K:!1,L:!1,Ja:!1,Ia:!1,I:"#E16161",u:0,o:0,Wa:!1},oe={Pa:null,parent:null,da:0,flags:0,Y:!1,Z:!1,X:!1,K:!1,L:!1,Ja:!1,Ia:!1,
I:"#FFEFD7",u:0,o:0,Wa:!1},Ib={Ua:function(a){return Dd(a,Xc)},fb:function(a,b,c){c=c||he;var d=R();if(a!==lc||d-kc>=Me){var g=this.Ua(a);Xa=g>>8;lb=g&255;Xa&&lb&8&&(qe=Xa);kc=d;lc=a}return this.Fa(a,b,Xa,lb,c)},gb:function(a,b){b=b||oe;var c=de(a),d=c>>8;c&=255;return this.Fa(a,a&&a.GetParent?a.GetParent():null,d,c,b)},Fa:function(a,b,c,d,g){var h=this.P(d),k=this.ma(d,c),f=this.la(d,c);g.Pa=a||null;g.parent=b||null;g.da=c||0;g.flags=d||0;g.Y=this.Ka(d,c);g.Z=!!(d&2);g.X=!!(d&4);g.K=h;g.L=k;g.Ja=
f;g.Ia=h||k;g.I=this.lb(d,c);g.u=a&&a.actuallayoutwidth!==void 0?a.actuallayoutwidth|0:0;g.o=b&&b.actuallayoutwidth!==void 0?b.actuallayoutwidth|0:0;g.Wa=a!==null&&a!==aa;return g},P:function(a){return!!(a&8)},ma:function(a,b){b=b||Xa;return!!(a&4&&(a&8||b&&b===qe))},la:function(a,b){b=b||Xa;return!(!(a&4)||a&2||!b||this.ma(a,b))},Ka:function(a,b){return a&2||e.hp_friend_enabled&&this.P(a)?!1:a&1?!0:this.la(a,b)},lb:function(a,b){return a&1&&!(a&2)?"":this.la(a,b)?"#E16161":this.ma(a,b)?"#ffffff":
a&6?"#5BEFB5":a&8?"#FFEFD7":b===2?"#5B79E6":b===1?"#E7B659":"#E16161"},Va:function(a,b){if(!m(a))return!1;if(b==="any")return!0;a=this.Ua(a)&255;if(b==="friend"){if(this.P(a))return!0;hc=a;return!1}return b==="enemy"?this.Ka(a):!0}},Xa=0,lb=0,qe=0,kc=0,lc=null,Me=500,Xc=24,ka=null,Q=null,pa=null,ya=null,xa=null,wa=null,gb=null,oa=null,Ta=null,Zc=null,Vb=null,Ub=null,Tb=null,Qb=-1,Pb=-1,cb=null,Pc=null,Qc=0,Oa=!1,sc=null,tc=null,uc=null,vc=null,wc=null,xc=null,yc=null,zc=null,Ac=null,Bc=null,Cc="",
Id=0,va=0,mc=-1,Ec=null,Fc=null,cd="",r={Ab:function(a,b){a:{if(!b){if(nc&&a<nc){b=!1;break a}nc=a+(T&&a<=T?180:$d())}a=b?Vc("any"):Vc("enemy");if(m(a)&&a!==q){var c=Wc(Cd(a)),d=Wc(Cd(q));b=c<=0&&d>0||c<=0&&!b?!1:be(a)}else b=!1}return b},ob:function(){sc=tc=uc=vc=wc=xc=yc=zc=Ac=Bc=w=n=M=L=C=aa=E=q=ea=F=G=H=p=B=Y=ca=Pa=null;Cc="";ba=Ha=Za=0;Db()},C:function(){Na=$c=ad=Gd=rc=ua=qc=Yc=La=Ma=qb=rb=sb=Kc=md=nd=od=db=gb=oa=Ta=Zc=Vb=Ub=Tb=ka=Q=pa=ya=xa=wa=null;Pb=Qb=-1;cb=null;cd="";this.R()},bb:function(){var a=
-15+u(e.hp_info_health_margin_top,0,100,23)*.65;Math.abs(a)<.5&&(a=0);a=Math.round(a*10)/10;Math.abs(a-Math.round(a))<.01&&(a=Math.round(a));a+="%";Y&&Y.IsValid()||!w||!w.IsValid()||(Y=w.FindChildTraverse("InfoHealthContainer"));if(Y&&Y.style&&Kc!==a)try{Kc=Y.style.marginTop=a}catch(c){Kc=null}ca&&ca.IsValid()||!w||!w.IsValid()||(ca=w.FindChildTraverse("UnitHealthbarContainer"));a=ud||Math.round(u(e.hp_healthbar_height,0,230,130));var b=a+"px";ca&&ca.style&&md!==b&&(md=ca.style.height=b);C&&C.style&&
(a=Math.min(75,Math.round(a*75/230))+"px",nd!=="52%"&&(nd=C.style.height="52%"),od!==a&&(od=C.style.fontSize=a))},T:function(a){if(gb!==a||ka===null){var b=A(a);b||(b="");gb=a;if(ka!==b&&q)try{ka=q.style.washColor=b}catch(c){ka=null}}},Db:function(a,b,c){if(Vb!==a||ya===null)if(Vb=a,a=A(a)||"#5fff80",ya!==a&&F&&F.style)try{ya=F.style.washColor=a}catch(d){ya=null}if(Ub!==b||xa===null)if(Ub=b,b=A(b)||"#ffe55b",xa!==b&&G&&G.style)try{xa=G.style.washColor=b}catch(d){xa=null}if(Tb!==c||wa===null)if(Tb=
c,c=A(c)||"#ffffff",wa!==c&&H&&H.style)try{wa=H.style.backgroundColor=c}catch(d){wa=null}},hb:function(){if(F&&F.style)try{F.style.washColor=""}catch(a){}if(G&&G.style)try{G.style.washColor=""}catch(a){}if(H&&H.style)try{H.style.backgroundColor=""}catch(a){}Vb=Ub=Tb=ya=xa=wa=null},ba:function(a){if(e.hp_ult_color_enabled){if(!p||!p.IsValid()){var b=R();if(Qa&&b-Qa<2E3)return;if((p=la.FindChildTraverse("unit_ult_ready_icon"))&&p.IsValid())Qa=0;else{Qa=b;return}}if(p&&p.style&&(oa!==a||!Q)&&(b=A(a)||
"#E16161",oa=a,Q!==b))try{Q=p.style.washColor=b}catch(c){Q=null}}else{a=e.hp_ult_color_custom||"#E16161";if(!p||!p.IsValid()){b=R();if(Qa&&b-Qa<2E3)return;if((p=la.FindChildTraverse("unit_ult_ready_icon"))&&p.IsValid())Qa=0;else{Qa=b;return}}if(p&&p.style&&(oa!==a||!Q)&&(b=A(a)||"#E16161",oa=a,Q!==b))try{Q=p.style.washColor=b}catch(c){Q=null}}},Ca:function(){oa=null;if(p&&p.style&&Q!=="")try{Q=p.style.washColor=""}catch(a){Q=null}},xa:function(a){if(Ta!==a||!pa){var b=A(a);if(n&&n.style&&(Ta=a,pa!==
b))try{pa=n.style.washColor=b}catch(c){pa=null}}},S:function(a){L&&L.style&&(La!=="visible"&&(La=L.style.visibility="visible"),a=a?"1.0":"0.01",Ma!==a&&(Ma=L.style.opacity=a))},wa:function(a){Ob(a)},ab:function(a,b,c){if(!e.hp_counter_visible)this.wa(!1);else if(n&&(a!==Qb||b!==Pb||!!c!==Oa)){this.wa(!0);var d=e.hp_counter_format|0;d=d===1?(b>0?Math.round(a/b*100):0)+"%":d===2?String(a):a+" / "+b;try{n.text!==d&&(n.text=d)}catch(g){try{n.SetAttributeString("text",d)}catch(h){}}c=!!c;d=qb===null||
rb===null||M&&M.style&&sb===null;c!==Oa||d?(Oa=c,Hd(Oa)):Oa=c;Qb=a;Pb=b}},cb:function(a){if(C&&C.style)try{db!==a&&(db=C.style.visibility=a)}catch(b){db=null}},Ga:function(){if(!q||!q.style||!ka)return!1;try{return A(String(q.style.washColor||""))!==ka}catch(a){}return!1},Ha:function(){if(this.Ga())return!0;if(e.hp_counter_visible&&n&&n.style){try{if(qb!==null&&n.style.fontSize!==qb)return!0}catch(a){}try{if(rb!==null&&n.style.height!==rb)return!0}catch(a){}}if(e.hp_counter_visible&&M&&M.style)try{if(sb!==
null&&M.style.transform!==sb)return!0}catch(a){}if(F&&F.style&&ya)try{if(A(String(F.style.washColor||""))!==ya)return!0}catch(a){}if(G&&G.style&&xa)try{if(A(String(G.style.washColor||""))!==xa)return!0}catch(a){}if(H&&H.style&&wa)try{if(A(String(H.style.backgroundColor||""))!==wa)return!0}catch(a){}return!1},R:function(){Md=jd=0}},Lb=null,Nb=0,Mb=0,Be=160,Na=null,$c=null,ad=null,Gd=null,rc=null,ua=null,qc=null,Yc=null,ke={ka:!1,qa:"",N:0,current:0,max:0,oa:!1},Ge={tb:function(a){if(a===Pc)return Qc;
Pc=a;for(var b=0,c=0,d=0,g=a.indexOf("|"),h=a.lastIndexOf("|"),k=0;k<a.length;k++){var f=a.charCodeAt(k);if(f===124)b++;else if(f===34||f===39)g!==-1&&k<g&&d++,(h===-1||k>h)&&c++}a=e.hp_precise_pips_enabled?10:100;return Qc=b*(d>0?(d+1)*a:500)+c*a},reset:function(a){a.ka=!1;a.qa="";a.N=0;a.current=0;a.max=0;a.oa=!1;return a},G:function(a,b,c,d,g,h,k,f){f=this.reset(f||ke);var z=!!e.hp_counter_visible,J=e.hp_counter_format|0;f.ka=!!c;f.qa=e.hp_pip_visible?"visible":"collapse";if(!z)return f.N=2,f;
if(!g)return f;f.N=1;f.oa=!!(b&&b.g&&b.ea);if(J===1)return f.current=a,f.max=100,f;a=k>0?h/k:0;d=this.tb(d||"");f.max=d;f.current=a>=.97?d:Math.round(d*a);return f}},le={ga:!1,M:"",V:"",l:"",j:"",ia:!1,za:!1,m:.15},Ke={fa:function(a,b){b.washColor="";b.J=!1;b.l="";b.j="";b.m=.35;a=a.H;var c=l,d=x;b.J=!!(e.hp_friend_pulse_enabled&&a<=ja);b.J&&(b.m=.15);a=b.J&&e.hp_friend_pulse_color_enabled?e.hp_friend_pulse_color:a<=c?e.hp_friend_color_low:a<=d?e.hp_mode===1?Fa(e.hp_friend_color_low,e.hp_friend_color_mid,
(a-c)/y):e.hp_friend_color_mid:e.hp_mode===1?Fa(e.hp_friend_color_mid,e.hp_friend_color_high,(a-d)/K):e.hp_friend_color_high;b.washColor=A(a);b.l=A(e.hp_friend_heal_color);b.j=A(e.hp_friend_delta_color);b.A=A(e.hp_friend_bullet_shield_color);return b}},He={ua:function(a){a.ga=!1;a.M="";a.V="";a.l="";a.j="";a.ia=!1;a.za=!1;a.m=.15;return a},G:function(a,b,c,d,g){g=this.ua(g||le);var h=l,k=x,f=S;g.ga=d&&e.hp_pulse_hide_bar?!1:!!e.hp_bg_visible;if(a<=l&&Id&&c-Id<900&&(b<0||b<=l&&a>b))return a=ec(),g.ia=
!0,g.M=a,g.V=Bd(100,h,k),g.m=.05,g.za=!0,g;if(a<=h)b=e.hp_color_low,g.V=e.hp_mode===1?e.hp_text_color_mode?e.hp_text_color_low:e.hp_color_low:Bd(a,h,k);else{b=ec();a<=k?b=e.hp_mode===1?Fa(e.hp_color_low,e.hp_color_mid,(a-h)/y):e.hp_color_mid:(b=e.hp_mode===1?Fa(e.hp_color_mid,b,(a-k)/K):b,Sb>=5&&(g.m=Le[Math.min(Math.floor((Sb-5)/5),3)]));c=g;var z;e.hp_mode===1?z=e.hp_text_color_mode?a<=h?e.hp_text_color_low:a<=k?Fa(e.hp_text_color_low,e.hp_text_color_mid,(a-h)/y):Fa(e.hp_text_color_mid,e.hp_text_color_high,
(a-k)/K):a<=h?e.hp_color_low:a<=k?Fa(e.hp_color_low,e.hp_color_mid,(a-h)/y):Fa(e.hp_color_mid,ec(),(a-k)/K):z=Bd(a,h,k);c.V=z}h=g;d?(d=b,e.hp_pulse_color_enabled?(e.hp_pulse_color_mode|0)===1?(a=u((f-a)/Math.max(1,f),0,1,0),a=Fa(d,e.hp_pulse_color,a)):a=e.hp_pulse_color:a=d):a=b;h.M=a;g.l=e.hp_heal_color;g.j=e.hp_delta_color;g.A=e.hp_bullet_shield_color;return g}},hd=0,$a=-1,Jb=-1,sa=-1,ed=-1,Sb=0,Ga=0,fa=0,Rb=0,ta=0,Ya=0,Wb=[{min:11,F:"level_tier2"},{min:19,F:"level_tier3"},{min:27,F:"level_tier4"},
{min:35,F:"level_tier5"}],Kd="level_number_visible",vb=null,ia=null,P=null,fd=-1,Ea=null,ne={parse:function(a){if(!a||a.charCodeAt(0)===123)return 0;for(var b=0,c=0;c<a.length;c++){var d=a.charCodeAt(c)-48;d>=0&&d<=9&&(b=b*10+d)}return b},eb:function(a){for(var b=Wb.length-1;b>=0;b--)if(a>=Wb[b].min)return Wb[b].F;return""}},Hc=0;try{Yd()}catch(a){}try{Xd()}catch(a){}try{Zd()}catch(a){}})();
