function Bc(k){var w=0;return function(){return w<k.length?{done:!1,value:k[w++]}:{done:!0}}}var Cc=typeof Object.defineProperties=="function"?Object.defineProperty:function(k,w,x){if(k==Array.prototype||k==Object.prototype)return k;k[w]=x.value;return k};
function Vd(k){k=["object"==typeof globalThis&&globalThis,k,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var w=0;w<k.length;++w){var x=k[w];if(x&&x.Math==Math)return x}throw Error("Cannot find global object");}var Wd=Vd(this);function Xd(k,w){if(w)a:{var x=Wd;k=k.split(".");for(var L=0;L<k.length-1;L++){var S=k[L];if(!(S in x))break a;x=x[S]}k=k[k.length-1];L=x[k];w=w(L);w!=L&&w!=null&&Cc(x,k,{configurable:!0,writable:!0,value:w})}}
Xd("Symbol",function(k){function w(Z){if(this instanceof w)throw new TypeError("Symbol is not a constructor");return new x(L+(Z||"")+"_"+S++,Z)}function x(Z,gb){this.u=Z;Cc(this,"description",{configurable:!0,writable:!0,value:gb})}if(k)return k;x.prototype.toString=function(){return this.u};var L="jscomp_symbol_"+(Math.random()*1E9>>>0)+"_",S=0;return w});
Xd("Symbol.iterator",function(k){if(k)return k;k=Symbol("Symbol.iterator");Cc(Array.prototype,k,{configurable:!0,writable:!0,value:function(){return Yd(Bc(this))}});return k});function Yd(k){k={next:k};k[Symbol.iterator]=function(){return this};return k}function Zd(k,w){k instanceof String&&(k+="");var x=0,L=!1,S={next:function(){if(!L&&x<k.length){var Z=x++;return{value:w(Z,k[Z]),done:!1}}L=!0;return{done:!0,value:void 0}}};S[Symbol.iterator]=function(){return S};return S}
Xd("Array.prototype.values",function(k){return k?k:function(){return Zd(this,function(w,x){return x})}});
(function(){function k(){if(O||hb!==null||!(ha<0)||ib!==null){for(var a=ha>=0?jb[ha]:"",b=[m,l,p],c=0;c<b.length;c++){var e=b[c];if(e)try{e.RemoveClass("low_hp_pulsing"),a&&e.RemoveClass(a),e.style&&(e.style.animationDuration="",e.style.brightness="")}catch(g){}}O=0;hb=null;ha=-1;kb=za=La=aa=P=ia=ib=null}}function w(a,b){if(!a)return O&&k(),!1;if(!O){O=1;kb=za=La=aa=P=ia=null;try{m&&m.AddClass("low_hp_pulsing")}catch(f){}try{p&&p.AddClass("low_hp_pulsing")}catch(f){}}var c=t(d.hp_pulse_bpm,30,300,
75);a=(60/c).toFixed(3)+"s";if(hb!==a)try{m&&m.IsValid&&m.IsValid()&&(m.style.animationDuration=a),p&&p.IsValid&&p.IsValid()&&(p.style.animationDuration=a),hb=a}catch(f){hb=null}a=t(d.hp_pulse_intensity,0,2,1)|0;if(ha!==a){var e=ha>=0?jb[ha]:"",g=jb[a];if(e){try{m&&m.IsValid&&m.IsValid()&&m.RemoveClass(e)}catch(f){}try{p&&p.IsValid&&p.IsValid()&&p.RemoveClass(e)}catch(f){}}if(g){try{m&&m.IsValid&&m.IsValid()&&m.AddClass(g)}catch(f){}try{p&&p.IsValid&&p.IsValid()&&p.AddClass(g)}catch(f){}}ha=a}if(!d.hp_pulse_text_enabled){try{l&&
l.style&&(l.style.animationDuration="",l.style.brightness="")}catch(f){}ib=null;return!1}if(!l||!l.style)return!1;c=Math.max(1,6E4/c);b=b%c/c;c=a===2?.55:a===0?.85:.65;b=(c+((a===2?2:a===0?1.15:1.5)-c)*(b<.5?b*2:(1-b)*2)).toFixed(2);if(ib!==b)try{ib=l.style.brightness=b}catch(f){ib=null}return!0}function x(a,b){a=a||A;if(!b){b=Aa>=0?jb[Aa]:"";if(a)try{a.RemoveClass("low_hp_pulsing"),b&&a.RemoveClass(b),a.style&&(a.style.animationDuration="",a.style.brightness="")}catch(f){}Ma=0;Aa=-1;F=ac=null;return!1}if(b=
!Ma){Ma=1;Aa=-1;F=null;try{a&&a.AddClass("low_hp_pulsing")}catch(f){}}var c=t(d.hp_friend_pulse_intensity,0,2,1)|0;if(Aa!==c){var e=Aa>=0?jb[Aa]:"",g=jb[c];try{a&&e&&a.RemoveClass(e),a&&g&&a.AddClass(g)}catch(f){}Aa=c}c=(60/t(d.hp_friend_pulse_bpm,30,300,75)).toFixed(3)+"s";if(ac!==c)try{a&&a.style&&(a.style.animationDuration=c),ac=c}catch(f){ac=null}return b}function L(a,b){if(a===!0||a===!1)return a;if(a===1||a==="1")return!0;if(a===0||a==="0")return!1;if(typeof a==="string"){a=a.toLowerCase();
if(a==="true")return!0;if(a==="false")return!1}return!!b}function S(){try{if(typeof GameUI!=="undefined"&&GameUI&&GameUI.CustomUIConfig)return GameUI.CustomUIConfig()}catch(a){}return null}function Z(){if(!bc||!r(bc)){var a=ba;for(var b=null,c=0;a&&c<24;){r(a)&&(b=a);var e=null;try{e=a.GetParent?a.GetParent():null}catch(g){e=null}if(!e||e===a)break;a=e;c+=1}bc=b||ba||null}a=bc;if(!r(a)||!a.GetAttributeString)return"";try{return String(a.GetAttributeString("hp_colors_minimal_cfg_raw","")||"")}catch(g){}return""}
function gb(a){return a===0?!!d.hp_enabled:a===1?!!d.hp_friend_enabled:!!d.hp_level_number_visible}function Na(a,b){gb(a)&&!Bb[a]&&(Bb[a]=!0,u(a,b===void 0?.01:b,function(){Bb[a]=!1})||(Bb[a]=!1))}function lb(a){return!(!Ba[a]||!ja[a])}function cc(){var a=H();if(!Dc||a-Dc>=5E3||dc!==ka||mb!==la||Oa!==la||d.hp_enabled&&!lb(0)||d.hp_friend_enabled&&!lb(1)||d.hp_level_number_visible&&!lb(2)){Dc=a;var b=ka;try{ec()}catch(c){}ka!==b||dc!==ka||mb!==la||Oa!==la||d.hp_enabled&&!lb(0)||d.hp_friend_enabled&&
!lb(1)||d.hp_level_number_visible&&!lb(2)||a-Cb>=5E3&&td()?Ec&&a-Ec<250||(Ec=a,dc=ka,ma=T=!0,Pa=na=0,Qa=null,Db(),Na(0,.01),Na(1,.01),Na(2,.01)):dc=ka}}function $d(a,b){a=Number(a);return!isFinite(a)||a<0?b:a}function u(a,b,c){if(!gb(a))return!1;b=$d(b,.05);var e=H()+b*1E3;if(ja[a]&&ja[a]<=e)return!1;ja[a]=e;var g=++Fc[a];$.Schedule(b,function(){g===Fc[a]&&(ja[a]=0,c&&c(),gb(a)&&(a===0?ae():a===1?be():d.hp_level_number_visible?(Ba[2]=!0,fc=ce()?0:fc+1,u(2,fc>10?5:.5)):Eb(2,!0)))});return!0}function ud(a){if(!a)return!1;
var b=0,c;for(c in a)if(Object.prototype.hasOwnProperty.call(a,c)&&Object.prototype.hasOwnProperty.call(nb,c)){var e=c;var g=c,f=a[c];if(Object.prototype.hasOwnProperty.call(nb,g)){var h=nb[g];if(g==="hp_counter_position"||g==="hp_pulse_text_position")b:if(h=f,g=0,f=200,h&&typeof h==="object")Array.isArray(h)?(h.length>0&&(g=t(h[0],0,400,0)),h.length>1&&(f=t(h[1],-50,400,200))):(Object.prototype.hasOwnProperty.call(h,"x")&&(g=t(h.x,0,400,0)),Object.prototype.hasOwnProperty.call(h,"y")&&(f=t(h.y,-50,
400,200))),h=Math.round(g)+","+Math.round(f);else{if(typeof h==="string"){var D=h.match(/-?\d+(?:\.\d+)?/g);if(D&&D.length>0){g=t(D[0],0,400,0);D.length>1&&(f=t(D[1],-50,400,200));h=Math.round(g)+","+Math.round(f);break b}}typeof h==="number"&&(f=t(h,-50,400,200));h=Math.round(g)+","+Math.round(f)}else typeof h==="boolean"?h=L(f,h):typeof h==="number"?(g=Number(f),h=isFinite(g)?Math.round(g):h):h=typeof h==="string"?typeof f==="string"&&f.length>0?f:h:f}else h=f;d[e]=h;b+=1}if(!b)return!1;hc();try{ec()}catch(ca){}try{Ra()}catch(ca){}Db();
Sa=!0;la++;ma=T=!0;Pa=na=0;Qa=null;Oa=mb=-1;ic();vd();Na(0);Na(1);Na(2);return!0}function Gc(){var a=S(),b="";if(a)try{b=String(a.__hpColorsCfgRaw||"")}catch(c){b=""}b||(b=Z());if(!b)return!1;if(b===Fb&&Sa)return cc("shared_same_raw"),!0;a=null;try{a=JSON.parse(b)}catch(c){return!1}a=a&&typeof a==="object"?a.values||a:null;if(!a||typeof a!=="object"||!ud(a))return!1;Fb=b;return!0}function wd(){if(!Sa&&!Gc()){ob+=1;var a=ob<=8,b=ob>20,c=ob===1?"overlay_startup":"overlay_retry",e=!0;!a&&b&&(e=ob===
21||(ob-20-1)%6===0)&&(c="overlay_late_retry");if(e){c=String(c||"overlay_request");try{$.DispatchEvent("ClientUI_FireOutput",JSON.stringify({magic_word:"HP_COLORS_PRESET_REQUEST",mod_title:"HP Colors",reason:c}))}catch(g){}}$.Schedule(a?.5:b?10:3,wd)}}function de(){var a=S(),b="";try{b=a?String(a.__hpColorsCfgRaw||""):""}catch(c){b=""}b||(b=Z());return b?b===Fb?(cc("event_store_same_raw"),!0):Gc():!1}function ee(a){function b(c){c=+c|0;return c<0?0:c>255?255:c}return"#"+(16777216|b(a[0])<<16|b(a[1])<<
8|b(a[2])).toString(16).slice(1)}function oa(a,b,c){a=a.slice(1);a.length===3&&(a=a[0]+a[0]+a[1]+a[1]+a[2]+a[2]);b=b.slice(1);b.length===3&&(b=b[0]+b[0]+b[1]+b[1]+b[2]+b[2]);a=parseInt(a,16);b=parseInt(b,16);return"#"+(16777216|((a>>16&255)+((b>>16&255)-(a>>16&255))*c|0)<<16|((a>>8&255)+((b>>8&255)-(a>>8&255))*c|0)<<8|(a&255)+((b&255)-(a&255))*c|0).toString(16).slice(1)}function pa(a){if(typeof a!=="string")return"";a=a.trim();if(!a)return"";if(a.charAt(0)==="#")return a.length===4?("#"+a.charAt(1)+
a.charAt(1)+a.charAt(2)+a.charAt(2)+a.charAt(3)+a.charAt(3)).toLowerCase():a.length>=7?a.slice(0,7).toLowerCase():a;var b=a.match(/^rgba?\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)/i);return b?ee([b[1],b[2],b[3]]):a}function Gb(){return d.hp_team_colors?Q===2?"#6485FC":"#FFC961":d.hp_color_high}function xd(a,b,c){return d.hp_pulse_color_enabled?(d.hp_pulse_color_mode|0)===1?(b=t((c-b)/Math.max(1,c),0,1,0),oa(a,d.hp_pulse_color,b)):d.hp_pulse_color:a}function Hc(a,b,c){return d.hp_text_color_mode?a<=b?d.hp_text_color_low:
a<=c?d.hp_text_color_mid:d.hp_text_color_high:a<=b?d.hp_color_low:a<=c?d.hp_color_mid:Gb()}function r(a){try{return!(!a||a.IsValid&&!a.IsValid())}catch(b){}return!1}function ic(){pb=null;Hb="";Ib=Jb=0}function yd(a,b){if(!r(a))return!1;if(b==="any")return!0;a=jc(a,Kb)&255;if(b==="friend"){if(a&8)return!0;Ib=a;return!1}return b==="enemy"?zd(a)?!0:!1:!0}function Ic(a){a=a||"any";Ib=0;var b=H(),c;if(c=Hb===a&&r(pb)){c=b-Jb;var e=a,g=H();c=c<=(qa&&g<=qa?80:e==="friend"?160:Ca>=8||U>=8?300:120)}if(c)return pb;
c=ba.FindChildTraverse("unit_healthbar_lagging");if(yd(c,a)||r(v)&&(c=v.FindChildTraverse("unit_healthbar_lagging"),yd(c,a)))return pb=c,Hb=a,Jb=b,c;pb=null;Hb=a;Jb=b;return null}function ra(a){try{return!(!a||!a.IsValid||a.IsValid())}catch(b){}return!1}function kc(a){try{return a&&a.actuallayoutwidth!==void 0?a.actuallayoutwidth|0:0}catch(b){}return 0}function Jc(a){try{return a&&a.GetParent?a.GetParent():null}catch(b){}return null}function Ad(){return U>=8?2500:U>=3?1800:Ca>=8?2500:Ca>=3?1800:1200}
function fe(a,b){if(!b){if(lc&&a<lc)return!1;b=qa&&a<=qa?180:Ad();lc=a+b}if(!M||!M.Children)return!1;a=[];try{a=M.Children()}catch(h){return!1}b=m;for(var c=Bd(m,-1),e=0;e<a.length;e++){var g=a[e];if(r(g)){var f="";try{f=String(g.id||"")}catch(h){f=""}f==="unit_healthbar_lagging"&&(f=Bd(g,e),f>c&&(b=g,c=f))}}return b&&b!==m?Cd(b):!1}function jc(a,b){var c=0,e=0,g=0;for(b=b||Kb;a&&g<b&&!(a.BHasClass&&(c||(a.BHasClass("team2")?c=2:a.BHasClass("team1")&&(c=1)),e&1||!a.BHasClass("enemy")||(e|=1),e&2||
!a.BHasClass("team_neutral")||(e|=2),e&4||!(a.BHasClass("building")||a.BHasClass("destroyable_building")||a.BHasClass("guardian")||a.BHasClass("boss_tier1")||a.BHasClass("boss_tier2")||a.BHasClass("boss_tier_01")||a.BHasClass("boss_tier_02")||a.BHasClass("boss_tier_01_brazier_guardian")||a.BHasClass("boss_barracks"))||(e|=4),e&8||!a.BHasClass("friend")||(e|=8),c&&e&15))&&a.GetParent;)a=a.GetParent(),g++;return c<<8|e}function Bd(a,b){if(!r(a))return-1;var c=kc(a),e=kc(Jc(a)),g=e>0,f=g?120:-200,h=
jc(a,Kb)&255;h&1&&!(h&2)?f+=g?700:120:h&8?f-=160:h&2?f-=120:h&15||(f-=40);a===m&&(f+=g?80:-40);c>0&&(f+=40);e>0&&(f+=Math.min(e,400)/20);b>=0&&(f+=Math.min(b,20));return f}function Cd(a){V=M=(W=m=a)&&a.GetParent?a.GetParent():null;Da=Ea=Ta=0;ic();Kc=z=Q=0;Lc=null;ec();sa=Lb=Ua=-1;Ca=0;mc=-1;Mb();return!0}function Db(){qa=H()+1600;lc=nc=0}function Dd(a){return qa&&a<=qa||U||N&&N<4||X&&X<4?!0:z&2?N<4:z&4?d.hp_skip_buildings?X<4:N<4:z&1?!1:N<4}function oc(a){return!!(a&4&&(a&8||Q&&Q===Ed))}function zd(a){return a&
2||d.hp_friend_enabled&&a&8?!1:a&1?!0:!(!(a&4)||a&2||!Q||oc(a))}function Va(a){if(kb!==a||aa===null){var b=pa(a);b||(b="");kb=a;if(aa!==b&&m)try{aa=m.style.washColor=b}catch(c){aa=null}}}function pc(a){if(d.hp_ult_color_enabled){if(!p||!p.IsValid()){var b=H();if(ta&&b-ta<2E3)return;if((p=ba.FindChildTraverse("unit_ult_ready_icon"))&&p.IsValid())ta=0;else{ta=b;return}}if(p&&p.style&&(za!==a||!P)&&(b=pa(a)||"#E16161",za=a,P!==b))try{P=p.style.washColor=b}catch(c){P=null}}else{a=d.hp_ult_color_custom||
"#E16161";if(!p||!p.IsValid()){b=H();if(ta&&b-ta<2E3)return;if((p=ba.FindChildTraverse("unit_ult_ready_icon"))&&p.IsValid())ta=0;else{ta=b;return}}if(p&&p.style&&(za!==a||!P)&&(b=pa(a)||"#E16161",za=a,P!==b))try{P=p.style.washColor=b}catch(c){P=null}}}function Nb(a){if(La!==a||!ia){var b=pa(a);if(l&&l.style&&(La=a,ia!==b))try{ia=l.style.washColor=b}catch(c){ia=null}}}function Fd(){return z&1&&!(z&2)?"":z&4&&!(z&2)&&Q&&!oc(z)?"#E16161":oc(z)?"#ffffff":z&6?"#5BEFB5":z&8?"#FFEFD7":Q===2?"#5B79E6":Q===
1?"#E7B659":"#E16161"}function qb(a,b){var c=(a=a||A)&&a.IsValid&&a.IsValid()?Gd(a):0;qc=!1;Wa=0;rb=F=null;Xa=sb=tb=-1;Mc=I=0;Ob=null;Pb=Qb=0;x(a,!1);if(b&&a&&a===A&&c&8&&a.style){b=c&4?"#ffffff":"#FFEFD7";try{a.style.washColor=b,F=pa(b),rb=b}catch(e){rb=F=null}}}function Gd(a){var b=H();if(a===Ob&&b-Qb<ge)return Pb;var c=jc(a,Kb)&255;Ob=a;Qb=b;return Pb=c}function t(a,b,c,e){a=Number(a);isFinite(a)||(a=Number(e));isFinite(a)||(a=0);isFinite(b)&&a<b&&(a=b);isFinite(c)&&a>c&&(a=c);return a}function Rb(a){return t(a,
0,100,0)|0}function hc(){var a=Rb(d.hp_low_threshold),b=Rb(d.hp_high_threshold);b<a&&(b=a);var c=d.hp_kill_zone_width|0;c<1&&(c=1);c>100&&(c=100);var e=t(d.hp_counter_size,72,400,145);n.low=a;n.high=b;n.i=Math.max(1,b-a);n.g=Math.max(1,100-b);n.H=Rb(d.hp_pulse_threshold);n.o=Rb(d.hp_friend_pulse_threshold);n.m=e;n.G=t(d.hp_pulse_text_scale,72,320,e);n.l=Hd(d.hp_counter_position,!0);n.F=Hd(d.hp_pulse_text_position,!1);n.A=Math.round(t(d.hp_healthbar_height,0,230,130));n.C=Rb(d.hp_kill_zone_threshold);
n.D=c;n.j=d.hp_kill_zone_color||"#FF2222";n.B=pa(n.j)}function Sb(a){E&&E.style&&(ua!=="visible"&&(ua=E.style.visibility="visible"),a=a?"1.0":"0.01",va!==a&&(va=E.style.opacity=a))}function Ra(){wa=rc=sc=Nc=Tb=da=Ub=tc=ua=va=Ya=Za=$a=uc=Oc=Pc=Qc=ab=kb=za=La=Rc=aa=P=ia=null;Vb=Wb=-1;bb=null;Sc="";Mb()}function Id(){if(!m||!m.style||!aa)return!1;try{return pa(String(m.style.washColor||""))!==aa}catch(a){}return!1}function td(){if(Id())return!0;if(d.hp_counter_visible&&l&&l.style){try{if(Ya!==null&&
l.style.fontSize!==Ya)return!0}catch(a){}try{if(Za!==null&&l.style.height!==Za)return!0}catch(a){}}if(d.hp_counter_visible&&J&&J.style)try{if($a!==null&&J.style.transform!==$a)return!0}catch(a){}return!1}function Mb(){Tc=vc=0}function Fa(a,b){if((!C||!r(C))&&a&&d.hp_kill_zone_enabled&&v&&v.FindChildTraverse)try{C=v.FindChildTraverse("hp_kill_zone_marker")}catch(h){}if(C&&C.style){var c=!E||!E.style||ua!=="visible"||va!=="1.0";if(!a||!d.hp_kill_zone_enabled||b<=0||c){if(tc=null,wa!=="collapse"&&(wa=
C.style.visibility="collapse"),da!=="0")try{da=C.style.opacity="0"}catch(h){da=null}}else{a=n.C;c=n.D;var e=Math.round(b*a/100-c/2);e<0&&(e=0);e>b-c&&(e=Math.max(0,b-c));e+="px";var g=c+"px";Rc!==n.j&&(Rc=n.j,Nc=n.B);var f=Nc;b=b+"|"+a+"|"+c+"|"+n.j+"|"+f+"|"+ua+"|"+va;if(tc!==b||wa!=="visible"||da!=="0.95"||Ub!=="1000"||rc!==e||sc!==g||Tb!==f){tc=b;wa!=="visible"&&(wa=C.style.visibility="visible");if(da!=="0.95")try{da=C.style.opacity="0.95"}catch(h){da=null}if(Ub!=="1000")try{Ub=C.style.zIndex=
"1000"}catch(h){Ub=null}rc!==e&&(rc=C.style.marginLeft=e);sc!==g&&(sc=C.style.width=g);if(Tb!==f)try{Tb=C.style.backgroundColor=f}catch(h){Tb=null}}}}}function Hd(a,b){var c=0,e=200;b=b?-200:0;if(a&&typeof a==="object")return Array.isArray(a)?(a.length>0&&(c=t(a[0],0,400,0)),a.length>1&&(e=t(a[1],b,400,200))):(Object.prototype.hasOwnProperty.call(a,"x")&&(c=t(a.x,0,400,0)),Object.prototype.hasOwnProperty.call(a,"y")&&(e=t(a.y,b,400,200))),{x:c,y:e};if(typeof a==="string"){var g=a.match(/-?\d+(?:\.\d+)?/g);
if(g&&g.length>0)return c=t(g[0],0,400,0),g.length>1&&(e=t(g[1],b,400,200)),{x:c,y:e}}typeof a==="number"&&(e=t(a,b,400,200));return{x:c,y:e}}function Uc(a){if(l&&l.style){a=!!(a&&d.hp_pulse_enabled&&d.hp_pulse_text_enabled);var b=n.m||t(d.hp_counter_size,72,400,145);b=a?n.G||t(d.hp_pulse_text_scale,72,320,b):b;var c=a?n.F:n.l,e=t(c.x,0,400,0),g=t(c.y,-50,400,200);c=b+"px";var f="100%";if(a){a=130;try{var h=l.GetParent?l.GetParent():null;h&&h.actuallayoutheight>0&&(a=h.actuallayoutheight)}catch(D){}f=
Math.max(a,Math.round(b*1.85))+"px"}h="translate3d("+Math.round(e)+"px, "+Math.round(Math.max(g-150,-200))+"px, 0px)";Ya!==c&&(Ya=l.style.fontSize=c);Za!==f&&(Za=l.style.height=f);J&&J.style&&$a!==h&&($a=J.style.transform=h)}}function Ga(a){if(l&&l.style){var b=a?"visible":"collapse";if(bb!==b)try{bb=l.style.visibility=b}catch(c){bb=null}a||(Vb=Wb=-1,Ha=!1)}}function Vc(a){if(Sc!==String(a||"")+"|"+bb+"|"+wa+"|"+da+"|"+ua+"|"+va+"|"+O||O)k(),Ga(!1),Fa(!1,0),Va(a||""),Nb("#ffffff"),Sb(!0),Sc=String(a||
"")+"|"+bb+"|"+wa+"|"+da+"|"+ua+"|"+va+"|"+O}function Jd(){k();Ga(!1);Fa(!1,0);Sb(!0)}function ec(){var a="";try{Ia&&(a=Ia.text||Ia.GetAttributeString("text","")||"")}catch(b){a=""}if(m!==Wc||M!==Xc||V!==Yc||l!==Zc||E!==$c||C!==ad||B!==bd||a!==cd)Wc=m,Xc=M,Yc=V,Zc=l,$c=E,ad=C,bd=B,cd=a,ka++,Oa=mb=mc=-1,Cb=dd=H(),Ra(),k(),qc=!1,F=Ja=y=ea=ed=A=null,Xa=sb=tb=-1,cb=Wa=I=0,Qa=null,wc=sa=Lb=Ua=-1,Ca=X=ub=N=U=vb=0,Ha=!1,fd="",ma=T=!0,Pa=na=0,Db()}function gd(a,b){gb(a)&&!Ba[a]&&(Ba[a]=!0,u(a,b||.05))}function Eb(a,
b){if(b)if(a===0){k();if(m&&m.style)try{m.style.washColor=""}catch(c){}if(p&&p.style)try{p.style.washColor=""}catch(c){}if(l&&l.style)try{l.style.washColor=""}catch(c){}La=ia=za=P=kb=aa=null;Fa(!1,0);E&&E.style&&(ua!=="collapse"&&(ua=E.style.visibility="collapse"),va!=="0"&&(va=E.style.opacity="0"));if(l&&l.style){try{l.style.fontSize="",l.style.height="",l.style.washColor=""}catch(c){}La=ia=Za=Ya=null}J&&J.style&&(J.style.transform="",$a=null);wc=sa=Lb=Ua=-1;Ca=X=ub=N=U=vb=0;Mb()}else if(a===1)qb(A,
!0),A=null;else{if(!G||!G.IsValid())if(Y&&Y.IsValid()||(Y=ba.FindChildTraverse("UnitStatus")),Y)for(b=Y;b;){if(b.BHasClass&&b.BHasClass("enemy")){G=b;break}if(!b.GetParent)break;b=b.GetParent()}if(G&&G.IsValid&&G.IsValid()){try{G.RemoveClass(hd)}catch(c){}for(b=0;b<4;b++)try{G.RemoveClass(id[b])}catch(c){}}Qa=!1;jd=-1;fc=0}Ba[a]=!1;Bb[a]=!1;ja[a]=0;Fc[a]++}function vd(){hc();d.hp_enabled?gd(0):Eb(0,!0);d.hp_friend_enabled?gd(1):Eb(1,!0);d.hp_level_number_visible?gd(2):Eb(2,!0);d.hp_counter_visible||
(Ga(!1),Vb=Wb=-1);!d.hp_pulse_enabled&&O&&k();O?(hb=null,ha=-1,w(!0,H())):d.hp_pulse_text_enabled||(Ha=!1,Uc(!1));!d.hp_friend_pulse_enabled&&Ma&&x(y,!1);d.hp_kill_zone_enabled||Fa(!1,0);if(B&&B.style&&!d.hp_pip_visible&&ab!=="collapse")try{ab=B.style.visibility="collapse"}catch(a){ab=null}}function Kd(a,b,c){if(!d.hp_counter_visible)Ga(!1);else if(l&&(a!==Wb||b!==Vb)){Ga(!0);var e=d.hp_counter_format|0;e=e===1?(b>0?Math.round(a/b*100):0)+"%":e===2?String(a):a+" / "+b;try{l.text!==e&&(l.text=e)}catch(g){try{l.SetAttributeString("text",
e)}catch(f){}}c=!!c;e=Ya===null||Za===null||J&&J.style&&$a===null;c!==Ha||e?(Ha=c,Uc(Ha)):Ha=c;Wb=a;Vb=b}}function ae(){Ba[0]=!0;try{if(d.hp_enabled){var a=H(),b=!1;if(Ta||m)if(ra(v)||ra(l)||ra(E)||ra(B)||ra(W)||ra(V)||ra(m)||ra(M)||ra(Ia))v=l=J=E=B=W=V=m=M=p=C=ea=xa=Ia=null,Da=Ea=Ta=0,Wc=Xc=Yc=Zc=$c=ad=bd=null,cd="",Ra(),ma=T=!0,ic(),Db();if(r(m)){if(Dd(a))if(nc&&a<nc)b=!1;else{nc=a+(qa&&a<=qa?180:Ad());var c=Ic("enemy");if(r(c)&&c!==m){var e=kc(Jc(c)),g=kc(Jc(m));b=e<=0&&g>0||e<=0?!1:Cd(c)}else b=
!1}}else{if(!kd||a>=kd)kd=(m=Ic("any"))?0:a+150;if(!m){u(0,.15);return}}var f;if(!(f=Ta))a:{if(Ta){var h=!d.hp_counter_visible||r(l);if(r(v)&&h&&r(E)&&r(B)&&r(W)&&r(V)&&r(Ia)){f=1;break a}Da=Ta=0}var D=H();if(Da&&D<Da)var ca=0;else Ea++,r(v)||(v=ba.FindChildTraverse("UnitStatus")),v?(r(l)||!d.hp_counter_visible&&bb==="collapse"||(l=v.FindChildTraverse("hp_counter")),d.hp_counter_visible&&!r(J)&&(J=v.FindChildTraverse("hp_counter_anchor")),r(E)||(E=v.FindChildTraverse("unit_healthbar_bg")),r(B)||(B=
v.FindChildTraverse("unit_healthbar_pip_label")),r(W)||(W=v.FindChildTraverse("unit_healthbar_lagging")),d.hp_kill_zone_enabled&&!r(C)&&(C=v.FindChildTraverse("hp_kill_zone_marker")),r(p)||(p=v.FindChildTraverse("unit_ult_ready_icon")),r(ea)||(ea=v.FindChildTraverse("InfoHealthContainer")),r(xa)||(xa=v.FindChildTraverse("UnitHealthbarContainer")),r(Ia)||(Ia=ba.FindChildTraverse("name")),r(p)&&(ta=0),W&&!r(V)&&(V=W.GetParent()),B&&W&&V?(Ta=1,Da=Ea=0,ca=1):(Da=D+(Ea<8?150:Ea<24?500:1500),ca=0)):(Da=
D+(Ea<8?150:Ea<24?500:1500),ca=0);f=ca}if(f){if(m.GetParent){var wb=m.GetParent();M!==wb&&(M=wb)}!b&&Dd(a)&&fe(a,!1);ec();b=m;var K=H();if(!(b===Lc&&K-Kc<he)){var xc=jc(b,Kb);Q=xc>>8;z=xc&255;Q&&z&8&&(Ed=Q);Kc=K;Lc=b}var q=zd(z);mb!==la&&(mb=la,T=!0,na=0,Ra());K=Q+":"+z;K!==fd&&(fd=K,Ra(),T=!0,na=a,ma=!0,Pa=a,Qa=null,Db());if(d.hp_skip_buildings&&z&4)X++,N=0,z&8||oc(z)?(Vc("#ffffff"),d.hp_friend_enabled&&Jd()):Vc(Fd()),u(0,X<4?.3:X<12?.6:1.5);else if(K=T,q&&a-Cb>=5E3&&(Cb=a,td()&&(Ra(),T=!0,na=a,
K=!0)),z&2)k(),ub++,X=N=0,Sb(!0),Fa(!1,0),Ga(!1),Va("#5BEFB5"),Nb("#ffffff"),yc=a,u(0,ub<4?.75:1.5);else if(q){X=ub=N=0;if(T){if(a<na){u(0,.05);return}hc();Sb(!q||!!d.hp_bg_visible);d.hp_counter_visible?Uc(Ha):Ga(!1);var ya=-15+t(d.hp_info_health_margin_top,0,100,23)*.65;Math.abs(ya)<.5&&(ya=0);var Xb=Math.round(ya*10)/10;Math.abs(Xb-Math.round(Xb))<.01&&(Xb=Math.round(Xb));ya=Xb+"%";ea&&ea.IsValid()||!v||!v.IsValid()||(ea=v.FindChildTraverse("InfoHealthContainer"));if(ea&&ea.style&&uc!==ya)try{uc=
ea.style.marginTop=ya}catch(Ld){uc=null}xa&&xa.IsValid()||!v||!v.IsValid()||(xa=v.FindChildTraverse("UnitHealthbarContainer"));var xb=n.A||Math.round(t(d.hp_healthbar_height,0,230,130));ya=xb+"px";xa&&xa.style&&Oc!==ya&&(Oc=xa.style.height=ya);if(B&&B.style){var yb=Math.min(75,Math.round(xb*75/230))+"px";Pc!=="52%"&&(Pc=B.style.height="52%");Qc!==yb&&(Qc=B.style.fontSize=yb)}Cb=H();Mb();sa=Ua=-1;T=!1;na=0}if(Sa){var ld=m.actuallayoutwidth|0,Yb=M&&M.actuallayoutwidth!==void 0?M.actuallayoutwidth|0:
0;if(ld!==Ua||Yb!==Lb||O||K||mc!==ka)if(Ca=0,Ua=ld,Lb=Yb,yc=a,Yb<=0)U++,Va(Gb()),Fa(!1,0),u(0,U<3?.18:U<6?.75:U<10?1.5:2.5);else{U=0;d.hp_kill_zone_enabled?Fa(!0,Yb):wa!=="collapse"&&Fa(!1,0);q=ld/Yb*100|0;var R=n.low,fa=n.high,md=n.H,db=!!(d.hp_pulse_enabled&&q<=md);if(Math.abs(q-sa)<3&&q>R&&sa>R&&!O&&!db&&!K)u(0,.25);else{xb=sa;q===wc?vb++:(vb=0,wc=q);sa=q;var zb=!!d.hp_counter_visible,Ka=d.hp_counter_format|0;yb="";if(B)try{var Zb=d.hp_pip_visible?"visible":"collapse";ab!==Zb&&(ab=B.style.visibility=
Zb);zb&&Ka!==1&&(yb=B.text||B.GetAttributeString("text","")||"")}catch(Ld){yb="",ab=null}if(zb&&W&&V)if(Ka===1)Kd(q,100,db);else{var zc=W.actuallayoutwidth||0,eb=V.actuallayoutwidth||0;zb=eb>0?zc/eb:0;Ka=yb;if(Ka!==Md){Md=Ka;zc=Zb=0;var Nd=Ka.lastIndexOf("|");for(eb=0;eb<Ka.length;eb++){var nd=Ka.charCodeAt(eb);nd===124?Zb++:nd!==34&&nd!==39||!(Nd===-1||eb>Nd)||zc++}Od=Zb*500+zc*100}var fb=Od;Kd(zb>=.97?fb:Math.round(fb*zb),fb,db)}else zb||Ga(!1);fb=.15;Sb(db&&d.hp_pulse_hide_bar?!1:!!d.hp_bg_visible);
if(q<=R){if(dd&&a-dd<900&&(xb<0||xb<=R&&q>xb)){var Pd=Gb();k();Va(Pd);pc(Pd);Nb(Hc(100,R,fa));u(0,.05);return}var $b=d.hp_color_low;var Qd=d.hp_mode===1?d.hp_text_color_mode?d.hp_text_color_low:d.hp_color_low:Hc(q,R,fa);var Rd=db?xd($b,q,md):$b;Va(Rd);pc(Rd)}else{var Sd=Gb();$b=q<=fa?d.hp_mode===1?oa(d.hp_color_low,d.hp_color_mid,(q-R)/n.i):d.hp_color_mid:d.hp_mode===1?oa(d.hp_color_mid,Sd,(q-fa)/n.g):Sd;var od;d.hp_mode===1?od=d.hp_text_color_mode?q<=R?d.hp_text_color_low:q<=fa?oa(d.hp_text_color_low,
d.hp_text_color_mid,(q-R)/n.i):oa(d.hp_text_color_mid,d.hp_text_color_high,(q-fa)/n.g):q<=R?d.hp_color_low:q<=fa?oa(d.hp_color_low,d.hp_color_mid,(q-R)/n.i):oa(d.hp_color_mid,Gb(),(q-fa)/n.g):od=Hc(q,R,fa);Qd=od;q>fa&&vb>=5&&(fb=ie[Math.min(Math.floor((vb-5)/5),3)]);var Td=db?xd($b,q,md):$b;Va(Td);pc(Td)}Nb(Qd);w(db,a)&&(fb=.1);mc=ka;u(0,fb)}}else{Ca++;if(q&&a>=Tc){Tc=a+(vc>=8?950:vc>=3?700:350);if(Id()){Mb();Ra();T=!0;na=a;sa=Ua=-1;u(0,.05);return}vc++}u(0,a-yc>2E3?1.5:.25)}}else Va("#E16161"),pc("#E16161"),
Nb("#ffffff"),u(0,.05)}else{N++;X=ub=0;var Ud=!!(z&8&&d.hp_friend_enabled);if(Ud)a:{if(Jd(),d.hp_friend_enabled){if(qc&&ja[1]&&ja[1]>a){if(ja[1]-a<=250)break a;if(A&&r(A)){if(pd&&a-pd<3E3)break a;pd=a;break a}}qd&&a-qd<2500||(qd=a,Na(1,.01))}}else Vc(Fd());yc=a;u(0,Ud?N<4?.2:2:N<4?.2:1.25)}}else u(0,.15)}else Eb(0,!0)}catch(Ld){u(0,.5)}finally{}}function ce(){Ab&&Ab.IsValid()||(Ab=ba.FindChildTraverse("unit_level_label"));Y&&Y.IsValid()||(Y=ba.FindChildTraverse("UnitStatus"));if(Y&&(!G||!G.IsValid()))for(var a=
Y;a;){if(a.BHasClass&&a.BHasClass("enemy")){G=a;break}if(!a.GetParent)break;a=a.GetParent()}if(!Ab||!Y||!G)return!1;a=!!d.hp_level_number_visible;Qa!==a&&(a?G.AddClass(hd):G.RemoveClass(hd),Qa=a);if(!a)return!1;var b="";try{b=Ab.text||Ab.GetAttributeString("text","")||""}catch(g){b=""}if(!b||b.charCodeAt(0)===123)return!1;for(var c=a=0;c<b.length;c++){var e=b.charCodeAt(c)-48;e>=0&&e<=9&&(a=a*10+e)}if(a===jd||!a)return!1;jd=a;for(b=0;b<4;b++)G.RemoveClass(id[b]);for(b=3;b>=0;b--)if(a>=je[b]){G.AddClass(id[b]);
break}return!0}function be(){Ba[1]=!0;try{if(d.hp_friend_enabled){var a=H();if(!y||!y.IsValid()){qb(A,!1);Ja=y=A=null;y=Ic("friend");if(!y){rd++;if(Ib&4){u(1,2.5);return}if(Ib){u(1,1.2);return}u(1,rd>75?3:.2);return}Ob=null;Pb=Qb=0}rd=0;if(y.GetParent){var b=y.GetParent();Ja!==b&&(Ja=b)}y!==ed&&(ed=y,Oa=-1,ma=!0,Pa=0,F=null,Xa=sb=tb=-1);if(b=Oa!==la)ma=!0,Pa=0,F=null,Xa=sb=tb=-1,I=0;if(ma){if(a<Pa){u(1,.05);return}ma=!1;qb(A,!1)}if(Gd(y)&8){b&&(Oa=la);cb=0;var c=y.actuallayoutwidth|0,e=Ja&&Ja.actuallayoutwidth!==
void 0?Ja.actuallayoutwidth|0:0;if(e<=0)Wa++,u(1,Wa<4?.2:Wa<12?.4:.8);else{Wa=0;if((b=c===tb&&e===sb)&&!Ma)if(a>=Mc){Mc=a+(I>=3?2500:1200);a:{if(y&&y.style&&F)try{var g=pa(String(y.style.washColor||""))!==F;break a}catch(q){}g=!1}if(g)F=null;else{I++;u(1,Ac[Math.min(Math.floor(I/3),4)]);return}}else{I++;u(1,Ac[Math.min(Math.floor(I/3),4)]);return}tb=c;sb=e;a=c/e*100|0;c=Xa;var f=n.low,h=n.high,D=!!(d.hp_friend_pulse_enabled&&a<=n.o);var ca=D&&d.hp_friend_pulse_color_enabled?d.hp_friend_pulse_color:
a<=f?d.hp_friend_color_low:a<=h?d.hp_mode===1?oa(d.hp_friend_color_low,d.hp_friend_color_mid,(a-f)/n.i):d.hp_friend_color_mid:d.hp_mode===1?oa(d.hp_friend_color_mid,d.hp_friend_color_high,(a-h)/n.g):d.hp_friend_color_high;if(rb===ca&&F){var wb=F;var K=!1}else wb=pa(ca),K=F!==wb;if(K&&y)try{F=y.style.washColor=wb,rb=ca,qc=!0,A=y}catch(q){rb=F=null}f=!!Ma;var xc=x(y,D);f=!D&&f;h=D?.15:.35;D&&!xc&&!K&&a===c&&b?(I++,h=Ac[Math.min(Math.floor(I/3),4)]):D||K||f||a!==c?I=0:(I++,h=Ac[Math.min(Math.floor(I/
3),4)]);Xa=a;u(1,h)}}else A===y?(qb(A,!1),A=null):Ma&&x(y,!1),I=0,Xa=-1,Wa=0,cb++,cb===4||cb===12?(qb(A,!1),Ob=Ja=y=A=null,Pb=Qb=0,ic(),u(1,.1)):u(1,cb<4?1.2:cb<12?2:3)}else qb(A,!0),A=null,Ba[1]=!1}catch(q){u(1,.5)}finally{}}var nb={hp_enabled:!0,hp_mode:1,hp_low_threshold:25,hp_high_threshold:65,hp_bg_visible:!0,hp_team_colors:!1,hp_info_health_margin_top:23,hp_healthbar_height:130,hp_color_low:"#E16161",hp_color_mid:"#FF7B00",hp_color_high:"#00FF00",hp_counter_visible:!0,hp_counter_size:145,hp_counter_position:"27,20",
hp_text_color_mode:0,hp_text_color_low:"#E16161",hp_text_color_mid:"#FF7B00",hp_text_color_high:"#FFFFFF",hp_pulse_bpm:75,hp_pulse_intensity:1,hp_pulse_enabled:!0,hp_pulse_text_enabled:!1,hp_pulse_text_scale:120,hp_pulse_text_position:"20,196",hp_pulse_hide_bar:!1,hp_pulse_color_enabled:!1,hp_pulse_color:"#FF2222",hp_pulse_color_mode:0,hp_skip_buildings:!1,hp_pulse_threshold:25,hp_counter_format:0,hp_friend_enabled:!1,hp_friend_pulse_enabled:!1,hp_friend_pulse_bpm:75,hp_friend_pulse_intensity:1,hp_friend_pulse_threshold:25,
hp_friend_color_low:"#E16161",hp_friend_color_mid:"#FF7B00",hp_friend_color_high:"#00FF00",hp_friend_pulse_color_enabled:!1,hp_friend_pulse_color:"#FF2222",hp_level_number_visible:!0,hp_pip_visible:!0,hp_ult_color_enabled:!0,hp_ult_color_custom:"#E16161",hp_kill_zone_enabled:!1,hp_kill_zone_threshold:25,hp_kill_zone_color:"#FF2222",hp_kill_zone_width:3},d={},n={},H=Date.now?Date.now.bind(Date):function(){return+new Date},jb=["pulse_subtle","","pulse_intense"],ie=[.35,.8,1.5,2.5],Ac=[.35,.9,1.8,3,
3],Ba=[!1,!1,!1],Bb=[!1,!1,!1],Fc=[0,0,0],ja=[0,0,0],O=0,hb=null,ha=-1,ib=null,y=null,Ja=null,A=null,F=null,rb=null,tb=-1,sb=-1,Xa=-1,I=0,qc=!1,pd=0,Wa=0,cb=0,qd=0,Mc=0,Ma=0,Aa=-1,ac=null,rd=0,pb=null,Hb="",Jb=0,Ib=0;(function(){for(var a in nb)Object.prototype.hasOwnProperty.call(nb,a)&&(d[a]=nb[a])})();hc();var Sa=!1,ob=0,T=!0,na=0,ma=!0,Pa=0,Cb=0,Fb="",Ec=0,ta=0,bc=null,sd="",la=0,mb=-1,Oa=-1,ed=null,dc=-1,Dc=0;try{$.RegisterForUnhandledEvent("ClientUI_FireOutput",function(a){if(typeof a!=="string"||
a.indexOf("HP_COLORS_PRESET_SNAPSHOT")!==-1)try{if(Sa&&typeof a==="string"&&a===sd)cc("event_duplicate_payload");else if(!Sa||!de()){try{var b=typeof a==="string"?JSON.parse(a):a}catch(g){b=null}if(b&&b.magic_word==="HP_COLORS_PRESET_SNAPSHOT"&&(!b.mod_title||b.mod_title==="HP Colors")&&b.values&&typeof b.values==="object"){var c=typeof b.values_raw==="string"?b.values_raw:"";if(c)var e=c;else try{e=JSON.stringify(b.values)}catch(g){e=""}e&&e===Fb&&Sa?(typeof a==="string"&&(sd=a),cc("event_payload_same_raw")):
ud(b.values)&&e&&(Fb=e,typeof a==="string"&&(sd=a))}}}catch(g){}})}catch(a){}var ba=$.GetContextPanel(),v=null,l=null,J=null,E=null,B=null,W=null,V=null,m=null,M=null,p=null,C=null,ea=null,xa=null,Ia=null,Ta=0,Ea=0,Da=0,kd=0,nc=0,lc=0,qa=0,Tc=0,vc=0,ua=null,va=null,Ya=null,Za=null,$a=null,uc=null,Oc=null,Pc=null,Qc=null,ab=null,Q=0,z=0,Ed=0,Kc=0,Lc=null,he=500,Kb=24,aa=null,P=null,ia=null,kb=null,za=null,La=null,Rc=null,Wb=-1,Vb=-1,bb=null,Md=null,Od=0,Ha=!1,Wc=null,Xc=null,Yc=null,Zc=null,$c=null,
ad=null,bd=null,cd="",dd=0,ka=0,mc=-1,fd="",Sc="",Ob=null,Qb=0,Pb=0,ge=160,wa=null,rc=null,sc=null,Nc=null,Tb=null,da=null,Ub=null,tc=null,yc=0,Ua=-1,Lb=-1,sa=-1,wc=-1,vb=0,U=0,N=0,ub=0,X=0,Ca=0,je=[11,19,27,35],id=["level_tier2","level_tier3","level_tier4","level_tier5"],hd="level_number_visible",Ab=null,Y=null,G=null,jd=-1,Qa=null,fc=0;try{Gc()}catch(a){}try{vd()}catch(a){}try{wd()}catch(a){}})();
