function Hc(k){var w=0;return function(){return w<k.length?{done:!1,value:k[w++]}:{done:!0}}}var Ic=typeof Object.defineProperties=="function"?Object.defineProperty:function(k,w,x){if(k==Array.prototype||k==Object.prototype)return k;k[w]=x.value;return k};
function pe(k){k=["object"==typeof globalThis&&globalThis,k,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var w=0;w<k.length;++w){var x=k[w];if(x&&x.Math==Math)return x}throw Error("Cannot find global object");}var qe=pe(this);function re(k,w){if(w)a:{var x=qe;k=k.split(".");for(var F=0;F<k.length-1;F++){var D=k[F];if(!(D in x))break a;x=x[D]}k=k[k.length-1];F=x[k];w=w(F);w!=F&&w!=null&&Ic(x,k,{configurable:!0,writable:!0,value:w})}}
re("Symbol",function(k){function w(O){if(this instanceof w)throw new TypeError("Symbol is not a constructor");return new x(F+(O||"")+"_"+D++,O)}function x(O,Jc){this.u=O;Ic(this,"description",{configurable:!0,writable:!0,value:Jc})}if(k)return k;x.prototype.toString=function(){return this.u};var F="jscomp_symbol_"+(Math.random()*1E9>>>0)+"_",D=0;return w});
re("Symbol.iterator",function(k){if(k)return k;k=Symbol("Symbol.iterator");Ic(Array.prototype,k,{configurable:!0,writable:!0,value:function(){return se(Hc(this))}});return k});function se(k){k={next:k};k[Symbol.iterator]=function(){return this};return k}function te(k,w){k instanceof String&&(k+="");var x=0,F=!1,D={next:function(){if(!F&&x<k.length){var O=x++;return{value:w(O,k[O]),done:!1}}F=!0;return{done:!0,value:void 0}}};D[Symbol.iterator]=function(){return D};return D}
re("Array.prototype.values",function(k){return k?k:function(){return te(this,function(w,x){return x})}});
(function(){function k(){if(l)try{G&&d.hp_pulse_text_enabled||(l.style&&(l.style.animationDuration=""),l.style&&(l.style.brightness=""),lb=null)}catch(a){}}function w(){var a=Number(d.hp_pulse_bpm)||75;a<30&&(a=30);a>300&&(a=300);a=(60/a).toFixed(3)+"s";Cb!==a&&(Cb=a,m&&m.IsValid&&m.IsValid()&&(m.style.animationDuration=a),p&&p.IsValid&&p.IsValid()&&(p.style.animationDuration=a))}function x(){var a=Number(d.hp_pulse_intensity)|0;if(a<0||a>2)a=1;if(Aa!==a){var b=Aa>=0?Db[Aa]:"",c=Db[a];Aa=a;if(b){try{m&&
m.IsValid&&m.IsValid()&&m.RemoveClass(b)}catch(e){}try{p&&p.IsValid&&p.IsValid()&&p.RemoveClass(b)}catch(e){}}if(c){try{m&&m.IsValid&&m.IsValid()&&m.AddClass(c)}catch(e){}try{p&&p.IsValid&&p.IsValid()&&p.AddClass(c)}catch(e){}}G&&k()}}function F(a,b){if(a)try{a.RemoveClass("low_hp_pulsing"),b&&a.RemoveClass(b),a.style&&(a.style.animationDuration="",a.style.brightness="")}catch(c){}}function D(){if(G||Cb!==null||!(Aa<0)||lb!==null){var a=Aa>=0?Db[Aa]:"";G=0;Cb=null;Aa=-1;Eb=Oa=mb=ba=T=ia=lb=null;F(m,
a);F(l,a);F(p,a)}}function O(a){var b=Fb>=0?Db[Fb]:"";Pa=0;Fb=-1;A=ec=null;F(a||ca,b)}function Jc(a,b){if(a===!0||a===!1)return a;if(a===1||a==="1")return!0;if(a===0||a==="0")return!1;if(typeof a==="string"){a=a.toLowerCase();if(a==="true")return!0;if(a==="false")return!1}return!!b}function Fd(){try{if(typeof GameUI!=="undefined"&&GameUI&&GameUI.CustomUIConfig)return GameUI.CustomUIConfig()}catch(a){}return null}function Gd(){if(!fc||!r(fc)){var a=ja;for(var b=null,c=0;a&&c<24;){r(a)&&(b=a);var e=
null;try{e=a.GetParent?a.GetParent():null}catch(h){e=null}if(!e||e===a)break;a=e;c+=1}fc=b||ja||null}a=fc;if(!r(a)||!a.GetAttributeString)return"";try{return String(a.GetAttributeString("hp_colors_minimal_cfg_raw","")||"")}catch(h){}return""}function Hd(a){d.hp_enabled&&!nb&&(nb=!0,H(a===void 0?.01:a,function(){nb=!1})||(nb=!1))}function Kc(a){d.hp_friend_enabled&&!Gb&&(Gb=!0,P(a===void 0?.01:a,function(){Gb=!1})||(Gb=!1))}function Id(a){d.hp_level_number_visible&&!ob&&(ob=!0,Lc(a===void 0?.01:a,
function(){ob=!1})||(ob=!1))}function hc(){var a=I();if(!Mc||a-Mc>=5E3||ic!==ka||pb!==la||Qa!==la||!((!d.hp_enabled||Ra&&Ba)&&(!d.hp_friend_enabled||Sa&&da)&&(!d.hp_level_number_visible||Ta&&Ca))){Mc=a;var b=ka;try{jc()}catch(c){}ka!==b||ic!==ka||pb!==la||Qa!==la||((!d.hp_enabled||Ra&&Ba)&&(!d.hp_friend_enabled||Sa&&da)&&(!d.hp_level_number_visible||Ta&&Ca)?a-Hb>=5E3&&Jd():1)?Nc&&a-Nc<250||(Nc=a,ic=ka,ma=V=!0,Ua=na=0,Va=null,Ib(),Hd(.01),Kc(.01),Id(.01)):ic=ka}}function Oc(a,b){a=Number(a);return!isFinite(a)||
a<0?b:a}function H(a,b){if(!d.hp_enabled)return!1;a=Oc(a,.05);var c=I()+a*1E3;if(Ba&&Ba<=c)return!1;Ba=c;var e=++kc;$.Schedule(a,function(){e===kc&&(Ba=0,b&&b(),d.hp_enabled&&ue())});return!0}function P(a,b){if(!d.hp_friend_enabled)return!1;a=Oc(a,.05);var c=I()+a*1E3;if(da&&da<=c)return!1;da=c;var e=++Pc;$.Schedule(a,function(){e===Pc&&(da=0,b&&b(),d.hp_friend_enabled&&ve())});return!0}function Lc(a,b){if(!d.hp_level_number_visible)return!1;a=Oc(a,.05);var c=I()+a*1E3;if(Ca&&Ca<=c)return!1;Ca=c;
var e=++lc;$.Schedule(a,function(){e===lc&&(Ca=0,b&&b(),d.hp_level_number_visible&&(d.hp_level_number_visible?(Ta=!0,mc=we()?0:mc+1,Lc(mc>10?5:.5)):(Kd(),ob=Ta=!1,Ca=0,lc++)))});return!0}function Ld(a){if(!a)return!1;var b=0,c;for(c in a)if(Object.prototype.hasOwnProperty.call(a,c)&&Object.prototype.hasOwnProperty.call(qb,c)){var e=c;var h=c,g=a[c];if(Object.prototype.hasOwnProperty.call(qb,h)){var f=qb[h];if(h==="hp_counter_position"||h==="hp_pulse_text_position")b:if(f=g,h=0,g=200,f&&typeof f===
"object")Array.isArray(f)?(f.length>0&&(h=u(f[0],0,400,0)),f.length>1&&(g=u(f[1],-50,400,200))):(Object.prototype.hasOwnProperty.call(f,"x")&&(h=u(f.x,0,400,0)),Object.prototype.hasOwnProperty.call(f,"y")&&(g=u(f.y,-50,400,200))),f=Math.round(h)+","+Math.round(g);else{if(typeof f==="string"){var J=f.match(/-?\d+(?:\.\d+)?/g);if(J&&J.length>0){h=u(J[0],0,400,0);J.length>1&&(g=u(J[1],-50,400,200));f=Math.round(h)+","+Math.round(g);break b}}typeof f==="number"&&(g=u(f,-50,400,200));f=Math.round(h)+","+
Math.round(g)}else typeof f==="boolean"?f=Jc(g,f):typeof f==="number"?(h=Number(g),f=isFinite(h)?Math.round(h):f):f=typeof f==="string"?typeof g==="string"&&g.length>0?g:f:g}else f=g;d[e]=f;b+=1}if(!b)return!1;nc();try{jc()}catch(Q){}try{Wa()}catch(Q){}Ib();Xa=!0;la++;ma=V=!0;Ua=na=0;Va=null;Qa=pb=-1;oc();Md();Hd();Kc();Id();return!0}function Qc(){var a=Fd(),b="";if(a)try{b=String(a.__hpColorsCfgRaw||"")}catch(c){b=""}b||(b=Gd());if(!b)return!1;if(b===Jb&&Xa)return hc("shared_same_raw"),!0;a=null;
try{a=JSON.parse(b)}catch(c){return!1}a=a&&typeof a==="object"?a.values||a:null;if(!a||typeof a!=="object"||!Ld(a))return!1;Jb=b;return!0}function Nd(){if(!Xa&&!Qc()){rb+=1;var a=rb<=8,b=rb>20,c=rb===1?"overlay_startup":"overlay_retry",e=!0;!a&&b&&(e=rb===21||(rb-20-1)%6===0)&&(c="overlay_late_retry");if(e){c=String(c||"overlay_request");try{$.DispatchEvent("ClientUI_FireOutput",JSON.stringify({magic_word:"HP_COLORS_PRESET_REQUEST",mod_title:"HP Colors",reason:c}))}catch(h){}}$.Schedule(a?.5:b?10:
3,Nd)}}function xe(){var a=Fd(),b="";try{b=a?String(a.__hpColorsCfgRaw||""):""}catch(c){b=""}b||(b=Gd());return b?b===Jb?(hc("event_store_same_raw"),!0):Qc():!1}function ye(a){function b(c){c=+c|0;return c<0?0:c>255?255:c}return"#"+(16777216|b(a[0])<<16|b(a[1])<<8|b(a[2])).toString(16).slice(1)}function oa(a,b,c){a=a.slice(1);a.length===3&&(a=a[0]+a[0]+a[1]+a[1]+a[2]+a[2]);b=b.slice(1);b.length===3&&(b=b[0]+b[0]+b[1]+b[1]+b[2]+b[2]);a=parseInt(a,16);b=parseInt(b,16);return"#"+(16777216|((a>>16&255)+
((b>>16&255)-(a>>16&255))*c|0)<<16|((a>>8&255)+((b>>8&255)-(a>>8&255))*c|0)<<8|(a&255)+((b&255)-(a&255))*c|0).toString(16).slice(1)}function pa(a){if(typeof a!=="string")return"";a=a.trim();if(!a)return"";if(a.charAt(0)==="#")return a.length===4?("#"+a.charAt(1)+a.charAt(1)+a.charAt(2)+a.charAt(2)+a.charAt(3)+a.charAt(3)).toLowerCase():a.length>=7?a.slice(0,7).toLowerCase():a;var b=a.match(/^rgba?\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)/i);return b?ye([b[1],b[2],b[3]]):a}function Kb(){return d.hp_team_colors?
U===2?"#6485FC":"#FFC961":d.hp_color_high}function Od(a,b,c){return d.hp_pulse_color_enabled?(d.hp_pulse_color_mode|0)===1?(b=u((c-b)/Math.max(1,c),0,1,0),oa(a,d.hp_pulse_color,b)):d.hp_pulse_color:a}function Rc(a,b,c){return d.hp_text_color_mode?a<=b?d.hp_text_color_low:a<=c?d.hp_text_color_mid:d.hp_text_color_high:a<=b?d.hp_color_low:a<=c?d.hp_color_mid:Kb()}function r(a){try{return!(!a||a.IsValid&&!a.IsValid())}catch(b){}return!1}function oc(){sb=null;Lb="";Mb=Nb=0}function Pd(a,b){if(!r(a))return!1;
if(b==="any")return!0;a=pc(a,Ob)&255;if(b==="friend"){if(a&8)return!0;Mb=a;return!1}return b==="enemy"?Qd(a)?!0:!1:!0}function Sc(a){a=a||"any";Mb=0;var b=I(),c;if(c=Lb===a&&r(sb)){c=b-Nb;var e=a,h=I();c=c<=(qa&&h<=qa?80:e==="friend"?160:Da>=8||W>=8?300:120)}if(c)return sb;c=ja.FindChildTraverse("unit_healthbar_lagging");if(Pd(c,a)||r(v)&&(c=v.FindChildTraverse("unit_healthbar_lagging"),Pd(c,a)))return sb=c,Lb=a,Nb=b,c;sb=null;Lb=a;Nb=b;return null}function ra(a){try{return!(!a||!a.IsValid||a.IsValid())}catch(b){}return!1}
function qc(a){try{return a&&a.actuallayoutwidth!==void 0?a.actuallayoutwidth|0:0}catch(b){}return 0}function Tc(a){try{return a&&a.GetParent?a.GetParent():null}catch(b){}return null}function Rd(){return W>=8?2500:W>=3?1800:Da>=8?2500:Da>=3?1800:1200}function ze(a,b){if(!b){if(rc&&a<rc)return!1;b=qa&&a<=qa?180:Rd();rc=a+b}if(!R||!R.Children)return!1;a=[];try{a=R.Children()}catch(f){return!1}b=m;for(var c=Sd(m,-1),e=0;e<a.length;e++){var h=a[e];if(r(h)){var g="";try{g=String(h.id||"")}catch(f){g=""}g===
"unit_healthbar_lagging"&&(g=Sd(h,e),g>c&&(b=h,c=g))}}return b&&b!==m?Td(b):!1}function pc(a,b){var c=0,e=0,h=0;for(b=b||Ob;a&&h<b&&!(a.BHasClass&&(c||(a.BHasClass("team2")?c=2:a.BHasClass("team1")&&(c=1)),e&1||!a.BHasClass("enemy")||(e|=1),e&2||!a.BHasClass("team_neutral")||(e|=2),e&4||!(a.BHasClass("building")||a.BHasClass("destroyable_building")||a.BHasClass("guardian")||a.BHasClass("boss_tier1")||a.BHasClass("boss_tier2")||a.BHasClass("boss_tier_01")||a.BHasClass("boss_tier_02")||a.BHasClass("boss_tier_01_brazier_guardian")||
a.BHasClass("boss_barracks"))||(e|=4),e&8||!a.BHasClass("friend")||(e|=8),c&&e&15))&&a.GetParent;)a=a.GetParent(),h++;return c<<8|e}function Sd(a,b){if(!r(a))return-1;var c=qc(a),e=qc(Tc(a)),h=e>0,g=h?120:-200,f=pc(a,Ob)&255;f&1&&!(f&2)?g+=h?700:120:f&8?g-=160:f&2?g-=120:f&15||(g-=40);a===m&&(g+=h?80:-40);c>0&&(g+=40);e>0&&(g+=Math.min(e,400)/20);b>=0&&(g+=Math.min(b,20));return g}function Td(a){X=R=(Y=m=a)&&a.GetParent?a.GetParent():null;Ea=Fa=Ya=0;oc();Uc=y=U=0;Vc=null;jc();sa=Pb=Za=-1;Da=0;sc=
-1;Qb();return!0}function Ib(){qa=I()+1600;rc=tc=0}function Ud(a){return qa&&a<=qa||W||S&&S<4||Z&&Z<4?!0:y&2?S<4:y&4?d.hp_skip_buildings?Z<4:S<4:y&1?!1:S<4}function uc(a){return!!(a&4&&(a&8||U&&U===Vd))}function Qd(a){return a&2||d.hp_friend_enabled&&a&8?!1:a&1?!0:!(!(a&4)||a&2||!U||uc(a))}function $a(a){if(Eb!==a||ba===null){var b=pa(a);b||(b="");Eb=a;if(ba!==b&&m)try{ba=m.style.washColor=b}catch(c){ba=null}}}function vc(a){if(d.hp_ult_color_enabled){if(!p||!p.IsValid()){var b=I();if(ta&&b-ta<2E3)return;
if((p=ja.FindChildTraverse("unit_ult_ready_icon"))&&p.IsValid())ta=0;else{ta=b;return}}if(p&&p.style&&(Oa!==a||!T)&&(b=pa(a)||"#E16161",Oa=a,T!==b))try{T=p.style.washColor=b}catch(c){T=null}}else{a=d.hp_ult_color_custom||"#E16161";if(!p||!p.IsValid()){b=I();if(ta&&b-ta<2E3)return;if((p=ja.FindChildTraverse("unit_ult_ready_icon"))&&p.IsValid())ta=0;else{ta=b;return}}if(p&&p.style&&(Oa!==a||!T)&&(b=pa(a)||"#E16161",Oa=a,T!==b))try{T=p.style.washColor=b}catch(c){T=null}}}function Rb(a){if(mb!==a||!ia){var b=
pa(a);if(l&&l.style&&(mb=a,ia!==b))try{ia=l.style.washColor=b}catch(c){ia=null}}}function Wd(){return y&1&&!(y&2)?"":y&4&&!(y&2)&&U&&!uc(y)?"#E16161":uc(y)?"#ffffff":y&6?"#5BEFB5":y&8?"#FFEFD7":U===2?"#5B79E6":U===1?"#E7B659":"#E16161"}function Xd(a){Sb=!1;Ga=0;A=null;ab=bb=-1;Wc=K=0;wc();O(a)}function wc(){Xc=null;Yc=Zc=0}function Yd(a){var b=I();if(a===Xc&&b-Zc<Ae)return Yc;var c=pc(a,Ob)&255;Xc=a;Zc=b;return Yc=c}function Tb(a){var b=ca,c=b&&b.IsValid&&b.IsValid()?Yd(b):0;if(a&&b&&c&8){if(b&&b===
ca&&(Sb=!1,Ga=0,O(b),A=null,ab=bb=-1,K=0,b.style)){a=c&4?"#ffffff":"#FFEFD7";try{b.style.washColor=a,A=pa(a),Ub=a}catch(e){Ub=A=null}}}else Xd(b);ca=null;wc()}function u(a,b,c,e){a=Number(a);isFinite(a)||(a=Number(e));isFinite(a)||(a=0);isFinite(b)&&a<b&&(a=b);isFinite(c)&&a>c&&(a=c);return a}function Vb(a){return u(a,0,100,0)|0}function nc(){var a=Vb(d.hp_low_threshold),b=Vb(d.hp_high_threshold);b<a&&(b=a);var c=d.hp_kill_zone_width|0;c<1&&(c=1);c>100&&(c=100);var e=u(d.hp_counter_size,72,400,145);
n.low=a;n.high=b;n.i=Math.max(1,b-a);n.g=Math.max(1,100-b);n.H=Vb(d.hp_pulse_threshold);n.o=Vb(d.hp_friend_pulse_threshold);n.m=e;n.G=u(d.hp_pulse_text_scale,72,320,e);n.l=Zd(d.hp_counter_position,!0);n.F=Zd(d.hp_pulse_text_position,!1);n.A=Math.round(u(d.hp_healthbar_height,0,230,130));n.C=Vb(d.hp_kill_zone_threshold);n.D=c;n.j=d.hp_kill_zone_color||"#FF2222";n.B=pa(n.j)}function Wb(a){E&&E.style&&(ua!=="visible"&&(ua=E.style.visibility="visible"),a=a?"1.0":"0.01",va!==a&&(va=E.style.opacity=a))}
function Wa(){wa=xc=yc=$c=Xb=ea=Yb=zc=ua=va=cb=db=eb=Ac=ad=bd=cd=fb=Eb=Oa=mb=dd=ba=T=ia=null;Zb=$b=-1;gb=null;ed="";Qb()}function $d(){if(!m||!m.style||!ba)return!1;try{return pa(String(m.style.washColor||""))!==ba}catch(a){}return!1}function Jd(){if($d())return!0;if(d.hp_counter_visible&&l&&l.style){try{if(cb!==null&&l.style.fontSize!==cb)return!0}catch(a){}try{if(db!==null&&l.style.height!==db)return!0}catch(a){}}if(d.hp_counter_visible&&M&&M.style)try{if(eb!==null&&M.style.transform!==eb)return!0}catch(a){}return!1}
function Qb(){fd=Bc=0}function Ha(a,b){if((!B||!r(B))&&a&&d.hp_kill_zone_enabled&&v&&v.FindChildTraverse)try{B=v.FindChildTraverse("hp_kill_zone_marker")}catch(f){}if(B&&B.style){var c=!E||!E.style||ua!=="visible"||va!=="1.0";if(!a||!d.hp_kill_zone_enabled||b<=0||c){if(zc=null,wa!=="collapse"&&(wa=B.style.visibility="collapse"),ea!=="0")try{ea=B.style.opacity="0"}catch(f){ea=null}}else{a=n.C;c=n.D;var e=Math.round(b*a/100-c/2);e<0&&(e=0);e>b-c&&(e=Math.max(0,b-c));e+="px";var h=c+"px";dd!==n.j&&(dd=
n.j,$c=n.B);var g=$c;b=b+"|"+a+"|"+c+"|"+n.j+"|"+g+"|"+ua+"|"+va;if(zc!==b||wa!=="visible"||ea!=="0.95"||Yb!=="1000"||xc!==e||yc!==h||Xb!==g){zc=b;wa!=="visible"&&(wa=B.style.visibility="visible");if(ea!=="0.95")try{ea=B.style.opacity="0.95"}catch(f){ea=null}if(Yb!=="1000")try{Yb=B.style.zIndex="1000"}catch(f){Yb=null}xc!==e&&(xc=B.style.marginLeft=e);yc!==h&&(yc=B.style.width=h);if(Xb!==g)try{Xb=B.style.backgroundColor=g}catch(f){Xb=null}}}}}function Zd(a,b){var c=0,e=200;b=b?-200:0;if(a&&typeof a===
"object")return Array.isArray(a)?(a.length>0&&(c=u(a[0],0,400,0)),a.length>1&&(e=u(a[1],b,400,200))):(Object.prototype.hasOwnProperty.call(a,"x")&&(c=u(a.x,0,400,0)),Object.prototype.hasOwnProperty.call(a,"y")&&(e=u(a.y,b,400,200))),{x:c,y:e};if(typeof a==="string"){var h=a.match(/-?\d+(?:\.\d+)?/g);if(h&&h.length>0)return c=u(h[0],0,400,0),h.length>1&&(e=u(h[1],b,400,200)),{x:c,y:e}}typeof a==="number"&&(e=u(a,b,400,200));return{x:c,y:e}}function gd(a){if(l&&l.style){a=!!(a&&d.hp_pulse_enabled&&
d.hp_pulse_text_enabled);var b=n.m||u(d.hp_counter_size,72,400,145);b=a?n.G||u(d.hp_pulse_text_scale,72,320,b):b;var c=a?n.F:n.l,e=u(c.x,0,400,0),h=u(c.y,-50,400,200);c=b+"px";var g="100%";if(a){a=130;try{var f=l.GetParent?l.GetParent():null;f&&f.actuallayoutheight>0&&(a=f.actuallayoutheight)}catch(J){}g=Math.max(a,Math.round(b*1.85))+"px"}f="translate3d("+Math.round(e)+"px, "+Math.round(Math.max(h-150,-200))+"px, 0px)";cb!==c&&(cb=l.style.fontSize=c);db!==g&&(db=l.style.height=g);M&&M.style&&eb!==
f&&(eb=M.style.transform=f)}}function Ia(a){if(l&&l.style){var b=a?"visible":"collapse";if(gb!==b)try{gb=l.style.visibility=b}catch(c){gb=null}a||(Zb=$b=-1,Ja=!1)}}function hd(a){if(ed!==String(a||"")+"|"+gb+"|"+wa+"|"+ea+"|"+ua+"|"+va+"|"+G||G)D(),Ia(!1),Ha(!1,0),$a(a||""),Rb("#ffffff"),Wb(!0),ed=String(a||"")+"|"+gb+"|"+wa+"|"+ea+"|"+ua+"|"+va+"|"+G}function ae(){D();Ia(!1);Ha(!1,0);Wb(!0)}function jc(){var a="";try{Ka&&(a=Ka.text||Ka.GetAttributeString("text","")||"")}catch(b){a=""}if(m!==id||
R!==jd||X!==kd||l!==ld||E!==md||B!==nd||z!==od||a!==pd)id=m,jd=R,kd=X,ld=l,md=E,nd=B,od=z,pd=a,ka++,Qa=pb=sc=-1,Hb=qd=I(),Wa(),D(),Sb=!1,A=La=t=fa=rd=ca=null,tb=ab=bb=-1,hb=Ga=K=0,Va=null,Cc=sa=Pb=Za=-1,Da=Z=ub=S=W=vb=0,Ja=!1,sd="",ma=V=!0,Ua=na=0,Ib()}function be(){D();if(m&&m.style)try{m.style.washColor=""}catch(a){}if(p&&p.style)try{p.style.washColor=""}catch(a){}if(l&&l.style)try{l.style.washColor=""}catch(a){}mb=ia=Oa=T=Eb=ba=null;Ha(!1,0);E&&E.style&&(ua!=="collapse"&&(ua=E.style.visibility=
"collapse"),va!=="0"&&(va=E.style.opacity="0"));if(l&&l.style){try{l.style.fontSize="",l.style.height="",l.style.washColor=""}catch(a){}mb=ia=db=cb=null}M&&M.style&&(M.style.transform="",eb=null);Cc=sa=Pb=Za=-1;Da=Z=ub=S=W=vb=0;Qb()}function Kd(){C&&C.IsValid()||ce();if(C&&C.IsValid&&C.IsValid()){try{C.RemoveClass(td)}catch(b){}for(var a=0;a<4;a++)try{C.RemoveClass(ud[a])}catch(b){}}Va=!1;vd=-1;mc=0}function Md(){nc();d.hp_enabled?d.hp_enabled&&!Ra&&(Ra=!0,H(.05)):(be(),nb=Ra=!1,Ba=0,kc++);d.hp_friend_enabled?
d.hp_friend_enabled&&!Sa&&(Sa=!0,P(.05)):(Tb(!0),Gb=Sa=!1,da=0,Pc++);d.hp_level_number_visible?d.hp_level_number_visible&&!Ta&&(Ta=!0,Lc(.05)):(Kd(),ob=Ta=!1,Ca=0,lc++);d.hp_counter_visible||(Ia(!1),Zb=$b=-1);!d.hp_pulse_enabled&&G&&D();G?(Cb=null,w(),x(),k()):d.hp_pulse_text_enabled||(Ja=!1,gd(!1));!d.hp_friend_pulse_enabled&&Pa&&O(t);d.hp_kill_zone_enabled||Ha(!1,0);if(z&&z.style&&!d.hp_pip_visible&&fb!=="collapse")try{fb=z.style.visibility="collapse"}catch(a){fb=null}}function de(a,b,c){if(!d.hp_counter_visible)Ia(!1);
else if(l&&(a!==$b||b!==Zb)){Ia(!0);var e=d.hp_counter_format|0;e=e===1?(b>0?Math.round(a/b*100):0)+"%":e===2?String(a):a+" / "+b;try{l.text!==e&&(l.text=e)}catch(h){try{l.SetAttributeString("text",e)}catch(g){}}c=!!c;e=cb===null||db===null||M&&M.style&&eb===null;c!==Ja||e?(Ja=c,gd(Ja)):Ja=c;$b=a;Zb=b}}function ue(){Ra=!0;try{if(d.hp_enabled){var a=I(),b=!1;if(Ya||m)if(ra(v)||ra(l)||ra(E)||ra(z)||ra(Y)||ra(X)||ra(m)||ra(R)||ra(Ka))v=l=M=E=z=Y=X=m=R=p=B=fa=xa=Ka=null,Ea=Fa=Ya=0,id=jd=kd=ld=md=nd=od=
null,pd="",Wa(),ma=V=!0,oc(),Ib();if(r(m)){if(Ud(a))if(tc&&a<tc)b=!1;else{tc=a+(qa&&a<=qa?180:Rd());var c=Sc("enemy");if(r(c)&&c!==m){var e=qc(Tc(c)),h=qc(Tc(m));b=e<=0&&h>0||e<=0?!1:Td(c)}else b=!1}}else{if(!wd||a>=wd)wd=(m=Sc("any"))?0:a+150;if(!m){H(.15);return}}var g;if(!(g=Ya))a:{if(Ya){var f=!d.hp_counter_visible||r(l);if(r(v)&&f&&r(E)&&r(z)&&r(Y)&&r(X)&&r(Ka)){g=1;break a}Ea=Ya=0}var J=I();if(Ea&&J<Ea)var Q=0;else Fa++,r(v)||(v=ja.FindChildTraverse("UnitStatus")),v?(r(l)||!d.hp_counter_visible&&
gb==="collapse"||(l=v.FindChildTraverse("hp_counter")),d.hp_counter_visible&&!r(M)&&(M=v.FindChildTraverse("hp_counter_anchor")),r(E)||(E=v.FindChildTraverse("unit_healthbar_bg")),r(z)||(z=v.FindChildTraverse("unit_healthbar_pip_label")),r(Y)||(Y=v.FindChildTraverse("unit_healthbar_lagging")),d.hp_kill_zone_enabled&&!r(B)&&(B=v.FindChildTraverse("hp_kill_zone_marker")),r(p)||(p=v.FindChildTraverse("unit_ult_ready_icon")),r(fa)||(fa=v.FindChildTraverse("InfoHealthContainer")),r(xa)||(xa=v.FindChildTraverse("UnitHealthbarContainer")),
r(Ka)||(Ka=ja.FindChildTraverse("name")),r(p)&&(ta=0),Y&&!r(X)&&(X=Y.GetParent()),z&&Y&&X?(Ya=1,Ea=Fa=0,Q=1):(Ea=J+(Fa<8?150:Fa<24?500:1500),Q=0)):(Ea=J+(Fa<8?150:Fa<24?500:1500),Q=0);g=Q}if(g){if(m.GetParent){var wb=m.GetParent();R!==wb&&(R=wb)}!b&&Ud(a)&&ze(a,!1);jc();b=m;var N=I();if(!(b===Vc&&N-Uc<Be)){var Ma=pc(b,Ob);U=Ma>>8;y=Ma&255;U&&y&8&&(Vd=U);Uc=N;Vc=b}var q=Qd(y);pb!==la&&(pb=la,V=!0,na=0,Wa());N=U+":"+y;N!==sd&&(sd=N,Wa(),V=!0,na=a,ma=!0,Ua=a,Va=null,Ib());if(d.hp_skip_buildings&&y&4)Z++,
S=0,y&8||uc(y)?(hd("#ffffff"),d.hp_friend_enabled&&ae()):hd(Wd()),H(Z<4?.3:Z<12?.6:1.5);else if(N=V,q&&a-Hb>=5E3&&(Hb=a,Jd()&&(Wa(),V=!0,na=a,N=!0)),y&2)D(),ub++,Z=S=0,Wb(!0),Ha(!1,0),Ia(!1),$a("#5BEFB5"),Rb("#ffffff"),Dc=a,H(ub<4?.75:1.5);else if(q){Z=ub=S=0;if(V){if(a<na){H(.05);return}nc();Wb(!q||!!d.hp_bg_visible);d.hp_counter_visible?gd(Ja):Ia(!1);fa&&fa.IsValid()||!v||!v.IsValid()||(fa=v.FindChildTraverse("InfoHealthContainer"));if(fa&&fa.style){var ya=-15+u(d.hp_info_health_margin_top,0,100,
23)*.65;Math.abs(ya)<.5&&(ya=0);var za=Math.round(ya*10)/10;Math.abs(za-Math.round(za))<.01&&(za=Math.round(za));var aa=za+"%";if(Ac!==aa)try{Ac=fa.style.marginTop=aa}catch(ac){Ac=null}}xa&&xa.IsValid()||!v||!v.IsValid()||(xa=v.FindChildTraverse("UnitHealthbarContainer"));var xb=n.A||Math.round(u(d.hp_healthbar_height,0,230,130));aa=xb+"px";xa&&xa.style&&ad!==aa&&(ad=xa.style.height=aa);if(z&&z.style){var yb=Math.min(75,Math.round(xb*75/230))+"px";bd!=="52%"&&(bd=z.style.height="52%");cd!==yb&&(cd=
z.style.fontSize=yb)}Hb=I();Qb();sa=Za=-1;V=!1;na=0}if(Xa){var xd=m.actuallayoutwidth|0,bc=R&&R.actuallayoutwidth!==void 0?R.actuallayoutwidth|0:0;if(xd!==Za||bc!==Pb||G||N||sc!==ka)if(Da=0,Za=xd,Pb=bc,Dc=a,bc<=0)W++,$a(Kb()),Ha(!1,0),H(W<3?.18:W<6?.75:W<10?1.5:2.5);else{W=0;d.hp_kill_zone_enabled?Ha(!0,bc):wa!=="collapse"&&Ha(!1,0);q=xd/bc*100|0;var L=n.low,ha=n.high,yd=n.H,ib=!!(d.hp_pulse_enabled&&q<=yd);if(Math.abs(q-sa)<3&&q>L&&sa>L&&!G&&!ib&&!N)H(.25);else{xb=sa;q===Cc?vb++:(vb=0,Cc=q);sa=q;
var zb=!!d.hp_counter_visible,Na=d.hp_counter_format|0;yb="";if(z)try{var cc=d.hp_pip_visible?"visible":"collapse";fb!==cc&&(fb=z.style.visibility=cc);zb&&Na!==1&&(yb=z.text||z.GetAttributeString("text","")||"")}catch(ac){yb="",fb=null}if(zb&&Y&&X)if(Na===1)de(q,100,ib);else{var Ec=Y.actuallayoutwidth||0,jb=X.actuallayoutwidth||0;zb=jb>0?Ec/jb:0;Na=yb;if(Na!==ee){ee=Na;Ec=cc=0;var fe=Na.lastIndexOf("|");for(jb=0;jb<Na.length;jb++){var zd=Na.charCodeAt(jb);zd===124?cc++:zd!==34&&zd!==39||!(fe===-1||
jb>fe)||Ec++}ge=cc*500+Ec*100}var kb=ge;de(zb>=.97?kb:Math.round(kb*zb),kb,ib)}else zb||Ia(!1);kb=.15;Wb(ib&&d.hp_pulse_hide_bar?!1:!!d.hp_bg_visible);if(q<=L){if(qd&&a-qd<900&&(xb<0||xb<=L&&q>xb)){var he=Kb();D();$a(he);vc(he);Rb(Rc(100,L,ha));H(.05);return}var dc=d.hp_color_low;var ie=d.hp_mode===1?d.hp_text_color_mode?d.hp_text_color_low:d.hp_color_low:Rc(q,L,ha);var je=ib?Od(dc,q,yd):dc;$a(je);vc(je)}else{var ke=Kb();dc=q<=ha?d.hp_mode===1?oa(d.hp_color_low,d.hp_color_mid,(q-L)/n.i):d.hp_color_mid:
d.hp_mode===1?oa(d.hp_color_mid,ke,(q-ha)/n.g):ke;var Ad;d.hp_mode===1?Ad=d.hp_text_color_mode?q<=L?d.hp_text_color_low:q<=ha?oa(d.hp_text_color_low,d.hp_text_color_mid,(q-L)/n.i):oa(d.hp_text_color_mid,d.hp_text_color_high,(q-ha)/n.g):q<=L?d.hp_color_low:q<=ha?oa(d.hp_color_low,d.hp_color_mid,(q-L)/n.i):oa(d.hp_color_mid,Kb(),(q-ha)/n.g):Ad=Rc(q,L,ha);ie=Ad;q>ha&&vb>=5&&(kb=Ce[Math.min(Math.floor((vb-5)/5),3)]);var le=ib?Od(dc,q,yd):dc;$a(le);vc(le)}Rb(ie);if(ib){if(!G&&!G){G=1;ba=T=ia=null;try{m&&
m.AddClass("low_hp_pulsing")}catch(ac){}try{p&&p.AddClass("low_hp_pulsing")}catch(ac){}x();w()}if(d.hp_pulse_text_enabled){if(l&&l.style&&G&&d.hp_pulse_text_enabled){var De=u(d.hp_pulse_bpm,30,300,75),me=Math.max(1,6E4/De);a=a%me/me;a=a<.5?a*2:(1-a)*2;var Fc=u(d.hp_pulse_intensity,0,2,1)|0;L=Fc===2?.55:Fc===0?.85:.65;var ne=(L+((Fc===2?2:Fc===0?1.15:1.5)-L)*a).toFixed(2);if(lb!==ne)try{lb=l.style.brightness=ne}catch(ac){lb=null}}kb=.1}}else G&&D();sc=ka;H(kb)}}else{Da++;if(q&&a>=fd){fd=a+(Bc>=8?950:
Bc>=3?700:350);if($d()){Qb();Wa();V=!0;na=a;sa=Za=-1;H(.05);return}Bc++}H(a-Dc>2E3?1.5:.25)}}else $a("#E16161"),vc("#E16161"),Rb("#ffffff"),H(.05)}else{S++;Z=ub=0;var oe=!!(y&8&&d.hp_friend_enabled);if(oe)a:{if(ae(),d.hp_friend_enabled){if(Sb&&da&&da>a){if(da-a<=250)break a;if(ca&&r(ca)){if(Bd&&a-Bd<3E3)break a;Bd=a;break a}}Cd&&a-Cd<2500||(Cd=a,Kc(.01))}}else hd(Wd());Dc=a;H(oe?S<4?.2:2:S<4?.2:1.25)}}else H(.15)}else be(),nb=Ra=!1,Ba=0,kc++}catch(ac){H(.5)}finally{}}function ce(){Ab&&Ab.IsValid()||
(Ab=ja.FindChildTraverse("unit_level_label"));Bb&&Bb.IsValid()||(Bb=ja.FindChildTraverse("UnitStatus"));if(!(!Bb||C&&C.IsValid()))a:{for(var a=Bb;a;){if(a.BHasClass&&a.BHasClass("enemy")){C=a;break a}if(!a.GetParent)break;a=a.GetParent()}C=null}return Ab&&Bb&&C}function we(){if(!ce())return!1;if(C&&C.IsValid()){var a=!!d.hp_level_number_visible;Va!==a&&(a?C.AddClass(td):C.RemoveClass(td),Va=a)}a="";try{a=Ab.text||Ab.GetAttributeString("text","")||""}catch(h){a=""}if(!a||a.charCodeAt(0)===123)return!1;
for(var b=0,c=0;c<a.length;c++){var e=a.charCodeAt(c)-48;e>=0&&e<=9&&(b=b*10+e)}a=b;if(a===vd||!a)return!1;vd=a;for(b=0;b<4;b++)C.RemoveClass(ud[b]);for(b=3;b>=0;b--)if(a>=Ee[b]){C.AddClass(ud[b]);break}return!0}function ve(){Sa=!0;try{if(d.hp_friend_enabled){var a=I();if(!t||!t.IsValid()){Tb(!1);La=t=null;t=Sc("friend");if(!t){Dd++;if(Mb&4){P(2.5);return}if(Mb){P(1.2);return}P(Dd>75?3:.2);return}wc()}Dd=0;if(t.GetParent){var b=t.GetParent();La!==b&&(La=b)}t!==rd&&(rd=t,Qa=-1,ma=!0,Ua=0,A=null,tb=
ab=bb=-1);if(b=Qa!==la)ma=!0,Ua=0,A=null,tb=ab=bb=-1,K=0;if(ma){if(a<Ua){P(.05);return}ma=!1;Xd(ca)}if(Yd(t)&8){b&&(Qa=la);hb=0;var c=t.actuallayoutwidth|0,e=La&&La.actuallayoutwidth!==void 0?La.actuallayoutwidth|0:0;if(e<=0)Ga++,P(Ga<4?.2:Ga<12?.4:.8);else{Ga=0;if((b=c===bb&&e===ab)&&!Pa)if(a>=Wc){Wc=a+(K>=3?2500:1200);a:{if(t&&t.style&&A)try{var h=pa(String(t.style.washColor||""))!==A;break a}catch(aa){}h=!1}if(h)A=null;else{K++;P(Gc[Math.min(Math.floor(K/3),4)]);return}}else{K++;P(Gc[Math.min(Math.floor(K/
3),4)]);return}bb=c;ab=e;a=c/e*100|0;c=tb;var g=n.low,f=n.high,J=!!(d.hp_friend_pulse_enabled&&a<=n.o);var Q=J&&d.hp_friend_pulse_color_enabled?d.hp_friend_pulse_color:a<=g?d.hp_friend_color_low:a<=f?d.hp_mode===1?oa(d.hp_friend_color_low,d.hp_friend_color_mid,(a-g)/n.i):d.hp_friend_color_mid:d.hp_mode===1?oa(d.hp_friend_color_mid,d.hp_friend_color_high,(a-f)/n.g):d.hp_friend_color_high;if(Ub===Q&&A){var wb=A;var N=!1}else wb=pa(Q),N=A!==wb;if(N&&t)try{A=t.style.washColor=wb,Ub=Q,Sb=!0,ca=t}catch(aa){Ub=
A=null}g=.35;Q=f=!1;if(J){if(!Pa){Q=!0;Pa=1;Fb=-1;A=null;try{t&&t.AddClass("low_hp_pulsing")}catch(aa){}var Ma=Number(d.hp_friend_pulse_intensity)|0;if(Ma<0||Ma>2)Ma=1;Fb=Ma;var q=Db[Ma];if(q)try{t.AddClass(q)}catch(aa){}}var ya=Number(d.hp_friend_pulse_bpm)||75;ya<30&&(ya=30);ya>300&&(ya=300);var za=(60/ya).toFixed(3)+"s";if(ec!==za)try{t&&(t.style.animationDuration=za),ec=za}catch(aa){ec=null}g=.15}else Pa&&(O(t),A=null,f=!0);J&&!Q&&!N&&a===c&&b?(K++,g=Gc[Math.min(Math.floor(K/3),4)]):J||N||f||
a!==c?K=0:(K++,g=Gc[Math.min(Math.floor(K/3),4)]);tb=a;P(g)}}else ca===t?Tb(!1):Pa&&O(t),K=0,tb=-1,Ga=0,hb++,hb===4||hb===12?(Tb(!1),La=t=null,wc(),oc(),P(.1)):P(hb<4?1.2:hb<12?2:3)}else Tb(!0),Sa=!1}catch(aa){P(.5)}finally{}}var qb={hp_enabled:!0,hp_mode:1,hp_low_threshold:25,hp_high_threshold:65,hp_bg_visible:!0,hp_team_colors:!1,hp_info_health_margin_top:23,hp_healthbar_height:130,hp_color_low:"#E16161",hp_color_mid:"#FF7B00",hp_color_high:"#00FF00",hp_counter_visible:!0,hp_counter_size:145,hp_counter_position:"27,20",
hp_text_color_mode:0,hp_text_color_low:"#E16161",hp_text_color_mid:"#FF7B00",hp_text_color_high:"#FFFFFF",hp_pulse_bpm:75,hp_pulse_intensity:1,hp_pulse_enabled:!0,hp_pulse_text_enabled:!1,hp_pulse_text_scale:120,hp_pulse_text_position:"20,196",hp_pulse_hide_bar:!1,hp_pulse_color_enabled:!1,hp_pulse_color:"#FF2222",hp_pulse_color_mode:0,hp_skip_buildings:!1,hp_pulse_threshold:25,hp_counter_format:0,hp_friend_enabled:!1,hp_friend_pulse_enabled:!1,hp_friend_pulse_bpm:75,hp_friend_pulse_intensity:1,hp_friend_pulse_threshold:25,
hp_friend_color_low:"#E16161",hp_friend_color_mid:"#FF7B00",hp_friend_color_high:"#00FF00",hp_friend_pulse_color_enabled:!1,hp_friend_pulse_color:"#FF2222",hp_level_number_visible:!0,hp_pip_visible:!0,hp_ult_color_enabled:!0,hp_ult_color_custom:"#E16161",hp_kill_zone_enabled:!1,hp_kill_zone_threshold:25,hp_kill_zone_color:"#FF2222",hp_kill_zone_width:3},d={},n={},I=Date.now?Date.now.bind(Date):function(){return+new Date},Db=["pulse_subtle","","pulse_intense"],Ce=[.35,.8,1.5,2.5],Gc=[.35,.9,1.8,3,
3],Ra=!1,Sa=!1,Ta=!1,nb=!1,Gb=!1,ob=!1,kc=0,Pc=0,lc=0,Ba=0,da=0,Ca=0,G=0,Cb=null,Aa=-1,lb=null,t=null,La=null,ca=null,A=null,Ub=null,bb=-1,ab=-1,tb=-1,K=0,Sb=!1,Bd=0,Ga=0,hb=0,Cd=0,Wc=0,Pa=0,Fb=-1,ec=null,Dd=0,sb=null,Lb="",Nb=0,Mb=0;(function(){for(var a in qb)Object.prototype.hasOwnProperty.call(qb,a)&&(d[a]=qb[a])})();nc();var Xa=!1,rb=0,V=!0,na=0,ma=!0,Ua=0,Hb=0,Jb="",Nc=0,ta=0,fc=null,Ed="",la=0,pb=-1,Qa=-1,rd=null,ic=-1,Mc=0;try{$.RegisterForUnhandledEvent("ClientUI_FireOutput",function(a){if(typeof a!==
"string"||a.indexOf("HP_COLORS_PRESET_SNAPSHOT")!==-1)try{if(Xa&&typeof a==="string"&&a===Ed)hc("event_duplicate_payload");else if(!Xa||!xe()){try{var b=typeof a==="string"?JSON.parse(a):a}catch(h){b=null}if(b&&b.magic_word==="HP_COLORS_PRESET_SNAPSHOT"&&(!b.mod_title||b.mod_title==="HP Colors")&&b.values&&typeof b.values==="object"){var c=typeof b.values_raw==="string"?b.values_raw:"";if(c)var e=c;else try{e=JSON.stringify(b.values)}catch(h){e=""}e&&e===Jb&&Xa?(typeof a==="string"&&(Ed=a),hc("event_payload_same_raw")):
Ld(b.values)&&e&&(Jb=e,typeof a==="string"&&(Ed=a))}}}catch(h){}})}catch(a){}var ja=$.GetContextPanel(),v=null,l=null,M=null,E=null,z=null,Y=null,X=null,m=null,R=null,p=null,B=null,fa=null,xa=null,Ka=null,Ya=0,Fa=0,Ea=0,wd=0,tc=0,rc=0,qa=0,fd=0,Bc=0,ua=null,va=null,cb=null,db=null,eb=null,Ac=null,ad=null,bd=null,cd=null,fb=null,U=0,y=0,Vd=0,Uc=0,Vc=null,Be=500,Ob=24,ba=null,T=null,ia=null,Eb=null,Oa=null,mb=null,dd=null,$b=-1,Zb=-1,gb=null,ee=null,ge=0,Ja=!1,id=null,jd=null,kd=null,ld=null,md=null,
nd=null,od=null,pd="",qd=0,ka=0,sc=-1,sd="",ed="",Xc=null,Zc=0,Yc=0,Ae=160,wa=null,xc=null,yc=null,$c=null,Xb=null,ea=null,Yb=null,zc=null,Dc=0,Za=-1,Pb=-1,sa=-1,Cc=-1,vb=0,W=0,S=0,ub=0,Z=0,Da=0,Ee=[11,19,27,35],ud=["level_tier2","level_tier3","level_tier4","level_tier5"],td="level_number_visible",Ab=null,Bb=null,C=null,vd=-1,Va=null,mc=0;try{Qc()}catch(a){}try{Md()}catch(a){}try{Nd()}catch(a){}})();
