"use strict";

// GENERATED by pipeline/extract_poi.py - do not edit by hand.
// Source: dl_midtown default_ents (item_crate_spawn objective positions).
var QolLiteMapUrnData = {
    dl_midtown: {
        spawns: {
            left:  { mid: { u: 0.19382, v: 0.5 }, top: { u: 0.2872, v: 0.34524 }, bottom: { u: 0.32887, v: 0.64137 } },
            right: { mid: { u: 0.80618, v: 0.5 }, top: { u: 0.67113, v: 0.35863 }, bottom: { u: 0.7128, v: 0.65476 } }
        }
    }
};
