(()=>{function Ja(a){return a.BHasClass("team1")||a.BHasClass("friend")||a.BHasClass("ally")}function Ka(a){return a.BHasClass("team2")||a.BHasClass("enemy")}function ua(a,c){A[a]=(A[a]||0)+1;c-La<6E4||(La=c,$.Msg("[BT-PERF]","sweeps=",A.oa,"linger=",A.ha,"prox=",A.ia),A.oa=0,A.ha=0,A.ia=0)}function M(a){a!==pb&&(H(b.ja,a),H(b.g,a),pb=a)}function Ma(a){if(a!==na){var c=b.la,e=na;na=c?.IsValid?.()&&e!==a?c.text=a:e}}function Na(a,c){var e=b.ka;e?.IsValid?.()&&(a=!!a,c=!!c,Oa!==a&&(e.SetHasClass("active",
a),Oa=a),Pa!==c&&(e.SetHasClass("buff-active",c),Pa=c))}function D(a){a=Math.max(0,a|0);var c=a/60|0;a%=60;return(c<10?"0"+c:""+c)+":"+(a<10?"0"+a:""+a)}function qb(a){a=Math.max(0,a|0);var c=a%60;return(a/60|0)+":"+(c<10?"0"+c:""+c)}function Qa(a){for(;a.GetParent?.();)a=a.GetParent();return a}function rb(a,c){Ra=Date.now()+c*1E3;va=$.Schedule(c,()=>wa(a))}function sb(a){if(a===U){var c=Date.now();Ra>0&&c>Ra+15E3?($.Msg("[BT-WATCHDOG] Main loop missed scheduled heartbeat, restarting"),xa(1),Sa()):
$.Schedule(5,()=>sb(a))}}function xa(a){U++;va&&($.CancelScheduled(va),va=null);if(a){V=ia=ja=N=z=t=0;oa=Ta=-1;O=pa=E=!1;ya=!0;B.length=0;P=C=!1;W=Object.create(null);X=Y=Z=!1;x&&($.CancelScheduled(x),x=null);Q=null;qa=0;za=!1;Aa=aa=0;u.G.length=0;u.N.length=0;u.ca=0;La=F.length=0;A.oa=0;A.ha=0;A.ia=0;Ua();if(R){try{$.CancelScheduled(R)}catch{}R=null}if(S){try{$.CancelScheduled(S)}catch{}S=null}if(I){try{$.CancelScheduled(I)}catch{}I=null}if(J){try{$.CancelScheduled(J)}catch{}J=null}ba=ca=0;try{b.K?.RemoveClass?.("active"),
b.K?.RemoveClass?.("ally-claim"),b.K?.RemoveClass?.("enemy-claim")}catch{}try{b.L?.RemoveClass?.("active"),b.L?.RemoveClass?.("ally-claim"),b.L?.RemoveClass?.("enemy-claim")}catch{}for(let c in G)Va(G[c],!0);G=Object.create(null);da=0;M(D(v[0].d));H(b.J,"1");Ba(!0);Wa(b.i,"neutral-card-mode",!1);ka();ea("s2r://panorama/images/hud/modifiers/icon_rejuvenator.svg");tb(!0);Xa=Ya=K=la="";Za="s2r://panorama/images/hud/modifiers/icon_rejuvenator.svg";Pa=Oa=null;b.g?.IsValid?.()&&(b.g.style.clip="rect(0%,0%,100%,0%)",
b.g.style.color="#ffffff",b.g.text="");b.C?.IsValid?.()&&(b.C.style.clip="rect(0%,100%,100%,100%)",b.C.style.color="#ffffff",b.C.text="")}}function Ca(a){a=a||Date.now();if(a-ub<200)return vb;var c=0;if($a?.IsValid?.())try{c=wb($a.text)}catch{}if(!c)try{let e=b.ba;!e?.IsValid?.()&&b.root?.IsValid?.()&&(e=b.root.FindChildTraverse("TopBar"),b.ba=e);if(e){let d=e.FindChildrenWithClassTraverse("GameTime");d?.[0]?.text&&($a=d[0],c=wb(d[0].text))}}catch{}c>0&&(vb=c,ub=a);return c}function wb(a){if(!a)return 0;
a=String(a);var c=a.indexOf(":");if(c<0)return 0;var e=0,d=0;for(let f=0;f<c;f++){var k=a.charCodeAt(f);k>=48&&k<=57&&(e=e*10+(k-48))}for(let f=c+1,h=0;f<a.length&&h<2;f++,h++)if(k=a.charCodeAt(f),k>=48&&k<=57)d=d*10+(k-48);else break;return e*60+(d>59?d%60:d)}function xb(){if(!b.I?.BHasClass)return!1;try{return b.I.BHasClass("connectedToHideout")||b.I.BHasClass("connectedtohideout")||b.I.BHasClass("connectedToHideOut")}catch{}return!1}function ab(){if(b.S?.IsValid?.())return b.S;try{b.S=b.root.FindChildTraverse("hud_minimap")}catch(a){}return b.S}
function Da(a){a=Number(a);return!isFinite(a)||Math.abs(a)>1E6?null:a}function Ea(a){return!isFinite(a)||a<0?0:a>100?100:a}function yb(a,c,e){a=Number(a);return!isFinite(a)||a<=0||a>(e||512)?c:a}function Wa(a,c,e){if(a?.IsValid?.()){e=!!e;var d=!1;try{d=!!a.BHasClass?.(c)}catch{d=!1}d!==e&&a.SetHasClass(c,e)}}function H(a,c){a?.IsValid?.()&&(a.text=c)}function zb(a){a=a||Date.now();return P||C||ca>0||ba>0||L>0&&a-L<1500?250:da>0?500:750}function bb(a,c){if(!a?.IsValid?.())return"player_fallback_"+
c;try{let e=a.id;if(e&&String(e).length>0)return e;if(a.pa)return a.pa;Fa++;c="player_panel_"+Fa;return a.pa=c}catch{}Fa++;return"player_panel_"+Fa}function cb(a,c,e,d){var k=W[a];k?c&&(k.o=c):(k={x:0,y:0,R:0,Ba:!0,o:c||0,wa:0,Ha:0},W[a]=k);k.wa=e||Date.now();d!==void 0&&d!==null&&(k.Ha=d);return k}function Ab(a){if(!a?.length)return!1;var c=a.length<3?a.length:3;for(let e=0;e<c;e++){let d=a[e];try{if(d?.IsValid?.()&&d.BHasClass?.("map_button"))return!0}catch{}}return!1}function fa(a,c){var e=ab();
if(!e)return null;a=a||Date.now();var d=zb(a);if(!c&&aa>0&&a-aa<d)return u;a:{d=a||Date.now();if(!(!c&&d-qa<800&&Ab(Q))){c=null;try{c=e.FindChildrenWithClassTraverse("map_button")}catch{c=Ab(Q)?Q:null;break a}Q=c||[];qa=d}c=Q}if(!c)return u;if(!c?.length)return u.G.length=0,u.N.length=0,aa=u.ca=a,ua("snapshotSweeps",a),u;var k=d=0,f=e?.IsValid?.()?e:null;e=yb(f?.actuallayoutwidth||f?.contentwidth,1512,8192);f=yb(f?.actuallayoutheight||f?.contentheight,862,8192);var h=++db;try{for(let m=0,l=c.length;m<
l;m++){let g=c[m];if(g?.IsValid?.()&&g.BHasClass?.("map_button"))if(g.BHasClass("player")){let p=Da(g.actualxoffset),q=Da(g.actualyoffset);if(p===null||q===null)continue;let y=Ea(p/e*100),eb=Ea(q/f*100),r=u.G[d];r||(r={id:"",h:null,isActive:!1,ga:!1,o:0,O:0,P:0,actualX:0,actualY:0},u.G[d]=r);let ha=bb(g,m),Bb=cb(ha,0,a,h);var n=Bb?.o||0;n||(n=Ja(g)?1:Ka(g)?2:0,Bb.o=n);r.id=ha;r.h=g;r.isActive=g.BHasClass("active");r.ga=g.BHasClass("playerdead");r.o=n;r.O=y;r.P=eb;r.actualX=p;r.actualY=q;d++}else if(g.BHasClass("powerup_spawn")){let p=
Da(g.actualxoffset),q=Da(g.actualyoffset);if(p===null||q===null)continue;let y=Ea(p/e*100),eb=Ea(q/f*100),r=u.N[k];r||(r={id:"",h:null,isActive:!1,type:"unknown",O:0,P:0,actualX:0,actualY:0},u.N[k]=r);n="unknown";for(let ha=0;ha<fb.length;ha++)if(g.BHasClass(fb[ha])){n=fb[ha];break}r.id=g.id||"powerup_"+m;r.h=g;r.isActive=g.BHasClass("active");r.type=n;r.O=y;r.P=eb;r.actualX=p;r.actualY=q;k++}}}catch{}u.G.length=d;u.N.length=k;aa=u.ca=a;ua("snapshotSweeps",a);return u}function Cb(a,c,e,d,k){if(a?.length&&
c&&!(e<=0)){d=d||Date.now();ua("proximityPasses",d);for(var f=0;f<e;f++){var h=c[f];h&&(h.V=Infinity,h.W=Infinity)}for(let p=0,q=a.length;p<q;p++){var n=a[p];if(!n)continue;var m=n.id||bb(n.h,p),l=cb(m,n.o||0,d,db);f=l.o||n.o||0;!f&&n.h?.IsValid?.()&&(f=Ja(n.h)?1:Ka(n.h)?2:0);l.o=f;h=n.O;let y=n.P;var g=Math.abs(l.x-h)>.5||Math.abs(l.y-y)>.5;if(n.ga){if(n=l.R||(g?0:d),l.x=h,l.y=y,l.R=n||d,f===2&&gb(m),!g&&d-l.R>=2E3)continue}else l.x=h,l.y=y,l.R=0;if(f===1||f===2)for(m=0;m<e;m++){l=c[m];if(!l)continue;
g=h-l.x;n=y-l.y;g=g*g+n*n;f===1?g<l.V&&(l.V=g):g<l.W&&(l.W=g)}}for(a=0;a<e;a++)if(d=c[a])k?(d.l=Math.min(d.l,d.V),d.m=Math.min(d.m,d.W)):(d.l=d.V,d.m=d.W)}}function Db(a){if(!a)return!1;try{if(a.BHasClass("RejuvCount_1")||a.BHasClass("RejuvCount_2")||a.BHasClass("RejuvCount_3")||a.BHasClass("RejuvCount_4"))return!0;let c=a.Children();if(c)for(a=0;a<c.length;a++){let e=c[a];if(e.BHasClass("RejuvCount_1")||e.BHasClass("RejuvCount_2")||e.BHasClass("RejuvCount_3")||e.BHasClass("RejuvCount_4"))return!0}}catch{}return!1}
function Eb(){M("Spawn");H(b.J,v[t].n);ka();b.j?.IsValid?.()&&b.j.AddClass("white");E=!0;pa=!1;ra=.1}function ea(a){if(b.j?.IsValid?.()&&a!==Za)try{typeof b.j.SetImage==="function"?b.j.SetImage(a):b.j.src=a,Za=a}catch{}}function tb(){V=ia=0;na="";Na(Z||Y||X,!1)}function ma(a){ka();a>0&&b.j?.IsValid?.()&&(b.j.AddClass("reverse"),b.j.AddClass("rotating"),sa=$.Schedule(.8,()=>{b.j?.IsValid?.()&&b.j.RemoveClass("rotating");sa=null}))}function ka(){if(sa){try{$.CancelScheduled(sa)}catch{}sa=null}b.j?.IsValid?.()&&
(b.j.RemoveClass("rotating"),b.j.RemoveClass("reverse"),b.j.RemoveClass("white"))}function hb(){b.i?.IsValid?.()&&(x&&($.CancelScheduled(x),x=null),b.i.RemoveClass("neutral-exiting"),b.i.AddClass("neutral-mode"),b.i.AddClass("neutral-entering"),x=$.Schedule(.22,()=>{b.i?.IsValid?.()&&b.i.RemoveClass("neutral-entering");x=null}))}function Ba(a,c){b.i?.IsValid?.()&&(x&&($.CancelScheduled(x),x=null),b.i.RemoveClass("neutral-entering"),a?(b.i.RemoveClass("neutral-exiting"),b.i.RemoveClass("neutral-mode")):
(b.i.AddClass("neutral-exiting"),x=$.Schedule(.22,()=>{b.i?.IsValid?.()&&(b.i.RemoveClass("neutral-mode"),b.i.RemoveClass("neutral-exiting"));if(c)try{c()}catch{}x=null})))}function Fb(a){Wa(b.i,"neutral-card-mode",!1);b.U?.IsValid?.()&&b.U.SetImage("s2r://panorama/images/minimap/neutral_small_psd.vtex");Ba(!1,a);b.g?.IsValid?.()&&K!=="#ffffff"&&(K=b.g.style.color="#ffffff")}function ib(a,c,e,d,k,f,h,n,m){if(!(m>=a&&m<=c))return e==="bot"&&Z?(Z=!1,Ba(!1,()=>{ea("s2r://panorama/images/hud/modifiers/icon_rejuvenator.svg");
ma(t)}),b.g?.IsValid?.()&&K!=="#ffffff"&&(K=b.g.style.color="#ffffff")):e==="medium"&&Y?(Y=!1,b.T?.IsValid?.()&&b.T.SetImage("s2r://panorama/images/minimap/neutral_small_psd.vtex"),Ba(!1,()=>{ea("s2r://panorama/images/hud/modifiers/icon_rejuvenator.svg");ma(t)}),b.g?.IsValid?.()&&K!=="#ffffff"&&(K=b.g.style.color="#ffffff")):e==="card"&&X&&(X=!1,Fb(()=>{ea("s2r://panorama/images/hud/modifiers/icon_rejuvenator.svg");ma(t)})),!1;e!=="bot"||Z||(Z=!0,hb(),ea(k||"s2r://panorama/images/npcs/neutral_bot_psd.vtex"),
ka());e!=="medium"||Y||(Y=!0,b.T?.IsValid?.()&&b.T.SetImage(d),hb(),ea(k||"s2r://panorama/images/npcs/neutral_bot_psd.vtex"),ka());e!=="card"||X||(X=!0,Wa(b.i,h,!0),b.U?.IsValid?.()&&b.U.SetImage(d),ea(k||"s2r://panorama/images/minimap/neutral_vault_psd.vtex"),hb(),ka());z=e=Math.max(0,c-m);M(D(e));a="rect(0%,"+Math.floor(e/(c-a)*100)+"%,100%,0%)";a!==la&&b.g?.IsValid?.()&&(la=b.g.style.clip=a);b.g?.IsValid?.()&&K!==f&&(K=b.g.style.color=f);ra=.1;return!0}function Ga(a){var c=(a=a==="LEFT")?b.Z:b.aa,
e=a?Ha:Ia;if(c&&e){try{c.RemoveClass(e)}catch{}a?Ha=null:Ia=null}}function Ua(){Ga("LEFT");Ga("RIGHT")}function bc(a,c){var e=a==="LEFT",d=e?b.Z:b.aa;c=cc[c];if(d&&c&&(e?Ha:Ia)!==c){Ga(a);try{d.AddClass(c)}catch{}e?Ha=c:Ia=c}}function dc(a){var c=a==="LEFT"?b.Z:b.aa;if(c)try{c.AddClass("glow-enemy"),$.Schedule(3,()=>{try{c.RemoveClass("glow-enemy")}catch{}})}catch{}}function ec(a,c,e){try{let m=a==="LEFT",l=m?b.K:b.L,g=m?b.ra:b.sa,p=m?b.ea:b.fa,q=m?I:J;if(l?.IsValid?.()&&g?.IsValid?.()){var d=m?R:
S;if(d)try{$.CancelScheduled(d)}catch{}if(q)try{$.CancelScheduled(q)}catch{}l.RemoveClass("active");l.RemoveClass("ally-claim");l.RemoveClass("enemy-claim");var k=fc[e];if(k)try{g.style.backgroundImage='url("'+k+'")'}catch{}l.SetHasClass("ally-claim",!c);l.SetHasClass("enemy-claim",c);if(p?.IsValid?.())try{p.text=qb(160)}catch{}var f=Date.now();m?ca=f:ba=f;var h=$.Schedule(.016,()=>{try{l?.IsValid?.()&&l.AddClass("active")}catch{}m?I=null:J=null});m?I=h:J=h;var n=$.Schedule(160,()=>{jb(a)});m?R=n:
S=n}}catch(m){}}function jb(a){try{let c=a==="LEFT"?b.K:b.L;c?.IsValid?.()&&(c.RemoveClass("active"),c.RemoveClass("ally-claim"),c.RemoveClass("enemy-claim"))}catch{}if(a==="LEFT"){if(R)try{$.CancelScheduled(R)}catch{}if(I)try{$.CancelScheduled(I)}catch{}I=R=null;ca=0}else{if(S)try{$.CancelScheduled(S)}catch{}if(J)try{$.CancelScheduled(J)}catch{}J=S=null;ba=0}}function Gb(a,c,e,d,k,f){a=Math.max(0,160-(Date.now()-a)/1E3);var h=a/160;try{if(c?.IsValid?.()){let n=qb(a);n!==d&&(d=c.text=n)}}catch{}try{e?.IsValid?.()&&
(c=.5+h*.5,h=.3+h*.7,c!==k&&(k=e.style.preTransformScale2d=c),h!==f&&(f=e.style.opacity=h))}catch{}return[a,d,k,f]}function kb(a,c){a=a||Date.now();for(let e in W){let d=W[e];d?G[e]||(c||a-(d.wa||0)>6E3)&&delete W[e]:delete W[e]}}function Hb(a,c,e){var d=ab();if(d)try{let n=a||Date.now(),m=(c||fa(n,!!e))?.N||[];if(m.length){a=B;c=0;for(let l=0,g=m.length;l<g;l++){let p=m[l];if(!p?.isActive)continue;let q=a[c];q||(q={type:"",x:0,y:0,h:null,M:"LEFT",Y:!1,l:Infinity,m:Infinity},a[c]=q);q.type=p.type;
q.x=p.O;q.y=p.P;q.h=p.h;q.M="LEFT";q.Y=!1;q.l=Infinity;q.m=Infinity;c++}a.length=c;if(a.length!==0){a.sort((l,g)=>l.x-g.x);Ua();var k=d.BHasClass?.("invert_map");for(let l=0,g=a.length;l<g;l++)d=l===0?"LEFT":"RIGHT",a[l].M=k?d==="LEFT"?"RIGHT":"LEFT":d,bc(a[l].M,a[l].type);var f=a[0],h=a[1]||f;T=k?{left:{x:h.x,y:h.y},right:{x:f.x,y:f.y}}:{left:{x:f.x,y:f.y},right:{x:h.x,y:h.y}};if(P){let l=k?w.right:w.left,g=k?w.left:w.right;a[0].l=l.D;a[0].m=l.F;a[1]&&(a[1].l=g.D,a[1].m=g.F);P=!1}C=!0;L=0}}}catch{}}
function hc(a,c){if(!G[a]&&c&&c.IsValid?.())try{let g=b.xa;if(g?.IsValid?.()){var e=b.S,d=g.contentwidth||404,k=g.contentheight||404,f=e?.IsValid?.()&&e.BHasClass?.("invert_map"),h=(c.actualxoffset||0)+4,n=c.actualyoffset||0;f&&(h=d-h-24,n=k-n-24);c.style.opacity="0.5";e="LingerQ_"+a;var m=g.FindChildTraverse(e);m||(m=$.CreatePanel("Label",g,e),m.AddClass("linger-question-child"),m.text="?");m.style.position=h+"px "+n+"px 0px";m.AddClass("active");var l=$.Schedule(5,()=>{var p=G[a];p&&(Va(p,!1),delete G[a],
da=Math.max(0,da-1))});G[a]={va:l,qa:c,ya:m};da++}}catch(g){}}function Va(a,c){if(a){try{c&&a.va&&$.CancelScheduled(a.va)}catch{}try{a.qa?.IsValid?.()&&(a.qa.style.opacity=null)}catch{}try{a.ya?.IsValid?.()&&a.ya.DeleteAsync(0)}catch{}}}function gb(a){var c=G[a];c&&(Va(c,!0),delete G[a],da=Math.max(0,da-1))}function Ib(){if(O){Jb();var a=Ca();O?(a=t<0||t>=v.length?0:Math.max(0,v[t].d-(a-N)),a="Rejuv "+(E||a<=0?"now":Kb(a))):a="";Lb(a)}}function Mb(){if(O){Jb();var a=Ca();a=O?"Bridge "+Kb(300-a%300):
"";Lb(a)}}function Lb(a){var c=Date.now();if(!(c-Nb<300)&&(Nb=c,a)){var e=String(a).replace(/["\r\n;]/g," ").trim();if(e){b.H=null;b.X=null;try{$.DispatchEvent("CitadelConCommand","say_chat_team")}catch{}$.Schedule(ta[0],()=>lb(e,0,0))}}}function Jb(){b.v?.IsValid?.()||(b.v=b.root?.FindChildTraverse("Chat"));b.H?.IsValid?.()||(b.H=b.root?.FindChildTraverse("ChatInput"))}function lb(a,c,e){var d=ic(),k=jc();kc(d,k)?e<1&&c<ta.length-1?$.Schedule(ta[c+1],()=>lb(a,c+1,e+1)):lc(d,a):c>=ta.length-1||$.Schedule(ta[c+
1],()=>lb(a,c+1,0))}function kc(a,c){return a?.IsValid?.()&&c?.IsValid?.()?(a=String(c.text||"").trim())&&a!=="#citadel_chat_placeholder"?a!=="To (ALL):"&&a.indexOf("(ALL)")===-1:!1:!1}function lc(a,c){try{$.DispatchEvent("SetInputFocus",a)}catch{}try{a.text=c,$.Schedule(0,()=>{try{$.DispatchEvent("CitadelChatInputSubmitted",a)}catch{}try{a.text=""}catch{}Ob(a)})}catch{Ob(a)}}function Ob(a){var c=Pb();try{$.DispatchEvent("CitadelChatInputBlur",a)}catch{}try{$.DispatchEvent("DropInputFocus",a)}catch{}if(c?.IsValid?.()){try{$.DispatchEvent("CitadelChatInputBlur",
c)}catch{}try{$.DispatchEvent("DropInputFocus",c)}catch{}}$.Schedule(0,()=>{try{$.DispatchEvent("CitadelChatInputBlur",a)}catch{}})}function Pb(){if(b.v?.IsValid?.())return b.v;var a=b.root?.IsValid?.()?b.root:Qa($.GetContextPanel());if(!a?.IsValid?.())return null;a=a.FindChildTraverse("Chat");return a?.IsValid?.()?b.v=a:null}function ic(){if(b.H?.IsValid?.())return b.H;var a=b.root?.IsValid?.()?b.root:Qa($.GetContextPanel());if(!a?.IsValid?.())return null;var c=b.v?.IsValid?.()?b.v:a.FindChildTraverse("Chat");
if(c?.IsValid?.()){let e=c.FindChildTraverse("ChatControls")?.FindChildTraverse?.("ChatInput")||c.FindChildTraverse("ChatInput");if(e?.IsValid?.())return b.v=c,b.H=e}a=a.FindChildTraverse("ChatInput");return a?.IsValid?.()?b.H=a:null}function jc(){if(b.X?.IsValid?.())return b.X;var a=b.v?.IsValid?.()?b.v:Pb();if(!a?.IsValid?.())return null;a=a.FindChildTraverse("ChatControls")?.FindChildTraverse?.("ChatTargetLabel")||a.FindChildTraverse("ChatTargetLabel");return a?.IsValid?.()?b.X=a:null}function Kb(a){a=
Math.max(0,a|0);var c=a/60|0;a%=60;return c<=0?a+"s":c+":"+(a<10?"0"+a:a)}function wa(a){if(a===U){var c=Date.now(),e=Ca(c),d=ab();try{b.na?.IsValid?.()&&b.na.BHasClass?.("gScoreboardOpen")||b.root?.IsValid?.()&&b.root.BHasClass?.("gScoreboardOpen")||b.I?.IsValid?.()&&b.I.BHasClass?.("gScoreboardOpen")||d?.IsValid?.()&&d.BHasClass?.("gScoreboardOpen")||b.ma?.IsValid?.()&&b.ma.BHasClass?.("gScoreboardOpen")}catch{}!Number.isFinite(e)||e<0||(e<10?za||(Q=null,qa=0,aa=u.ca=0,za=!0):za=!1);if(O){if(c-
mb>=6E4&&(mb=c,xb())){xa(1);wa(U);return}if(oa>=0&&(e+5<oa||oa>30&&e<=2))xa(1),wa(U);else{oa=e;for(var k of mc)if(c-k.u>=k.B)switch(k.u=c,k.A){case "rejuv":if(e!==Ta){Ta=e;if(t<0||t>=v.length)t=0;d=ib(60,120,"bot","s2r://panorama/images/npcs/neutral_bot_psd.vtex",null,"#00ff00",null,null,e);var f=ib(300,360,"medium","s2r://panorama/images/minimap/neutral_small_psd.vtex","s2r://panorama/images/minimap/neutral_medium_psd.vtex","#00ff00",null,null,e),h=ib(420,480,"card","s2r://panorama/images/minimap/neutral_large_psd.vtex",
"s2r://panorama/images/minimap/neutral_vault_psd.vtex","#00ff00","neutral-card-mode",Fb,e);d||f||h||(E?(z=0,M("Spawn"),ra=.1):(d=Math.max(0,v[t].d-(e-N)),d<=0?Eb():(z=d,M(D(d)),f="rect(0%,"+Math.floor((E?1:z/v[t].d)*100)+"%,100%,0%)",f!==la&&b.g?.IsValid?.()&&(la=b.g.style.clip=f)),ra=E||d<=10?.1:1))}break;case "buff":ia>0&&(V=Math.max(0,220-(e-ia)),Ma(D(V)),V<=0&&tb());break;case "bridge":d=300-e%300;f=D(d);f!==Qb&&(H(b.da,f),H(b.C,f),Qb=f);f=d/300;h="rect(0%,100%,100%,"+Math.floor((1-f)*100)+"%)";
h!==Ya&&b.C?.IsValid?.()&&(Ya=b.C.style.clip=h,f=Math.floor(255*f),f="rgb(255,"+f+","+f+")",f!==Xa&&(Xa=b.C.style.color=f));d<=10&&!P&&!C&&T&&(P=!0,w.left.D=w.left.F=w.right.D=w.right.F=Infinity);nb<=10&&nb>0&&d>10&&(L=c,B.length=0,C=!1);nb=d;break;case "miniCard":b.ka?.IsValid?.()&&(d=Z||Y||X,f=ia>0,Na(d||f,f&&!d),d&&!f&&b.la?.IsValid?.()&&Ma(D(Math.max(0,v[t>=0&&t<v.length?t:0].d-(e-N)))));break;case "claim":ca<=0&&ba<=0||(ca>0&&(d=Gb(ca,b.ea,b.ta,Rb,Sb,Tb),Rb=d[1],Sb=d[2],Tb=d[3],d[0]<=0&&jb("LEFT")),
ba>0&&(d=Gb(ba,b.fa,b.ua,Ub,Vb,Wb),Ub=d[1],Vb=d[2],Wb=d[3],d[0]<=0&&jb("RIGHT")));break;case "scan":c-ob>=3E3&&(ob=c,O&&(d=Db(b.Aa)||Db(b.za),E&&d&&!pa&&(ja++,ia=h=Ca(),V=220,Na(!0,!0),Ma(D(V)),f=ja>2?3:ja,E=!1,t=f<0?0:f>3?3:f,z=v[t].d,N=h,M(D(z)),H(b.J,v[t].n),ma(t),la="",b.g?.IsValid?.()&&(b.g.style.clip="rect(0%,0%,100%,0%)",b.g.text=""),kb(Date.now(),!0)),pa=d));break;case "linger":d=c;f=null;L>0&&d-L<1500&&!C&&d-Xb>=200&&(Xb=d,Hb(d,null,!0));!C&&B.length===0&&L>0&&d-L>=3E3&&d-L<4E3&&Hb(d,null,
!0);if(d-Yb>=zb(d)&&(Yb=d,f=f||fa(d,!1),d=d||Date.now(),f=(f||fa(d,!1))?.G||[],f.length)){ua("lingerChecks",d);try{for(let m=0,l=f.length;m<l;m++){let g=f[m];if(!g)continue;let p=g.id||bb(g.h,m),q=cb(p,g.o||0,d,db),y=q?.o||g.o||0;!y&&g.h?.IsValid?.()&&(y=Ja(g.h)?1:Ka(g.h)?2:0);if(y!==2)continue;h=q?.Ba??!0;q.o=y;q.Ba=g.isActive;q.x=g.O;q.y=g.P;g.ga?(q.R=d,gb(p)):h&&!g.isActive?hc(p,g.h):!h&&g.isActive&&gb(p)}}catch{}}break;case "pretrack":d=c;f=null;if(P&&T&&d-Zb>=1E3&&(Zb=d,f=f||fa(d,!1),T&&(f=f||
fa(d,!1),f?.G?.length))){F.length=2;h=F[0]||(F[0]={x:0,y:0,l:Infinity,m:Infinity});h.x=T.left.x;h.y=T.left.y;var n=F[1]||(F[1]={x:0,y:0,l:Infinity,m:Infinity});n.x=T.right.x;n.y=T.right.y;Cb(f.G,F,2,d,!1);h.l<w.left.D&&(w.left.D=h.l);h.m<w.left.F&&(w.left.F=h.m);n.l<w.right.D&&(w.right.D=n.l);n.m<w.right.F&&(w.right.F=n.m)}break;case "monitor":f=c;d=null;if(C&&f-$b>=300)if($b=f,d=d||fa(f,!1),B.length===0)C=!1;else{h=(d||fa(f,!1))?.G||[];d=!0;n=0;for(let m=0,l=B.length;m<l;m++){let g=B[m];if(g.Y)continue;
let p=!1;try{g.h?.IsValid?.()&&(p=g.h.BHasClass("active"))}catch{}p?d=!1:F[n++]=g}n>0&&h.length>0&&Cb(h,F,n,f,!0);for(let m=0,l=B.length;m<l;m++){f=B[m];if(f.Y)continue;h=!1;try{f.h?.IsValid?.()&&(h=f.h.BHasClass("active"))}catch{}h?d=!1:(h=f.m<=64,h=!(f.l<=64)||h&&f.m<f.l,Ga(f.M),h&&dc(f.M),ec(f.M,h,f.type),f.Y=!0)}F.length=0;d&&(Ua(),C=!1,B.length=0)}break;case "prune":c-Aa>=3E3&&(Aa=c,kb(c,!1))}rb(a,ra)}}else{if(c-ac>=3E4&&(ac=c,ya=xb(),!ya)){O=!0;ja=0;ya=E=pa=!1;mb=Date.now();ob=0;B.length=0;
P=C=!1;aa=Aa=0;Q=null;qa=0;a:if(E=!1,ja===0)t=0,N=e,z=0,Eb();else{c=0;for(k=0;k<4;k++){if(e<c+v[k].d){t=k;N=c;z=c+v[k].d-e;M(D(z));H(b.J,v[k].n);ma(k);break a}c+=v[k].d}k=v[3].d;c=(e-c)%300%k;t=3;N=e-c;z=k-c;M(D(z));H(b.J,"3");ma(3)}kb(Date.now(),!0)}rb(a,30)}}}function Sa(){var a=Qa($.GetContextPanel());b.root=a;b.I=a.FindChildTraverse("Hud");b.ba=a.FindChildTraverse("TopBar");b.ja=a.FindChildTraverse("RejuvTime");b.J=a.FindChildTraverse("RejuvNum");b.j=a.FindChildTraverse("RejuvImg");b.i=a.FindChildTraverse("Rejuv");
b.da=a.FindChildTraverse("BuffTime");b.g=a.FindChildTraverse("RejuvTimeClip");b.C=a.FindChildTraverse("BuffTimeClip");b.Z=a.FindChildTraverse("MinimapGlowLeft");b.aa=a.FindChildTraverse("MinimapGlowRight");b.ma=a.FindChildTraverse("ScoreboardContainer")||a.FindChildTraverse("Scoreboard");try{globalThis.handleRejuvPingActivate=Ib,globalThis.handleBuffPingActivate=Mb,$.GetContextPanel().handleRejuvPingActivate=Ib,$.GetContextPanel().handleBuffPingActivate=Mb}catch{}b.K=a.FindChildTraverse("MinimapBuffClaimLeft");
b.L=a.FindChildTraverse("MinimapBuffClaimRight");b.ra=a.FindChildTraverse("ClaimIconLeft");b.sa=a.FindChildTraverse("ClaimIconRight");b.ta=a.FindChildTraverse("ClaimRingLeft");b.ua=a.FindChildTraverse("ClaimRingRight");b.ea=a.FindChildTraverse("ClaimTimerLeft");b.fa=a.FindChildTraverse("ClaimTimerRight");b.xa=a.FindChildTraverse("HudMinimapContainer");b.Ca=a.FindChildTraverse("minimap_container");b.na=a.FindChildTraverse("minimap_persp");b.T=a.FindChildTraverse("NeutralSpawnBadge");b.U=a.FindChildTraverse("NeutralSpawnBadge2");
b.ka=a.FindChildTraverse("RejuvMiniCard");b.la=a.FindChildTraverse("RejuvMiniTime");if(a=b.ba)if(a=a.FindChildTraverse("RejuvenatorCharges"))b.Aa=a.FindChildTraverse("RejuvenatorFriendly"),b.za=a.FindChildTraverse("RejuvenatorEnemy");if(!(b.ja&&b.J&&b.j&&b.da))return $.Schedule(.5,Sa);xa(1);U++;a=U;wa(a);sb(a)}var v=[{d:600,n:"1"},{d:410,n:"2"},{d:350,n:"3"},{d:290,n:"3"}],fb=["powerup_gun","powerup_survival","powerup_casting","powerup_movement"],ta=[.01,.03,.06,.1,.15,.25],Nb=0,va,O=!1,ya=!0,E=!1,
t=0,z=0,N=0,ja=0,ia=0,V=0,Ta=-1,oa=-1,ac=0,mb=0,ob=0,ra=1,pa=!1,Xb=0,nb=300,L=0,Yb=0,Aa=0,B=[],C=!1,$b=0,P=!1,Zb=0,w={left:{D:Infinity,F:Infinity},right:{D:Infinity,F:Infinity}},T=null,R=null,S=null,ca=0,ba=0,$a=null,vb=0,ub=0,aa=0,Q=null,qa=0,W=Object.create(null),db=0,Fa=0,Z=!1,Y=!1,X=!1,x=null,I=null,J=null,sa=null,pb="",Qb="",na="",Rb="",Ub="",la="",K="",Ya="",Xa="",Za="",Oa=null,Pa=null,Sb=-1,Tb=-1,Vb=-1,Wb=-1,F=[],u={G:[],N:[],ca:0},A={oa:0,ha:0,ia:0},La=0,G=Object.create(null),da=0,za=!1,U=
0,Ra=0,b={root:null,I:null,ba:null,v:null,ma:null,S:null,Ca:null,na:null,xa:null,Z:null,aa:null,ja:null,g:null,J:null,j:null,i:null,da:null,C:null,H:null,X:null,Aa:null,za:null,K:null,L:null,ra:null,sa:null,ta:null,ua:null,ea:null,fa:null,T:null,U:null,ka:null,la:null},fc={Ea:"s2r://panorama/images/minimap/powerup_weapon.vsvg",Ga:"s2r://panorama/images/minimap/powerup_health.vsvg",Da:"s2r://panorama/images/minimap/powerup_magic.vsvg",Fa:"s2r://panorama/images/minimap/powerup_movement.vsvg"},cc={Ea:"glow-gun",
Ga:"glow-survival",Da:"glow-casting",Fa:"glow-movement"},Ha=null,Ia=null,mc=[{A:"rejuv",B:1E3,u:0},{A:"buff",B:1E3,u:0},{A:"bridge",B:1E3,u:0},{A:"miniCard",B:1E3,u:0},{A:"claim",B:100,u:0},{A:"scan",B:3E3,u:0},{A:"linger",B:300,u:0},{A:"pretrack",B:1E3,u:0},{A:"monitor",B:300,u:0},{A:"prune",B:3E3,u:0}];Sa()})();
