function G(e){var l=0;return function(){return l<e.length?{done:!1,value:e[l++]}:{done:!0}}}var H=typeof Object.defineProperties=="function"?Object.defineProperty:function(e,l,h){if(e==Array.prototype||e==Object.prototype)return e;e[l]=h.value;return e};
function aa(e){e=["object"==typeof globalThis&&globalThis,e,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var l=0;l<e.length;++l){var h=e[l];if(h&&h.Math==Math)return h}throw Error("Cannot find global object");}var ba=aa(this);function Z(e,l){if(l)a:{var h=ba;e=e.split(".");for(var g=0;g<e.length-1;g++){var r=e[g];if(!(r in h))break a;h=h[r]}e=e[e.length-1];g=h[e];l=l(g);l!=g&&l!=null&&H(h,e,{configurable:!0,writable:!0,value:l})}}
Z("Symbol",function(e){function l(t){if(this instanceof l)throw new TypeError("Symbol is not a constructor");return new h(g+(t||"")+"_"+r++,t)}function h(t,y){this.i=t;H(this,"description",{configurable:!0,writable:!0,value:y})}if(e)return e;h.prototype.toString=function(){return this.i};var g="jscomp_symbol_"+(Math.random()*1E9>>>0)+"_",r=0;return l});
Z("Symbol.iterator",function(e){if(e)return e;e=Symbol("Symbol.iterator");H(Array.prototype,e,{configurable:!0,writable:!0,value:function(){return ca(G(this))}});return e});function ca(e){e={next:e};e[Symbol.iterator]=function(){return this};return e}function da(e,l){e instanceof String&&(e+="");var h=0,g=!1,r={next:function(){if(!g&&h<e.length){var t=h++;return{value:l(t,e[t]),done:!1}}g=!0;return{done:!0,value:void 0}}};r[Symbol.iterator]=function(){return r};return r}
Z("Array.prototype.values",function(e){return e?e:function(){return da(this,function(l,h){return h})}});
(function(){function e(b){return String(b||"").toLowerCase().replace(/[^a-z0-9_]+/g,"_").replace(/^_+|_+$/g,"")}function l(){try{if(typeof GameUI!=="undefined"&&GameUI&&GameUI.CustomUIConfig)return GameUI.CustomUIConfig()}catch(b){}return null}function h(b){if(b&&typeof b==="object"){var a={},c;for(c in b)Object.prototype.hasOwnProperty.call(b,c)&&(a[c]=b[c]);try{var d=l();if(d){var f=JSON.stringify(a);f!==O&&(O=f,d.__hpColorsCfgRaw=f)}}catch(m){}}}function g(b){var a={};if(!b)return a;for(var c in b)Object.prototype.hasOwnProperty.call(b,
c)&&(a[c]=b[c]);return a}function r(b){if(!b)return null;if(z&&Object.prototype.hasOwnProperty.call(z,b))return z[b]||null;if(!n||!Array.isArray(n.elements))return null;for(var a=0;a<n.elements.length;a++){var c=n.elements[a];if(c&&c.id===b)return c}return null}function t(b,a){if(b===!0||b===!1)return b;if(b===1||b==="1")return!0;if(b===0||b==="0")return!1;if(typeof b==="string"){b=b.toLowerCase();if(b==="true")return!0;if(b==="false")return!1}return!!a}function y(b,a){if(!b)return a;var c=b.defaultValue,
d=String(b.type||"");d==="positionpicker"?(c=0,d=200,b=b.id==="hp_counter_position"||b.id==="hp_pulse_text_position"?-50:0,a&&typeof a==="object"?Array.isArray(a)?(a.length>0&&(c=Number(a[0])),a.length>1&&(d=Number(a[1]))):(Object.prototype.hasOwnProperty.call(a,"x")&&(c=Number(a.x)),Object.prototype.hasOwnProperty.call(a,"y")&&(d=Number(a.y))):typeof a==="string"?(a=a.match(/-?\d+(?:\.\d+)?/g))&&a.length>0&&(c=Number(a[0]),a.length>1&&(d=Number(a[1]))):typeof a==="number"&&(d=Number(a)),isFinite(c)||
(c=0),isFinite(d)||(d=200),c<0&&(c=0),d<b&&(d=b),c>400&&(c=400),d>400&&(d=400),b=Math.round(c)+","+Math.round(d)):d==="toggle"?b=t(a,c):d==="cycler"?(b=Array.isArray(b.options)?b.options.length:0,a=Number(a),isFinite(a)||(a=Number(c)),isFinite(a)||(a=0),a=Math.round(a),a<0&&(a=0),b>0&&a>=b&&(a=Number(c),!isFinite(a)||a<0||a>=b)&&(a=0),b=a):d==="slider"||d==="stepper"?(a=Number(a),isFinite(a)||(a=Number(c)),isFinite(a)||(a=0),c=Number(b.step),isFinite(c)&&c!==0||(c=1),d=isFinite(Number(b.min))?Number(b.min):
-Infinity,b=isFinite(Number(b.max))?Number(b.max):Infinity,a<d&&(a=d),a>b&&(a=b),b=Math.round(c)===c?Math.round(a):parseFloat(a.toFixed(2))):b=d==="colorpicker"?typeof a==="string"&&a.length>0?a:typeof c==="string"&&c.length>0?c:"#FFFFFF":a!==void 0?a:c;return b}function w(b){if(b&&I===b&&D)return g(D);for(var a={},c=b&&Array.isArray(b.elements)?b.elements:[],d=0;d<c.length;d++){var f=c[d];f&&f.id&&f.type!=="button"&&(a[f.id]=y(f,f.defaultValue))}b&&(I=b,D=g(a));return a}function J(b){var a;for(a=
$.GetContextPanel();a&&a.GetParent&&a.GetParent();)a=a.GetParent();if(a=a||null){try{a.SetAttributeString&&a.SetAttributeString("anita_v1_hp_colors",b)}catch(d){}try{var c=a.FindChildTraverse?a.FindChildTraverse("Hud"):null;c&&c.SetAttributeString&&c.SetAttributeString("anita_v1_hp_colors",b)}catch(d){}}}function ea(){var b=l();if(!b)return null;try{var a=String(b.__hpColorsCfgRaw||"");if(!a)return null;var c=JSON.parse(a);return c&&typeof c==="object"?g(c):null}catch(d){}return null}function P(b,
a){if(!n)return!1;k||(k=w(n));if(n){b=p||k||w(n);var c=w(n),d={};for(f in b)Object.prototype.hasOwnProperty.call(b,f)&&Object.prototype.hasOwnProperty.call(c,f)&&b[f]!==c[f]&&(d[fa[f]||f]=b[f]);var f=JSON.stringify({v:Math.max(1,Math.floor(Number(n.storageVersion)||1)),c:1,values:d})}else f="";if(!f)return!1;b="";try{b=ha.encode(f)}catch(m){return!1}if(!a&&b===A)return J(b),h(k),!1;a=k;c=p;K=String(f||"");A=String(b||"");L=g(a||{});k=g(a||{});p=g(c||a||{});J(A);h(k);return!1}function Q(b,a){var c=
++R;$.Schedule(a?0:.35,function(){c===R&&P(b,!!a)})}function M(b){b&&(h(b),$.DispatchEvent("ClientUI_FireOutput",JSON.stringify({magic_word:"ANITA_BULK_UPDATE",mod_title:"HP Colors",values:b,update_source:"bridge_bootstrap",skip_bridge_persist:!0,force_emit:!0})))}function S(b){B=String(b||"request");var a=++T;$.Schedule(0,function(){if(a===T){var c=B;if(n){var d=ea();d?(k=g(d),p=g(d),P(c+":shared",!0),M(d,c+":shared")):(d=K&&A&&L?{raw:K,encoded:A,values:g(L),source:"cache"}:null)?(k=g(d.values),
p=g(d.values),J(d.encoded),M(d.values,c+":"+d.source)):(d=k||p)&&M(d,c+":session")}else B=c}})}function N(b){return b==="bridge_bootstrap"||b==="core_auto_resync"||b==="ui_resync"||b==="ui_reset"||b==="ui_code_apply"||b==="baked_preset_apply"||b==="ui_refresh_after_apply"}var fa={hp_enabled:"e",hp_mode:"m",hp_low_threshold:"l",hp_high_threshold:"h",hp_bg_visible:"b",hp_team_colors:"t",hp_info_health_margin_top:"ihmt",hp_healthbar_height:"hbh",hp_color_low:"cl",hp_color_mid:"cm",hp_color_high:"ch",
hp_counter_visible:"cv",hp_counter_size:"s",hp_counter_position:"p",hp_text_color_mode:"tm",hp_level_number_visible:"lnv",hp_pip_visible:"plv",hp_ult_color_enabled:"uce",hp_ult_color_custom:"ucc",hp_text_color_low:"tl",hp_text_color_mid:"ti",hp_text_color_high:"th",hp_pulse_bpm:"bp",hp_pulse_intensity:"pi",hp_pulse_enabled:"pe",hp_pulse_text_enabled:"pte",hp_pulse_text_scale:"pts",hp_pulse_text_position:"ptp",hp_pulse_hide_bar:"phb",hp_pulse_color_enabled:"pce",hp_pulse_color:"pc",hp_pulse_color_mode:"pcm",
hp_skip_buildings:"sb",hp_pulse_threshold:"pt",hp_friend_enabled:"fe",hp_friend_pulse_enabled:"fpe",hp_friend_pulse_bpm:"fpb",hp_friend_pulse_intensity:"fpi",hp_friend_pulse_threshold:"fpt",hp_friend_color_low:"fcl",hp_friend_color_mid:"fcm",hp_friend_color_high:"fch",hp_friend_pulse_color_enabled:"fpce",hp_friend_pulse_color:"fpc",hp_kill_zone_enabled:"kze",hp_kill_zone_threshold:"kzt",hp_kill_zone_color:"kzc",hp_kill_zone_width:"kzw",hp_counter_format:"cf"},n=null,k=null,p=null,A="",K="",L=null,
R=0,T=0,B="",O="",I=null,D=null,z=null,ha=function(){return{encode:function(b){for(var a=[],c=0;c<b.length;c++){var d=b.charCodeAt(c);d<128?a.push(d):(d<2048?a.push(192|d>>6):(a.push(224|d>>12),a.push(128|d>>6&63)),a.push(128|d&63))}b="";for(c=0;c<a.length;c+=3){d=a[c];var f=a[c+1]||0,m=a[c+2]||0;b+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_"[d>>2];b+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_"[(d&3)<<4|f>>4];b+=c+1<a.length?"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_"[(f&
15)<<2|m>>6]:"";b+=c+2<a.length?"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_"[m&63]:""}return b},decode:function(b){function a(x){if(x===void 0)return 0;if(!Object.prototype.hasOwnProperty.call(c,x))throw Error("Invalid base64url char: "+x);return c[x]}for(var c={},d=0;d<64;d++)c["ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_"[d]]=d;d=[];for(var f=0;f<b.length;f+=4){var m=a(b[f]),u=a(b[f+1]),q=b[f+2]!==void 0?a(b[f+2]):0,C=b[f+3]!==void 0?a(b[f+3]):0;d.push(m<<
2|u>>4);b[f+2]!==void 0&&d.push((u&15)<<4|q>>2);b[f+3]!==void 0&&d.push((q&3)<<6|C)}b="";for(f=0;f<d.length;f++)m=d[f],m<128?b+=String.fromCharCode(m):m<224?b+=String.fromCharCode((m&31)<<6|d[++f]&63):(u=d[++f],q=d[++f],b+=String.fromCharCode((m&15)<<12|(u&63)<<6|q&63));return b}}}();$.RegisterForUnhandledEvent("ClientUI_FireOutput",function(b){if(typeof b!=="string"||b.indexOf("ANITA_")!==-1)try{var a=typeof b==="string"?JSON.parse(b):b;if(a)if(a.magic_word==="ANITA_REGISTER"){var c=a.config;if(c&&
String(c.title||"")==="HP Colors"&&e(c.storageNamespace)==="hp_colors"){var d={title:"HP Colors",storageNamespace:"hp_colors",storageVersion:Math.max(1,Math.floor(Number(c.storageVersion)||1)),elements:[]},f=Array.isArray(c.elements)?c.elements:[];for(a=0;a<f.length;a++){var m=f[a];m&&m.id&&d.elements.push({id:m.id,type:m.type,defaultValue:m.defaultValue,options:Array.isArray(m.options)?m.options.slice(0):null,step:m.step})}z={};for(a=0;a<d.elements.length;a++){var u=d.elements[a];z[u.id]=u}n=d;D=
I=null;k||(k=w(n));p||(p=g(k));var q=!0}else q=!1;q&&B&&S(B)}else if(a.magic_word==="ANITA_REQUEST_BOOTSTRAP")a.mod_title==="HP Colors"&&e(a.storageNamespace)==="hp_colors"&&S(String(a.reason||"request"));else if(a.magic_word==="ANITA_BULK_UPDATE"){if(a.mod_title==="HP Colors"&&n&&a.values&&typeof a.values==="object"){k||(k=w(n));p||(p=g(k));var C=String(a.update_source||"ui_update"),x=N(C);d=q=!1;for(var v in a.values)if(Object.prototype.hasOwnProperty.call(a.values,v)){var U=r(v);if(U){var E=y(U,
a.values[v]);k[v]!==E&&(k[v]=E,q=!0);a.skip_bridge_persist||x||p[v]===E||(p[v]=E,d=!0)}}q&&h(k);a.skip_bridge_persist||N(C)||(q||d||a.force_persist)&&Q(C,!!a.force_persist)}}else if(a.magic_word==="ANITA_UPDATE"&&a.mod_title==="HP Colors"&&n&&a.setting_id){var V=r(a.setting_id);if(V){k||(k=w(n));p||(p=g(k));var W=String(a.update_source||"ui_update"),X=N(W),F=y(V,a.value),Y=k[a.setting_id]!==F;Y&&(k[a.setting_id]=F,h(k));q=!1;X||p[a.setting_id]===F||(p[a.setting_id]=F,q=!0);a.skip_bridge_persist||
W==="bridge_bootstrap"||X||(Y||q||a.force_persist)&&Q(String(a.update_source||"ui_update"),!!a.force_persist)}}}catch(ia){}})})();
