var fb=typeof Object.defineProperties=="function"?Object.defineProperty:function(g,m,r){if(g==Array.prototype||g==Object.prototype)return g;g[m]=r.value;return g};function Wb(g){g=["object"==typeof globalThis&&globalThis,g,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var m=0;m<g.length;++m){var r=g[m];if(r&&r.Math==Math)return r}throw Error("Cannot find global object");}var Hc=Wb(this),Ic="Int8 Uint8 Uint8Clamped Int16 Uint16 Int32 Uint32 Float32 Float64".split(" ");
Hc.BigInt64Array&&(Ic.push("BigInt64"),Ic.push("BigUint64"));function hd(g,m){if(m)for(var r=0;r<Ic.length;r++)id(Ic[r]+"Array.prototype."+g,m)}function Ed(g,m){m&&id(g,m)}function id(g,m){var r=Hc;g=g.split(".");for(var P=0;P<g.length-1;P++){var T=g[P];if(!(T in r))return;r=r[T]}g=g[g.length-1];P=r[g];m=m(P);m!=P&&m!=null&&fb(r,g,{configurable:!0,writable:!0,value:m})}
Ed("Math.trunc",function(g){return g?g:function(m){m=Number(m);if(isNaN(m)||m===Infinity||m===-Infinity||m===0)return m;var r=Math.floor(Math.abs(m));return m<0?-r:r}});function Fd(g){g=Math.trunc(g)||0;g<0&&(g+=this.length);if(!(g<0||g>=this.length))return this[g]}Ed("Array.prototype.at",function(g){return g?g:Fd});hd("at",function(g){return g?g:Fd});Ed("String.prototype.at",function(g){return g?g:Fd});function Gd(g){var m=0;return function(){return m<g.length?{done:!1,value:g[m++]}:{done:!0}}}
Ed("Symbol",function(g){function m(ia){if(this instanceof m)throw new TypeError("Symbol is not a constructor");return new r(P+(ia||"")+"_"+T++,ia)}function r(ia,Xb){this.i=ia;fb(this,"description",{configurable:!0,writable:!0,value:Xb})}if(g)return g;r.prototype.toString=function(){return this.i};var P="jscomp_symbol_"+(Math.random()*1E9>>>0)+"_",T=0;return m});
Ed("Symbol.iterator",function(g){if(g)return g;g=Symbol("Symbol.iterator");fb(Array.prototype,g,{configurable:!0,writable:!0,value:function(){return Hd(Gd(this))}});return g});function Hd(g){g={next:g};g[Symbol.iterator]=function(){return this};return g}function Id(g,m){g instanceof String&&(g+="");var r=0,P=!1,T={next:function(){if(!P&&r<g.length){var ia=r++;return{value:m(ia,g[ia]),done:!1}}P=!0;return{done:!0,value:void 0}}};T[Symbol.iterator]=function(){return T};return T}
Ed("Array.prototype.values",function(g){return g?g:function(){return Id(this,function(m,r){return r})}});
(function(){function g(){if(ja||gb!==null||!(ka<0)||Na!==null){var a=ka>=0?ub[ka]:"";ja=0;gb=null;ka=-1;hb=Ba=ib=la=Q=oa=Na=null;for(var b=[k,l,q],c=0;c<b.length;c++){var d=b[c];if(d)try{d.RemoveClass("low_hp_pulsing"),a&&d.RemoveClass(a),d.style&&(d.style.animationDuration="",d.style.brightness="")}catch(f){}}}}function m(a,b){if(!a)return ja&&g(),!1;if(!ja){ja=1;la=Q=oa=null;try{k&&k.AddClass("low_hp_pulsing")}catch(h){}try{q&&q.AddClass("low_hp_pulsing")}catch(h){}}var c=t(e.hp_pulse_bpm,30,300,
75);a=(60/c).toFixed(3)+"s";gb!==a&&(gb=a,k&&k.IsValid&&k.IsValid()&&(k.style.animationDuration=a),q&&q.IsValid&&q.IsValid()&&(q.style.animationDuration=a));a=t(e.hp_pulse_intensity,0,2,1)|0;if(ka!==a){var d=ka>=0?ub[ka]:"",f=ub[a];ka=a;if(d){try{k&&k.IsValid&&k.IsValid()&&k.RemoveClass(d)}catch(h){}try{q&&q.IsValid&&q.IsValid()&&q.RemoveClass(d)}catch(h){}}if(f){try{k&&k.IsValid&&k.IsValid()&&k.AddClass(f)}catch(h){}try{q&&q.IsValid&&q.IsValid()&&q.AddClass(f)}catch(h){}}}if(!l)return!1;try{if(!e.hp_pulse_text_enabled)return l.style&&
(l.style.animationDuration=""),l.style&&(l.style.brightness=""),Na=null,!1}catch(h){}if(!l.style)return!1;c=Math.max(1,6E4/c);b=b%c/c;c=a===2?.55:a===0?.85:.65;b=(c+((a===2?2:a===0?1.15:1.5)-c)*(b<.5?b*2:(1-b)*2)).toFixed(2);if(Na!==b)try{Na=l.style.brightness=b}catch(h){Na=null}return!0}function r(a,b){var c=vb>=0?ub[vb]:"";if(!b){if(wb=0,vb=-1,pa=null,a=a||D)try{a.RemoveClass("low_hp_pulsing"),c&&a.RemoveClass(c),a.style&&(a.style.animationDuration="",a.style.brightness="")}catch(d){}}else if(!wb){wb=
1;vb=-1;pa=null;try{a&&a.AddClass("low_hp_pulsing")}catch(d){}vb=c=t(e.hp_friend_pulse_intensity,0,2,1)|0;if(c=ub[c])try{a.AddClass(c)}catch(d){}c=t(e.hp_friend_pulse_bpm,30,300,75);try{a&&(a.style.animationDuration=(60/c).toFixed(3)+"s")}catch(d){}}}function P(a,b){if(a===!0||a===!1)return a;if(a===1||a==="1")return!0;if(a===0||a==="0")return!1;if(typeof a==="string"){a=a.toLowerCase();if(a==="true")return!0;if(a==="false")return!1}return!!b}function T(a,b){if(!Object.prototype.hasOwnProperty.call(U,
a))return b;var c=U[a];a==="hp_counter_position"||a==="hp_pulse_text_position"?(c=0,a=200,b&&typeof b==="object"?(Array.isArray(b)?(b.length>0&&(c=t(b[0],0,400,0)),b.length>1&&(a=t(b[1],-50,400,200))):(Object.prototype.hasOwnProperty.call(b,"x")&&(c=t(b.x,0,400,0)),Object.prototype.hasOwnProperty.call(b,"y")&&(a=t(b.y,-50,400,200))),b=Math.round(c)+","+Math.round(a)):(typeof b==="string"?(b=b.match(/-?\d+(?:\.\d+)?/g))&&b.length>0&&(c=t(b[0],0,400,0),b.length>1&&(a=t(b[1],-50,400,200))):typeof b===
"number"&&(a=t(b,-50,400,200)),b=Math.round(c)+","+Math.round(a))):typeof c==="boolean"?b=P(b,c):typeof c==="number"?(b=Number(b),b=isFinite(b)?Math.round(b):c):b=typeof c==="string"?typeof b==="string"&&b.length>0?b:c:b;return b}function ia(a){return a==="hp_low_threshold"||a==="hp_high_threshold"||a==="hp_mode"||a==="hp_friend_color_low"||a==="hp_friend_color_mid"||a==="hp_friend_color_high"||a==="hp_friend_pulse_enabled"||a==="hp_friend_pulse_threshold"||a==="hp_friend_pulse_bpm"||a==="hp_friend_pulse_intensity"||
a==="hp_friend_pulse_color_enabled"||a==="hp_friend_pulse_color"}function Xb(a){return a==="hp_pulse_color_enabled"||a==="hp_pulse_color"||a==="hp_pulse_color_mode"}function Yb(a){return a===0?!!e.hp_enabled:a===1?!!e.hp_friend_enabled:!!e.hp_level_number_visible}function V(a,b){Yb(a)&&!Zb[a]&&(Zb[a]=!0,x(a,b===void 0?.01:b)||(Zb[a]=!1))}function x(a,b){if(!Yb(a))return!1;b=Number(b);if(!isFinite(b)||b<0)b=.05;var c=E()+b*1E3;if($b[a]&&$b[a]<=c)return!1;$b[a]=c;var d=++jd[a];$.Schedule(b,function(){if(d===
jd[a]&&($b[a]=0,Zb[a]=!1,Yb(a)))if(a===0)a:{N[0]=!0;try{if(e.hp_enabled){var f=E();kd(f);if(Oa.refreshEnemy(f)){var h=Oa.target,C=h.teamId+":"+h.flags;C!==ac&&(ac=C,n.invalidateEnemyVisualCaches(),Y=!0,qa=f,ma=!0,Ca=f,Da=null);var u=h.isEnemy;if(e.hp_skip_buildings&&h.isBuilding){g();ra++;sa=0;if(h.isFriendly||h.isFriendlyBuilding)n.setBarColor("#ffffff"),n.clearUltIconColor(),n.setTextColor("#ffffff"),n.setBarVisible(!0),e.hp_friend_enabled&&V(1);else{var Z=Oa.getIgnoredTargetColor();n.setBarColor(Z);
n.setUltColor(Z);n.setTextColor("#ffffff");n.setBarVisible(!!e.hp_bg_visible)}Ea(!1,0);x(0,ra<4?.3:ra<12?.6:1.5)}else if(!Jd(f,u)){u&&!Fa&&(!jb||f<=Ga)&&f-bc>=1E3&&(bc=f,kb());u&&f-cc>=5E3&&(cc=f,n.hasEnemyStyleDrift()&&(n.invalidateEnemyVisualCaches(),Y=!0,qa=f));var H=0;if(Y){if(f<qa){x(0,.05);break a}Jc();n.setBarVisible(!u||!!e.hp_bg_visible);e.hp_counter_visible?Kc(ta):xb(!1);var Pa=-15+t(e.hp_info_health_margin_top,0,100,23)*.65;Math.abs(Pa)<.5&&(Pa=0);var ua=Math.round(Pa*10)/10;Math.abs(ua-
Math.round(ua))<.01&&(ua=Math.round(ua));var O=ua+"%";aa&&aa.IsValid()||!w||!w.IsValid()||(aa=w.FindChildTraverse("InfoHealthContainer"));if(aa&&aa.style&&dc!==O)try{dc=aa.style.marginTop=O}catch(ec){dc=null}na&&na.IsValid()||!w||!w.IsValid()||(na=w.FindChildTraverse("UnitHealthbarContainer"));var A=p.healthbarHeight||Math.round(t(e.hp_healthbar_height,0,230,130));O=A+"px";na&&na.style&&Lc!==O&&(Lc=na.style.height=O);if(B&&B.style){var yb=Math.min(75,Math.round(A*75/230))+"px";Mc!=="52%"&&(Mc=B.style.height=
"52%");Nc!==yb&&(Nc=B.style.fontSize=yb)}cc=E();R=ba=-1;Y=!1;qa=0;H=1}A=!!H;!A&&u&&f>=Oc&&(Oc=f+(fc>=8?950:fc>=3?700:350),n.hasEnemyBarStyleDrift()?(n.resetStyleDriftBackoff(),n.invalidateEnemyVisualCaches(),R=ba=-1,A=!0):fc++);if(h.isNeutral)g(),n.setBarVisible(!0),Ea(!1,0),n.setBarColor("#5BEFB5"),n.setTextColor("#ffffff"),hc=f,x(0,1.5);else if(h.flags&1)if(ra=sa=0,ca||jb||Fa||e.hp_team_colors||da(e.hp_color_high)!==da(U.hp_color_high)){var va=Oa.metrics,Pc=va.barWidth,zb=va.parentWidth;if(Pc!==
ba||zb!==Ha||ja||A||lb!==ic)if(ea=0,ba=Pc,Ha=zb,hc=f,zb<=0)W++,n.setBarColor(mb()),Ea(!1,0),x(0,W<4?.18:W<12?.35:.75);else{W=0;e.hp_kill_zone_enabled?Ea(!0,zb):Qa!=="collapse"&&Ea(!1,0);h=Pc/zb*100|0;var y=p.low,Ia=p.high,Qc=p.pulseThreshold,nb=!!(e.hp_pulse_enabled&&h<=Qc);if(Math.abs(h-R)<3&&h>y&&R>y&&!ja&&!nb&&!A)x(0,.25);else{u=R;h===ob?Ja++:(Ja=0,ob=h);R=h;var pb=!!e.hp_counter_visible,Ka=e.hp_counter_format|0;va="";if(B)try{var Ab=e.hp_pip_visible?"visible":"collapse";Ra!==Ab&&(Ra=B.style.visibility=
Ab);pb&&Ka!==1&&(va=B.text||B.GetAttributeString("text","")||"")}catch(ec){va="",Ra=null}if(pb&&S&&X)if(Ka===1)ld(h,100,nb);else{var jc=S.actuallayoutwidth||0,Sa=X.actuallayoutwidth||0;pb=Sa>0?jc/Sa:0;Ka=va;if(Ka!==kc){kc=Ka;jc=Ab=0;var md=Ka.lastIndexOf("|");for(Sa=0;Sa<Ka.length;Sa++){var Rc=Ka.charCodeAt(Sa);Rc===124?Ab++:Rc!==34&&Rc!==39||!(md===-1||Sa>md)||jc++}lc=Ab*500+jc*100}var qb=lc;ld(pb>=.97?qb:Math.round(qb*pb),qb,nb)}else pb||xb(!1);qb=.15;if(h<=y&&wa&&f-wa<900&&(u<0||u<=y&&h>u)){var nd=
mb();g();n.setBarColor(nd);n.setUltColor(nd);n.setTextColor(mc(100,y,Ia));x(0,.05);var nc=-1}else{n.setBarVisible(nb&&e.hp_pulse_hide_bar?!1:!!e.hp_bg_visible);if(h<=y){var La=e.hp_color_low;var Bb=e.hp_text_color_mode&&e.hp_mode===1?e.hp_text_color_low:mc(h,y,Ia)}else h<=Ia?e.hp_mode===1?(La=xa(e.hp_color_low,e.hp_color_mid,(h-y)/p.denomMid),Bb=od(h,y,Ia)):(La=e.hp_color_mid,Bb=mc(h,y,Ia)):(e.hp_mode===1?(La=xa(e.hp_color_mid,mb(),(h-Ia)/p.denomHigh),Bb=od(h,y,Ia)):(La=mb(),Bb=mc(h,y,Ia)),Ja>=5&&
(qb=Kd[Math.min(Math.floor((Ja-5)/5),3)]));nb&&e.hp_pulse_color_enabled&&(La=(e.hp_pulse_color_mode|0)===1?xa(La,e.hp_pulse_color,t((Qc-h)/Math.max(1,Qc),0,1,0)):e.hp_pulse_color);n.setBarColor(La);n.setUltColor(La);n.setTextColor(Bb);nc=qb}nc<0||(lb=ic,m(nb,f)&&(nc=.1),x(0,nc))}}else ea++,x(0,f-hc>2E3?1.5:.25)}else n.setBarColor("#E16161"),n.setUltColor("#E16161"),n.setTextColor("#ffffff"),x(0,.05);else sa++,ra=0,n.setBarVisible(!0),Ea(!1,0),hc=f,x(0,sa<4?.4:sa<12?.75:1.5)}}else x(0,.15)}else pd(),
N[0]=!1}catch(ec){x(0,.5)}}else if(a===1)a:{N[1]=!0;try{if(e.hp_friend_enabled){var qd=E();kd(qd);if(!K||!K.IsValid())if(Ta(D,!1),Ua=K=D=null,K=oc(),!K){pc++;x(1,pc>75?3:.2);break a}pc=0;if(K.GetParent){var rd=K.GetParent();Ua!==rd&&(Ua=rd)}if(ma){if(qd<Ca){x(1,.05);break a}ma=!1;Ta(D,!1)}var td=sd(K);if(td&1&&!(td&4)){var Sc=K.actuallayoutwidth|0,qc=Ua&&Ua.actuallayoutwidth!==void 0?Ua.actuallayoutwidth|0:0;if(qc<=0)rb++,x(1,rb<4?.2:rb<12?.4:.8);else if(rb=0,Sc!==Cb||qc!==Db||wb){Va=0;Cb=Sc;Db=qc;
y=Sc/qc*100|0;H=p.low;O=p.high;f=!1;e.hp_friend_pulse_enabled&&(f=y<=p.friendPulseThreshold);var Ld=f&&e.hp_friend_pulse_color_enabled?e.hp_friend_pulse_color:e.hp_mode===1?y<=H?e.hp_friend_color_low:y<=O?xa(e.hp_friend_color_low,e.hp_friend_color_mid,(y-H)/Math.max(1,O-H)):xa(e.hp_friend_color_mid,e.hp_friend_color_high,(y-O)/Math.max(1,100-O)):y<=H?e.hp_friend_color_low:y<=O?e.hp_friend_color_mid:e.hp_friend_color_high;var ud=da(Ld);if(pa!==ud&&K)try{pa=K.style.washColor=ud,Eb=!0,D=K}catch(ec){pa=
null}y=f?.15:.35;r(K,f);x(1,y)}else Va++,x(1,Md[Math.min(Math.floor(Va/3),4)])}else{if(Eb||D)Ta(D,!1),D=null;rb=Va=0;x(1,1.5)}}else Ta(D,!0),D=null,N[1]=!1}catch(ec){x(1,.5)}}else e.hp_level_number_visible?(N[2]=!0,Fb=Nd()?0:Fb+1,x(2,Fb>10?5:.5)):(vd(),N[2]=!1)});return!0}function wd(){for(var a=$.GetContextPanel();a&&a.GetParent&&a.GetParent();)a=a.GetParent();return a||null}function kd(a){if(Tc&&a<Tc)return!1;Tc=a+250;var b=z.getSharedStore();if(!b)return!1;var c=z.readMatchResetInfo(b);if(!c)return!1;
var d=String(c&&c.token||"");if(!d||d===rc)return!1;var f=z.readMatchResetAck(b);if(f&&String(f.token||"")===d&&(c=Number(c&&c.at),isFinite(c)&&c>0&&(wa&&wa>c+500||a-c>2E3)))return rc=d,!1;rc=d;Oa.clearPanels();Oa.resetProbeState();sc=Gb=Hb=tc=0;Oa.resetEnemyScanCache();uc=null;Ib=vc=0;n.invalidateEnemyVisualCaches();g();r(D,!1);D=null;Eb=!1;ob=R=Ha=ba=-1;Ja=0;Db=Cb=-1;pc=Va=0;lb=-1;ic++;Jb=ac="";kc=null;lc=0;ta=!1;I=fa=Wa=Na=null;wc=-1;Da=null;Fb=0;sb=Xa=jb=ca=!1;bc=Kb=xc=Lb=Mb=0;Fa=!1;Ga=0;Ma="";
Y=!0;qa=0;ma=!0;Ca=0;n.resetStyleDriftBackoff();Nb();Uc("match_reset");z.writeMatchResetAck(b,d);return!0}function xd(){var a={},b;for(b in U)Object.prototype.hasOwnProperty.call(U,b)&&(a[b]=e[b]);try{var c=JSON.stringify(a);c!==Ma&&(Ma=c,z.writeSharedConfigRaw(c))}catch(d){}}function yd(a,b){if(!a)return!1;var c=0,d;for(d in a)Object.prototype.hasOwnProperty.call(a,d)&&Object.prototype.hasOwnProperty.call(U,d)&&(e[d]=T(d,a[d]),c+=1);if(!c)return!1;try{yc()}catch(f){}try{n.invalidateEnemyVisualCaches()}catch(f){}Nb();
ma=Y=!0;Ca=0;zc();V(0);V(1);V(2);a=E();jb=!0;b==="durable_shared"?Ac(a,!0,!0):(Ga=a+(b==="shared"?15E3:6E3),b!=="shared"&&xd(),Ac(a,!1,!0));return!0}function Ac(a,b,c){Xa=ca=!0;try{var d=wd();d&&(d.__hpColorsBootstrapAppliedAt=a||E())}catch(f){}b&&(Fa=!0,Ga=0);c&&z.markBootstrapSeen()}function zd(a){var b=z.readSharedConfigRaw(a);if(!b||a==="shared"&&b===Ma)return!1;var c=null;try{c=JSON.parse(b)}catch(d){return!1}c=a==="shared"&&c&&typeof c==="object"?c.values||c:c;if(!c||typeof c!=="object"||!yd(c,
a))return!1;a==="shared"&&(Ma=b);return!0}function kb(){return!Fa&&(zd("durable_shared")||zd("shared"))}function Ob(a){var b=E();Uc(a||"overlay_request");if(!(Kb&&b-Kb<400)){if(!ya)try{var c=wd();c&&(c.__hpColorsBootstrapRequests||(c.__hpColorsBootstrapRequests={last:0,attempts:0}),ya=c.__hpColorsBootstrapRequests)}catch(d){}if(ya){c=ya.attempts<8?400:3E3;if(ya.last&&b-ya.last<c)return;ya.last=b;ya.attempts=(ya.attempts||0)+1}Kb=b;z.dispatchBootstrapRequest(a)}}function Pb(){ca||Xa||kb()||(Mb>=8?
(Ob("overlay_slow_retry"),$.Schedule(3,Pb)):(Mb+=1,Ob(Mb===1?"overlay_startup":"overlay_retry"),$.Schedule(.5,Pb)))}function Od(a){if(!(ca||Xa||sb)){sb=!0;try{$.Schedule(.01,function(){sb=!1;ca||Xa||kb()||(Ob(a||"overlay_retry"),$.Schedule(.5,Pb))})}catch(b){if(sb=!1,!(ca||Xa||kb())){Ob(a||"overlay_retry");try{$.Schedule(.5,Pb)}catch(c){}}}}}function xa(a,b,c){a=a.slice(1);a.length===3&&(a=a[0]+a[0]+a[1]+a[1]+a[2]+a[2]);b=b.slice(1);b.length===3&&(b=b[0]+b[0]+b[1]+b[1]+b[2]+b[2]);a=parseInt(a,16);
b=parseInt(b,16);return"#"+(16777216|((a>>16&255)+((b>>16&255)-(a>>16&255))*c|0)<<16|((a>>8&255)+((b>>8&255)-(a>>8&255))*c|0)<<8|(a&255)+((b&255)-(a&255))*c|0).toString(16).slice(1)}function da(a){if(typeof a!=="string")return"";var b=a.trim();if(!b)return"";if(b.charAt(0)==="#")return b.length===4?("#"+b.charAt(1)+b.charAt(1)+b.charAt(2)+b.charAt(2)+b.charAt(3)+b.charAt(3)).toLowerCase():b.length>=7?b.slice(0,7).toLowerCase():b;if(a=b.match(/^rgba?\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)/i)){b=+a[1]|0;
var c=+a[2]|0;a=+a[3]|0;b<0?b=0:b>255&&(b=255);c<0?c=0:c>255&&(c=255);a<0?a=0:a>255&&(a=255);return"#"+(16777216|b<<16|c<<8|a).toString(16).slice(1)}return b}function mb(){return e.hp_team_colors?L===2?"#6485FC":"#FFC961":e.hp_color_high}function mc(a,b,c){return e.hp_text_color_mode?a<=b?e.hp_text_color_low:a<=c?e.hp_text_color_mid:e.hp_text_color_high:a<=b?e.hp_color_low:a<=c?e.hp_color_mid:mb()}function od(a,b,c){var d=p.denomMid||Math.max(1,c-b),f=p.denomHigh||Math.max(1,100-c);if(e.hp_text_color_mode)return a<=
b?e.hp_text_color_low:a<=c?xa(e.hp_text_color_low,e.hp_text_color_mid,(a-b)/d):xa(e.hp_text_color_mid,e.hp_text_color_high,(a-c)/f);if(a<=b)return e.hp_color_low;if(a<=c)return xa(e.hp_color_low,e.hp_color_mid,(a-b)/d);a=(a-c)/f;b=mb();return xa(e.hp_color_mid,b,a)}function v(a){try{return!(!a||a.IsValid&&!a.IsValid())}catch(b){}return!1}function oc(){return Ya.FindChildTraverse("unit_healthbar_lagging")}function Pd(){if(tb){var a=!e.hp_counter_visible||v(l);if(v(w)&&a&&v(F)&&v(B)&&v(S)&&v(X)&&v(za))return 1;
Za=tb=0}a=E();if(Za&&a<Za)return 0;$a++;v(w)||(w=Ya.FindChildTraverse("UnitStatus"));if(!w)return Za=a+($a<8?150:$a<24?500:1500),0;v(l)||!e.hp_counter_visible&&Qb==="collapse"||(l=w.FindChildTraverse("hp_counter"));e.hp_counter_visible&&!v(M)&&(M=w.FindChildTraverse("hp_counter_anchor"));v(F)||(F=w.FindChildTraverse("unit_healthbar_bg"));v(B)||(B=w.FindChildTraverse("unit_healthbar_pip_label"));v(S)||(S=w.FindChildTraverse("unit_healthbar_lagging"));e.hp_kill_zone_enabled&&!v(J)&&(J=w.FindChildTraverse("hp_kill_zone_marker"));
v(q)||(q=w.FindChildTraverse("unit_ult_ready_icon"));v(q)&&(Rb=0);v(aa)||(aa=w.FindChildTraverse("InfoHealthContainer"));v(na)||(na=w.FindChildTraverse("UnitHealthbarContainer"));v(za)||(za=Ya.FindChildTraverse("name"));S&&!v(X)&&(X=S.GetParent());if(B&&S&&X)return tb=1,Za=$a=0,1;Za=a+($a<8?150:$a<24?500:1500);return 0}function Aa(a){try{return!(!a||!a.IsValid||a.IsValid())}catch(b){}return!1}function Nb(){sc=E()+1600;Gb=Hb=0}function Uc(a){var b=E(),c=z.getPresetRequestState(z.getSharedStore());
if(c){if(c.last&&b-c.last<120)return;c.last=b}z.dispatchPresetRequest(a)}function Jd(a,b){if(!b||ca||jb||Fa||!wa||a-wa>1800||e.hp_team_colors||da(e.hp_color_high)!==da(U.hp_color_high))return!1;var c=z.getSharedStore();b=z.getFirstPaintProbeState(c);c=z.hasBootstrapEvidence(c);var d=b?b.nextAt||0:Lb;if(!c&&d&&a<d)return!1;if(!d||a>=d){bc=a;if(kb()||!c&&!b)return!1;c=b?(b.waitCount||0)+1:xc+1;d=c<4?80:c<10?150:250;b?(b.waitCount=c,b.nextAt=a+d):(xc=c,Lb=a+d);if(c===1||c===5)Uc("first_paint_wait"),
Ob("first_paint_wait")}x(0,Math.max(.05,Math.min(.12,((b?b.nextAt||a+80:Lb)-a)/1E3)));return!0}function Vc(a,b){for(var c=0,d=0,f=0;a&&f<10;){if(a.BHasClass)if(c||(a.BHasClass("team2")?c=2:a.BHasClass("team1")&&(c=1)),b){if(d&1||!a.BHasClass("friend")||(d|=1),d&2||!a.BHasClass("player")||(d|=2),d&4||!a.BHasClass("enemy")||(d|=4),c&&(d&7)===7)break}else if(d&1||!a.BHasClass("enemy")||(d|=1),d&2||!a.BHasClass("team_neutral")&&!a.BHasClass("neutral")||(d|=2),d&4||!(a.BHasClass("building")||a.BHasClass("boss_tier1")||
a.BHasClass("boss_tier2")||a.BHasClass("boss_barracks"))||(d|=4),d&8||!a.BHasClass("friend")||(d|=8),c&&d&15)break;if(!a.GetParent)break;a=a.GetParent();f++}return(c&3)<<Ad|d&Bc}function Ta(a,b){Eb=!1;pa=null;Db=Cb=-1;rb=Va=0;uc=null;Ib=vc=0;r(a,!1);if(b&&a&&a===D&&(b=a&&a.IsValid&&a.IsValid()?sd(a):0)&&b&1&&!(b&4)&&a.style)try{a.style.washColor="#FFEFD7",pa=da("#FFEFD7")}catch(c){pa=null}}function sd(a){var b=E();if(a===uc&&b-vc<Qd)return Ib;Ib=Vc(a,!0)&Bc;uc=a;vc=b;return Ib}function t(a,b,c,d){a=
Number(a);isFinite(a)||(a=Number(d));isFinite(a)||(a=0);isFinite(b)&&a<b&&(a=b);isFinite(c)&&a>c&&(a=c);return a}function Sb(a){return t(a,0,100,0)|0}function Jc(){var a=Sb(e.hp_low_threshold),b=Sb(e.hp_high_threshold);b<a&&(b=a);var c=e.hp_kill_zone_width|0;c<1&&(c=1);c>100&&(c=100);var d=t(e.hp_counter_size,72,400,145);p.low=a;p.high=b;p.denomMid=Math.max(1,b-a);p.denomHigh=Math.max(1,100-b);p.pulseThreshold=Sb(e.hp_pulse_threshold);p.friendPulseThreshold=Sb(e.hp_friend_pulse_threshold);p.counterSize=
d;p.pulseTextSize=t(e.hp_pulse_text_scale,72,320,d);p.counterPosition=Bd(e.hp_counter_position,!0);p.pulseTextPosition=Bd(e.hp_pulse_text_position,!1);p.healthbarHeight=Math.round(t(e.hp_healthbar_height,0,230,130));p.killZoneThreshold=Sb(e.hp_kill_zone_threshold);p.killZoneWidth=c;p.killZoneColorRaw=e.hp_kill_zone_color||"#FF2222";p.killZoneColor=da(p.killZoneColorRaw)}function Ea(a,b){if((!J||!v(J))&&a&&e.hp_kill_zone_enabled&&w&&w.FindChildTraverse)try{J=w.FindChildTraverse("hp_kill_zone_marker")}catch(C){}if(J&&
J.style){var c=!F||!F.style||ab!=="visible"||bb!=="1.0";if(!a||!e.hp_kill_zone_enabled||b<=0||c)Cc=null,Qa!=="collapse"&&(Qa=J.style.visibility="collapse");else{a=p.killZoneThreshold;c=p.killZoneWidth;var d=Math.round(b*a/100-c/2);d<0&&(d=0);d>b-c&&(d=Math.max(0,b-c));d+="px";var f=c+"px";Wc!==p.killZoneColorRaw&&(Wc=p.killZoneColorRaw,Xc=p.killZoneColor);var h=Xc;b=b+"|"+a+"|"+c+"|"+p.killZoneColorRaw+"|"+h+"|"+ab+"|"+bb;if(Cc!==b||Qa!=="visible"||Dc!==d||Ec!==f||Tb!==h)if(Cc=b,Qa!=="visible"&&(Qa=
J.style.visibility="visible"),Dc!==d&&(Dc=J.style.marginLeft=d),Ec!==f&&(Ec=J.style.width=f),Tb!==h)try{Tb=J.style.backgroundColor=h}catch(C){Tb=null}}}}function Bd(a,b){var c=0,d=200;b=b?-200:0;if(a&&typeof a==="object")return Array.isArray(a)?(a.length>0&&(c=t(a[0],0,400,0)),a.length>1&&(d=t(a[1],b,400,200))):(Object.prototype.hasOwnProperty.call(a,"x")&&(c=t(a.x,0,400,0)),Object.prototype.hasOwnProperty.call(a,"y")&&(d=t(a.y,b,400,200))),{x:c,y:d};if(typeof a==="string"){var f=a.match(/-?\d+(?:\.\d+)?/g);
if(f&&f.length>0)return c=t(f[0],0,400,0),f.length>1&&(d=t(f[1],b,400,200)),{x:c,y:d}}typeof a==="number"&&(d=t(a,b,400,200));return{x:c,y:d}}function Kc(a){if(l&&l.style){a=!!(a&&e.hp_pulse_enabled&&e.hp_pulse_text_enabled);var b=p.counterSize||t(e.hp_counter_size,72,400,145);b=a?p.pulseTextSize||t(e.hp_pulse_text_scale,72,320,b):b;var c=a?p.pulseTextPosition:p.counterPosition,d=t(c.x,0,400,0),f=t(c.y,-50,400,200);c=b+"px";var h="100%";if(a){a=130;try{var C=l.GetParent?l.GetParent():null;C&&C.actuallayoutheight>
0&&(a=C.actuallayoutheight)}catch(u){}h=Math.max(a,Math.round(b*1.85))+"px"}C="translate3d("+Math.round(d)+"px, "+Math.round(Math.max(f-150,-200))+"px, 0px)";cb!==c&&(cb=l.style.fontSize=c);db!==h&&(db=l.style.height=h);M&&M.style&&eb!==C&&(eb=M.style.transform=C)}}function xb(a){if(l&&l.style){var b=a?"visible":"collapse";if(Qb!==b)try{Qb=l.style.visibility=b}catch(c){Qb=null}a||(Ub=Vb=-1,ta=!1)}}function yc(){var a="";try{za&&(a=za.text||za.GetAttributeString("text","")||"")}catch(b){a=""}k===Fc&&
G===Yc&&X===Zc&&l===$c&&F===ad&&J===bd&&B===cd?a!==Jb&&(Jb=a,kc=null,lc=0,ob=R=Ha=ba=-1,ea=ra=sa=W=Ja=0,n.resetStyleDriftBackoff()):(Fc=k,Yc=G,Zc=X,$c=l,ad=F,bd=J,cd=B,Jb=a,ic++,lb=-1,cc=wa=E(),Fa&&(Fa=!1,Ga=wa+6E3),n.invalidateEnemyVisualCaches(),g(),Eb=!1,pa=Ua=K=aa=D=null,Db=Cb=-1,Va=0,Da=null,ob=R=Ha=ba=-1,ea=ra=sa=W=Ja=0,ta=!1,ac="",sb=Xa=jb=ca=!1,xc=Lb=0,Ma="",Mb=Kb=0,Ga&&Ga<wa&&(Ga=0),ma=Y=!0,Ca=qa=0,Nb(),Od("panel_rebind"))}function pd(){g();if(k&&k.style)try{k.style.washColor=""}catch(a){}if(q&&
q.style)try{q.style.washColor=""}catch(a){}if(l&&l.style)try{l.style.washColor=""}catch(a){}ib=oa=Ba=Q=hb=la=null;Ea(!1,0);F&&F.style&&(ab!=="collapse"&&(ab=F.style.visibility="collapse"),bb!=="0"&&(bb=F.style.opacity="0"));if(l&&l.style){try{l.style.fontSize="",l.style.height="",l.style.washColor=""}catch(a){}ib=oa=db=cb=null}M&&M.style&&(M.style.transform="",eb=null);ob=R=Ha=ba=-1;ea=ra=sa=W=Ja=0}function vd(){if(!I||!I.IsValid()){fa&&fa.IsValid()||(fa=Ya.FindChildTraverse("LevelContainer"));for(var a=
fa;a;){if(a.BHasClass&&a.BHasClass("enemy")){I=a;break}if(!a.GetParent)break;a=a.GetParent()}}if(I&&I.IsValid&&I.IsValid()){try{I.RemoveClass(Cd)}catch(b){}for(a=0;a<4;a++)try{I.RemoveClass(dd[a])}catch(b){}}Da=!1;wc=-1;Fb=0}function ed(a,b){Yb(a)&&!N[a]&&(N[a]=!0,x(a,b||.05))}function zc(a){Jc();if(e.hp_enabled)ed(0);else if(a==="hp_enabled"||N[0])pd(),N[0]=!1;if(e.hp_friend_enabled)ed(1);else if(a==="hp_friend_enabled"||N[1])Ta(D,!0),D=null,N[1]=!1;if(e.hp_level_number_visible)ed(2);else if(a===
"hp_level_number_visible"||N[2])vd(),N[2]=!1;e.hp_counter_visible?a==="hp_counter_visible"&&(Ub=Vb=-1,V(0)):xb(!1);e.hp_pulse_enabled&&e.hp_pulse_text_enabled||((ja||a==="hp_pulse_enabled"||a==="hp_pulse_text_enabled")&&g(),ta=!1,Kc(!1));!e.hp_friend_pulse_enabled&&wb&&r(K,!1);if(a==="hp_ult_color_enabled"||a==="hp_ult_color_custom")Q=Ba=null,V(0);e.hp_kill_zone_enabled?a==="hp_kill_zone_enabled"&&V(0):Ea(!1,0);if(B&&B.style&&!e.hp_pip_visible&&Ra!=="collapse")try{Ra=B.style.visibility="collapse"}catch(b){Ra=
null}}function ld(a,b,c){if(!e.hp_counter_visible)xb(!1);else if(l&&(a!==Vb||b!==Ub)){xb(!0);var d=e.hp_counter_format|0;d=d===1?(b>0?Math.round(a/b*100):0)+"%":d===2?String(a):a+" / "+b;try{l.text!==d&&(l.text=d)}catch(f){try{l.SetAttributeString("text",d)}catch(h){}}c=!!c;d=cb===null||db===null||M&&M.style&&eb===null;c!==ta||d?(ta=c,Kc(ta)):ta=c;Vb=a;Ub=b}}function Nd(){Wa&&Wa.IsValid()||(Wa=Ya.FindChildTraverse("unit_level_label"));fa&&fa.IsValid()||(fa=Ya.FindChildTraverse("LevelContainer"));
if(fa&&(!I||!I.IsValid()))for(var a=fa;a;){if(a.BHasClass&&a.BHasClass("enemy")){I=a;break}if(!a.GetParent)break;a=a.GetParent()}if(!Wa||!fa||!I)return!1;Da!==!0&&(I.AddClass(Cd),Da=!0);var b="";try{b=Wa.text||Wa.GetAttributeString("text","")||""}catch(f){b=""}if(!b||b.charCodeAt(0)===123)return!1;for(var c=a=0;c<b.length;c++){var d=b.charCodeAt(c)-48;d>=0&&d<=9&&(a=a*10+d)}if(a===wc||!a)return!1;wc=a;for(b=0;b<4;b++)I.RemoveClass(dd[b]);for(b=3;b>=0;b--)if(a>=Rd[b]){I.AddClass(dd[b]);break}return!0}
var U={hp_enabled:!0,hp_mode:1,hp_low_threshold:25,hp_high_threshold:65,hp_bg_visible:!0,hp_team_colors:!1,hp_info_health_margin_top:23,hp_healthbar_height:130,hp_color_low:"#E16161",hp_color_mid:"#FF7B00",hp_color_high:"#00FF00",hp_counter_visible:!0,hp_counter_size:145,hp_counter_position:"27,20",hp_text_color_mode:0,hp_text_color_low:"#E16161",hp_text_color_mid:"#FF7B00",hp_text_color_high:"#FFFFFF",hp_pulse_bpm:75,hp_pulse_intensity:1,hp_pulse_enabled:!0,hp_pulse_text_enabled:!1,hp_pulse_text_scale:120,
hp_pulse_text_position:"20,196",hp_pulse_hide_bar:!1,hp_pulse_color_enabled:!1,hp_pulse_color:"#FF2222",hp_pulse_color_mode:0,hp_skip_buildings:!1,hp_pulse_threshold:25,hp_counter_format:0,hp_friend_enabled:!1,hp_friend_pulse_enabled:!1,hp_friend_pulse_bpm:75,hp_friend_pulse_intensity:1,hp_friend_pulse_threshold:25,hp_friend_color_low:"#E16161",hp_friend_color_mid:"#FF7B00",hp_friend_color_high:"#00FF00",hp_friend_pulse_color_enabled:!1,hp_friend_pulse_color:"#FF2222",hp_level_number_visible:!0,hp_pip_visible:!0,
hp_ult_color_enabled:!0,hp_ult_color_custom:"#E16161",hp_kill_zone_enabled:!1,hp_kill_zone_threshold:25,hp_kill_zone_color:"#FF2222",hp_kill_zone_width:3},e={},p={},E=Date.now?Date.now.bind(Date):function(){return+new Date},ub=["pulse_subtle","","pulse_intense"],Kd=[.35,.8,1.5,2.5],Md=[.35,.7,1.4,2,2],N=[!1,!1,!1],Zb=[!1,!1,!1],jd=[0,0,0],$b=[0,0,0],ja=0,gb=null,ka=-1,Na=null,K=null,Ua=null,D=null,pa=null,Cb=-1,Db=-1,Va=0,Eb=!1,rb=0,wb=0,vb=-1,pc=0;(function(){for(var a in U)Object.prototype.hasOwnProperty.call(U,
a)&&(e[a]=U[a])})();Jc();var z={eventChannel:"ClientUI_FireOutput",presetSnapshotMagic:"HP_COLORS_PRESET_SNAPSHOT",presetRequestMagic:"HP_COLORS_PRESET_REQUEST",bulkUpdateMagic:"ANITA_BULK_UPDATE",singleUpdateMagic:"ANITA_UPDATE",bootstrapRequestMagic:"ANITA_REQUEST_BOOTSTRAP",sharedCfgRawKey:"__hpColorsCfgRaw",sharedDurableCfgRawKey:"__hpColorsDurableCfgRaw",sharedBootstrapSeenKey:"__hpColorsBootstrapSeen",sharedFirstPaintProbeKey:"__hpColorsFirstPaintProbe",sharedPresetRequestKey:"__hpColorsPresetRequests",
sharedMatchResetKey:"__hpColorsMatchReset",sharedMatchResetAckKey:"__hpColorsMatchResetAck",getSharedStore:function(){try{if(typeof GameUI!=="undefined"&&GameUI&&GameUI.CustomUIConfig)return GameUI.CustomUIConfig()}catch(a){}return null},parsePayload:function(a){try{return typeof a==="string"?JSON.parse(a):a}catch(b){}return null},shouldInspectPayload:function(a){return typeof a!=="string"?!0:a.indexOf("ANITA")===-1&&a.indexOf(this.presetSnapshotMagic)===-1?!1:a.indexOf("HP Colors")!==-1},acceptsTitle:function(a){return!(!a||
a.mod_title!=="HP Colors")},isBulkUpdate:function(a){return!(!a||a.magic_word!==this.bulkUpdateMagic)},isSingleUpdate:function(a){return!(!a||a.magic_word!==this.singleUpdateMagic)},isPresetSnapshot:function(a){return!(!a||a.magic_word!==this.presetSnapshotMagic)},isBootstrapReplaySource:function(a){return a==="bridge_bootstrap"||a==="ui_resync"||a==="ui_reset"||a==="ui_code_apply"||a==="baked_preset_apply"||a==="core_auto_resync"||a==="ui_refresh_after_apply"},dispatchPayload:function(a){try{return $.DispatchEvent(this.eventChannel,
JSON.stringify(a)),!0}catch(b){}return!1},dispatchBootstrapRequest:function(a){return this.dispatchPayload({magic_word:this.bootstrapRequestMagic,mod_title:"HP Colors",storageNamespace:"hp_colors",reason:String(a||"overlay_request")})},dispatchPresetRequest:function(a){return this.dispatchPayload({magic_word:this.presetRequestMagic,mod_title:"HP Colors",reason:String(a||"overlay_request")})},getPresetRequestState:function(a){if(!a)return null;try{return a[this.sharedPresetRequestKey]||(a[this.sharedPresetRequestKey]=
{last:0}),a[this.sharedPresetRequestKey]}catch(b){}return null},readSharedConfigRaw:function(a){var b=this.getSharedStore();if(!b)return"";a=a==="durable_shared"?this.sharedDurableCfgRawKey:this.sharedCfgRawKey;try{return String(b[a]||"")}catch(c){}return""},writeSharedConfigRaw:function(a){var b=this.getSharedStore();if(!b)return!1;try{return b[this.sharedCfgRawKey]=a,!0}catch(c){}return!1},markBootstrapSeen:function(){var a=this.getSharedStore();if(!a)return!1;try{return a[this.sharedBootstrapSeenKey]=
"1",!0}catch(b){}return!1},hasBootstrapEvidence:function(a){if(!a)return!1;try{return!!(a[this.sharedBootstrapSeenKey]||a[this.sharedDurableCfgRawKey]||a[this.sharedCfgRawKey])}catch(b){}return!1},getFirstPaintProbeState:function(a){if(!a)return null;try{return a[this.sharedFirstPaintProbeKey]||(a[this.sharedFirstPaintProbeKey]={nextAt:0,waitCount:0}),a[this.sharedFirstPaintProbeKey]}catch(b){}return null},readMatchResetInfo:function(a){if(!a)return null;try{var b=a[this.sharedMatchResetKey];return b?
typeof b==="object"?b:{token:String(b),reason:"legacy"}:null}catch(c){}return null},readMatchResetAck:function(a){if(!a)return null;try{return a[this.sharedMatchResetAckKey]||{}}catch(b){}return null},writeMatchResetAck:function(a,b){if(!a)return!1;try{return a[this.sharedMatchResetAckKey]={token:b,at:Date.now?Date.now():+new Date},!0}catch(c){}return!1},getPresetSnapshotValues:function(a){var b=a&&a.values&&typeof a.values==="object"?a.values:null;if(!b)return null;a=typeof a.values_raw==="string"?
a.values_raw:"";if(!a)try{a=JSON.stringify(b)}catch(c){a=""}return{values:b,raw:a}}},ca=!1,jb=!1,Mb=0,Xa=!1,sb=!1,Lb=0,xc=0,Y=!0,qa=0,ma=!0,Ca=0,Kb=0,bc=0,Ga=0,Fa=!1,cc=0,Oc=0,fc=0,ya=null,Ma="",Rb=0,rc="",Tc=0;$.RegisterForUnhandledEvent("ClientUI_FireOutput",function(a){if(z.shouldInspectPayload(a)){var b=z.parsePayload(a);if(z.acceptsTitle(b))if(z.isPresetSnapshot(b))a=z.getPresetSnapshotValues(b),!a||a.raw&&a.raw===Ma&&ca||!yd(a.values,"shared")||!a.raw||(Ma=a.raw);else{a=E();a:{var c=z.isBulkUpdate(b),
d=z.isSingleUpdate(b);if(c||d){var f=z.isBootstrapReplaySource(String(b.update_source||"")),h=f||!!b.force_emit,C=c?b.values||{}:null,u=d?b.setting_id:"",Z=!1,H=!1,Pa=!1,ua=!1,O=!1;if(c)for(var A in C){if(Object.prototype.hasOwnProperty.call(C,A)&&(O=!0,Object.prototype.hasOwnProperty.call(U,A)&&(A!=="hp_counter_position"||b.update_source!=="hp_counter_autoposition"))){var yb=T(A,C[A]);e[A]!==yb&&(e[A]=yb,Z=!0,A.indexOf("hp_friend_")!==0&&(H=!0),ia(A)&&(Pa=!0),Xb(A)&&(ua=!0))}}else if(Object.prototype.hasOwnProperty.call(U,
u)){if(u==="hp_counter_position"&&b.update_source==="hp_counter_autoposition")break a;A=T(u,b.value);Z=e[u]!==A;e[u]=A;Z&&(u.indexOf("hp_friend_")!==0&&(H=!0),ia(u)&&(Pa=!0),Xb(u)&&(ua=!0))}if(Z){H&&(Y=!0,qa=a+(f?240:80));Pa&&(e.hp_friend_enabled?(ma=!0,Ca=f?E()+240:0,Ta(D,!1),V(1)):(ma=!1,Ca=0));ua&&(Y=!0,qa=0,Ba=hb=null,R=ba=-1,V(0));xd();if(c||u==="hp_level_number_visible")Da=null;zc(d?u:void 0);c?(e.hp_pulse_enabled||g(),ja&&(gb=null,ka=-1,m(!0,E()))):u!=="hp_pulse_enabled"||e.hp_pulse_enabled?
!ja||u!=="hp_pulse_bpm"&&u!=="hp_pulse_intensity"&&u!=="hp_pulse_text_enabled"&&u!=="hp_pulse_text_scale"||(gb=null,ka=-1,m(!0,E())):g();f&&Ac(a,!0,!1)}else{if(h||c&&O){try{yc()}catch(va){}try{n.invalidateEnemyVisualCaches()}catch(va){}try{Ta(D,!1)}catch(va){}Nb();Y=!0;qa=0;ma=!0;Ca=0;Da=null;lb=R=Ha=ba=-1;zc();V(0);V(1);V(2)}f&&!ca&&Ac(a,!1,!1)}}}}}});var Ya=$.GetContextPanel(),w=null,l=null,M=null,F=null,B=null,S=null,X=null,k=null,G=null,q=null,J=null,aa=null,na=null,za=null,tb=0,$a=0,Za=0,tc=
0,Hb=0,Gb=0,sc=0,ab=null,bb=null,cb=null,db=null,eb=null,dc=null,Lc=null,Mc=null,Nc=null,Ra=null,Oa={panels:{unitStatus:null,counter:null,counterAnchor:null,background:null,pipLabel:null,baseRedBar:null,baseRedBarParent:null,redBar:null,redBarParent:null,ultIcon:null,killMarker:null,infoHealthContainer:null,healthbarContainer:null,name:null},target:{teamId:0,flags:0,isEnemy:!1,isFriendly:!1,isNeutral:!1,isBuilding:!1,isFriendlyBuilding:!1,isEnemyBuilding:!1},metrics:{barWidth:0,parentWidth:0,replacedRedBar:!1},
sync:function(){var a=this.panels;a.unitStatus=w;a.counter=l;a.counterAnchor=M;a.background=F;a.pipLabel=B;a.baseRedBar=S;a.baseRedBarParent=X;a.redBar=k;a.redBarParent=G;a.ultIcon=q;a.killMarker=J;a.infoHealthContainer=aa;a.healthbarContainer=na;a.name=za;a=this.target;a.teamId=L;a.flags=ha;a.isFriendly=this.isFriendlyTarget(ha);a.isNeutral=!!(ha&2);a.isBuilding=!!(ha&4);a.isFriendlyBuilding=this.isFriendlyBuilding(ha,L);a.isEnemyBuilding=this.isEnemyBuilding(ha,L);a.isEnemy=this.isEnemyTarget(ha,
L);a=this.metrics;a.barWidth=k&&k.actuallayoutwidth!==void 0?k.actuallayoutwidth|0:0;a.parentWidth=G&&G.actuallayoutwidth!==void 0?G.actuallayoutwidth|0:0;a.replacedRedBar=k!==null&&k!==S;return this},clearPanels:function(){w=l=M=F=B=S=X=k=G=q=J=aa=na=za=null;return this.sync()},resetProbeState:function(){Za=$a=tb=0},resetPanelHistory:function(){Fc=Yc=Zc=$c=ad=bd=cd=null;Jb=""},invalidateIfInvalid:function(){if(!tb&&!k||!(Aa(w)||Aa(l)||Aa(F)||Aa(B)||Aa(S)||Aa(X)||Aa(k)||Aa(G)||Aa(za)))return!1;this.clearPanels();
this.resetProbeState();this.resetPanelHistory();n.invalidateEnemyVisualCaches();ma=Y=!0;Nb();return!0},refreshEnemy:function(a){var b=!1;this.invalidateIfInvalid();if(v(k))b=this.refreshCurrentRedBar(a,!1);else{if(!tc||a>=tc)tc=(k=oc())?0:a+150;if(!k)return this.sync(),!1}if(!tb&&!Pd())return this.sync(),!1;if(k.GetParent){var c=k.GetParent();G!==c&&(G=c)}b||this.refreshCurrentRedBar(a,!1);yc();this.scanEnemy(k);this.sync();return!0},refreshCurrentRedBar:function(a,b){var c=sc&&a<=sc,d=!1;if(b){var f=
oc();v(f)&&f!==k&&(d=this.adoptRedBar(f))}else if(!Hb||a>=Hb){Hb=a+(c?180:W>=12?2500:W>=4?1800:ea>=8?2500:ea>=3?1800:1200);f=0;if(v(k)&&G&&G.Children)try{for(var h=G.Children(),C=0;C<h.length;C++){var u=h[C];if(v(u)){var Z="";try{Z=String(u.id||"")}catch(H){Z=""}if(Z==="unit_healthbar_lagging"&&++f>1)break}}}catch(H){}if(!v(k)||f<=1)f=oc(),v(f)&&f!==k&&(d=this.adoptRedBar(f))}if(d)return!0;if(!b){if(Gb&&a<Gb)return!1;Gb=a+(c?180:W>=12?2500:W>=4?1800:ea>=10?1400:ea>=4?1300:1200)}if(!G||!G.Children)return!1;
a=[];try{a=G.Children()}catch(H){return!1}b=k;c=this.scoreRedBarCandidate(k,-1);for(d=0;d<a.length;d++)if(f=a[d],v(f)){h="";try{h=String(f.id||"")}catch(H){h=""}if(h==="unit_healthbar_lagging"){h=this.scoreRedBarCandidate(f,d);if(Gc)try{Gc.set(f,1)}catch(H){}h>c&&(b=f,c=h)}}return b&&b!==k?this.adoptRedBar(b):!1},scoreRedBarCandidate:function(a,b){if(!v(a))return-1;var c=a===k?100:0;try{(Gc?Gc.has(a):a===k||a===Fc)||(c+=1E3)}catch(h){}var d=0;try{d=Vc(a,!1)}catch(h){d=0}d&=Bc;d&1&&(c+=90);d&8&&(c-=
1200);d&2&&(c-=1E3);d&4&&e.hp_skip_buildings&&(c-=400);try{(a.actuallayoutwidth|0)>0&&(c+=20)}catch(h){}try{var f=a.GetParent?a.GetParent():null;f&&(f.actuallayoutwidth|0)>0&&(c+=10)}catch(h){}b>=0&&(c+=Math.min(b,20));return c},resetEnemyScanCache:function(){fd=ha=L=0;gd=null},adoptRedBar:function(a){X=G=(S=k=a)&&a.GetParent?a.GetParent():null;this.resetProbeState();this.resetEnemyScanCache();yc();R=Ha=ba=-1;ea=0;lb=-1;n.resetStyleDriftBackoff();this.sync();return!0},scanEnemy:function(a){var b=
E();if(a===gd&&b-fd<Sd)return!1;var c=Vc(a,!1);L=c>>Ad&3;ha=c&Bc;L&&ha&8&&(Dd=L);fd=b;gd=a;return!0},isFriendlyTarget:function(a){return!!(a&8)},isFriendlyBuilding:function(a,b){b=b||L;return!!(a&4&&(a&8||b&&b===Dd))},isEnemyBuilding:function(a,b){b=b||L;return!(!(a&4)||a&2||!b||this.isFriendlyBuilding(a,b))},isEnemyTarget:function(a,b){return a&2||e.hp_friend_enabled&&this.isFriendlyTarget(a)?!1:a&1?!0:this.isEnemyBuilding(a,b)},getIgnoredTargetColor:function(){var a=ha;return a&1&&!(a&2)?"":this.isEnemyBuilding(a,
L)?"#E16161":this.isFriendlyBuilding(a,L)?"#ffffff":a&6?"#5BEFB5":a&8?"#FFEFD7":L===2?"#5B79E6":L===1?"#E7B659":"#E16161"}},Gc=typeof WeakMap==="function"?new WeakMap:null,L=0,ha=0,Dd=0,fd=0,gd=null,Sd=500,Ad=4,Bc=15,la=null,Q=null,oa=null,hb=null,Ba=null,ib=null,Wc=null,Vb=-1,Ub=-1,Qb=null,kc=null,lc=0,ta=!1,Fc=null,Yc=null,Zc=null,$c=null,ad=null,bd=null,cd=null,Jb="",wa=0,ic=0,lb=-1,ac="",n={setBarColor:function(a){if(hb!==a||la===null)if(hb=a,(a=da(a))||(a=""),la!==a&&k)try{la=k.style.washColor=
a}catch(b){la=null}},clearUltIconColor:function(){Ba=null;if(!(q&&q.IsValid&&q.IsValid()&&q.style))Q=null;else if(Q!=="")try{Q=q.style.washColor=""}catch(a){Q=null}},setUltColor:function(a){a=e.hp_ult_color_enabled?a:e.hp_ult_color_custom;if(Ba!==a||!Q){Ba=a;a=da(a)||"#E16161";if(!q||!q.IsValid()){var b=E();if(Rb&&b-Rb<2E3)return;if((q=Ya.FindChildTraverse("unit_ult_ready_icon"))&&q.IsValid())Rb=0;else{Rb=b;return}}if(q&&q.style&&Q!==a)try{Q=q.style.washColor=a}catch(c){Q=null}}},setTextColor:function(a){if(ib!==
a||!oa)if(ib=a,a=da(a),l&&l.style&&oa!==a)try{oa=l.style.washColor=a}catch(b){oa=null}},setBarVisible:function(a){F&&F.style&&(ab!=="visible"&&(ab=F.style.visibility="visible"),a=a?"1.0":"0.01",bb!==a&&(bb=F.style.opacity=a))},invalidateEnemyVisualCaches:function(){Qa=Dc=Ec=Xc=Tb=Cc=ab=bb=cb=db=eb=dc=Lc=Mc=Nc=Ra=hb=Ba=ib=Wc=la=Q=oa=null;Ub=Vb=-1;Qb=null;ea=ra=sa=W=0;this.resetStyleDriftBackoff()},hasEnemyBarStyleDrift:function(){if(!k||!k.style||!la)return!1;try{return da(String(k.style.washColor||
""))!==la}catch(a){}return!1},hasEnemyStyleDrift:function(){if(this.hasEnemyBarStyleDrift())return!0;if(e.hp_counter_visible&&l&&l.style){try{if(cb!==null&&l.style.fontSize!==cb)return!0}catch(a){}try{if(db!==null&&l.style.height!==db)return!0}catch(a){}}if(e.hp_counter_visible&&M&&M.style)try{if(eb!==null&&M.style.transform!==eb)return!0}catch(a){}return!1},resetStyleDriftBackoff:function(){Oc=fc=0}},uc=null,vc=0,Ib=0,Qd=160,Qa=null,Dc=null,Ec=null,Xc=null,Tb=null,Cc=null,hc=0,ba=-1,Ha=-1,R=-1,ob=
-1,Ja=0,W=0,sa=0,ra=0,ea=0,Rd=[11,19,27,35],dd=["level_tier2","level_tier3","level_tier4","level_tier5"],Cd="level_number_visible",Wa=null,fa=null,I=null,wc=-1,Da=null,Fb=0;kb();zc();Pb()})();
