var Cb=typeof Object.defineProperties=="function"?Object.defineProperty:function(k,r,x){if(k==Array.prototype||k==Object.prototype)return k;k[r]=x.value;return k};function Ic(k){k=["object"==typeof globalThis&&globalThis,k,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var r=0;r<k.length;++r){var x=k[r];if(x&&x.Math==Math)return x}throw Error("Cannot find global object");}var ld=Ic(this),md="Int8 Uint8 Uint8Clamped Int16 Uint16 Int32 Uint32 Float32 Float64".split(" ");
ld.BigInt64Array&&(md.push("BigInt64"),md.push("BigUint64"));function fe(k,r){if(r)for(var x=0;x<md.length;x++)ge(md[x]+"Array.prototype."+k,r)}function Ie(k,r){r&&ge(k,r)}function ge(k,r){var x=ld;k=k.split(".");for(var P=0;P<k.length-1;P++){var V=k[P];if(!(V in x))return;x=x[V]}k=k[k.length-1];P=x[k];r=r(P);r!=P&&r!=null&&Cb(x,k,{configurable:!0,writable:!0,value:r})}
Ie("Math.trunc",function(k){return k?k:function(r){r=Number(r);if(isNaN(r)||r===Infinity||r===-Infinity||r===0)return r;var x=Math.floor(Math.abs(r));return r<0?-x:x}});function Je(k){k=Math.trunc(k)||0;k<0&&(k+=this.length);if(!(k<0||k>=this.length))return this[k]}Ie("Array.prototype.at",function(k){return k?k:Je});fe("at",function(k){return k?k:Je});Ie("String.prototype.at",function(k){return k?k:Je});function Ke(k){var r=0;return function(){return r<k.length?{done:!1,value:k[r++]}:{done:!0}}}
Ie("Symbol",function(k){function r(ha){if(this instanceof r)throw new TypeError("Symbol is not a constructor");return new x(P+(ha||"")+"_"+V++,ha)}function x(ha,Yb){this.i=ha;Cb(this,"description",{configurable:!0,writable:!0,value:Yb})}if(k)return k;x.prototype.toString=function(){return this.i};var P="jscomp_symbol_"+(Math.random()*1E9>>>0)+"_",V=0;return r});
Ie("Symbol.iterator",function(k){if(k)return k;k=Symbol("Symbol.iterator");Cb(Array.prototype,k,{configurable:!0,writable:!0,value:function(){return Le(Ke(this))}});return k});function Le(k){k={next:k};k[Symbol.iterator]=function(){return this};return k}function Me(k,r){k instanceof String&&(k+="");var x=0,P=!1,V={next:function(){if(!P&&x<k.length){var ha=x++;return{value:r(ha,k[ha]),done:!1}}P=!0;return{done:!0,value:void 0}}};V[Symbol.iterator]=function(){return V};return V}
Ie("Array.prototype.values",function(k){return k?k:function(){return Me(this,function(r,x){return x})}});
(function(){var k,r,x,P,V,ha,Yb,nd,od,pd,qd,rd,sd,Db;function ia(){if(ja||Eb!==null||!(va<0)||mb!==null){var a=va>=0?Fb[va]:"";ja=0;Eb=null;va=-1;Gb=Fa=Hb=wa=Q=Ga=mb=null;for(var b=[n,p,u],c=0;c<b.length;c++){var d=b[c];if(d)try{d.RemoveClass("low_hp_pulsing"),a&&d.RemoveClass(a),d.style&&(d.style.animationDuration="",d.style.brightness="")}catch(f){}}}}function td(a){if(a.stop)return ia(),!1;if(!a.shouldPulse)return!1;if(!ja){ja=1;wa=Q=Ga=null;try{n&&n.AddClass("low_hp_pulsing")}catch(d){}try{u&&
u.AddClass("low_hp_pulsing")}catch(d){}}Eb!==a.duration&&(Eb=a.duration,n&&n.IsValid&&n.IsValid()&&(n.style.animationDuration=a.duration),u&&u.IsValid&&u.IsValid()&&(u.style.animationDuration=a.duration));if(va!==a.intensityIndex){var b=va>=0?Fb[va]:"",c=Fb[a.intensityIndex];va=a.intensityIndex;if(b){try{n&&n.IsValid&&n.IsValid()&&n.RemoveClass(b)}catch(d){}try{u&&u.IsValid&&u.IsValid()&&u.RemoveClass(b)}catch(d){}}if(c){try{n&&n.IsValid&&n.IsValid()&&n.AddClass(c)}catch(d){}try{u&&u.IsValid&&u.IsValid()&&
u.AddClass(c)}catch(d){}}}if(a.resetText){try{p&&p.style&&(p.style.animationDuration="",p.style.brightness=""),mb=null}catch(d){}return!1}if(!a.textEnabled||!p||!p.style)return!1;if(mb!==a.textBrightness)try{mb=p.style.brightness=a.textBrightness}catch(d){mb=null}return a.fastSchedule}function Jc(a,b){b=Kc.ally(b,he);var c=a||K;if(b.stop){a=Wa>=0?Fb[Wa]:"";Ib=0;Wa=-1;Ha=null;if(!c)return!1;try{c.RemoveClass("low_hp_pulsing"),a&&c.RemoveClass(a),c.style&&(c.style.animationDuration="",c.style.brightness=
"")}catch(f){}return!1}if(!b.shouldPulse)return!1;if(b.start){Ib=1;Wa=-1;Ha=null;try{a&&a.AddClass("low_hp_pulsing")}catch(f){}}if(Wa!==b.intensityIndex){c=Wa>=0?Fb[Wa]:"";var d=Fb[b.intensityIndex];try{a&&c&&a.RemoveClass(c),a&&d&&a.AddClass(d)}catch(f){}Wa=b.intensityIndex}try{a&&a.style&&(a.style.animationDuration=b.duration)}catch(f){}return b.start}function Ne(a,b){if(a===!0||a===!1)return a;if(a===1||a==="1")return!0;if(a===0||a==="0")return!1;if(typeof a==="string"){a=a.toLowerCase();if(a===
"true")return!0;if(a==="false")return!1}return!!b}function Jb(a,b){if(a===b)return!0;if(a===null||b===null||typeof a!==typeof b)return!1;if(typeof a==="object")try{return JSON.stringify(a)===JSON.stringify(b)}catch(c){}return!1}function ie(a,b){var c={};if(!a||typeof a!=="object"||Array.isArray(a))return c;for(var d in L)Object.prototype.hasOwnProperty.call(L,d)&&(b&&d==="hp_precise_pips_enabled"||Object.prototype.hasOwnProperty.call(a,d)&&(c[d]=Lc.coerceCfgValue(d,a[d])));return c}function je(a){return a===
"hp_low_threshold"||a==="hp_high_threshold"||a==="hp_mode"||a==="hp_team_colors"||a==="hp_ult_color_enabled"||a==="hp_ult_color_custom"||a==="hp_friend_color_low"||a==="hp_friend_color_mid"||a==="hp_friend_color_high"||a==="hp_friend_heal_color"||a==="hp_friend_delta_color"||a==="hp_friend_bullet_shield_color"||a==="hp_friend_pulse_enabled"||a==="hp_friend_pulse_threshold"||a==="hp_friend_pulse_bpm"||a==="hp_friend_pulse_intensity"||a==="hp_friend_pulse_color_enabled"||a==="hp_friend_pulse_color"}
function ke(a){return a==="hp_pulse_color_enabled"||a==="hp_pulse_color"||a==="hp_pulse_color_mode"}function nb(a){return Kb?!1:a===0?!!e.hp_enabled:a===1?!!e.hp_friend_enabled:!!e.hp_level_number_visible}function W(a,b){le.requestKick(a,b)}function D(a,b){return le.schedule(a,b)}function ud(){Lb=null;Mb=0;try{vd()}catch(a){}try{q.invalidateEnemyVisualCaches()}catch(a){}try{ob(K,!1)}catch(a){}Zb();aa=!0;ka=0;xa=!0;Xa=0;Ia=null;pb=ba=Ja=ca=-1;wd();W(0,.01,"preset_apply");W(1,.01,"preset_apply");W(2,
.01,"preset_apply")}function me(){for(var a=$.GetContextPanel();a&&a.GetParent&&a.GetParent();)a=a.GetParent();return a||null}function ne(a){if(xd&&a<xd)return!1;xd=a+250;var b=z.getSharedStore();if(!b)return!1;var c=z.readMatchResetInfo(b);if(!c)return!1;var d=String(c&&c.token||"");if(!d||d===Mc)return!1;var f=z.readMatchResetAck(b);if(f&&String(f.token||"")===d&&(f=Number(c&&c.at),isFinite(f)&&f>0&&(la&&la>f+500||a-f>2E3)))return Mc=d,!1;Mc=d;$b.resetForMatch(d,c.reason);z.writeMatchResetAck(b,
d);return!0}function yd(){var a={},b;for(b in L)Object.prototype.hasOwnProperty.call(L,b)&&(a[b]=Ka[b]);try{var c=JSON.stringify(a);c!==Ya&&(Ya=c,z.writeSharedConfigRaw(c))}catch(d){}}function ac(a,b,c){bc=La=!0;qb+=1;Za=!1;try{var d=me();d&&(d.__hpColorsBootstrapAppliedAt=a||G())}catch(f){}b&&($a=!0,ab=0);c&&z.markBootstrapSeen()}function oe(a){var b=z.readSharedConfigRaw(a);if(!b||a==="shared"&&b===Ya)return!1;var c=null;try{c=JSON.parse(b)}catch(d){return!1}c=a==="shared"&&c&&typeof c==="object"?
c.values||c:c;if(!c||typeof c!=="object"||!$b.applySnapshotValues(c,a))return!1;a==="shared"&&(Ya=b);return!0}function Nc(){return!$a&&(oe("durable_shared")||oe("shared"))}function pe(a){var b=G();$b.requestSnapshot(a||"overlay_request");if(!(cc&&b-cc<400)){if(!Ma)try{var c=me();c&&(c.__hpColorsBootstrapRequests||(c.__hpColorsBootstrapRequests={last:0,attempts:0}),Ma=c.__hpColorsBootstrapRequests)}catch(d){}if(Ma){c=Ma.attempts<8?400:3E3;if(Ma.last&&b-Ma.last<c)return;Ma.last=b;Ma.attempts=(Ma.attempts||
0)+1}cc=b;z.dispatchBootstrapRequest(a)}}function zd(a,b){if(La||bc||Kb||Za)return!1;a=Number(a);if(!isFinite(a)||a<0)a=.01;Za=!0;var c=++qb,d=dc;try{$.Schedule(a,function(){if(c===qb&&Nb.isActive(d)&&(Za=!1,!La&&!bc&&!Nc())){var f=ec>=8;f||(ec+=1);pe(b||(f?"overlay_slow_retry":ec===1?"overlay_startup":"overlay_retry"));zd(f?3:.5)}})}catch(f){return c===qb&&(Za=!1),!1}return!0}function Na(a,b,c){a=a.slice(1);a.length===3&&(a=a[0]+a[0]+a[1]+a[1]+a[2]+a[2]);b=b.slice(1);b.length===3&&(b=b[0]+b[0]+b[1]+
b[1]+b[2]+b[2]);a=parseInt(a,16);b=parseInt(b,16);return"#"+(16777216|((a>>16&255)+((b>>16&255)-(a>>16&255))*c|0)<<16|((a>>8&255)+((b>>8&255)-(a>>8&255))*c|0)<<8|(a&255)+((b&255)-(a&255))*c|0).toString(16).slice(1)}function E(a){if(typeof a!=="string")return"";var b=a.trim();if(!b)return"";if(b.charAt(0)==="#")return b.length===4?("#"+b.charAt(1)+b.charAt(1)+b.charAt(2)+b.charAt(2)+b.charAt(3)+b.charAt(3)).toLowerCase():b.length>=7?b.slice(0,7).toLowerCase():b;if(a=b.match(/^rgba?\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)/i)){b=
+a[1]|0;var c=+a[2]|0;a=+a[3]|0;b<0?b=0:b>255&&(b=255);c<0?c=0:c>255&&(c=255);a<0?a=0:a>255&&(a=255);return"#"+(16777216|b<<16|c<<8|a).toString(16).slice(1)}return b}function Ob(){return e.hp_team_colors?Oa===2?"#6485FC":"#FFC961":e.hp_color_high}function Oc(a,b,c){return e.hp_text_color_mode?a<=b?e.hp_text_color_low:a<=c?e.hp_text_color_mid:e.hp_text_color_high:a<=b?e.hp_color_low:a<=c?e.hp_color_mid:Ob()}function qe(a,b,c){var d=x||Math.max(1,c-b),f=P||Math.max(1,100-c);if(e.hp_text_color_mode)return a<=
b?e.hp_text_color_low:a<=c?Na(e.hp_text_color_low,e.hp_text_color_mid,(a-b)/d):Na(e.hp_text_color_mid,e.hp_text_color_high,(a-c)/f);if(a<=b)return e.hp_color_low;if(a<=c)return Na(e.hp_color_low,e.hp_color_mid,(a-b)/d);a=(a-c)/f;b=Ob();return Na(e.hp_color_mid,b,a)}function t(a){try{return!(!a||a.IsValid&&!a.IsValid())}catch(b){}return!1}function Pc(){return bb.FindChildTraverse("unit_healthbar_lagging")}function Oe(){if(Pb){var a=!e.hp_counter_visible||t(p);if(t(v)&&a&&t(M)&&t(A)&&t(ma)&&t(ya)&&
t(cb))return 1;rb=Pb=0}a=G();if(rb&&a<rb)return 0;sb++;t(v)||(v=bb.FindChildTraverse("UnitStatus"));if(!v)return rb=a+(sb<8?150:sb<24?500:1500),0;t(p)||!e.hp_counter_visible&&fc==="collapse"||(p=v.FindChildTraverse("hp_counter"));e.hp_counter_visible&&!t(R)&&(R=v.FindChildTraverse("hp_counter_anchor"));t(M)||(M=v.FindChildTraverse("unit_healthbar_bg"));t(A)||(A=v.FindChildTraverse("unit_healthbar_pip_label"));t(ma)||(ma=v.FindChildTraverse("unit_healthbar_lagging"));t(H)||(H=v.FindChildTraverse("unit_healthbar_healing"));
t(I)||(I=v.FindChildTraverse("unit_healthbar_delta"));t(B)||(B=v.FindChildTraverse("unit_healthbar_bullet_shield"));t(na)||(na=v.FindChildTraverse("unit_healthbar_tech_shield"));e.hp_kill_zone_enabled&&!t(C)&&(C=v.FindChildTraverse("hp_kill_zone_marker"));t(u)||(u=v.FindChildTraverse("unit_ult_ready_icon"));t(u)&&(hc=0);t(oa)||(oa=v.FindChildTraverse("InfoHealthContainer"));t(za)||(za=v.FindChildTraverse("UnitHealthbarContainer"));t(cb)||(cb=bb.FindChildTraverse("name"));ma&&!t(ya)&&(ya=ma.GetParent());
if(A&&ma&&ya)return Pb=1,rb=sb=0,1;rb=a+(sb<8?150:sb<24?500:1500);return 0}function N(a){try{return!(!a||!a.IsValid||a.IsValid())}catch(b){}return!1}function Zb(){Qc=G()+1600;tb=ic=0}function Pe(a,b){if(!b||La||Qb||$a||!la||a-la>1800||e.hp_team_colors||E(e.hp_color_high)!==E(L.hp_color_high))return!1;var c=z.getSharedStore();b=z.getFirstPaintProbeState(c);c=z.hasBootstrapEvidence(c);var d=b?b.nextAt||0:jc;if(!c&&d&&a<d)return!1;if(!d||a>=d){Rc=a;if(Nc()||!c&&!b)return!1;c=b?(b.waitCount||0)+1:Sc+
1;d=c<4?80:c<10?150:250;b?(b.waitCount=c,b.nextAt=a+d):(Sc=c,jc=a+d);if(c===1||c===5)$b.requestSnapshot("first_paint_wait"),pe("first_paint_wait")}D(0,Math.max(.05,Math.min(.12,((b?b.nextAt||a+80:jc)-a)/1E3)),"enemy_bootstrap_wait");return!0}function Ad(a,b){for(var c=0,d=0,f=0;a&&f<10;){if(a.BHasClass)if(c||(a.BHasClass("team2")?c=2:a.BHasClass("team1")&&(c=1)),b){if(d&1||!a.BHasClass("friend")||(d|=1),d&2||!a.BHasClass("player")||(d|=2),d&4||!a.BHasClass("enemy")||(d|=4),c&&(d&7)===7)break}else if(d&
1||!a.BHasClass("enemy")||(d|=1),d&2||!a.BHasClass("team_neutral")&&!a.BHasClass("neutral")||(d|=2),d&4||!e.hp_skip_buildings&&d&1||!(a.BHasClass("building")||a.BHasClass("boss_tier1")||a.BHasClass("boss_tier2")||a.BHasClass("boss_barracks"))||(d|=4),d&8||!a.BHasClass("friend")||(d|=8),c&&d&15)break;if(!a.GetParent)break;a=a.GetParent();f++}return(c&3)<<Bd|d&Cd}function ob(a,b){kc=!1;Ha=null;lc=mc=-1;Rb=ub=0;Tc=null;nc=Uc=0;oc=pc=qc=null;Jc(a,!1);if(b&&a&&a===K){var c=a&&a.IsValid&&a.IsValid()?re(a):
0;if(c&&c&1&&!(c&4)&&a.style){try{a.style.washColor="#FFEFD7",Ha=E("#FFEFD7")}catch(d){Ha=null}q.clearUltColor();if(b){if(Aa&&Aa.style)try{Aa.style.washColor=""}catch(d){}if(Ba&&Ba.style)try{Ba.style.washColor=""}catch(d){}if(Y&&Y.style)try{Y.style.backgroundColor=""}catch(d){}}}}}function re(a){var b=G();if(a===Tc&&b-Uc<Qe)return nc;nc=Ad(a,!0);Tc=a;Uc=b;return nc}function Vc(a,b){if(!a||!a.Children)return null;try{var c=a.Children();for(a=0;a<c.length;a++){var d=c[a];if(d&&d.id===b)return d}}catch(f){}return null}
function y(a,b,c,d){a=Number(a);isFinite(a)||(a=Number(d));isFinite(a)||(a=0);isFinite(b)&&a<b&&(a=b);isFinite(c)&&a>c&&(a=c);return a}function rc(a){return y(a,0,100,0)|0}function Wc(){var a=rc(e.hp_low_threshold),b=rc(e.hp_high_threshold);b<a&&(b=a);var c=e.hp_kill_zone_width|0;c<1&&(c=1);c>100&&(c=100);var d=y(e.hp_counter_size,72,400,145);k=a;r=b;x=Math.max(1,b-a);P=Math.max(1,100-b);V=rc(e.hp_pulse_threshold);ha=rc(e.hp_friend_pulse_threshold);Yb=d;nd=y(e.hp_pulse_text_scale,72,320,d);od=se(e.hp_counter_position,
!0);pd=se(e.hp_pulse_text_position,!1);qd=Math.round(y(e.hp_healthbar_height,0,230,130));rd=rc(e.hp_kill_zone_threshold);sd=c;Db=e.hp_kill_zone_color||"#FF2222";te=E(Db)}function db(a,b,c){c=c||da;c.killMarkerMissing=!C||!t(C);c.killMarkerCanResolve=!!(a&&e.hp_kill_zone_enabled&&v&&v.FindChildTraverse);c.killMarkerReady=!(!C||!C.style);c.killMarkerBarHidden=!M||!M.style||eb!=="visible"||fb!=="1.0";return Re.enemy(a,b,c)}function vb(a){if(a.killMarkerAction===3){try{C=v.FindChildTraverse("hp_kill_zone_marker")}catch(b){}if(!C||
!C.style)return;a=db(!0,a.killMarkerParentWidth,a)}if(a.killMarkerAction===2)Xc=null,C&&C.style&&Sb!=="collapse"&&(Sb=C.style.visibility="collapse");else if(a.killMarkerAction===1&&C&&C.style&&(Xc=a.killMarkerSig,Sb!=="visible"&&(Sb=C.style.visibility="visible"),Yc!==a.killMarkerX&&(Yc=C.style.marginLeft=a.killMarkerX),Zc!==a.killMarkerWidth&&(Zc=C.style.width=a.killMarkerWidth),sc!==a.killMarkerColor))try{sc=C.style.backgroundColor=a.killMarkerColor}catch(b){sc=null}}function se(a,b){var c=0,d=200;
b=b?-200:0;if(a&&typeof a==="object")return Array.isArray(a)?(a.length>0&&(c=y(a[0],0,400,0)),a.length>1&&(d=y(a[1],b,400,200))):(Object.prototype.hasOwnProperty.call(a,"x")&&(c=y(a.x,0,400,0)),Object.prototype.hasOwnProperty.call(a,"y")&&(d=y(a.y,b,400,200))),{x:c,y:d};if(typeof a==="string"){var f=a.match(/-?\d+(?:\.\d+)?/g);if(f&&f.length>0)return c=y(f[0],0,400,0),f.length>1&&(d=y(f[1],b,400,200)),{x:c,y:d}}typeof a==="number"&&(d=y(a,b,400,200));return{x:c,y:d}}function Dd(a){if(p&&p.style){a=
!!(a&&e.hp_pulse_enabled&&e.hp_pulse_text_enabled);var b=Yb||y(e.hp_counter_size,72,400,145);b=a?nd||y(e.hp_pulse_text_scale,72,320,b):b;var c=a?pd:od,d=y(c.x,0,400,0),f=y(c.y,-50,400,200);c=b+"px";var g="100%";if(a){a=130;try{var h=p.GetParent?p.GetParent():null;h&&h.actuallayoutheight>0&&(a=h.actuallayoutheight)}catch(l){}g=Math.max(a,Math.round(b*1.85))+"px"}h="translate3d("+Math.round(d)+"px, "+Math.round(Math.max(f-150,-200))+"px, 0px)";wb!==c&&(wb=p.style.fontSize=c);xb!==g&&(xb=p.style.height=
g);R&&R.style&&yb!==h&&(yb=R.style.transform=h)}}function Ed(a){if(p&&p.style){var b=a?"visible":"collapse";if(fc!==b)try{fc=p.style.visibility=b}catch(c){fc=null}a||(tc=uc=-1,Ca=!1)}}function vd(){var a="";try{cb&&(a=cb.text||cb.GetAttributeString("text","")||"")}catch(b){a=""}n===$c&&X===Fd&&ya===Gd&&p===Hd&&M===Id&&C===Jd&&A===Kd&&H===Ld&&I===Md&&B===Nd&&na===Od?a!==vc&&(vc=a,Lb=null,Mb=0,Tb=ba=Ja=ca=-1,pa=gb=hb=qa=ib=0,q.resetStyleDriftBackoff()):($c=n,Fd=X,Gd=ya,Hd=p,Id=M,Jd=C,Kd=A,Ld=H,Md=I,
Nd=B,Od=na,vc=a,jb++,pb=-1,ad=la=G(),$a&&($a=!1,ab=la+6E3),q.invalidateEnemyVisualCaches(),ia(),kc=!1,Ha=Da=ea=oa=K=null,lc=mc=-1,ub=0,Ia=null,Tb=ba=Ja=ca=-1,pa=gb=hb=qa=ib=0,Ca=!1,bd=Ub=null,bc=Qb=La=!1,qb+=1,Za=!1,Sc=jc=0,Ya="",ec=cc=0,ab&&ab<la&&(ab=0),xa=aa=!0,Xa=ka=0,Zb(),zd(.01,"panel_rebind"))}function ue(){ia();if(n&&n.style)try{n.style.washColor=""}catch(a){}if(u&&u.style)try{u.style.washColor=""}catch(a){}if(p&&p.style)try{p.style.washColor=""}catch(a){}if(H&&H.style)try{H.style.washColor=
""}catch(a){}if(I&&I.style)try{I.style.washColor=""}catch(a){}if(B&&B.style)try{B.style.backgroundColor=""}catch(a){}wc=xc=yc=Pa=Qa=Ra=Hb=Ga=Fa=Q=Gb=wa=null;vb(db(!1,0,da));M&&M.style&&(eb!=="collapse"&&(eb=M.style.visibility="collapse"),fb!=="0"&&(fb=M.style.opacity="0"));if(p&&p.style){try{p.style.fontSize="",p.style.height="",p.style.washColor=""}catch(a){}Hb=Ga=xb=wb=null}R&&R.style&&(R.style.transform="",yb=null);Tb=ba=Ja=ca=-1;pa=gb=hb=qa=ib=0}function ve(){if(!S||!S.IsValid()){Z&&Z.IsValid()||
(Z=bb.FindChildTraverse("LevelContainer"));for(var a=Z;a;){if(a.BHasClass&&a.BHasClass("enemy")){S=a;break}if(!a.GetParent)break;a=a.GetParent()}}if(S&&S.IsValid&&S.IsValid()){try{S.RemoveClass(we)}catch(b){}for(a=0;a<4;a++)try{S.RemoveClass(zc[a].cls)}catch(b){}}Ia=!1;cd=-1;Vb=0}function Pd(a,b){nb(a)&&!T[a]&&(T[a]=!0,D(a,b||.05,a===0?"enemy_paint":a===1?"ally_paint":"level_poll"))}function wd(a){Wc();if(e.hp_enabled)Pd(0);else if(a==="hp_enabled"||T[0])ue(),T[0]=!1;if(e.hp_friend_enabled)Pd(1);
else if(a==="hp_friend_enabled"||T[1])ob(K,!0),K=null,T[1]=!1;if(e.hp_level_number_visible)Pd(2);else if(a==="hp_level_number_visible"||T[2])ve(),T[2]=!1;e.hp_counter_visible?a==="hp_counter_visible"&&(tc=uc=-1,W(0,.01,"preset_apply")):Ed(!1);a==="hp_precise_pips_enabled"&&(Lb=null,Mb=0,W(0,.01,"preset_apply"));e.hp_pulse_enabled&&e.hp_pulse_text_enabled||((ja||a==="hp_pulse_enabled"||a==="hp_pulse_text_enabled")&&ia(),Ca=!1,Dd(!1));!e.hp_friend_pulse_enabled&&Ib&&Jc(ea,!1);if(a==="hp_ult_color_enabled"||
a==="hp_ult_color_custom")Q=Fa=null,W(0,.01,"preset_apply");e.hp_kill_zone_enabled?a==="hp_kill_zone_enabled"&&W(0,.01,"preset_apply"):vb(db(!1,0,da));if(A&&A.style&&!e.hp_pip_visible&&ra!=="collapse")try{ra=A.style.visibility="collapse"}catch(b){ra=null}Nb.ensureQuiescentCheck()}function xe(a){a.confirmed=!1;a.panel=null;a.parent=null;a.teamId=0;a.barWidth=0;a.parentWidth=0;a.hp=0;return a}var L={hp_enabled:!0,hp_mode:1,hp_low_threshold:25,hp_high_threshold:65,hp_bg_visible:!0,hp_team_colors:!1,
hp_info_health_margin_top:23,hp_healthbar_height:130,hp_color_low:"#E16161",hp_color_mid:"#FF7B00",hp_color_high:"#00FF00",hp_heal_color:"#5fff80",hp_delta_color:"#ffe55b",hp_bullet_shield_color:"#ffffff",hp_counter_visible:!0,hp_counter_size:145,hp_counter_position:"27,20",hp_text_color_mode:0,hp_text_color_low:"#E16161",hp_text_color_mid:"#FF7B00",hp_text_color_high:"#FFFFFF",hp_pulse_bpm:75,hp_pulse_intensity:1,hp_pulse_enabled:!0,hp_pulse_text_enabled:!1,hp_pulse_text_scale:120,hp_pulse_text_position:"20,196",
hp_pulse_hide_bar:!1,hp_pulse_color_enabled:!1,hp_pulse_color:"#FF2222",hp_pulse_color_mode:0,hp_skip_buildings:!1,hp_pulse_threshold:25,hp_counter_format:0,hp_friend_enabled:!1,hp_friend_pulse_enabled:!1,hp_friend_pulse_bpm:75,hp_friend_pulse_intensity:1,hp_friend_pulse_threshold:25,hp_friend_color_low:"#E16161",hp_friend_color_mid:"#FF7B00",hp_friend_color_high:"#00FF00",hp_friend_heal_color:"#5fff80",hp_friend_delta_color:"#504c47",hp_friend_bullet_shield_color:"#ffffff",hp_friend_pulse_color_enabled:!1,
hp_friend_pulse_color:"#FF2222",hp_level_number_visible:!0,hp_pip_visible:!0,hp_precise_pips_enabled:!1,hp_ult_color_enabled:!0,hp_ult_color_custom:"#E16161",hp_kill_zone_enabled:!1,hp_kill_zone_threshold:25,hp_kill_zone_color:"#FF2222",hp_kill_zone_width:3},Ka={},O={},e={},zb={resetDefaults:function(){for(var a in L)Object.prototype.hasOwnProperty.call(L,a)&&(Ka[a]=L[a],e[a]=L[a]);for(var b in O)Object.prototype.hasOwnProperty.call(O,b)&&delete O[b];return{baseChanged:!0,resolvedChanged:!0}},applyBaseValues:function(a){var b=
{count:0,baseChanged:!1,resolvedChanged:!1};if(!a||typeof a!=="object"||Array.isArray(a))return b;for(var c in a)if(Object.prototype.hasOwnProperty.call(a,c)&&Object.prototype.hasOwnProperty.call(L,c)){var d=Lc.coerceCfgValue(c,a[c]);b.count+=1;Jb(Ka[c],d)||(Ka[c]=d,b.baseChanged=!0);d=Object.prototype.hasOwnProperty.call(O,c)?O[c]:Ka[c];Jb(e[c],d)||(e[c]=d,b.resolvedChanged=!0)}return b},applyBaseValue:function(a,b){if(!Object.prototype.hasOwnProperty.call(L,a))return 0;var c=0;b=Lc.coerceCfgValue(a,
b);Jb(Ka[a],b)||(Ka[a]=b,c|=1);b=Object.prototype.hasOwnProperty.call(O,a)?O[a]:Ka[a];Jb(e[a],b)||(e[a]=b,c|=2);return c},replaceConditionalValues:function(a){var b={changed:!1,resolvedChanged:!1},c={};if(a&&typeof a==="object"&&!Array.isArray(a))for(var d in a)Object.prototype.hasOwnProperty.call(a,d)&&Object.prototype.hasOwnProperty.call(L,d)&&d!=="hp_precise_pips_enabled"&&(c[d]=Lc.coerceCfgValue(d,a[d]));for(var f in O)Object.prototype.hasOwnProperty.call(O,f)&&!Object.prototype.hasOwnProperty.call(c,
f)&&(b.changed=!0);for(var g in c)Object.prototype.hasOwnProperty.call(c,g)&&Object.prototype.hasOwnProperty.call(O,g)&&Jb(O[g],c[g])||(b.changed=!0);for(var h in O)Object.prototype.hasOwnProperty.call(O,h)&&delete O[h];for(var l in c)Object.prototype.hasOwnProperty.call(c,l)&&(O[l]=c[l]);for(var m in L)Object.prototype.hasOwnProperty.call(L,m)&&(a=Object.prototype.hasOwnProperty.call(O,m)?O[m]:Ka[m],Jb(e[m],a)||(e[m]=a,b.resolvedChanged=!0));return b}};var te=Db=sd=rd=qd=pd=od=nd=Yb=ha=V=P=x=r=k=
void 0;var G=Date.now?Date.now.bind(Date):function(){return+new Date},Fb=["pulse_subtle","","pulse_intense"],Se=[.35,.8,1.5,2.5],Te=[.35,.7,1.4,2,2],bb=$.GetContextPanel(),Qd=null,dc=1,Kb=!1,Ac=!1,T=[!1,!1,!1],Bc=[!1,!1,!1],Cc=[0,0,0],kb=[0,0,0],Nb={isActive:function(a){if(Kb||a!==void 0&&a!==dc)return!1;if(t(bb))return!0;this.stop();return!1},ensureQuiescentCheck:function(){if(Kb||Ac||nb(0)||nb(1)||nb(2))return!1;Ac=!0;var a=dc;try{return $.Schedule(5,function(){Ac=!1;Nb.isActive(a)&&Nb.ensureQuiescentCheck()}),
!0}catch(b){return Ac=!1}},stop:function(){if(Kb)return!1;Kb=!0;dc+=1;qb+=1;Ac=Za=!1;for(var a=0;a<Cc.length;a+=1)Cc[a]+=1,kb[a]=0,Bc[a]=!1,T[a]=!1;try{$.UnregisterForUnhandledEvent(z.eventChannel,Qd)}catch(b){}Qd=null;Sa.clearPanels();Sa.resetProbeState();Sa.resetPanelHistory();ea=Da=Aa=Ba=Y=Ab=K=S=Ta=Z=null;return!0}},w={skipBuildings:!1,isEnemy:!1,settingsDirty:!1,settingsHold:!1,presetReady:!0,bootstrapWait:!1,styleDrift:!1,barWidth:0,parentWidth:0,lastBarWidth:-1,lastParentWidth:-1,lastUpdateAt:0,
now:0,low:0,lastHp:-1,hp:0,pulseActive:!1,pulseTextEnabled:!1,pulseEnabled:!1,pulseThreshold:0,shouldPulse:!1,wasDirty:!1,colorGeneration:0,panelGeneration:0,stableFrames:0,nonEnemyFrames:0,neutralFrames:0,buildingFrames:0,noParentWidthFrames:0,friendNonEnemy:!1,friendEnabled:!1},ye={action:0,delay:.25,reason:"enemy_paint",hp:0,shouldPulse:!1,pulseFast:!1,friendNonEnemy:!1},Rd=-1,Sd=0,ja=0,Eb=null,va=-1,mb=null,ea=null,Da=null,Aa=null,Ba=null,Y=null,Ab=null,K=null,Ha=null,qc=null,pc=null,oc=null,
mc=-1,lc=-1,ub=0,kc=!1,Rb=0,Ib=0,Wa=-1,dd=0,Td={confirmed:!1,teamId:0,panel:null,parent:null,barWidth:0,parentWidth:0,hp:0},ze={washColor:"",healColor:"",deltaColor:"",bulletShieldColor:"",inPulse:!1,nextDelay:.35},ed={shouldPulse:!1,start:!1,stop:!1,duration:"",intensityIndex:-1,textEnabled:!1,textBrightness:"",resetText:!1,fastSchedule:!1},he={shouldPulse:!1,start:!1,stop:!1,duration:"",intensityIndex:-1},Kc={resetEnemy:function(a){a.shouldPulse=!1;a.start=!1;a.stop=!1;a.duration="";a.intensityIndex=
-1;a.textEnabled=!1;a.textBrightness="";a.resetText=!1;a.fastSchedule=!1;return a},enemy:function(a,b,c){c=this.resetEnemy(c||ed);if(!a)return c.stop=!!ja,c;c.shouldPulse=!0;c.start=!ja;a=y(e.hp_pulse_bpm,30,300,75);c.duration=(60/a).toFixed(3)+"s";c.intensityIndex=y(e.hp_pulse_intensity,0,2,1)|0;if(!e.hp_pulse_text_enabled)return c.resetText=!0,c;a=Math.max(1,6E4/a);b=b%a/a;a=c.intensityIndex;var d=a===2?.55:a===0?.85:.65;c.textEnabled=!0;c.textBrightness=(d+((a===2?2:a===0?1.15:1.5)-d)*(b<.5?b*
2:(1-b)*2)).toFixed(2);c.fastSchedule=!0;return c},resetAlly:function(a){a.shouldPulse=!1;a.start=!1;a.stop=!1;a.duration="";a.intensityIndex=-1;return a},ally:function(a,b){b=this.resetAlly(b||he);if(!a)return b.stop=!!Ib,b;b.shouldPulse=!0;b.start=!Ib;a=y(e.hp_friend_pulse_bpm,30,300,75);b.duration=(60/a).toFixed(3)+"s";b.intensityIndex=y(e.hp_friend_pulse_intensity,0,2,1)|0;return b}},Lc={formatPositionValue:function(a){var b=0;var c=200;a&&typeof a==="object"?(Array.isArray(a)?(a.length>0&&(b=
y(a[0],0,400,0)),a.length>1&&(c=y(a[1],-50,400,200))):(Object.prototype.hasOwnProperty.call(a,"x")&&(b=y(a.x,0,400,0)),Object.prototype.hasOwnProperty.call(a,"y")&&(c=y(a.y,-50,400,200))),b=Math.round(b)+","+Math.round(c)):(typeof a==="string"?(a=a.match(/-?\d+(?:\.\d+)?/g))&&a.length>0&&(b=y(a[0],0,400,0),a.length>1&&(c=y(a[1],-50,400,200))):typeof a==="number"&&(c=y(a,-50,400,200)),b=Math.round(b)+","+Math.round(c));return b},coerceBooleanValue:function(a,b){return Ne(a,b)},coerceNumberValue:function(a,
b){a=Number(a);return isFinite(a)?Math.round(a):b},coerceStringValue:function(a,b){return typeof a==="string"&&a.length>0?a:b},coerceCfgValue:function(a,b){if(!Object.prototype.hasOwnProperty.call(L,a))return b;var c=L[a];return a==="hp_counter_position"||a==="hp_pulse_text_position"?this.formatPositionValue(b):typeof c==="boolean"?this.coerceBooleanValue(b,c):typeof c==="number"?this.coerceNumberValue(b,c):typeof c==="string"?this.coerceStringValue(b,c):b}};zb.resetDefaults();Wc();var z={eventChannel:"ClientUI_FireOutput",
presetSnapshotMagic:"HP_COLORS_PRESET_SNAPSHOT",presetRequestMagic:"HP_COLORS_PRESET_REQUEST",bulkUpdateMagic:"ANITA_BULK_UPDATE",singleUpdateMagic:"ANITA_UPDATE",bootstrapRequestMagic:"ANITA_REQUEST_BOOTSTRAP",sharedCfgRawKey:"__hpColorsCfgRaw",sharedDurableCfgRawKey:"__hpColorsDurableCfgRaw",sharedBootstrapSeenKey:"__hpColorsBootstrapSeen",sharedFirstPaintProbeKey:"__hpColorsFirstPaintProbe",sharedPresetRequestKey:"__hpColorsPresetRequests",sharedMatchResetKey:"__hpColorsMatchReset",sharedMatchResetAckKey:"__hpColorsMatchResetAck",
getSharedStore:function(){try{if(typeof GameUI!=="undefined"&&GameUI&&GameUI.CustomUIConfig)return GameUI.CustomUIConfig()}catch(a){}return null},parsePayload:function(a){try{return typeof a==="string"?JSON.parse(a):a}catch(b){}return null},shouldInspectPayload:function(a){return typeof a!=="string"||a.indexOf(this.presetSnapshotMagic)!==-1?!0:a.indexOf("ANITA")===-1?!1:a.indexOf("HP Colors")!==-1},acceptsTitle:function(a){return!(!a||a.mod_title!=="HP Colors")},isBulkUpdate:function(a){return!(!a||
a.magic_word!==this.bulkUpdateMagic)},isSingleUpdate:function(a){return!(!a||a.magic_word!==this.singleUpdateMagic)},isPresetSnapshot:function(a){return!(!a||a.magic_word!==this.presetSnapshotMagic)},acceptsPresetSnapshot:function(a){return!(!this.isPresetSnapshot(a)||a.mod_title&&a.mod_title!=="HP Colors")},isBootstrapReplaySource:function(a){return a==="bridge_bootstrap"||a==="ui_resync"||a==="ui_reset"||a==="ui_code_apply"||a==="baked_preset_apply"||a==="core_auto_resync"||a==="ui_refresh_after_apply"},
dispatchPayload:function(a){try{return $.DispatchEvent(this.eventChannel,JSON.stringify(a)),!0}catch(b){}return!1},dispatchBootstrapRequest:function(a){return this.dispatchPayload({magic_word:this.bootstrapRequestMagic,mod_title:"HP Colors",storageNamespace:"hp_colors",reason:String(a||"overlay_request")})},dispatchPresetRequest:function(a){return this.dispatchPayload({magic_word:this.presetRequestMagic,mod_title:"HP Colors",reason:String(a||"overlay_request")})},getPresetRequestState:function(a){if(!a)return null;
try{return a[this.sharedPresetRequestKey]||(a[this.sharedPresetRequestKey]={last:0}),a[this.sharedPresetRequestKey]}catch(b){}return null},readSharedConfigRaw:function(a){var b=this.getSharedStore();if(!b)return"";a=a==="durable_shared"?this.sharedDurableCfgRawKey:this.sharedCfgRawKey;try{return String(b[a]||"")}catch(c){}return""},writeSharedConfigRaw:function(a){var b=this.getSharedStore();if(!b)return!1;try{return b[this.sharedCfgRawKey]=a,!0}catch(c){}return!1},markBootstrapSeen:function(){var a=
this.getSharedStore();if(!a)return!1;try{return a[this.sharedBootstrapSeenKey]="1",!0}catch(b){}return!1},hasBootstrapEvidence:function(a){if(!a)return!1;try{return!!(a[this.sharedBootstrapSeenKey]||a[this.sharedDurableCfgRawKey]||a[this.sharedCfgRawKey])}catch(b){}return!1},getFirstPaintProbeState:function(a){if(!a)return null;try{return a[this.sharedFirstPaintProbeKey]||(a[this.sharedFirstPaintProbeKey]={nextAt:0,waitCount:0}),a[this.sharedFirstPaintProbeKey]}catch(b){}return null},readMatchResetInfo:function(a){if(!a)return null;
try{var b=a[this.sharedMatchResetKey];return b?typeof b==="object"?b:{token:String(b),reason:"legacy"}:null}catch(c){}return null},readMatchResetAck:function(a){if(!a)return null;try{return a[this.sharedMatchResetAckKey]||{}}catch(b){}return null},writeMatchResetAck:function(a,b){if(!a)return!1;try{return a[this.sharedMatchResetAckKey]={token:b,at:Date.now?Date.now():+new Date},!0}catch(c){}return!1},getPresetSnapshotValues:function(a){var b=a&&a.values&&typeof a.values==="object"&&!Array.isArray(a.values)?
a.values:null;if(!b)return null;var c=typeof a.values_raw==="string"?a.values_raw:"";if(!c)try{c=JSON.stringify(b)}catch(f){c=""}a=ie(a&&a.effective_values,!0);try{var d=JSON.stringify(ie(a,!0))}catch(f){d=""}return{values:b,raw:c,effectiveValues:a,effectiveRaw:d}}},La=!1,Qb=!1,ec=0,bc=!1,Za=!1,qb=0,jc=0,Sc=0,aa=!0,ka=0,xa=!0,Xa=0,Dc={resetDecision:function(a){a.action=0;a.delay=.25;a.reason="enemy_paint";a.hp=0;a.shouldPulse=!1;a.pulseFast=!1;a.friendNonEnemy=!1;return a},decide:function(a,b,c,d){d=
this.resetDecision(d||ye);c.now=b;c.isEnemy=!(!a||!a.isEnemy);c.friendNonEnemy=!!(a&&a.isFriendly&&c.friendEnabled);if(c.skipBuildings&&a&&a.isBuilding)return d.action=1,d.reason="enemy_skip_building",d.delay=c.buildingFrames<4?.3:c.buildingFrames<12?.6:1.5,d;if(a&&a.isNeutral)return d.action=2,d.reason="enemy_neutral",d.delay=c.neutralFrames<4?.75:1.5,d;if(!c.isEnemy)return d.action=3,d.friendNonEnemy=c.friendNonEnemy,d.reason=c.friendNonEnemy?"enemy_friend_target":"enemy_not_enemy",d.delay=c.friendNonEnemy?
c.nonEnemyFrames<4?.2:2:c.nonEnemyFrames<4?.4:c.nonEnemyFrames<12?.75:1.5,d;if(c.settingsDirty&&c.settingsHold)return d.action=4,d.reason="enemy_dirty_hold",d.delay=.05,d;if(c.bootstrapWait)return d.action=5,d.reason="enemy_bootstrap_wait",d.delay=c.bootstrapDelay||.05,d;if(!c.presetReady)return d.action=5,d.reason="enemy_preset_wait",d.delay=.05,d;if(c.styleDrift)return d.action=7,d.reason="enemy_style_drift",d.delay=.05,d;if(c.parentWidth<=0)return d.action=6,d.reason="enemy_no_parent_width",d.delay=
c.noParentWidthFrames<4?.18:c.noParentWidthFrames<12?.35:.75,d;a=!(!c.pulseActive||!c.pulseTextEnabled);if(c.barWidth===c.lastBarWidth&&c.parentWidth===c.lastParentWidth&&!a&&!c.wasDirty&&c.colorGeneration===c.panelGeneration)return d.action=7,d.reason="enemy_stable",d.delay=b-c.lastUpdateAt>2E3?1.5:.25,d;b=c.parentWidth>0?c.barWidth/c.parentWidth*100|0:0;d.hp=b;d.shouldPulse=!!(c.pulseEnabled&&b<=c.pulseThreshold);if(Math.abs(b-c.lastHp)<3&&b>c.low&&c.lastHp>c.low&&(!c.pulseTextEnabled||!c.pulseActive&&
!d.shouldPulse)&&!c.wasDirty)return d.action=8,d.reason="enemy_small_delta",d.delay=.25,d;d.action=9;d.reason=d.shouldPulse?"enemy_pulse":"enemy_paint";d.delay=.15;return d}},Ae={shouldWakeSameRaw:function(a){return a?a.watchdogSuppressed?!1:!!(a.panelUnseen||a.loopStopped||a.styleDrift):!0},markWake:function(a){Rd=jb;Sd=a},wakeLoops:function(a){var b=G();this.shouldWakeSameRaw({panelUnseen:Rd!==jb,loopStopped:e.hp_enabled&&!kb[0]||e.hp_friend_enabled&&!kb[1]||e.hp_level_number_visible&&!kb[2],styleDrift:!1,
watchdogSuppressed:!!(Sd&&b-Sd<250&&Rd===jb)})&&(this.markWake(b),xa=aa=!0,Xa=ka=0,Ia=null,Zb(),W(0,.01,a==="match_reset"?"match_reset":"preset_replay_enemy"),W(1,.01,a==="match_reset"?"match_reset":"preset_replay_ally"),W(2,.01,a==="match_reset"?"match_reset":"preset_replay_level"))}},le={schedule:function(a,b){if(!nb(a))return!1;b=Number(b);if(!isFinite(b)||b<0)b=.05;var c=G()+b*1E3;if(kb[a]&&kb[a]<=c)return!1;kb[a]=c;var d=++Cc[a],f=dc;$.Schedule(b,function(){if(d===Cc[a]&&Nb.isActive(f)&&(kb[a]=
0,Bc[a]=!1,nb(a)))if(a===0)a:{T[0]=!0;try{if(e.hp_enabled){var g=G();ne(g);if(Sa.refreshEnemy(g)){var h=Sa.snapshot;if(h.teamId!==bd||h.flags!==Ub)(h.isFriendly||h.isFriendlyBuilding)&&Ub!==null&&Ub&1&&q.clearUltColor(),bd=h.teamId,Ub=h.flags,q.invalidateEnemyVisualCaches(),aa=!0,ka=g,xa=!0,Xa=g,Ia=null;var l=h.isEnemy,m=ye;if(e.hp_skip_buildings&&h.isBuilding){w.skipBuildings=!!e.hp_skip_buildings;w.friendEnabled=!!e.hp_friend_enabled;w.buildingFrames=gb+1;m=Dc.decide(h,g,w,m);ia();q.clearLayerColors();
gb++;hb=0;if(h.isFriendly||h.isFriendlyBuilding)q.setEnemyBarColor("#ffffff"),q.clearUltColor(),q.setTextColor("#ffffff"),q.setBarVisible(!0),e.hp_friend_enabled&&W(1,.01,"friendly_target");else{var lb=Sa.getIgnoredTargetColor(h);q.setEnemyBarColor(lb);q.setUltColor(lb);q.setTextColor("#ffffff");q.setBarVisible(!!e.hp_bg_visible)}vb(db(!1,0,da));D(0,m.delay,m.reason)}else if(!Pe(g,l)){l&&!$a&&(!Qb||g<=ab)&&g-Rc>=1E3&&(Rc=g,Nc());l&&g-ad>=5E3&&(ad=g,q.hasEnemyStyleDrift()&&(q.invalidateEnemyVisualCaches(),
aa=!0,ka=g));var U=0;if(aa){if(g<ka){D(0,.05,"enemy_dirty_hold");break a}Wc();q.setBarVisible(!l||!!e.hp_bg_visible);e.hp_counter_visible?Dd(Ca):Ed(!1);var Bb=-15+y(e.hp_info_health_margin_top,0,100,23)*.65;Math.abs(Bb)<.5&&(Bb=0);var Ua=Math.round(Bb*10)/10;Math.abs(Ua-Math.round(Ua))<.01&&(Ua=Math.round(Ua));var J=Ua+"%";oa&&oa.IsValid()||!v||!v.IsValid()||(oa=v.FindChildTraverse("InfoHealthContainer"));if(oa&&oa.style&&fd!==J)try{fd=oa.style.marginTop=J}catch(Va){fd=null}za&&za.IsValid()||!v||
!v.IsValid()||(za=v.FindChildTraverse("UnitHealthbarContainer"));var fa=qd||Math.round(y(e.hp_healthbar_height,0,230,130));J=fa+"px";za&&za.style&&Ud!==J&&(Ud=za.style.height=J);if(A&&A.style){var Ec=Math.min(75,Math.round(fa*75/230))+"px";Vd!=="52%"&&(Vd=A.style.height="52%");Wd!==Ec&&(Wd=A.style.fontSize=Ec)}ad=G();ba=ca=-1;aa=!1;ka=0;U=1}fa=!!U;!fa&&l&&g>=Xd&&(Xd=g+(gd>=8?950:gd>=3?700:350),q.hasEnemyBarStyleDrift()?(q.resetStyleDriftBackoff(),q.invalidateEnemyVisualCaches(),ba=ca=-1,fa=!0):gd++);
if(h.isNeutral)w.neutralFrames=1,Dc.decide(h,g,w,m),ia(),q.setBarVisible(!0),vb(db(!1,0,da)),q.setEnemyBarColor("#5BEFB5"),q.setTextColor("#ffffff"),hd=g,D(0,1.5,"enemy_neutral");else if(h.flags&1)if(gb=hb=0,La||Qb||$a||e.hp_team_colors||E(e.hp_color_high)!==E(L.hp_color_high)){var sa=h.barWidth,F=h.parentWidth;w.skipBuildings=!!e.hp_skip_buildings;w.friendEnabled=!!e.hp_friend_enabled;w.settingsDirty=!!aa;w.settingsHold=g<ka;w.presetReady=!0;w.bootstrapWait=!1;w.styleDrift=!1;w.barWidth=sa;w.parentWidth=
F;w.lastBarWidth=ca;w.lastParentWidth=Ja;w.lastUpdateAt=hd;w.low=k;w.lastHp=ba;w.pulseActive=!!ja;w.pulseTextEnabled=!!e.hp_pulse_text_enabled;w.pulseEnabled=!!e.hp_pulse_enabled;w.pulseThreshold=V;w.wasDirty=!!fa;w.colorGeneration=pb;w.panelGeneration=jb;w.noParentWidthFrames=qa+(F<=0?1:0);m=Dc.decide(h,g,w,m);var Fc=!(!ja||!e.hp_pulse_text_enabled);if(sa!==ca||F!==Ja||Fc||fa||pb!==jb)if(pa=0,ca=sa,Ja=F,hd=g,F<=0)qa++,q.setEnemyBarColor(Ob()),vb(db(!1,0,da)),D(0,m.delay,m.reason);else{qa=0;l=sa/
F*100|0;sa=V;var Wb=!!(e.hp_pulse_enabled&&l<=sa);sa=ba;l===Tb?ib++:(ib=0,Tb=l);ba=l;var Gc=!!e.hp_counter_visible,Xb=e.hp_counter_format|0;Fc="";if((fa=!!A)&&Gc&&Xb!==1)try{Fc=A.text||A.GetAttributeString("text","")||""}catch(Va){Fc="",ra=null}Gc=!!(Gc&&ma&&ya);U=m=Ec=0;Gc&&Xb!==1&&(Ec=ma.actuallayoutwidth||0,m=F,U=h.totalParentWidth);var Be=Kc.enemy(Wb&&!(l<=k&&la&&g-la<900&&(sa<0||sa<=k&&l>sa)),g,ed),Ea=Ue.enemy(l,Be,fa,Fc,Gc,Ec,m,da,U);if(Ea.hasPipVisible&&A&&A.style)try{ra!==Ea.pipVisible&&(ra=
A.style.visibility=Ea.pipVisible)}catch(Va){ra=null}Ea.hasPipVisible&&q.applyPipVisibility(Ea.pipVisible);Ea.counterAction===1?q.applyHpReadout(Ea.current,Ea.max,Ea.lowMode):Ea.counterAction===2&&q.setHpReadoutVisible(!1);var Ce=td(Be);var ta=Ve.enemy(l,sa,g,Wb,da);ta.clearPulse&&ia();ta.hasBarVisible&&q.setBarVisible(ta.barVisible);q.setEnemyBarColor(ta.barColor);q.setLayerColors(ta.healColor,ta.deltaColor,ta.bulletShieldColor);q.setUltColor(ta.ultColor);q.setTextColor(ta.textColor);var De=ta.nextDelay;
if(ta.stopAfterApply){D(0,De,"enemy_warmup");var id=-1}else id=De;id<0||(vb(db(!!e.hp_kill_zone_enabled,F,da)),pb=jb,Ce&&(id=.1),D(0,id,Ce?"enemy_pulse":"enemy_paint"))}else pa++,D(0,m.delay,m.reason)}else q.setEnemyBarColor("#E16161"),q.setUltColor("#E16161"),q.setTextColor("#ffffff"),w.presetReady=!1,m=Dc.decide(h,g,w,m),D(0,m.delay,m.reason);else hb++,gb=0,w.friendEnabled=!!e.hp_friend_enabled,w.nonEnemyFrames=hb,m=Dc.decide(h,g,w,m),q.setBarVisible(!0),vb(db(!1,0,da)),hd=g,D(0,m.delay,m.reason)}}else D(0,
.15,"enemy_probe_missing_bar")}else ue(),T[0]=!1}catch(Va){D(0,.5,"enemy_error")}}else if(a===1)a:{T[1]=!0;try{if(e.hp_friend_enabled){var Ee=G();ne(Ee);if(!ea||!ea.IsValid())if(ob(K,!1),Da=ea=K=null,ea=Pc(),!ea){dd++;D(1,dd>75?3:.2,"ally_missing_bar");break a}dd=0;if(ea.GetParent){var Fe=ea.GetParent();Da!==Fe&&(Da=Fe,oc=pc=qc=Ab=Y=Ba=Aa=null)}t(Aa)||(Aa=Vc(Da,"unit_healthbar_healing"));t(Ba)||(Ba=Vc(Da,"unit_healthbar_delta"));t(Y)||(Y=Vc(Da,"unit_healthbar_bullet_shield"));t(Ab)||(Ab=Vc(Da,"unit_healthbar_tech_shield"));
if(xa){if(Ee<Xa){D(1,.05,"ally_dirty_hold");break a}xa=!1;ob(K,!1)}var Yd=re(ea);g=Td;h=ea;F=Da;g=xe(g||Td);g.panel=h;g.parent=F;g.teamId=Yd>>Bd&3;g.confirmed=!(!(Yd&1)||Yd&4);g.confirmed&&(g.barWidth=h&&h.actuallayoutwidth!==void 0?h.actuallayoutwidth|0:0,U=F&&F.actuallayoutwidth!==void 0?F.actuallayoutwidth|0:0,h=0,Y&&Y.actuallayoutwidth!==void 0&&(h+=Y.actuallayoutwidth|0),Ab&&Ab.actuallayoutwidth!==void 0&&(h+=Ab.actuallayoutwidth|0),g.parentWidth=U>0?Math.max(g.barWidth,U-h):0,g.hp=g.parentWidth>
0?g.barWidth/g.parentWidth*100|0:0);m=g;if(m.confirmed){J=m.barWidth;var Zd=m.parentWidth;if(Zd<=0)Rb++,D(1,Rb<4?.2:Rb<12?.4:.8,"ally_no_parent_width");else if(Rb=0,J!==mc||Zd!==lc||Ib){ub=0;mc=J;lc=Zd;var ua=We.ally(m,ze);if(Ha!==ua.washColor&&m.panel)try{Ha=m.panel.style.washColor=ua.washColor,kc=!0,K=m.panel}catch(Va){Ha=null}q.setUltColor(ua.washColor);if(qc!==ua.healColor&&Aa&&Aa.style)try{qc=Aa.style.washColor=ua.healColor}catch(Va){qc=null}if(pc!==ua.deltaColor&&Ba&&Ba.style)try{pc=Ba.style.washColor=
ua.deltaColor}catch(Va){pc=null}if(oc!==ua.bulletShieldColor&&Y&&Y.style)try{oc=Y.style.backgroundColor=ua.bulletShieldColor}catch(Va){oc=null}Jc(m.panel,ua.inPulse);D(1,ua.nextDelay,"ally_paint")}else ub++,D(1,Te[Math.min(Math.floor(ub/3),4)],"ally_stable")}else{xe(Td);if(kc||K)ob(K,!1),K=null;Rb=ub=0;D(1,1.5,"ally_unconfirmed")}}else ob(K,!0),K=null,T[1]=!1}catch(Va){D(1,.5,"ally_error")}}else if(e.hp_level_number_visible){T[2]=!0;g=Xe;g.label=null;g.container=null;g.wrapper=null;g.level=0;g.ready=
!1;Ta&&Ta.IsValid()||(Ta=bb.FindChildTraverse("unit_level_label"));Z&&Z.IsValid()||(Z=bb.FindChildTraverse("LevelContainer"));if(Z&&(!S||!S.IsValid()))for(h=Z;h;){if(h.BHasClass&&h.BHasClass("enemy")){S=h;break}if(!h.GetParent)break;h=h.GetParent()}g.label=Ta;g.container=Z;g.wrapper=S;g.ready=!!(Ta&&Z&&S);if(g.ready){h="";try{h=Ta.text||Ta.GetAttributeString("text","")||""}catch(Va){h=""}if(h&&h.charCodeAt(0)!==123){for(Wb=F=0;Wb<h.length;Wb++)Xb=h.charCodeAt(Wb)-48,Xb>=0&&Xb<=9&&(F=F*10+Xb);g.level=
F}}h=Ye.level(g,Ze);if(F=g.wrapper)if(h.visible&&Ia!==!0&&(F.AddClass(we),Ia=!0),h.changed){cd=g.level;for(g=0;g<4;g++)F.RemoveClass(zc[g].cls);h.tierClass&&F.AddClass(h.tierClass);g=!0}else g=!1;else g=!1;Vb=g?0:Vb+1;D(2,Vb>10?5:.5,Vb>10?"level_backoff":"level_poll")}else ve(),T[2]=!1});return!0},requestKick:function(a,b){nb(a)&&!Bc[a]&&(Bc[a]=!0,this.schedule(a,b===void 0?.01:b)||(Bc[a]=!1))}},$d="",cc=0,Rc=0,ab=0,$a=!1,ad=0,Xd=0,gd=0,Ma=null,Ya="",hc=0,Mc="",xd=0,$b={applySnapshotValues:function(a,
b){a=zb.applyBaseValues(a);if(!a.count)return!1;a.resolvedChanged&&ud();a=G();Qb=!0;b==="durable_shared"?ac(a,!0,!0):(ab=a+(b==="shared"?15E3:6E3),b!=="shared"&&yd(),ac(a,!1,!0));return!0},requestSnapshot:function(a){var b=G(),c=z.getPresetRequestState(z.getSharedStore());if(c){if(c.last&&b-c.last<120)return;c.last=b}z.dispatchPresetRequest(a)},handlePayload:function(a){a=z.getPresetSnapshotValues(a);if(!a)return!1;if(a.raw&&a.raw===Ya&&a.effectiveRaw===$d&&La)return Ae.wakeLoops("preset_same_raw"),
!0;var b=zb.applyBaseValues(a.values),c=zb.replaceConditionalValues(a.effectiveValues);a.raw&&(Ya=a.raw);$d=a.effectiveRaw;(b.count&&b.resolvedChanged||c.changed||c.resolvedChanged)&&ud();ac(G(),!1,!0);return!0},resetForMatch:function(){zb.replaceConditionalValues({});Wc();Sa.clearPanels();Sa.resetProbeState();Qc=tb=ic=jd=0;Sa.resetEnemyScanCache();Tc=null;nc=Uc=0;q.invalidateEnemyVisualCaches();ia();Jc(K,!1);K=null;kc=!1;Tb=ba=Ja=ca=-1;ib=0;lc=mc=-1;dd=ub=0;pb=-1;jb++;bd=Ub=null;vc="";Lb=null;Mb=
0;Ca=!1;S=Z=Ta=mb=null;cd=-1;Ia=null;Vb=0;bc=Qb=La=!1;qb+=1;Za=!1;Rc=cc=Sc=jc=ec=0;$a=!1;ab=0;Ya="";aa=!0;$d="";ka=0;xa=!0;Xa=0;q.resetStyleDriftBackoff();Zb();Ae.wakeLoops("match_reset");this.requestSnapshot("match_reset")}};Qd=$.RegisterForUnhandledEvent(z.eventChannel,function(a){if(Nb.isActive()&&z.shouldInspectPayload(a)){var b=z.parsePayload(a);if(z.acceptsPresetSnapshot(b))$b.handlePayload(b);else if(z.acceptsTitle(b)){a=G();a:{var c=z.isBulkUpdate(b),d=z.isSingleUpdate(b);if(c||d){var f=z.isBootstrapReplaySource(String(b.update_source||
"")),g=f||!!b.force_emit,h=c?b.values||{}:null,l=d?b.setting_id:"",m=!1,lb=!1,U=!1,Bb=!1,Ua=!1;if(c)for(var J in h){if(Object.prototype.hasOwnProperty.call(h,J)&&Object.prototype.hasOwnProperty.call(L,J)&&(J!=="hp_counter_position"||b.update_source!=="hp_counter_autoposition")){var fa=zb.applyBaseValue(J,h[J]);fa&1&&(lb=!0);fa&2&&(m=!0,J.indexOf("hp_friend_")!==0&&(U=!0),je(J)&&(Bb=!0),ke(J)&&(Ua=!0))}}else if(Object.prototype.hasOwnProperty.call(L,l)){if(l==="hp_counter_position"&&b.update_source===
"hp_counter_autoposition")break a;J=zb.applyBaseValue(l,b.value);lb=!!(J&1);if(m=!!(J&2))l.indexOf("hp_friend_")!==0&&(U=!0),je(l)&&(Bb=!0),ke(l)&&(Ua=!0)}if(m){U&&(aa=!0,ka=a+(f?240:80));Bb&&(e.hp_friend_enabled?(xa=!0,Xa=f?G()+240:0,ob(K,!1),W(1,.01,"preset_apply")):(xa=!1,Xa=0));Ua&&(aa=!0,ka=0,Fa=Gb=null,ba=ca=-1,W(0,.01,"preset_apply"));yd();if(c||l==="hp_level_number_visible")Ia=null;wd(d?l:void 0);U&&W(0,f?.24:.08);c?(e.hp_pulse_enabled||ia(),ja&&(Eb=null,va=-1,c=G(),td(Kc.enemy(!0,c,ed)))):
l!=="hp_pulse_enabled"||e.hp_pulse_enabled?!ja||l!=="hp_pulse_bpm"&&l!=="hp_pulse_intensity"&&l!=="hp_pulse_text_enabled"&&l!=="hp_pulse_text_scale"||(Eb=null,va=-1,c=G(),td(Kc.enemy(!0,c,ed))):ia();f&&ac(a,!0,!1)}else lb&&yd(),g&&ud(),f&&!La&&ac(a,!1,!1)}}}}});var v=null,p=null,R=null,M=null,A=null,ma=null,ya=null,n=null,X=null,u=null,H=null,I=null,B=null,na=null,C=null,oa=null,za=null,cb=null,Pb=0,sb=0,rb=0,jd=0,ic=0,tb=0,Qc=0,eb=null,fb=null,wb=null,xb=null,yb=null,fd=null,Ud=null,Vd=null,Wd=null,
ra=null,Ge={teamId:0,flags:0,isEnemy:!1,isNeutral:!1,isBuilding:!1,isFriendly:!1,isFriendlyBuilding:!1,barWidth:0,parentWidth:0,totalParentWidth:0},ce={classify:function(a,b,c,d,f){f=f||Ge;var g=this.isFriendlyTarget(d),h=!!(d&2),l=!!(d&4),m=this.isFriendlyBuilding(d,c);f.teamId=c||0;f.flags=d||0;f.isEnemy=this.isEnemyTarget(d,c);f.isNeutral=h;f.isBuilding=l;f.isFriendly=g;f.isFriendlyBuilding=m;f.barWidth=a&&a.actuallayoutwidth!==void 0?a.actuallayoutwidth|0:0;a=b&&b.actuallayoutwidth!==void 0?b.actuallayoutwidth|
0:0;b=0;B&&B.actuallayoutwidth!==void 0&&(b+=B.actuallayoutwidth|0);na&&na.actuallayoutwidth!==void 0&&(b+=na.actuallayoutwidth|0);f.totalParentWidth=a;f.parentWidth=a>0?Math.max(f.barWidth,a-b):0;return f},scanEnemy:function(a){var b=G();if(a===ae&&b-be<$e)return!1;var c=Ad(a,!1);Oa=c>>Bd&3;Hc=c&Cd;Oa&&Hc&8&&(He=Oa);be=b;ae=a;return!0},isFriendlyTarget:function(a){return!!(a&8)},isFriendlyBuilding:function(a,b){b=b||Oa;return!!(a&4&&(a&8||b&&b===He))},isEnemyBuilding:function(a,b){b=b||Oa;return!(!(a&
4)||a&2||!b||this.isFriendlyBuilding(a,b))},isEnemyTarget:function(a,b){return a&2||e.hp_friend_enabled&&this.isFriendlyTarget(a)?!1:a&1?!0:this.isEnemyBuilding(a,b)},getIgnoredTargetColor:function(a,b){return a&1&&!(a&2)?"":this.isEnemyBuilding(a,b)?"#E16161":this.isFriendlyBuilding(a,b)?"#ffffff":a&6?"#5BEFB5":a&8?"#FFEFD7":b===2?"#5B79E6":b===1?"#E7B659":"#E16161"}},Sa={snapshot:Ge,sync:function(){ce.classify(n,X,Oa,Hc,this.snapshot);return this},clearPanels:function(){v=p=R=M=A=ma=ya=n=X=u=H=
I=B=na=C=oa=za=cb=null;return this.sync()},resetProbeState:function(){rb=sb=Pb=0},resetPanelHistory:function(){$c=Fd=Gd=Hd=Id=Jd=Kd=Ld=Md=Nd=Od=null;vc=""},invalidateIfInvalid:function(){if(!Pb&&!n||!(N(v)||N(p)||N(R)||N(M)||N(A)||N(ma)||N(ya)||N(n)||N(X)||N(u)||N(H)||N(I)||N(B)||N(na)||N(C)||N(oa)||N(za)||N(cb)))return!1;this.clearPanels();this.resetProbeState();this.resetPanelHistory();q.invalidateEnemyVisualCaches();xa=aa=!0;Zb();return!0},refreshEnemy:function(a){var b=!1;this.invalidateIfInvalid();
if(t(n))b=this.refreshCurrentRedBar(a,!1);else{if(!jd||a>=jd)jd=(n=Pc())?0:a+150;if(!n)return this.sync(),!1}if(!Pb&&!Oe())return this.sync(),!1;if(n.GetParent){var c=n.GetParent();X!==c&&(X=c)}b||this.refreshCurrentRedBar(a,!1);vd();ce.scanEnemy(n);this.sync();return!0},refreshCurrentCompanionPanels:function(){if(v&&v.FindChildTraverse){var a=v.FindChildTraverse("unit_healthbar_bg");t(a)&&a!==M&&(M=a,fb=eb=null);t(H)||(H=v.FindChildTraverse("unit_healthbar_healing"));t(I)||(I=v.FindChildTraverse("unit_healthbar_delta"));
t(B)||(B=v.FindChildTraverse("unit_healthbar_bullet_shield"));t(na)||(na=v.FindChildTraverse("unit_healthbar_tech_shield"));a=v.FindChildTraverse("unit_ult_ready_icon");t(a)&&a!==u&&(ia(),u=a,Fa=Q=null)}},refreshCurrentRedBar:function(a,b){var c=Qc&&a<=Qc,d=!1;if(b){var f=Pc();this.refreshCurrentCompanionPanels();t(f)&&f!==n&&(d=this.adoptRedBar(f))}else if(!ic||a>=ic)ic=a+(c?180:qa>=12?2500:qa>=4?1800:pa>=8?2500:pa>=3?1800:1200),f=Pc(),this.refreshCurrentCompanionPanels(),t(f)&&f!==n&&(f.GetParent&&
f.GetParent()!==X||!X||!X.Children||tb&&a<tb)&&(d=this.adoptRedBar(f));if(!b){if(tb&&a<tb)return d;tb=a+(c?180:qa>=12?2500:qa>=4?1800:pa>=10?1400:pa>=4?1300:1200)}if(!X||!X.Children)return d;try{var g=X.Children()}catch(l){return!1}a=n;b=this.scoreRedBarCandidate(n,-1);for(c=0;c<g.length;c++)if(f=g[c],t(f)){var h="";try{h=String(f.id||"")}catch(l){h=""}if(h==="unit_healthbar_lagging"){h=this.scoreRedBarCandidate(f,c);if(kd)try{kd.set(f,1)}catch(l){}h>b&&(a=f,b=h)}}return a&&a!==n?this.adoptRedBar(a):
d},scoreRedBarCandidate:function(a,b){if(!t(a))return-1;var c=a===n?100:0;try{(kd?kd.has(a):a===n||a===$c)||(c+=1E3)}catch(g){}var d=0;try{d=Ad(a,!1)}catch(g){d=0}d&=Cd;d&1&&(c+=90);d&8&&(c-=1200);d&2&&(c-=1E3);d&4&&e.hp_skip_buildings&&(c-=400);try{(a.actuallayoutwidth|0)>0&&(c+=20)}catch(g){}try{var f=a.GetParent?a.GetParent():null;f&&(f.actuallayoutwidth|0)>0&&(c+=10)}catch(g){}b>=0&&(c+=Math.min(b,20));return c},resetEnemyScanCache:function(){be=Hc=Oa=0;ae=null},adoptRedBar:function(a){ya=X=(ma=
n=a)&&a.GetParent?a.GetParent():null;this.resetProbeState();this.resetEnemyScanCache();vd();ba=Ja=ca=-1;pa=0;pb=-1;q.resetStyleDriftBackoff();this.sync();return!0},getIgnoredTargetColor:function(a){return ce.getIgnoredTargetColor(a?a.flags:Hc,a?a.teamId:Oa)}},kd=typeof WeakMap==="function"?new WeakMap:null,Oa=0,Hc=0,He=0,be=0,ae=null,$e=500,Bd=4,Cd=15,wa=null,Q=null,Ga=null,Pa=null,Qa=null,Ra=null,Gb=null,Fa=null,Hb=null,de=null,wc=null,xc=null,yc=null,uc=-1,tc=-1,fc=null,Lb=null,Mb=0,Ca=!1,$c=null,
Fd=null,Gd=null,Hd=null,Id=null,Jd=null,Kd=null,Ld=null,Md=null,Nd=null,Od=null,vc="",la=0,jb=0,pb=-1,bd=null,Ub=null,q={setEnemyBarColor:function(a){if(Gb!==a||wa===null)if(Gb=a,(a=E(a))||(a=""),wa!==a&&n)try{wa=n.style.washColor=a}catch(b){wa=null}},clearUltColor:function(){Fa=null;if(!(u&&u.IsValid&&u.IsValid()&&u.style))Q=null;else if(Q!=="")try{Q=u.style.washColor=""}catch(a){Q=null}},setUltColor:function(a){a=e.hp_ult_color_enabled?a:e.hp_ult_color_custom;if(Fa!==a||!Q){Fa=a;a=E(a)||"#E16161";
if(!u||!u.IsValid()){var b=G();if(hc&&b-hc<2E3)return;if((u=bb.FindChildTraverse("unit_ult_ready_icon"))&&u.IsValid())hc=0;else{hc=b;return}}if(u&&u.style&&Q!==a)try{Q=u.style.washColor=a}catch(c){Q=null}}},setTextColor:function(a){if(Hb!==a||!Ga)if(Hb=a,a=E(a),p&&p.style&&Ga!==a)try{Ga=p.style.washColor=a}catch(b){Ga=null}},setLayerColors:function(a,b,c){if(wc!==a||Pa===null)if(wc=a,a=E(a)||"#5fff80",Pa!==a&&H&&H.style)try{Pa=H.style.washColor=a}catch(d){Pa=null}if(xc!==b||Qa===null)if(xc=b,b=E(b)||
"#ffe55b",Qa!==b&&I&&I.style)try{Qa=I.style.washColor=b}catch(d){Qa=null}if(yc!==c||Ra===null)if(yc=c,c=E(c)||"#ffffff",Ra!==c&&B&&B.style)try{Ra=B.style.backgroundColor=c}catch(d){Ra=null}},clearLayerColors:function(){if(H&&H.style)try{H.style.washColor=""}catch(a){}if(I&&I.style)try{I.style.washColor=""}catch(a){}if(B&&B.style)try{B.style.backgroundColor=""}catch(a){}wc=xc=yc=Pa=Qa=Ra=null},setBarVisible:function(a){M&&M.style&&(eb!=="visible"&&(eb=M.style.visibility="visible"),a=a?"1.0":"0.01",
fb!==a&&(fb=M.style.opacity=a))},invalidateEnemyVisualCaches:function(){Sb=Yc=Zc=ee=sc=Xc=eb=fb=wb=xb=yb=fd=Ud=Vd=Wd=ra=Gb=Fa=Hb=de=wc=xc=yc=wa=Q=Ga=Pa=Qa=Ra=null;tc=uc=-1;fc=null;pa=gb=hb=qa=0;this.resetStyleDriftBackoff()},hasEnemyBarStyleDrift:function(){if(n&&n.style&&wa)try{if(E(String(n.style.washColor||""))!==wa)return!0}catch(a){}if(u&&u.style&&Q)try{if(E(String(u.style.washColor||""))!==Q)return!0}catch(a){}return!1},hasEnemyStyleDrift:function(){if(this.hasEnemyBarStyleDrift())return!0;
if(e.hp_counter_visible&&p&&p.style){try{if(wb!==null&&p.style.fontSize!==wb)return!0}catch(a){}try{if(xb!==null&&p.style.height!==xb)return!0}catch(a){}}if(e.hp_counter_visible&&R&&R.style)try{if(yb!==null&&R.style.transform!==yb)return!0}catch(a){}if(H&&H.style&&Pa!==null)try{if(E(String(H.style.washColor||""))!==Pa)return!0}catch(a){}if(I&&I.style&&Qa!==null)try{if(E(String(I.style.washColor||""))!==Qa)return!0}catch(a){}if(B&&B.style&&Ra!==null)try{if(E(String(B.style.backgroundColor||""))!==
Ra)return!0}catch(a){}return!1},setHpReadoutVisible:function(a){Ed(a)},applyHpReadout:function(a,b,c){if(!e.hp_counter_visible)this.setHpReadoutVisible(!1);else if(p&&(a!==uc||b!==tc||!!c!==Ca)){this.setHpReadoutVisible(!0);var d=e.hp_counter_format|0;d=d===1?(b>0?Math.round(a/b*100):0)+"%":d===2?String(a):a+" / "+b;try{p.text!==d&&(p.text=d)}catch(f){try{p.SetAttributeString("text",d)}catch(g){}}c=!!c;d=wb===null||xb===null||R&&R.style&&yb===null;c!==Ca||d?(Ca=c,Dd(Ca)):Ca=c;uc=a;tc=b}},applyPipVisibility:function(a){if(A&&
A.style)try{ra!==a&&(ra=A.style.visibility=a)}catch(b){ra=null}},resetStyleDriftBackoff:function(){Xd=gd=0}},Tc=null,Uc=0,nc=0,Qe=160,Sb=null,Yc=null,Zc=null,ee=null,sc=null,Xc=null,af={hasPipVisible:!1,pipVisible:"",counterAction:0,current:0,max:0,lowMode:!1},Ue={parseMax:function(a){if(a===Lb)return Mb;Lb=a;for(var b=0,c=0,d=0,f=a.indexOf("|"),g=a.lastIndexOf("|"),h=0;h<a.length;h++){var l=a.charCodeAt(h);if(l===124)b++;else if(l===34||l===39)f!==-1&&h<f&&d++,(g===-1||h>g)&&c++}a=e.hp_precise_pips_enabled?
10:100;return Mb=b*(d>0?(d+1)*a:500)+c*a},reset:function(a){a.hasPipVisible=!1;a.pipVisible="";a.counterAction=0;a.current=0;a.max=0;a.lowMode=!1;return a},enemy:function(a,b,c,d,f,g,h,l,m){l=this.reset(l||af);var lb=!!e.hp_counter_visible,U=e.hp_counter_format|0;l.hasPipVisible=!!c;l.pipVisible=e.hp_pip_visible?"visible":"collapse";if(!lb)return l.counterAction=2,l;if(!f)return l;l.counterAction=1;l.lowMode=!!(b&&b.shouldPulse&&b.textEnabled);if(U===1)return l.current=a,l.max=100,l;a=h>0?g/h:0;d=
this.parseMax(d||"");m>h&&h>0&&(d=Math.round(d*h/m));l.max=d;l.current=a>=.97?d:Math.round(d*a);return l}},hd=0,ca=-1,Ja=-1,ba=-1,Tb=-1,ib=0,qa=0,hb=0,gb=0,pa=0,da={hasBarVisible:!1,barVisible:!1,barColor:"",ultColor:"",textColor:"",nextDelay:.15,clearPulse:!1,stopAfterApply:!1,hasPipVisible:!1,pipVisible:"",counterAction:0,counterCurrent:0,counterMax:0,counterLowMode:!1,killMarkerAction:0,killMarkerParentWidth:0,killMarkerX:"",killMarkerWidth:"",killMarkerColor:"",killMarkerSig:""},Ve={reset:function(a){a.hasBarVisible=
!1;a.barVisible=!1;a.barColor="";a.ultColor="";a.textColor="";a.nextDelay=.15;a.clearPulse=!1;a.stopAfterApply=!1;a.healColor="";a.deltaColor="";return a},colorForPulse:function(a,b,c){return e.hp_pulse_color_enabled?(e.hp_pulse_color_mode|0)===1?Na(a,e.hp_pulse_color,y((c-b)/Math.max(1,c),0,1,0)):e.hp_pulse_color:a},enemy:function(a,b,c,d,f){f=this.reset(f||da);var g=k,h=r,l=.15;if(a<=k&&la&&c-la<900&&(b<0||b<=k&&a>b))return a=Ob(),f.clearPulse=!0,f.barColor=a,f.ultColor=a,f.textColor=Oc(100,g,h),
f.nextDelay=.05,f.stopAfterApply=!0,f;f.hasBarVisible=!0;f.barVisible=d&&e.hp_pulse_hide_bar?!1:!!e.hp_bg_visible;a<=g?(b=e.hp_color_low,f.textColor=e.hp_text_color_mode&&e.hp_mode===1?e.hp_text_color_low:Oc(a,g,h)):a<=h?e.hp_mode===1?(b=Na(e.hp_color_low,e.hp_color_mid,(a-g)/x),f.textColor=qe(a,g,h)):(b=e.hp_color_mid,f.textColor=Oc(a,g,h)):(e.hp_mode===1?(b=Na(e.hp_color_mid,Ob(),(a-h)/P),f.textColor=qe(a,g,h)):(b=Ob(),f.textColor=Oc(a,g,h)),ib>=5&&(l=Se[Math.min(Math.floor((ib-5)/5),3)]));f.barColor=
d?this.colorForPulse(b,a,V):b;f.healColor=e.hp_heal_color;f.deltaColor=e.hp_delta_color;f.bulletShieldColor=e.hp_bullet_shield_color;f.ultColor=f.barColor;f.nextDelay=l;return f}},Re={enemy:function(a,b,c){c=c||da;c.killMarkerAction=0;c.killMarkerX="";c.killMarkerWidth="";c.killMarkerColor="";c.killMarkerSig="";c.killMarkerParentWidth=b;if(c.killMarkerMissing&&c.killMarkerCanResolve)return c.killMarkerAction=3,c;if(!c.killMarkerReady)return c;if(!a||!e.hp_kill_zone_enabled||b<=0||c.killMarkerBarHidden)return c.killMarkerAction=
2,c;a=rd;var d=sd,f=Math.round(b*a/100-d/2);f<0&&(f=0);f>b-d&&(f=Math.max(0,b-d));f+="px";var g=d+"px";de!==Db&&(de=Db,ee=te);var h=ee;b=b+"|"+a+"|"+d+"|"+Db+"|"+h+"|"+eb+"|"+fb;if(Xc===b&&Sb==="visible"&&Yc===f&&Zc===g&&sc===h)return c;c.killMarkerAction=1;c.killMarkerX=f;c.killMarkerWidth=g;c.killMarkerColor=h;c.killMarkerSig=b;return c}},We={ally:function(a,b){b=b||ze;b.washColor="";b.inPulse=!1;b.healColor="";b.deltaColor="";b.bulletShieldColor="";b.nextDelay=.35;var c=a.hp,d=k,f=r;a=e.hp_team_colors&&
a.teamId?a.teamId===2?"#6485FC":"#FFC961":e.hp_friend_color_high;b.inPulse=!!(e.hp_friend_pulse_enabled&&c<=ha);b.inPulse&&(b.nextDelay=.15);a=b.inPulse&&e.hp_friend_pulse_color_enabled?e.hp_friend_pulse_color:e.hp_mode===1?c<=d?e.hp_friend_color_low:c<=f?Na(e.hp_friend_color_low,e.hp_friend_color_mid,(c-d)/Math.max(1,f-d)):Na(e.hp_friend_color_mid,a,(c-f)/Math.max(1,100-f)):c<=d?e.hp_friend_color_low:c<=f?e.hp_friend_color_mid:a;b.washColor=E(a);b.healColor=E(e.hp_friend_heal_color);b.deltaColor=
E(e.hp_friend_delta_color);b.bulletShieldColor=E(e.hp_friend_bullet_shield_color);return b}},Ye={level:function(a,b){b.visible=!1;b.tierClass="";b.changed=!1;if(!a.ready)return b;b.visible=!0;a=a.level;if(!a||a===cd)return b;b.changed=!0;for(var c=zc.length-1;c>=0;c--)if(a>=zc[c].min){b.tierClass=zc[c].cls;break}return b}},zc=[{min:11,cls:"level_tier2"},{min:19,cls:"level_tier3"},{min:27,cls:"level_tier4"},{min:35,cls:"level_tier5"}],we="level_number_visible",Ta=null,Z=null,S=null,cd=-1,Ia=null,Xe=
{label:null,container:null,wrapper:null,level:0,ready:!1},Ze={visible:!1,tierClass:"",changed:!1},Vb=0;Nc();wd();zd(0,"overlay_startup")})();
