var qb=typeof Object.defineProperties=="function"?Object.defineProperty:function(g,p,u){if(g==Array.prototype||g==Object.prototype)return g;g[p]=u.value;return g};function hc(g){g=["object"==typeof globalThis&&globalThis,g,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var p=0;p<g.length;++p){var u=g[p];if(u&&u.Math==Math)return u}throw Error("Cannot find global object");}var Qc=hc(this),Rc="Int8 Uint8 Uint8Clamped Int16 Uint16 Int32 Uint32 Float32 Float64".split(" ");
Qc.BigInt64Array&&(Rc.push("BigInt64"),Rc.push("BigUint64"));function td(g,p){if(p)for(var u=0;u<Rc.length;u++)ud(Rc[u]+"Array.prototype."+g,p)}function Ud(g,p){p&&ud(g,p)}function ud(g,p){var u=Qc;g=g.split(".");for(var L=0;L<g.length-1;L++){var pa=g[L];if(!(pa in u))return;u=u[pa]}g=g[g.length-1];L=u[g];p=p(L);p!=L&&p!=null&&qb(u,g,{configurable:!0,writable:!0,value:p})}
Ud("Math.trunc",function(g){return g?g:function(p){p=Number(p);if(isNaN(p)||p===Infinity||p===-Infinity||p===0)return p;var u=Math.floor(Math.abs(p));return p<0?-u:u}});function Vd(g){g=Math.trunc(g)||0;g<0&&(g+=this.length);if(!(g<0||g>=this.length))return this[g]}Ud("Array.prototype.at",function(g){return g?g:Vd});td("at",function(g){return g?g:Vd});Ud("String.prototype.at",function(g){return g?g:Vd});function Wd(g){var p=0;return function(){return p<g.length?{done:!1,value:g[p++]}:{done:!0}}}
Ud("Symbol",function(g){function p(qa){if(this instanceof p)throw new TypeError("Symbol is not a constructor");return new u(L+(qa||"")+"_"+pa++,qa)}function u(qa,ic){this.i=qa;qb(this,"description",{configurable:!0,writable:!0,value:ic})}if(g)return g;u.prototype.toString=function(){return this.i};var L="jscomp_symbol_"+(Math.random()*1E9>>>0)+"_",pa=0;return p});
Ud("Symbol.iterator",function(g){if(g)return g;g=Symbol("Symbol.iterator");qb(Array.prototype,g,{configurable:!0,writable:!0,value:function(){return Xd(Wd(this))}});return g});function Xd(g){g={next:g};g[Symbol.iterator]=function(){return this};return g}function Yd(g,p){g instanceof String&&(g+="");var u=0,L=!1,pa={next:function(){if(!L&&u<g.length){var qa=u++;return{value:p(qa,g[qa]),done:!1}}L=!0;return{done:!0,value:void 0}}};pa[Symbol.iterator]=function(){return pa};return pa}
Ud("Array.prototype.values",function(g){return g?g:function(){return Yd(this,function(p,u){return u})}});
(function(){function g(){if(ca||rb!==null||!(ra<0)||$a!==null){var a=ra>=0?Gb[ra]:"";ca=0;rb=null;ra=-1;sb=Ia=tb=sa=R=wa=$a=null;for(var b=[h,k,q],c=0;c<b.length;c++){var f=b[c];if(f)try{f.RemoveClass("low_hp_pulsing"),a&&f.RemoveClass(a),f.style&&(f.style.animationDuration="",f.style.brightness="")}catch(e){}}}}function p(a,b,c){c=c||jc;c.shouldPulse=!1;c.start=!1;c.stop=!1;c.duration="";c.intensityIndex=-1;c.textEnabled=!1;c.textBrightness="";c.resetText=!1;c.fastSchedule=!1;if(!a)return c.stop=
!!ca,c;c.shouldPulse=!0;c.start=!ca;a=v(d.hp_pulse_bpm,30,300,75);c.duration=(60/a).toFixed(3)+"s";c.intensityIndex=v(d.hp_pulse_intensity,0,2,1)|0;if(!k||!k.style)return c;if(!d.hp_pulse_text_enabled)return c.resetText=!0,c;a=Math.max(1,6E4/a);b=b%a/a;a=c.intensityIndex;var f=a===2?.55:a===0?.85:.65;c.textEnabled=!0;c.textBrightness=(f+((a===2?2:a===0?1.15:1.5)-f)*(b<.5?b*2:(1-b)*2)).toFixed(2);c.fastSchedule=!0;return c}function u(a){if(a.stop)return g(),!1;if(!a.shouldPulse)return!1;if(!ca){ca=
1;sa=R=wa=null;try{h&&h.AddClass("low_hp_pulsing")}catch(f){}try{q&&q.AddClass("low_hp_pulsing")}catch(f){}}rb!==a.duration&&(rb=a.duration,h&&h.IsValid&&h.IsValid()&&(h.style.animationDuration=a.duration),q&&q.IsValid&&q.IsValid()&&(q.style.animationDuration=a.duration));if(ra!==a.intensityIndex){var b=ra>=0?Gb[ra]:"",c=Gb[a.intensityIndex];ra=a.intensityIndex;if(b){try{h&&h.IsValid&&h.IsValid()&&h.RemoveClass(b)}catch(f){}try{q&&q.IsValid&&q.IsValid()&&q.RemoveClass(b)}catch(f){}}if(c){try{h&&h.IsValid&&
h.IsValid()&&h.AddClass(c)}catch(f){}try{q&&q.IsValid&&q.IsValid()&&q.AddClass(c)}catch(f){}}}if(a.resetText){try{k&&k.style&&(k.style.animationDuration="",k.style.brightness=""),$a=null}catch(f){}return!1}if(!a.textEnabled||!k||!k.style)return!1;if($a!==a.textBrightness)try{$a=k.style.brightness=a.textBrightness}catch(f){$a=null}return a.fastSchedule}function L(a,b){var c=Hb>=0?Gb[Hb]:"";if(!b){if(Ib=0,Hb=-1,xa=null,a=a||H)try{a.RemoveClass("low_hp_pulsing"),c&&a.RemoveClass(c),a.style&&(a.style.animationDuration=
"",a.style.brightness="")}catch(f){}}else if(!Ib){Ib=1;Hb=-1;xa=null;try{a&&a.AddClass("low_hp_pulsing")}catch(f){}Hb=c=v(d.hp_friend_pulse_intensity,0,2,1)|0;if(c=Gb[c])try{a.AddClass(c)}catch(f){}c=v(d.hp_friend_pulse_bpm,30,300,75);try{a&&(a.style.animationDuration=(60/c).toFixed(3)+"s")}catch(f){}}}function pa(a,b){if(a===!0||a===!1)return a;if(a===1||a==="1")return!0;if(a===0||a==="0")return!1;if(typeof a==="string"){a=a.toLowerCase();if(a==="true")return!0;if(a==="false")return!1}return!!b}
function qa(a){return a==="hp_low_threshold"||a==="hp_high_threshold"||a==="hp_mode"||a==="hp_friend_color_low"||a==="hp_friend_color_mid"||a==="hp_friend_color_high"||a==="hp_friend_pulse_enabled"||a==="hp_friend_pulse_threshold"||a==="hp_friend_pulse_bpm"||a==="hp_friend_pulse_intensity"||a==="hp_friend_pulse_color_enabled"||a==="hp_friend_pulse_color"}function ic(a){return a==="hp_pulse_color_enabled"||a==="hp_pulse_color"||a==="hp_pulse_color_mode"}function kc(a){return a===0?!!d.hp_enabled:a===
1?!!d.hp_friend_enabled:!!d.hp_level_number_visible}function U(a,b){kc(a)&&!lc[a]&&(lc[a]=!0,B(a,b===void 0?.01:b)||(lc[a]=!1))}function B(a,b){if(!kc(a))return!1;b=Number(b);if(!isFinite(b)||b<0)b=.05;var c=I()+b*1E3;if(mc[a]&&mc[a]<=c)return!1;mc[a]=c;var f=++vd[a];$.Schedule(b,function(){if(f===vd[a]&&(mc[a]=0,lc[a]=!1,kc(a)))if(a===0)a:{P[0]=!0;try{if(d.hp_enabled){var e=I();wd(e);if(ub.refreshEnemy(e)){var t=ub.snapshot,F=t.teamId+":"+t.flags;F!==nc&&(nc=F,r.invalidateEnemyVisualCaches(),da=
!0,ya=e,ta=!0,Ja=e,Ka=null);var y=t.isEnemy;if(d.hp_skip_buildings&&t.isBuilding){g();za++;Aa=0;if(t.isFriendly||t.isFriendlyBuilding)r.setBarColor("#ffffff"),r.clearUltIconColor(),r.setTextColor("#ffffff"),r.setBarVisible(!0),d.hp_friend_enabled&&U(1);else{var ea=ub.getIgnoredTargetColor(t);r.setBarColor(ea);r.setUltColor(ea);r.setTextColor("#ffffff");r.setBarVisible(!!d.hp_bg_visible)}ab(La(!1,0,V));B(0,za<4?.3:za<12?.6:1.5)}else if(!Zd(e,y)){y&&!Ma&&(!vb||e<=Na)&&e-oc>=1E3&&(oc=e,wb());y&&e-pc>=
5E3&&(pc=e,r.hasEnemyStyleDrift()&&(r.invalidateEnemyVisualCaches(),da=!0,ya=e));var m=0;if(da){if(e<ya){B(0,.05);break a}Sc();r.setBarVisible(!y||!!d.hp_bg_visible);d.hp_counter_visible?Tc(Ba):Jb(!1);var bb=-15+v(d.hp_info_health_margin_top,0,100,23)*.65;Math.abs(bb)<.5&&(bb=0);var Ca=Math.round(bb*10)/10;Math.abs(Ca-Math.round(Ca))<.01&&(Ca=Math.round(Ca));var x=Ca+"%";fa&&fa.IsValid()||!z||!z.IsValid()||(fa=z.FindChildTraverse("InfoHealthContainer"));if(fa&&fa.style&&qc!==x)try{qc=fa.style.marginTop=
x}catch(cb){qc=null}ua&&ua.IsValid()||!z||!z.IsValid()||(ua=z.FindChildTraverse("UnitHealthbarContainer"));var M=l.healthbarHeight||Math.round(v(d.hp_healthbar_height,0,230,130));x=M+"px";ua&&ua.style&&Uc!==x&&(Uc=ua.style.height=x);if(D&&D.style){var Kb=Math.min(75,Math.round(M*75/230))+"px";Vc!=="52%"&&(Vc=D.style.height="52%");Wc!==Kb&&(Wc=D.style.fontSize=Kb)}pc=I();S=ha=-1;da=!1;ya=0;m=1}x=!!m;!x&&y&&e>=Xc&&(Xc=e+(rc>=8?950:rc>=3?700:350),r.hasEnemyBarStyleDrift()?(r.resetStyleDriftBackoff(),
r.invalidateEnemyVisualCaches(),S=ha=-1,x=!0):rc++);if(t.isNeutral)g(),r.setBarVisible(!0),ab(La(!1,0,V)),r.setBarColor("#5BEFB5"),r.setTextColor("#ffffff"),sc=e,B(0,1.5);else if(t.flags&1)if(za=Aa=0,ia||vb||Ma||d.hp_team_colors||ja(d.hp_color_high)!==ja(W.hp_color_high)){var xb=t.barWidth,n=t.parentWidth;if(xb!==ha||n!==Oa||ca||x||yb!==tc)if(ka=0,ha=xb,Oa=n,sc=e,n<=0)X++,r.setBarColor(zb()),ab(La(!1,0,V)),B(0,X<4?.18:X<12?.35:.75);else{X=0;m=xb/n*100|0;var Da=l.low,Ab=l.pulseThreshold,G=!!(d.hp_pulse_enabled&&
m<=Ab);if(Math.abs(m-S)<3&&m>Da&&S>Da&&!ca&&!G&&!x)B(0,.25);else{Da=S;m===Bb?Pa++:(Pa=0,Bb=m);S=m;var Qa=!!d.hp_counter_visible,N=d.hp_counter_format|0;x="";if((Ab=!!D)&&Qa&&N!==1)try{x=D.text||D.GetAttributeString("text","")||""}catch(cb){x="",Ra=null}Qa=!!(Qa&&T&&Y);var db=0,la=0;Qa&&N!==1&&(db=T.actuallayoutwidth||0,la=Y.actuallayoutwidth||0);N=V;N=xd(N||V);var uc=!!d.hp_counter_visible,eb=d.hp_counter_format|0;N.hasPipVisible=!!Ab;N.pipVisible=d.hp_pip_visible?"visible":"collapse";if(!uc)N.counterAction=
2;else if(Qa)if(N.counterAction=1,N.counterLowMode=!!G,eb===1)N.counterCurrent=m,N.counterMax=100;else{uc=la>0?db/la:0;eb=x||"";if(eb!==vc){vc=eb;Ab=Qa=0;var yd=eb.lastIndexOf("|");for(x=0;x<eb.length;x++){var Yc=eb.charCodeAt(x);Yc===124?Qa++:Yc!==34&&Yc!==39||!(yd===-1||x>yd)||Ab++}wc=Qa*500+Ab*100}var Zc=wc;N.counterMax=Zc;N.counterCurrent=uc>=.97?Zc:Math.round(Zc*uc)}var Z=N;if(Z.hasPipVisible&&D&&D.style)try{Ra!==Z.pipVisible&&(Ra=D.style.visibility=Z.pipVisible)}catch(cb){Ra=null}if(Z.counterAction===
1){var A=Z.counterCurrent,Sa=Z.counterMax,$d=Z.counterLowMode;if(!d.hp_counter_visible)Jb(!1);else if(k&&(A!==Lb||Sa!==Mb)){Jb(!0);var zd=d.hp_counter_format|0;var $c=zd===1?(Sa>0?Math.round(A/Sa*100):0)+"%":zd===2?String(A):A+" / "+Sa;try{k.text!==$c&&(k.text=$c)}catch(cb){try{k.SetAttributeString("text",$c)}catch(me){}}Z=!!$d;var ae=fb===null||gb===null||O&&O.style&&hb===null;Z!==Ba||ae?(Ba=Z,Tc(Ba)):Ba=Z;Lb=A;Mb=Sa}}else Z.counterAction===2&&Jb(!1);var be=!!(m<=l.low&&ma&&e-ma<900&&(Da<0||Da<=
l.low&&m>Da)),va=u(p(G&&!be,e,jc));A=V;A=xd(A||V);var Ta=l.low,Ua=l.high,Ad=l.pulseThreshold;Sa=.15;if(m<=l.low&&ma&&e-ma<900&&(Da<0||Da<=l.low&&m>Da)){var Bd=zb();A.clearPulse=!0;A.barColor=Bd;A.ultColor=Bd;A.textColor=xc(100,Ta,Ua);A.nextDelay=.05;A.stopAfterApply=!0}else{A.hasBarVisible=!0;A.barVisible=G&&d.hp_pulse_hide_bar?!1:!!d.hp_bg_visible;if(m<=Ta){var Va=d.hp_color_low;A.textColor=d.hp_text_color_mode&&d.hp_mode===1?d.hp_text_color_low:xc(m,Ta,Ua)}else m<=Ua?d.hp_mode===1?(Va=Ea(d.hp_color_low,
d.hp_color_mid,(m-Ta)/l.denomMid),A.textColor=Cd(m,Ta,Ua)):(Va=d.hp_color_mid,A.textColor=xc(m,Ta,Ua)):(d.hp_mode===1?(Va=Ea(d.hp_color_mid,zb(),(m-Ua)/l.denomHigh),A.textColor=Cd(m,Ta,Ua)):(Va=zb(),A.textColor=xc(m,Ta,Ua)),Pa>=5&&(Sa=ce[Math.min(Math.floor((Pa-5)/5),3)]));G&&d.hp_pulse_color_enabled&&(Va=(d.hp_pulse_color_mode|0)===1?Ea(Va,d.hp_pulse_color,v((Ad-m)/Math.max(1,Ad),0,1,0)):d.hp_pulse_color);A.barColor=Va;A.ultColor=Va;A.nextDelay=Sa}var Wa=A;Wa.clearPulse&&g();Wa.hasBarVisible&&r.setBarVisible(Wa.barVisible);
r.setBarColor(Wa.barColor);r.setUltColor(Wa.ultColor);r.setTextColor(Wa.textColor);var Dd=Wa.nextDelay;if(Wa.stopAfterApply){B(0,Dd);var Xa=-1}else Xa=Dd;Xa<0||(ab(La(!!d.hp_kill_zone_enabled,n,V)),yb=tc,va&&(Xa=.1),B(0,Xa))}}else ka++,B(0,e-sc>2E3?1.5:.25)}else r.setBarColor("#E16161"),r.setUltColor("#E16161"),r.setTextColor("#ffffff"),B(0,.05);else Aa++,za=0,r.setBarVisible(!0),ab(La(!1,0,V)),sc=e,B(0,Aa<4?.4:Aa<12?.75:1.5)}}else B(0,.15)}else Ed(),P[0]=!1}catch(cb){B(0,.5)}}else if(a===1)a:{P[1]=
!0;try{if(d.hp_friend_enabled){var Fd=I();wd(Fd);if(!na||!na.IsValid())if(ib(H,!1),Nb=na=H=null,na=yc(),!na){zc++;B(1,zc>75?3:.2);break a}zc=0;if(na.GetParent){var Gd=na.GetParent();Nb!==Gd&&(Nb=Gd)}if(ta){if(Fd<Ja){B(1,.05);break a}ta=!1;ib(H,!1)}var ad=Hd(na);e=bd;n=na;G=Nb;e=Id(e||bd);e.panel=n;e.parent=G;e.flags=ad;e.confirmed=!(!(ad&1)||ad&4);e.confirmed&&(e.barWidth=n&&n.actuallayoutwidth!==void 0?n.actuallayoutwidth|0:0,e.parentWidth=G&&G.actuallayoutwidth!==void 0?G.actuallayoutwidth|0:0,
e.hp=e.parentWidth>0?e.barWidth/e.parentWidth*100|0:0);m=e;if(m.confirmed){var Jd=m.barWidth,cd=m.parentWidth;if(cd<=0)Cb++,B(1,Cb<4?.2:Cb<12?.4:.8);else if(Cb=0,Jd!==Ob||cd!==Pb||Ib){jb=0;Ob=Jd;Pb=cd;n=(e=Kd)||Kd;n.washColor="";n.inPulse=!1;n.nextDelay=.35;e=n;la=m.hp;db=l.low;var Qb=l.high;e.inPulse=!!(d.hp_friend_pulse_enabled&&la<=l.friendPulseThreshold);e.inPulse&&(e.nextDelay=.15);var de=e.inPulse&&d.hp_friend_pulse_color_enabled?d.hp_friend_pulse_color:d.hp_mode===1?la<=db?d.hp_friend_color_low:
la<=Qb?Ea(d.hp_friend_color_low,d.hp_friend_color_mid,(la-db)/Math.max(1,Qb-db)):Ea(d.hp_friend_color_mid,d.hp_friend_color_high,(la-Qb)/Math.max(1,100-Qb)):la<=db?d.hp_friend_color_low:la<=Qb?d.hp_friend_color_mid:d.hp_friend_color_high;e.washColor=ja(de);x=e;if(xa!==x.washColor&&m.panel)try{xa=m.panel.style.washColor=x.washColor,Rb=!0,H=m.panel}catch(cb){xa=null}L(m.panel,x.inPulse);B(1,x.nextDelay)}else jb++,B(1,ee[Math.min(Math.floor(jb/3),4)])}else{Id(bd);if(Rb||H)ib(H,!1),H=null;Cb=jb=0;B(1,
1.5)}}else ib(H,!0),H=null,P[1]=!1}catch(cb){B(1,.5)}}else if(d.hp_level_number_visible){P[2]=!0;e=fe;e.label=null;e.container=null;e.wrapper=null;e.level=0;e.ready=!1;Ya&&Ya.IsValid()||(Ya=kb.FindChildTraverse("unit_level_label"));aa&&aa.IsValid()||(aa=kb.FindChildTraverse("LevelContainer"));if(aa&&(!Q||!Q.IsValid()))for(n=aa;n;){if(n.BHasClass&&n.BHasClass("enemy")){Q=n;break}if(!n.GetParent)break;n=n.GetParent()}e.label=Ya;e.container=aa;e.wrapper=Q;e.ready=!!(Ya&&aa&&Q);if(e.ready){n="";try{n=
Ya.text||Ya.GetAttributeString("text","")||""}catch(cb){n=""}if(n&&n.charCodeAt(0)!==123){for(va=G=0;va<n.length;va++)Xa=n.charCodeAt(va)-48,Xa>=0&&Xa<=9&&(G=G*10+Xa);e.level=G}}n=ge;n.visible=!1;n.tierClass="";n.changed=!1;if(e.ready&&(n.visible=!0,(G=e.level)&&G!==Ac))for(n.changed=!0,va=3;va>=0;va--)if(G>=he[va]){n.tierClass=dd[va];break}if(G=e.wrapper)if(n.visible&&Ka!==!0&&(G.AddClass(Ld),Ka=!0),n.changed){Ac=e.level;for(e=0;e<4;e++)G.RemoveClass(dd[e]);n.tierClass&&G.AddClass(n.tierClass);e=
!0}else e=!1;else e=!1;Sb=e?0:Sb+1;B(2,Sb>10?5:.5)}else Md(),P[2]=!1});return!0}function Nd(){for(var a=$.GetContextPanel();a&&a.GetParent&&a.GetParent();)a=a.GetParent();return a||null}function wd(a){if(ed&&a<ed)return!1;ed=a+250;var b=C.getSharedStore();if(!b)return!1;var c=C.readMatchResetInfo(b);if(!c)return!1;var f=String(c&&c.token||"");if(!f||f===Bc)return!1;var e=C.readMatchResetAck(b);if(e&&String(e.token||"")===f&&(c=Number(c&&c.at),isFinite(c)&&c>0&&(ma&&ma>c+500||a-c>2E3)))return Bc=f,
!1;Bc=f;ub.clearPanels();ub.resetProbeState();Cc=Tb=Ub=Dc=0;ub.resetEnemyScanCache();Ec=null;Vb=Fc=0;r.invalidateEnemyVisualCaches();g();L(H,!1);H=null;Rb=!1;Bb=S=Oa=ha=-1;Pa=0;Pb=Ob=-1;zc=jb=0;yb=-1;tc++;Wb=nc="";vc=null;wc=0;Ba=!1;Q=aa=Ya=$a=null;Ac=-1;Ka=null;Sb=0;Db=lb=vb=ia=!1;oc=Xb=Gc=Yb=Zb=0;Ma=!1;Na=0;Za="";da=!0;ya=0;ta=!0;Ja=0;r.resetStyleDriftBackoff();$b();fd("match_reset");C.writeMatchResetAck(b,f);return!0}function Od(){var a={},b;for(b in W)Object.prototype.hasOwnProperty.call(W,b)&&
(a[b]=d[b]);try{var c=JSON.stringify(a);c!==Za&&(Za=c,C.writeSharedConfigRaw(c))}catch(f){}}function Pd(a,b){if(!a)return!1;var c=0,f;for(f in a)Object.prototype.hasOwnProperty.call(a,f)&&Object.prototype.hasOwnProperty.call(W,f)&&(d[f]=gd.coerceCfgValue(f,a[f]),c+=1);if(!c)return!1;try{Hc()}catch(e){}try{r.invalidateEnemyVisualCaches()}catch(e){}$b();ta=da=!0;Ja=0;Ic();U(0);U(1);U(2);a=I();vb=!0;b==="durable_shared"?Jc(a,!0,!0):(Na=a+(b==="shared"?15E3:6E3),b!=="shared"&&Od(),Jc(a,!1,!0));return!0}
function Jc(a,b,c){lb=ia=!0;try{var f=Nd();f&&(f.__hpColorsBootstrapAppliedAt=a||I())}catch(e){}b&&(Ma=!0,Na=0);c&&C.markBootstrapSeen()}function Qd(a){var b=C.readSharedConfigRaw(a);if(!b||a==="shared"&&b===Za)return!1;var c=null;try{c=JSON.parse(b)}catch(f){return!1}c=a==="shared"&&c&&typeof c==="object"?c.values||c:c;if(!c||typeof c!=="object"||!Pd(c,a))return!1;a==="shared"&&(Za=b);return!0}function wb(){return!Ma&&(Qd("durable_shared")||Qd("shared"))}function ac(a){var b=I();fd(a||"overlay_request");
if(!(Xb&&b-Xb<400)){if(!Fa)try{var c=Nd();c&&(c.__hpColorsBootstrapRequests||(c.__hpColorsBootstrapRequests={last:0,attempts:0}),Fa=c.__hpColorsBootstrapRequests)}catch(f){}if(Fa){c=Fa.attempts<8?400:3E3;if(Fa.last&&b-Fa.last<c)return;Fa.last=b;Fa.attempts=(Fa.attempts||0)+1}Xb=b;C.dispatchBootstrapRequest(a)}}function bc(){ia||lb||wb()||(Zb>=8?(ac("overlay_slow_retry"),$.Schedule(3,bc)):(Zb+=1,ac(Zb===1?"overlay_startup":"overlay_retry"),$.Schedule(.5,bc)))}function ie(a){if(!(ia||lb||Db)){Db=!0;
try{$.Schedule(.01,function(){Db=!1;ia||lb||wb()||(ac(a||"overlay_retry"),$.Schedule(.5,bc))})}catch(b){if(Db=!1,!(ia||lb||wb())){ac(a||"overlay_retry");try{$.Schedule(.5,bc)}catch(c){}}}}}function Ea(a,b,c){a=a.slice(1);a.length===3&&(a=a[0]+a[0]+a[1]+a[1]+a[2]+a[2]);b=b.slice(1);b.length===3&&(b=b[0]+b[0]+b[1]+b[1]+b[2]+b[2]);a=parseInt(a,16);b=parseInt(b,16);return"#"+(16777216|((a>>16&255)+((b>>16&255)-(a>>16&255))*c|0)<<16|((a>>8&255)+((b>>8&255)-(a>>8&255))*c|0)<<8|(a&255)+((b&255)-(a&255))*
c|0).toString(16).slice(1)}function ja(a){if(typeof a!=="string")return"";var b=a.trim();if(!b)return"";if(b.charAt(0)==="#")return b.length===4?("#"+b.charAt(1)+b.charAt(1)+b.charAt(2)+b.charAt(2)+b.charAt(3)+b.charAt(3)).toLowerCase():b.length>=7?b.slice(0,7).toLowerCase():b;if(a=b.match(/^rgba?\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)/i)){b=+a[1]|0;var c=+a[2]|0;a=+a[3]|0;b<0?b=0:b>255&&(b=255);c<0?c=0:c>255&&(c=255);a<0?a=0:a>255&&(a=255);return"#"+(16777216|b<<16|c<<8|a).toString(16).slice(1)}return b}
function zb(){return d.hp_team_colors?ba===2?"#6485FC":"#FFC961":d.hp_color_high}function xc(a,b,c){return d.hp_text_color_mode?a<=b?d.hp_text_color_low:a<=c?d.hp_text_color_mid:d.hp_text_color_high:a<=b?d.hp_color_low:a<=c?d.hp_color_mid:zb()}function Cd(a,b,c){var f=l.denomMid||Math.max(1,c-b),e=l.denomHigh||Math.max(1,100-c);if(d.hp_text_color_mode)return a<=b?d.hp_text_color_low:a<=c?Ea(d.hp_text_color_low,d.hp_text_color_mid,(a-b)/f):Ea(d.hp_text_color_mid,d.hp_text_color_high,(a-c)/e);if(a<=
b)return d.hp_color_low;if(a<=c)return Ea(d.hp_color_low,d.hp_color_mid,(a-b)/f);a=(a-c)/e;b=zb();return Ea(d.hp_color_mid,b,a)}function w(a){try{return!(!a||a.IsValid&&!a.IsValid())}catch(b){}return!1}function yc(){return kb.FindChildTraverse("unit_healthbar_lagging")}function je(){if(Eb){var a=!d.hp_counter_visible||w(k);if(w(z)&&a&&w(J)&&w(D)&&w(T)&&w(Y)&&w(Ga))return 1;mb=Eb=0}a=I();if(mb&&a<mb)return 0;nb++;w(z)||(z=kb.FindChildTraverse("UnitStatus"));if(!z)return mb=a+(nb<8?150:nb<24?500:1500),
0;w(k)||!d.hp_counter_visible&&cc==="collapse"||(k=z.FindChildTraverse("hp_counter"));d.hp_counter_visible&&!w(O)&&(O=z.FindChildTraverse("hp_counter_anchor"));w(J)||(J=z.FindChildTraverse("unit_healthbar_bg"));w(D)||(D=z.FindChildTraverse("unit_healthbar_pip_label"));w(T)||(T=z.FindChildTraverse("unit_healthbar_lagging"));d.hp_kill_zone_enabled&&!w(E)&&(E=z.FindChildTraverse("hp_kill_zone_marker"));w(q)||(q=z.FindChildTraverse("unit_ult_ready_icon"));w(q)&&(dc=0);w(fa)||(fa=z.FindChildTraverse("InfoHealthContainer"));
w(ua)||(ua=z.FindChildTraverse("UnitHealthbarContainer"));w(Ga)||(Ga=kb.FindChildTraverse("name"));T&&!w(Y)&&(Y=T.GetParent());if(D&&T&&Y)return Eb=1,mb=nb=0,1;mb=a+(nb<8?150:nb<24?500:1500);return 0}function Ha(a){try{return!(!a||!a.IsValid||a.IsValid())}catch(b){}return!1}function $b(){Cc=I()+1600;Tb=Ub=0}function fd(a){var b=I(),c=C.getPresetRequestState(C.getSharedStore());if(c){if(c.last&&b-c.last<120)return;c.last=b}C.dispatchPresetRequest(a)}function Zd(a,b){if(!b||ia||vb||Ma||!ma||a-ma>1800||
d.hp_team_colors||ja(d.hp_color_high)!==ja(W.hp_color_high))return!1;var c=C.getSharedStore();b=C.getFirstPaintProbeState(c);c=C.hasBootstrapEvidence(c);var f=b?b.nextAt||0:Yb;if(!c&&f&&a<f)return!1;if(!f||a>=f){oc=a;if(wb()||!c&&!b)return!1;c=b?(b.waitCount||0)+1:Gc+1;f=c<4?80:c<10?150:250;b?(b.waitCount=c,b.nextAt=a+f):(Gc=c,Yb=a+f);if(c===1||c===5)fd("first_paint_wait"),ac("first_paint_wait")}B(0,Math.max(.05,Math.min(.12,((b?b.nextAt||a+80:Yb)-a)/1E3)));return!0}function hd(a,b){for(var c=0,f=
0,e=0;a&&e<10;){if(a.BHasClass)if(c||(a.BHasClass("team2")?c=2:a.BHasClass("team1")&&(c=1)),b){if(f&1||!a.BHasClass("friend")||(f|=1),f&2||!a.BHasClass("player")||(f|=2),f&4||!a.BHasClass("enemy")||(f|=4),c&&(f&7)===7)break}else if(f&1||!a.BHasClass("enemy")||(f|=1),f&2||!a.BHasClass("team_neutral")&&!a.BHasClass("neutral")||(f|=2),f&4||!d.hp_skip_buildings&&f&1||!(a.BHasClass("building")||a.BHasClass("boss_tier1")||a.BHasClass("boss_tier2")||a.BHasClass("boss_barracks"))||(f|=4),f&8||!a.BHasClass("friend")||
(f|=8),c&&f&15)break;if(!a.GetParent)break;a=a.GetParent();e++}return(c&3)<<Rd|f&Kc}function ib(a,b){Rb=!1;xa=null;Pb=Ob=-1;Cb=jb=0;Ec=null;Vb=Fc=0;L(a,!1);if(b&&a&&a===H&&(b=a&&a.IsValid&&a.IsValid()?Hd(a):0)&&b&1&&!(b&4)&&a.style)try{a.style.washColor="#FFEFD7",xa=ja("#FFEFD7")}catch(c){xa=null}}function Hd(a){var b=I();if(a===Ec&&b-Fc<ke)return Vb;Vb=hd(a,!0)&Kc;Ec=a;Fc=b;return Vb}function v(a,b,c,f){a=Number(a);isFinite(a)||(a=Number(f));isFinite(a)||(a=0);isFinite(b)&&a<b&&(a=b);isFinite(c)&&
a>c&&(a=c);return a}function ec(a){return v(a,0,100,0)|0}function Sc(){var a=ec(d.hp_low_threshold),b=ec(d.hp_high_threshold);b<a&&(b=a);var c=d.hp_kill_zone_width|0;c<1&&(c=1);c>100&&(c=100);var f=v(d.hp_counter_size,72,400,145);l.low=a;l.high=b;l.denomMid=Math.max(1,b-a);l.denomHigh=Math.max(1,100-b);l.pulseThreshold=ec(d.hp_pulse_threshold);l.friendPulseThreshold=ec(d.hp_friend_pulse_threshold);l.counterSize=f;l.pulseTextSize=v(d.hp_pulse_text_scale,72,320,f);l.counterPosition=Sd(d.hp_counter_position,
!0);l.pulseTextPosition=Sd(d.hp_pulse_text_position,!1);l.healthbarHeight=Math.round(v(d.hp_healthbar_height,0,230,130));l.killZoneThreshold=ec(d.hp_kill_zone_threshold);l.killZoneWidth=c;l.killZoneColorRaw=d.hp_kill_zone_color||"#FF2222";l.killZoneColor=ja(l.killZoneColorRaw)}function La(a,b,c){c=c||V;c.killMarkerAction=0;c.killMarkerX="";c.killMarkerWidth="";c.killMarkerColor="";c.killMarkerSig="";c.killMarkerParentWidth=b;if((!E||!w(E))&&a&&d.hp_kill_zone_enabled&&z&&z.FindChildTraverse)return c.killMarkerAction=
3,c;if(!E||!E.style)return c;var f=!J||!J.style||ob!=="visible"||pb!=="1.0";if(!a||!d.hp_kill_zone_enabled||b<=0||f)return c.killMarkerAction=2,c;a=l.killZoneThreshold;f=l.killZoneWidth;var e=Math.round(b*a/100-f/2);e<0&&(e=0);e>b-f&&(e=Math.max(0,b-f));e+="px";var t=f+"px";id!==l.killZoneColorRaw&&(id=l.killZoneColorRaw,jd=l.killZoneColor);var F=jd;b=b+"|"+a+"|"+f+"|"+l.killZoneColorRaw+"|"+F+"|"+ob+"|"+pb;if(Lc===b&&Fb==="visible"&&Mc===e&&Nc===t&&fc===F)return c;c.killMarkerAction=1;c.killMarkerX=
e;c.killMarkerWidth=t;c.killMarkerColor=F;c.killMarkerSig=b;return c}function ab(a){if(a.killMarkerAction===3){try{E=z.FindChildTraverse("hp_kill_zone_marker")}catch(b){}if(!E||!E.style)return;a=La(!0,a.killMarkerParentWidth,a)}if(a.killMarkerAction===2)Lc=null,E&&E.style&&Fb!=="collapse"&&(Fb=E.style.visibility="collapse");else if(a.killMarkerAction===1&&E&&E.style&&(Lc=a.killMarkerSig,Fb!=="visible"&&(Fb=E.style.visibility="visible"),Mc!==a.killMarkerX&&(Mc=E.style.marginLeft=a.killMarkerX),Nc!==
a.killMarkerWidth&&(Nc=E.style.width=a.killMarkerWidth),fc!==a.killMarkerColor))try{fc=E.style.backgroundColor=a.killMarkerColor}catch(b){fc=null}}function Sd(a,b){var c=0,f=200;b=b?-200:0;if(a&&typeof a==="object")return Array.isArray(a)?(a.length>0&&(c=v(a[0],0,400,0)),a.length>1&&(f=v(a[1],b,400,200))):(Object.prototype.hasOwnProperty.call(a,"x")&&(c=v(a.x,0,400,0)),Object.prototype.hasOwnProperty.call(a,"y")&&(f=v(a.y,b,400,200))),{x:c,y:f};if(typeof a==="string"){var e=a.match(/-?\d+(?:\.\d+)?/g);
if(e&&e.length>0)return c=v(e[0],0,400,0),e.length>1&&(f=v(e[1],b,400,200)),{x:c,y:f}}typeof a==="number"&&(f=v(a,b,400,200));return{x:c,y:f}}function Tc(a){if(k&&k.style){a=!!(a&&d.hp_pulse_enabled&&d.hp_pulse_text_enabled);var b=l.counterSize||v(d.hp_counter_size,72,400,145);b=a?l.pulseTextSize||v(d.hp_pulse_text_scale,72,320,b):b;var c=a?l.pulseTextPosition:l.counterPosition,f=v(c.x,0,400,0),e=v(c.y,-50,400,200);c=b+"px";var t="100%";if(a){a=130;try{var F=k.GetParent?k.GetParent():null;F&&F.actuallayoutheight>
0&&(a=F.actuallayoutheight)}catch(y){}t=Math.max(a,Math.round(b*1.85))+"px"}F="translate3d("+Math.round(f)+"px, "+Math.round(Math.max(e-150,-200))+"px, 0px)";fb!==c&&(fb=k.style.fontSize=c);gb!==t&&(gb=k.style.height=t);O&&O.style&&hb!==F&&(hb=O.style.transform=F)}}function Jb(a){if(k&&k.style){var b=a?"visible":"collapse";if(cc!==b)try{cc=k.style.visibility=b}catch(c){cc=null}a||(Mb=Lb=-1,Ba=!1)}}function Hc(){var a="";try{Ga&&(a=Ga.text||Ga.GetAttributeString("text","")||"")}catch(b){a=""}h===Oc&&
K===kd&&Y===ld&&k===md&&J===nd&&E===od&&D===pd?a!==Wb&&(Wb=a,vc=null,wc=0,Bb=S=Oa=ha=-1,ka=za=Aa=X=Pa=0,r.resetStyleDriftBackoff()):(Oc=h,kd=K,ld=Y,md=k,nd=J,od=E,pd=D,Wb=a,tc++,yb=-1,pc=ma=I(),Ma&&(Ma=!1,Na=ma+6E3),r.invalidateEnemyVisualCaches(),g(),Rb=!1,xa=Nb=na=fa=H=null,Pb=Ob=-1,jb=0,Ka=null,Bb=S=Oa=ha=-1,ka=za=Aa=X=Pa=0,Ba=!1,nc="",Db=lb=vb=ia=!1,Gc=Yb=0,Za="",Zb=Xb=0,Na&&Na<ma&&(Na=0),ta=da=!0,Ja=ya=0,$b(),ie("panel_rebind"))}function Ed(){g();if(h&&h.style)try{h.style.washColor=""}catch(a){}if(q&&
q.style)try{q.style.washColor=""}catch(a){}if(k&&k.style)try{k.style.washColor=""}catch(a){}tb=wa=Ia=R=sb=sa=null;ab(La(!1,0,V));J&&J.style&&(ob!=="collapse"&&(ob=J.style.visibility="collapse"),pb!=="0"&&(pb=J.style.opacity="0"));if(k&&k.style){try{k.style.fontSize="",k.style.height="",k.style.washColor=""}catch(a){}tb=wa=gb=fb=null}O&&O.style&&(O.style.transform="",hb=null);Bb=S=Oa=ha=-1;ka=za=Aa=X=Pa=0}function Md(){if(!Q||!Q.IsValid()){aa&&aa.IsValid()||(aa=kb.FindChildTraverse("LevelContainer"));
for(var a=aa;a;){if(a.BHasClass&&a.BHasClass("enemy")){Q=a;break}if(!a.GetParent)break;a=a.GetParent()}}if(Q&&Q.IsValid&&Q.IsValid()){try{Q.RemoveClass(Ld)}catch(b){}for(a=0;a<4;a++)try{Q.RemoveClass(dd[a])}catch(b){}}Ka=!1;Ac=-1;Sb=0}function qd(a,b){kc(a)&&!P[a]&&(P[a]=!0,B(a,b||.05))}function Ic(a){Sc();if(d.hp_enabled)qd(0);else if(a==="hp_enabled"||P[0])Ed(),P[0]=!1;if(d.hp_friend_enabled)qd(1);else if(a==="hp_friend_enabled"||P[1])ib(H,!0),H=null,P[1]=!1;if(d.hp_level_number_visible)qd(2);else if(a===
"hp_level_number_visible"||P[2])Md(),P[2]=!1;d.hp_counter_visible?a==="hp_counter_visible"&&(Mb=Lb=-1,U(0)):Jb(!1);d.hp_pulse_enabled&&d.hp_pulse_text_enabled||((ca||a==="hp_pulse_enabled"||a==="hp_pulse_text_enabled")&&g(),Ba=!1,Tc(!1));!d.hp_friend_pulse_enabled&&Ib&&L(na,!1);if(a==="hp_ult_color_enabled"||a==="hp_ult_color_custom")R=Ia=null,U(0);d.hp_kill_zone_enabled?a==="hp_kill_zone_enabled"&&U(0):ab(La(!1,0,V));if(D&&D.style&&!d.hp_pip_visible&&Ra!=="collapse")try{Ra=D.style.visibility="collapse"}catch(b){Ra=
null}}function xd(a){a.hasBarVisible=!1;a.barVisible=!1;a.barColor="";a.ultColor="";a.textColor="";a.nextDelay=.15;a.clearPulse=!1;a.stopAfterApply=!1;a.hasPipVisible=!1;a.pipVisible="";a.counterAction=0;a.counterCurrent=0;a.counterMax=0;a.counterLowMode=!1;a.killMarkerAction=0;a.killMarkerParentWidth=0;a.killMarkerX="";a.killMarkerWidth="";a.killMarkerColor="";a.killMarkerSig="";return a}function Id(a){a.confirmed=!1;a.panel=null;a.parent=null;a.flags=0;a.barWidth=0;a.parentWidth=0;a.hp=0;return a}
var W={hp_enabled:!0,hp_mode:1,hp_low_threshold:25,hp_high_threshold:65,hp_bg_visible:!0,hp_team_colors:!1,hp_info_health_margin_top:23,hp_healthbar_height:130,hp_color_low:"#E16161",hp_color_mid:"#FF7B00",hp_color_high:"#00FF00",hp_counter_visible:!0,hp_counter_size:145,hp_counter_position:"27,20",hp_text_color_mode:0,hp_text_color_low:"#E16161",hp_text_color_mid:"#FF7B00",hp_text_color_high:"#FFFFFF",hp_pulse_bpm:75,hp_pulse_intensity:1,hp_pulse_enabled:!0,hp_pulse_text_enabled:!1,hp_pulse_text_scale:120,
hp_pulse_text_position:"20,196",hp_pulse_hide_bar:!1,hp_pulse_color_enabled:!1,hp_pulse_color:"#FF2222",hp_pulse_color_mode:0,hp_skip_buildings:!1,hp_pulse_threshold:25,hp_counter_format:0,hp_friend_enabled:!1,hp_friend_pulse_enabled:!1,hp_friend_pulse_bpm:75,hp_friend_pulse_intensity:1,hp_friend_pulse_threshold:25,hp_friend_color_low:"#E16161",hp_friend_color_mid:"#FF7B00",hp_friend_color_high:"#00FF00",hp_friend_pulse_color_enabled:!1,hp_friend_pulse_color:"#FF2222",hp_level_number_visible:!0,hp_pip_visible:!0,
hp_ult_color_enabled:!0,hp_ult_color_custom:"#E16161",hp_kill_zone_enabled:!1,hp_kill_zone_threshold:25,hp_kill_zone_color:"#FF2222",hp_kill_zone_width:3},d={},l={},I=Date.now?Date.now.bind(Date):function(){return+new Date},Gb=["pulse_subtle","","pulse_intense"],ce=[.35,.8,1.5,2.5],ee=[.35,.7,1.4,2,2],P=[!1,!1,!1],lc=[!1,!1,!1],vd=[0,0,0],mc=[0,0,0],ca=0,rb=null,ra=-1,$a=null,na=null,Nb=null,H=null,xa=null,Ob=-1,Pb=-1,jb=0,Rb=!1,Cb=0,Ib=0,Hb=-1,zc=0,bd={confirmed:!1,panel:null,parent:null,flags:0,
barWidth:0,parentWidth:0,hp:0},Kd={washColor:"",inPulse:!1,nextDelay:.35},jc={shouldPulse:!1,start:!1,stop:!1,duration:"",intensityIndex:-1,textEnabled:!1,textBrightness:"",resetText:!1,fastSchedule:!1},gd={formatPositionValue:function(a){var b=0;var c=200;a&&typeof a==="object"?(Array.isArray(a)?(a.length>0&&(b=v(a[0],0,400,0)),a.length>1&&(c=v(a[1],-50,400,200))):(Object.prototype.hasOwnProperty.call(a,"x")&&(b=v(a.x,0,400,0)),Object.prototype.hasOwnProperty.call(a,"y")&&(c=v(a.y,-50,400,200))),
b=Math.round(b)+","+Math.round(c)):(typeof a==="string"?(a=a.match(/-?\d+(?:\.\d+)?/g))&&a.length>0&&(b=v(a[0],0,400,0),a.length>1&&(c=v(a[1],-50,400,200))):typeof a==="number"&&(c=v(a,-50,400,200)),b=Math.round(b)+","+Math.round(c));return b},coerceBooleanValue:function(a,b){return pa(a,b)},coerceNumberValue:function(a,b){a=Number(a);return isFinite(a)?Math.round(a):b},coerceStringValue:function(a,b){return typeof a==="string"&&a.length>0?a:b},coerceCfgValue:function(a,b){if(!Object.prototype.hasOwnProperty.call(W,
a))return b;var c=W[a];return a==="hp_counter_position"||a==="hp_pulse_text_position"?this.formatPositionValue(b):typeof c==="boolean"?this.coerceBooleanValue(b,c):typeof c==="number"?this.coerceNumberValue(b,c):typeof c==="string"?this.coerceStringValue(b,c):b}};(function(){for(var a in W)Object.prototype.hasOwnProperty.call(W,a)&&(d[a]=W[a])})();Sc();var C={eventChannel:"ClientUI_FireOutput",presetSnapshotMagic:"HP_COLORS_PRESET_SNAPSHOT",presetRequestMagic:"HP_COLORS_PRESET_REQUEST",bulkUpdateMagic:"ANITA_BULK_UPDATE",
singleUpdateMagic:"ANITA_UPDATE",bootstrapRequestMagic:"ANITA_REQUEST_BOOTSTRAP",sharedCfgRawKey:"__hpColorsCfgRaw",sharedDurableCfgRawKey:"__hpColorsDurableCfgRaw",sharedBootstrapSeenKey:"__hpColorsBootstrapSeen",sharedFirstPaintProbeKey:"__hpColorsFirstPaintProbe",sharedPresetRequestKey:"__hpColorsPresetRequests",sharedMatchResetKey:"__hpColorsMatchReset",sharedMatchResetAckKey:"__hpColorsMatchResetAck",getSharedStore:function(){try{if(typeof GameUI!=="undefined"&&GameUI&&GameUI.CustomUIConfig)return GameUI.CustomUIConfig()}catch(a){}return null},
parsePayload:function(a){try{return typeof a==="string"?JSON.parse(a):a}catch(b){}return null},shouldInspectPayload:function(a){return typeof a!=="string"?!0:a.indexOf("ANITA")===-1&&a.indexOf(this.presetSnapshotMagic)===-1?!1:a.indexOf("HP Colors")!==-1},acceptsTitle:function(a){return!(!a||a.mod_title!=="HP Colors")},isBulkUpdate:function(a){return!(!a||a.magic_word!==this.bulkUpdateMagic)},isSingleUpdate:function(a){return!(!a||a.magic_word!==this.singleUpdateMagic)},isPresetSnapshot:function(a){return!(!a||
a.magic_word!==this.presetSnapshotMagic)},isBootstrapReplaySource:function(a){return a==="bridge_bootstrap"||a==="ui_resync"||a==="ui_reset"||a==="ui_code_apply"||a==="baked_preset_apply"||a==="core_auto_resync"||a==="ui_refresh_after_apply"},dispatchPayload:function(a){try{return $.DispatchEvent(this.eventChannel,JSON.stringify(a)),!0}catch(b){}return!1},dispatchRawPayload:function(a){if(!a)return!1;try{return $.DispatchEvent(this.eventChannel,a),!0}catch(b){}return!1},dispatchBootstrapRequest:function(a){return this.dispatchPayload({magic_word:this.bootstrapRequestMagic,
mod_title:"HP Colors",storageNamespace:"hp_colors",reason:String(a||"overlay_request")})},dispatchPresetRequest:function(a){return this.dispatchPayload({magic_word:this.presetRequestMagic,mod_title:"HP Colors",reason:String(a||"overlay_request")})},getPresetRequestState:function(a){if(!a)return null;try{return a[this.sharedPresetRequestKey]||(a[this.sharedPresetRequestKey]={last:0}),a[this.sharedPresetRequestKey]}catch(b){}return null},readSharedConfigRaw:function(a){var b=this.getSharedStore();if(!b)return"";
a=a==="durable_shared"?this.sharedDurableCfgRawKey:this.sharedCfgRawKey;try{return String(b[a]||"")}catch(c){}return""},writeSharedConfigRaw:function(a){var b=this.getSharedStore();if(!b)return!1;try{return b[this.sharedCfgRawKey]=a,!0}catch(c){}return!1},markBootstrapSeen:function(){var a=this.getSharedStore();if(!a)return!1;try{return a[this.sharedBootstrapSeenKey]="1",!0}catch(b){}return!1},hasBootstrapEvidence:function(a){if(!a)return!1;try{return!!(a[this.sharedBootstrapSeenKey]||a[this.sharedDurableCfgRawKey]||
a[this.sharedCfgRawKey])}catch(b){}return!1},getFirstPaintProbeState:function(a){if(!a)return null;try{return a[this.sharedFirstPaintProbeKey]||(a[this.sharedFirstPaintProbeKey]={nextAt:0,waitCount:0}),a[this.sharedFirstPaintProbeKey]}catch(b){}return null},readMatchResetInfo:function(a){if(!a)return null;try{var b=a[this.sharedMatchResetKey];return b?typeof b==="object"?b:{token:String(b),reason:"legacy"}:null}catch(c){}return null},readMatchResetAck:function(a){if(!a)return null;try{return a[this.sharedMatchResetAckKey]||
{}}catch(b){}return null},writeMatchResetAck:function(a,b){if(!a)return!1;try{return a[this.sharedMatchResetAckKey]={token:b,at:Date.now?Date.now():+new Date},!0}catch(c){}return!1},getPresetSnapshotValues:function(a){var b=a&&a.values&&typeof a.values==="object"?a.values:null;if(!b)return null;a=typeof a.values_raw==="string"?a.values_raw:"";if(!a)try{a=JSON.stringify(b)}catch(c){a=""}return{values:b,raw:a}}},ia=!1,vb=!1,Zb=0,lb=!1,Db=!1,Yb=0,Gc=0,da=!0,ya=0,ta=!0,Ja=0,Xb=0,oc=0,Na=0,Ma=!1,pc=0,
Xc=0,rc=0,Fa=null,Za="",dc=0,Bc="",ed=0;$.RegisterForUnhandledEvent(C.eventChannel,function(a){if(C.shouldInspectPayload(a)){var b=C.parsePayload(a);if(C.acceptsTitle(b))if(C.isPresetSnapshot(b))a=C.getPresetSnapshotValues(b),!a||a.raw&&a.raw===Za&&ia||!Pd(a.values,"shared")||!a.raw||(Za=a.raw);else{a=I();a:{var c=C.isBulkUpdate(b),f=C.isSingleUpdate(b);if(c||f){var e=C.isBootstrapReplaySource(String(b.update_source||"")),t=e||!!b.force_emit,F=c?b.values||{}:null,y=f?b.setting_id:"",ea=!1,m=!1,bb=
!1,Ca=!1,x=!1;if(c)for(var M in F){if(Object.prototype.hasOwnProperty.call(F,M)&&(x=!0,Object.prototype.hasOwnProperty.call(W,M)&&(M!=="hp_counter_position"||b.update_source!=="hp_counter_autoposition"))){var Kb=gd.coerceCfgValue(M,F[M]);d[M]!==Kb&&(d[M]=Kb,ea=!0,M.indexOf("hp_friend_")!==0&&(m=!0),qa(M)&&(bb=!0),ic(M)&&(Ca=!0))}}else if(Object.prototype.hasOwnProperty.call(W,y)){if(y==="hp_counter_position"&&b.update_source==="hp_counter_autoposition")break a;M=gd.coerceCfgValue(y,b.value);ea=d[y]!==
M;d[y]=M;ea&&(y.indexOf("hp_friend_")!==0&&(m=!0),qa(y)&&(bb=!0),ic(y)&&(Ca=!0))}if(ea){m&&(da=!0,ya=a+(e?240:80));bb&&(d.hp_friend_enabled?(ta=!0,Ja=e?I()+240:0,ib(H,!1),U(1)):(ta=!1,Ja=0));Ca&&(da=!0,ya=0,Ia=sb=null,S=ha=-1,U(0));Od();if(c||y==="hp_level_number_visible")Ka=null;Ic(f?y:void 0);c?(d.hp_pulse_enabled||g(),ca&&(rb=null,ra=-1,c=I(),u(p(!0,c,jc)))):y!=="hp_pulse_enabled"||d.hp_pulse_enabled?!ca||y!=="hp_pulse_bpm"&&y!=="hp_pulse_intensity"&&y!=="hp_pulse_text_enabled"&&y!=="hp_pulse_text_scale"||
(rb=null,ra=-1,c=I(),u(p(!0,c,jc))):g();e&&Jc(a,!0,!1)}else{if(t||c&&x){try{Hc()}catch(xb){}try{r.invalidateEnemyVisualCaches()}catch(xb){}try{ib(H,!1)}catch(xb){}$b();da=!0;ya=0;ta=!0;Ja=0;Ka=null;yb=S=Oa=ha=-1;Ic();U(0);U(1);U(2)}e&&!ia&&Jc(a,!1,!1)}}}}}});var kb=$.GetContextPanel(),z=null,k=null,O=null,J=null,D=null,T=null,Y=null,h=null,K=null,q=null,E=null,fa=null,ua=null,Ga=null,Eb=0,nb=0,mb=0,Dc=0,Ub=0,Tb=0,Cc=0,ob=null,pb=null,fb=null,gb=null,hb=null,qc=null,Uc=null,Vc=null,Wc=null,Ra=null,
ub={panels:{unitStatus:null,counter:null,counterAnchor:null,background:null,pipLabel:null,baseRedBar:null,baseRedBarParent:null,redBar:null,redBarParent:null,ultIcon:null,killMarker:null,infoHealthContainer:null,healthbarContainer:null,name:null},snapshot:{teamId:0,flags:0,isEnemy:!1,isFriendly:!1,isNeutral:!1,isBuilding:!1,isFriendlyBuilding:!1,isEnemyBuilding:!1,barWidth:0,parentWidth:0,replacedRedBar:!1},sync:function(){var a=this.panels;a.unitStatus=z;a.counter=k;a.counterAnchor=O;a.background=
J;a.pipLabel=D;a.baseRedBar=T;a.baseRedBarParent=Y;a.redBar=h;a.redBarParent=K;a.ultIcon=q;a.killMarker=E;a.infoHealthContainer=fa;a.healthbarContainer=ua;a.name=Ga;a=this.snapshot;a.teamId=ba;a.flags=oa;a.isFriendly=this.isFriendlyTarget(oa);a.isNeutral=!!(oa&2);a.isBuilding=!!(oa&4);a.isFriendlyBuilding=this.isFriendlyBuilding(oa,ba);a.isEnemyBuilding=this.isEnemyBuilding(oa,ba);a.isEnemy=this.isEnemyTarget(oa,ba);a.barWidth=h&&h.actuallayoutwidth!==void 0?h.actuallayoutwidth|0:0;a.parentWidth=
K&&K.actuallayoutwidth!==void 0?K.actuallayoutwidth|0:0;a.replacedRedBar=h!==null&&h!==T;return this},clearPanels:function(){z=k=O=J=D=T=Y=h=K=q=E=fa=ua=Ga=null;return this.sync()},resetProbeState:function(){mb=nb=Eb=0},resetPanelHistory:function(){Oc=kd=ld=md=nd=od=pd=null;Wb=""},invalidateIfInvalid:function(){if(!Eb&&!h||!(Ha(z)||Ha(k)||Ha(J)||Ha(D)||Ha(T)||Ha(Y)||Ha(h)||Ha(K)||Ha(Ga)))return!1;this.clearPanels();this.resetProbeState();this.resetPanelHistory();r.invalidateEnemyVisualCaches();ta=
da=!0;$b();return!0},refreshEnemy:function(a){var b=!1;this.invalidateIfInvalid();if(w(h))b=this.refreshCurrentRedBar(a,!1);else{if(!Dc||a>=Dc)Dc=(h=yc())?0:a+150;if(!h)return this.sync(),!1}if(!Eb&&!je())return this.sync(),!1;if(h.GetParent){var c=h.GetParent();K!==c&&(K=c)}b||this.refreshCurrentRedBar(a,!1);Hc();this.scanEnemy(h);this.sync();return!0},refreshCurrentRedBar:function(a,b){var c=Cc&&a<=Cc,f=!1;if(b){var e=yc();w(e)&&e!==h&&(f=this.adoptRedBar(e))}else if(!Ub||a>=Ub){Ub=a+(c?180:X>=
12?2500:X>=4?1800:ka>=8?2500:ka>=3?1800:1200);e=0;if(w(h)&&K&&K.Children)try{for(var t=K.Children(),F=0;F<t.length;F++){var y=t[F];if(w(y)){var ea="";try{ea=String(y.id||"")}catch(m){ea=""}if(ea==="unit_healthbar_lagging"&&++e>1)break}}}catch(m){}if(!w(h)||e<=1)e=yc(),w(e)&&e!==h&&(f=this.adoptRedBar(e))}if(f)return!0;if(!b){if(Tb&&a<Tb)return!1;Tb=a+(c?180:X>=12?2500:X>=4?1800:ka>=10?1400:ka>=4?1300:1200)}if(!K||!K.Children)return!1;a=[];try{a=K.Children()}catch(m){return!1}b=h;c=this.scoreRedBarCandidate(h,
-1);for(f=0;f<a.length;f++)if(e=a[f],w(e)){t="";try{t=String(e.id||"")}catch(m){t=""}if(t==="unit_healthbar_lagging"){t=this.scoreRedBarCandidate(e,f);if(Pc)try{Pc.set(e,1)}catch(m){}t>c&&(b=e,c=t)}}return b&&b!==h?this.adoptRedBar(b):!1},scoreRedBarCandidate:function(a,b){if(!w(a))return-1;var c=a===h?100:0;try{(Pc?Pc.has(a):a===h||a===Oc)||(c+=1E3)}catch(t){}var f=0;try{f=hd(a,!1)}catch(t){f=0}f&=Kc;f&1&&(c+=90);f&8&&(c-=1200);f&2&&(c-=1E3);f&4&&d.hp_skip_buildings&&(c-=400);try{(a.actuallayoutwidth|
0)>0&&(c+=20)}catch(t){}try{var e=a.GetParent?a.GetParent():null;e&&(e.actuallayoutwidth|0)>0&&(c+=10)}catch(t){}b>=0&&(c+=Math.min(b,20));return c},resetEnemyScanCache:function(){rd=oa=ba=0;sd=null},adoptRedBar:function(a){Y=K=(T=h=a)&&a.GetParent?a.GetParent():null;this.resetProbeState();this.resetEnemyScanCache();Hc();S=Oa=ha=-1;ka=0;yb=-1;r.resetStyleDriftBackoff();this.sync();return!0},scanEnemy:function(a){var b=I();if(a===sd&&b-rd<le)return!1;var c=hd(a,!1);ba=c>>Rd&3;oa=c&Kc;ba&&oa&8&&(Td=
ba);rd=b;sd=a;return!0},isFriendlyTarget:function(a){return!!(a&8)},isFriendlyBuilding:function(a,b){b=b||ba;return!!(a&4&&(a&8||b&&b===Td))},isEnemyBuilding:function(a,b){b=b||ba;return!(!(a&4)||a&2||!b||this.isFriendlyBuilding(a,b))},isEnemyTarget:function(a,b){return a&2||d.hp_friend_enabled&&this.isFriendlyTarget(a)?!1:a&1?!0:this.isEnemyBuilding(a,b)},getIgnoredTargetColor:function(a){var b=a?a.flags:oa;a=a?a.teamId:ba;return b&1&&!(b&2)?"":this.isEnemyBuilding(b,a)?"#E16161":this.isFriendlyBuilding(b,
a)?"#ffffff":b&6?"#5BEFB5":b&8?"#FFEFD7":a===2?"#5B79E6":a===1?"#E7B659":"#E16161"}},Pc=typeof WeakMap==="function"?new WeakMap:null,ba=0,oa=0,Td=0,rd=0,sd=null,le=500,Rd=4,Kc=15,sa=null,R=null,wa=null,sb=null,Ia=null,tb=null,id=null,Lb=-1,Mb=-1,cc=null,vc=null,wc=0,Ba=!1,Oc=null,kd=null,ld=null,md=null,nd=null,od=null,pd=null,Wb="",ma=0,tc=0,yb=-1,nc="",r={setBarColor:function(a){if(sb!==a||sa===null)if(sb=a,(a=ja(a))||(a=""),sa!==a&&h)try{sa=h.style.washColor=a}catch(b){sa=null}},clearUltIconColor:function(){Ia=
null;if(!(q&&q.IsValid&&q.IsValid()&&q.style))R=null;else if(R!=="")try{R=q.style.washColor=""}catch(a){R=null}},setUltColor:function(a){a=d.hp_ult_color_enabled?a:d.hp_ult_color_custom;if(Ia!==a||!R){Ia=a;a=ja(a)||"#E16161";if(!q||!q.IsValid()){var b=I();if(dc&&b-dc<2E3)return;if((q=kb.FindChildTraverse("unit_ult_ready_icon"))&&q.IsValid())dc=0;else{dc=b;return}}if(q&&q.style&&R!==a)try{R=q.style.washColor=a}catch(c){R=null}}},setTextColor:function(a){if(tb!==a||!wa)if(tb=a,a=ja(a),k&&k.style&&wa!==
a)try{wa=k.style.washColor=a}catch(b){wa=null}},setBarVisible:function(a){J&&J.style&&(ob!=="visible"&&(ob=J.style.visibility="visible"),a=a?"1.0":"0.01",pb!==a&&(pb=J.style.opacity=a))},invalidateEnemyVisualCaches:function(){Fb=Mc=Nc=jd=fc=Lc=ob=pb=fb=gb=hb=qc=Uc=Vc=Wc=Ra=sb=Ia=tb=id=sa=R=wa=null;Mb=Lb=-1;cc=null;ka=za=Aa=X=0;this.resetStyleDriftBackoff()},hasEnemyBarStyleDrift:function(){if(!h||!h.style||!sa)return!1;try{return ja(String(h.style.washColor||""))!==sa}catch(a){}return!1},hasEnemyStyleDrift:function(){if(this.hasEnemyBarStyleDrift())return!0;
if(d.hp_counter_visible&&k&&k.style){try{if(fb!==null&&k.style.fontSize!==fb)return!0}catch(a){}try{if(gb!==null&&k.style.height!==gb)return!0}catch(a){}}if(d.hp_counter_visible&&O&&O.style)try{if(hb!==null&&O.style.transform!==hb)return!0}catch(a){}return!1},resetStyleDriftBackoff:function(){Xc=rc=0}},Ec=null,Fc=0,Vb=0,ke=160,Fb=null,Mc=null,Nc=null,jd=null,fc=null,Lc=null,sc=0,ha=-1,Oa=-1,S=-1,Bb=-1,Pa=0,X=0,Aa=0,za=0,ka=0,V={hasBarVisible:!1,barVisible:!1,barColor:"",ultColor:"",textColor:"",nextDelay:.15,
clearPulse:!1,stopAfterApply:!1,hasPipVisible:!1,pipVisible:"",counterAction:0,counterCurrent:0,counterMax:0,counterLowMode:!1,killMarkerAction:0,killMarkerParentWidth:0,killMarkerX:"",killMarkerWidth:"",killMarkerColor:"",killMarkerSig:""},he=[11,19,27,35],dd=["level_tier2","level_tier3","level_tier4","level_tier5"],Ld="level_number_visible",Ya=null,aa=null,Q=null,Ac=-1,Ka=null,fe={label:null,container:null,wrapper:null,level:0,ready:!1},ge={visible:!1,tierClass:"",changed:!1},Sb=0;wb();Ic();bc()})();
