const assert = require("node:assert/strict");
const test = require("node:test");

const { getValidationReport } = require("./validate-minimal.js");

test("minimal hp_colors source keeps only static builder-preset runtime assets", () => {
  const report = getValidationReport();

  assert.deepEqual(report.errors, []);
  assert.ok(report.unitStatusXml.includes("healthbar_logic.vjs_c"));
  assert.ok(report.bootstrapSource.includes("HPColorsPresetStore"));
  assert.ok(report.bootstrapSource.includes("__hpColorsCfgRaw"));
  assert.ok(report.bootstrapSource.includes("HP_COLORS_PRESET_SNAPSHOT"));
  assert.ok(report.bootstrapSource.includes("HP_COLORS_PRESET_REQUEST"));
  assert.ok(report.bootstrapSource.includes("capturePreset"));
  assert.ok(report.bootstrapSource.includes("publishPreset"));
  assert.ok(report.bootstrapSource.includes("publishUntilReady"));
  assert.ok(report.bootstrapSource.includes("cachedSnapshotPayload"));
  assert.ok(report.bootstrapSource.includes("sharedSnapshotWritten"));
  assert.ok(report.bootstrapSource.includes("cachedReplayStarted"));
  assert.ok(report.bootstrapSource.includes("cachedReplayCount"));
  assert.ok(report.bootstrapSource.includes("values_raw"));
  assert.ok(report.bootstrapSource.includes("PUBLISH_RETRY_DELAYS"));
  assert.ok(report.bootstrapSource.includes("CACHED_SNAPSHOT_REPLAY_SEC"));
  assert.ok(report.bootstrapSource.includes("CACHED_SNAPSHOT_REPLAY_LIMIT"));
  assert.ok(report.bootstrapSource.includes("cachedReplayCount >= CACHED_SNAPSHOT_REPLAY_LIMIT"));
  assert.ok(report.bootstrapSource.includes("cachedRootPanel"));
  assert.ok(report.bootstrapSource.includes("cachedStorePanel"));
  assert.ok(report.bootstrapSource.includes("replayCachedSnapshot"));
  assert.ok(report.bootstrapSource.includes("startCachedSnapshotReplay"));
  assert.ok(report.bootstrapSource.includes("$.Schedule(CACHED_SNAPSHOT_REPLAY_SEC, replayCachedSnapshot)"));
  assert.ok(!report.bootstrapSource.includes("PUBLISH_HEARTBEAT_SEC"));
  assert.ok(!report.bootstrapSource.includes("publishHeartbeat"));
  assert.ok(report.bootstrapSource.includes("GameUI.CustomUIConfig"));
  assert.ok(report.healthbarSource.includes("tryApplySharedSnapshot"));
  assert.ok(report.healthbarSource.includes("schedulePresetRetry"));
  assert.ok(report.healthbarSource.includes("HP_COLORS_PRESET_SNAPSHOT"));
  assert.ok(report.healthbarSource.includes("HP_COLORS_PRESET_REQUEST"));
  assert.ok(report.healthbarSource.includes("values_raw"));
  assert.ok(report.healthbarSource.includes("raw === sharedCfgRaw && presetApplied"));
  assert.ok(report.healthbarSource.includes("invalidateEnemyVisualCaches"));
  assert.ok(report.healthbarSource.includes("resetCachedPanelRefsIfInvalid"));
  assert.ok(report.healthbarSource.includes("lastEnemySignature"));
  assert.ok(report.healthbarSource.includes("lastCpPanel"));
  assert.ok(report.healthbarSource.includes("lastUnitName"));
  assert.ok(report.healthbarSource.includes("wasDirty"));
  assert.ok(report.healthbarSource.includes("startEnemyLoop"));
  assert.ok(report.healthbarSource.includes("stopEnemyLoop"));
  assert.ok(report.healthbarSource.includes("startAllyLoop"));
  assert.ok(report.healthbarSource.includes("stopAllyLoop"));
  assert.ok(report.healthbarSource.includes("startLevelLoop"));
  assert.ok(report.healthbarSource.includes("stopLevelLoop"));
  assert.ok(report.healthbarSource.includes("handleRuntimeToggleState"));
  assert.ok(report.healthbarSource.includes("nextCacheProbeAt"));
  assert.ok(report.healthbarSource.includes("ALLY_SCAN_CACHE_TTL"));
  assert.ok(report.healthbarSource.includes("STYLE_REAPPLY_WATCHDOG_MS"));
  assert.ok(!report.healthbarSource.includes("STYLE_REAPPLY_MS = 1000"));
  assert.ok(report.healthbarSource.includes("function refreshDerivedConfig()"));
  assert.ok(report.healthbarSource.includes("var dc = {}"));
  assert.ok(report.healthbarSource.includes("dc.low"));
  assert.ok(report.healthbarSource.includes("dc.counterPosition"));
  assert.ok(report.healthbarSource.includes("dc.killZoneThreshold"));
  assert.ok(report.healthbarSource.includes("refreshDerivedConfig();"));
  assert.ok(report.healthbarSource.includes("var shouldPulse = !!(cfg.hp_pulse_enabled && hp <= pulseThresh)"));
  assert.ok(report.healthbarSource.includes("uHT(hp, 100, shouldPulse)"));
  assert.ok(report.healthbarSource.includes("if (cfg.hp_kill_zone_enabled) sKZ(true, pw)"));
  assert.ok(!report.healthbarSource.includes("gRunning = true; gL()"));
  assert.ok(!report.healthbarSource.includes("aRunning = true; aL()"));
  assert.ok(!report.healthbarSource.includes("lL();"));
  assert.ok(report.files.includes("panorama/scripts/anita_ui_core.js"));
  assert.ok(!report.files.includes("panorama/scripts/anita_persist_loader.js"));
  assert.ok(!report.files.includes("panorama/scripts/hp_registrar.js"));
  assert.ok(!report.files.includes("panorama/styles/anita_ui.css"));
  assert.ok(!report.files.includes("panorama/layout/base_hud.xml"));
  assert.ok(!report.bootstrapSource.includes("ANITA_"));
  assert.ok(!report.healthbarSource.includes("ANITA_"));
  assert.ok(!report.healthbarSource.includes("deadlock_hero_debuts_seen"));
  assert.ok(!report.healthbarSource.includes("GameInterfaceAPI"));
  assert.ok(!report.bootstrapSource.includes("AnitaUI_Window"));
  assert.ok(!report.bootstrapSource.includes("colorpicker"));
  assert.equal(report.defaultKeys.length, 45);
});
