(()=>{function z(a){return a?a.toString().toLowerCase().replace(/[^a-z0-9]+/g," ").replace(/\s+/g," ").trim():""}function A(a){return a?(a=a.toString().match(/\d+/g))?parseInt(a.join(""),10)||0:0:0}function k(a,b,c){if(a){var d="_rpStyle_"+b;a[d]!==c&&(a.style[b]=c,a[d]=c)}}function C(a,b){a&&(k(a,"color",b),k(a,"washColor",b),k(a,"fontSize","16px"),k(a,"fontWeight","bold"),k(a,"verticalAlign","center"))}function q(a,b,c,d){var f=b[c];if(f&&f.IsValid())return f;b[c]=a.FindChildTraverse(d);return b[c]}
function x(a){var b=a.o||(a.o={});q(a,b,"cost","ModCost");q(a,b,"name","ModName");return b}function D(a){var b=x(a);q(a,b,"deficit","RecentPurchaseDeficitLabel");q(a,b,"divider","RecentPurchaseCostDivider");q(a,b,"goldIcon","goldIcon");return b}function E(a,b,c){var d={},f=0;for(var e=0;e<a.length;e++){var h=a[e];h.g=h.l;h.key&&(d[h.key]||(d[h.key]=[])).push({v:e,j:h.l,m:!1})}for(e=0;e<a.length;e++)if(h=F[a[e].key])for(let g=0;g<h.length;g++){let p=d[h[g]];if(p)for(let m=0;m<p.length;m++){let y=p[m];
if(!(y.m||y.v>=e)){a[e].g-=y.j;y.m=!0;break}}}for(d=0;d<a.length;d++)e=a[d],e.g<0&&(e.g=0),f+=e.g,b>=e.g?(e.rem=0,b-=e.g):(e.rem=e.g-b,b=0);a=f-c;return a<0?0:a}function L(a){for(let d=0;d<a.length;d++){let f=a[d];if(!f.h)continue;let e=f.rem,h=e>0;var b=D(f.h);let g=b.F,p=String(Math.max(0,e|0)).replace(/\B(?=(\d{3})+(?!\d))/g,",");if(g){var c=h?"-"+p:"0";g._rpText!==c&&(g.text=c,g._rpText=c);C(g,h?"#d64259":"#66ffd9")}C(b.G,"#d8d0c088");c=b.j;b=b.J;c&&(h?(k(c,"color","#d64259"),k(b,"washColor",
"#d64259")):(k(c,"color","#66ffd9"),k(b,"washColor","#66ffd9")));let m=h?"Need "+p+" more for "+(f.name||"item"):"";g&&(e>0?g._lastChatMsg!==m&&(g._lastChatMsg=m,g.SetPanelEvent("onactivate",()=>{l.send(m,Date.now())})):g._lastChatMsg&&(g._lastChatMsg=null,g.SetPanelEvent("onactivate",()=>{})))}}function G(a){for(;a?.GetParent?.();)a=a.GetParent();return a}function M(a){var b=H();try{$.DispatchEvent("CitadelChatInputBlur",a)}catch{}try{$.DispatchEvent("DropInputFocus",a)}catch{}if(b?.IsValid?.()){try{$.DispatchEvent("CitadelChatInputBlur",
b)}catch{}try{$.DispatchEvent("DropInputFocus",b)}catch{}}$.Schedule(0,()=>{try{$.DispatchEvent("CitadelChatInputBlur",a)}catch{}})}function H(){if(r.h?.IsValid?.())return r.h;var a=G($.GetContextPanel()).FindChildTraverse("Chat");return a?.IsValid?.()?r.h=a:null}function I(a,b){var c=r[a];if(c?.IsValid?.())return c;c=H();if(!c)return null;b=(c=c.FindChildTraverse("ChatControls"))?c.FindChildTraverse(b):null;b?.IsValid?.()&&(r[a]=b);return b}function J(){var a=$.GetContextPanel();if(a&&(n&&n.IsValid()||
(n=a.FindChildTraverse("RecentPurchaseTotalCostLabel")),t&&t.IsValid()||(t=a.FindChildTraverse("QuickbuyQueue")),u&&u.IsValid()||(u=a.FindChildTraverse("QuickbuySellQueue")),n)){var b=[];if(t)for(a=[t];a.length;){var c=a.pop();if(c.BHasClass&&c.BHasClass("QuickbuyItem")){var d=x(c),f=d.j;d=d.name;b.push({h:c,key:z(d?d.text:""),name:d?d.text:"",l:A(f?f.text:"")});continue}f=c.GetChildCount();for(--f;f>=0;f--)a.push(c.GetChild(f))}a=b;v&&v.IsValid()||(v=(b=G($.GetContextPanel()).FindChildTraverse("CurrentGoldAmount"))?
b.FindChildTraverse("hudCurGoldLabel"):null);b=v?A(v.text):0;f=0;if(u)for(c=[u];c.length;){d=c.pop();if(d.BHasClass&&d.BHasClass("QuickbuyItem")){d=x(d).j;f+=Math.floor(A(d?d.text:"")/2);continue}var e=d.GetChildCount();for(--e;e>=0;e--)c.push(d.GetChild(e))}c=f;b=E(a,b,c);b=String(b);n._rpText!==b&&(n.text=b,n._rpText=b);L(a)}$.Schedule(.05,J)}var B={"Aerial Supremacy":["Stamina Mastery"],"Apex Combat":["Ricochet"],"Arcane Surge":["Extra Stamina"],"Arctic Blast":["Cold Front"],"Armor Piercing Rounds":["High-Velocity Rounds"],
"Ballistic Enchantment":["Mystic Expansion"],"Boundless Spirit":["Improved Spirit"],"Burst Fire":["Rapid Rounds"],Capacitor:["Tesla Bullets"],Colossus:["Extra Health"],"Crippling Headshot":["Weakening Headshot"],"Crushing Fists":["Melee Charge"],"Cultist Sacrifice":["Monster Rounds"],"Disarming Hex":["Rusted Barrel"],"Divine Barrier":["Guardian Ward"],"Enduring Speed":["Sprint Boots"],"Escalating Exposure":["Mystic Vulnerability"],"Escalating Resilience":["Extended Magazine"],"Express Shot":["High-Velocity Rounds"],
"Focus Lens":["Spirit Sap"],Fortitude:["Extra Health"],"Fury Trance":["Bullet Lifesteal"],"Greater Expansion":["Mystic Expansion"],"Guardian Ward":["Grit"],Headhunter:["Headshot Booster"],"Healing Booster":["Extra Regen"],"Healing Nova":["Healing Rite"],"Healing Tempo":["Healing Booster"],"Improved Spirit":["Extra Spirit"],Indomitable:["Reactive Barrier"],Infuser:["Spirit Lifesteal"],Juggernaut:["Enduring Speed"],"Kinetic Dash":["Extra Stamina"],Leech:["Bullet Lifesteal","Spirit Lifesteal"],Lifestrike:["Melee Lifesteal"],
"Lightning Scroll":["Mystic Slow"],"Mercurial Magnum":["Quicksilver Reload"],"Opening Rounds":["High-Velocity Rounds"],"Point Blank":["Close Quarters"],"Radiant Regeneration":["Mystic Regeneration"],"Rapid Recharge":["Extra Charge"],"Reactive Barrier":["Grit"],"Rescue Beam":["Healing Rite"],Sharpshooter:["Long Range","High-Velocity Rounds"],Spellbreaker:["Debuff Reducer"],"Spirit Rend":["Spirit Shredder Bullets"],"Spirit Snatch":["Spirit Strike"],"Spiritual Overflow":["Spirit Lifesteal"],"Spirit Shielding":["Grit"],
"Stamina Mastery":["Extra Stamina"],"Superior Cooldown":["Compress Cooldown"],"Superior Duration":["Duration Extender"],"Surge of Power":["Extra Spirit"],"Swift Striker":["Rapid Rounds"],Tankbuster:["Mystic Burst"],"Titanic Magazine":["Extended Magazine"],"Timeless Emblem":["Transcendent Cooldown"],"Transcendent Cooldown":["Superior Cooldown"],"Trophy Collector":["Sprint Boots"],Unstoppable:["Debuff Reducer"],"Vampiric Burst":["Bullet Lifesteal"],"Veil Walker":["Sprint Boots"],"Vortex Web":["Slowing Hex"],
"Weighted Shots":["Slowing Bullets"],"Weapon Shielding":["Grit"]},F={},K=0,r={h:null,input:null,K:null},w=[0,.008,.012,.016,.032],l={B:function(a){return String(a||"").replace(/["\r\n;]/g," ").replace(/\s+/g," ").trim()},u:function(a,b,c){return Number(a)-Number(b||0)>=Number(c||0)},A:function(a){return a?.IsValid?.()?(a=String(a.text||"").trim())&&a!=="#citadel_chat_placeholder"?a!=="To (ALL):"&&a.indexOf("(ALL)")===-1:!1:!1},submit:function(a,b){try{a.text=b;$.DispatchEvent("CitadelChatInputSubmitted",
a);a.text="";var c=!0}catch{c=!1}if(c)return!0;try{$.DispatchEvent("SetInputFocus",a)}catch{}try{a.text=b,$.DispatchEvent("CitadelChatInputSubmitted",a),a.text=""}finally{M(a)}return!0},retry:function(a,b,c){var d=I("input","ChatInput"),f=I("targetLabel","ChatTargetLabel");l.A(f)&&d?.IsValid?.()?c<1&&b<w.length-1?$.Schedule(w[b+1],()=>l.retry(a,b+1,c+1)):l.submit(d,a):b>=w.length-1||$.Schedule(w[b+1],()=>l.retry(a,b+1,0))},send:function(a,b){if(!l.u(b,K,1E3))return!1;var c=l.B(a);if(!c)return!1;K=
b;try{$.DispatchEvent("CitadelConCommand","say_chat_team")}catch{}$.Schedule(w[0],()=>l.retry(c,0,0));return!0}},n=null,v=null,t=null,u=null;typeof module!=="undefined"&&module&&module.exports&&(module.exports.i=module.exports.i||{},module.exports.i.C=l,module.exports.i.D=E,module.exports.i.H=x,module.exports.i.I=D);(function(){for(let a in B)B.hasOwnProperty(a)&&(F[z(a)]=B[a].map(z))})();$.Schedule(0,J)})();
