(()=>{function v(a){return a?a.toString().toLowerCase().replace(/[^a-z0-9]+/g," ").replace(/\s+/g," ").trim():""}function w(a){return a?(a=a.toString().match(/\d+/g))?parseInt(a.join(""),10)||0:0:0}function k(a,b,e){if(a){var c="_rpStyle_"+b;a[c]!==e&&(a.style[b]=e,a[c]=e)}}function z(a,b){a&&(k(a,"color",b),k(a,"washColor",b),k(a,"fontSize","16px"),k(a,"fontWeight","bold"),k(a,"verticalAlign","center"))}function G(a){for(let e=0;e<a.length;e++){let c=a[e];if(!c.g)continue;let g=c.rem,d=g>0,f=c.g.FindChildTraverse("RecentPurchaseDeficitLabel"),
m=String(Math.max(0,g|0)).replace(/\B(?=(\d{3})+(?!\d))/g,",");if(f){var b=d?"-"+m:"0";f._rpText!==b&&(f.text=b,f._rpText=b);z(f,d?"#d64259":"#66ffd9")}b=c.g.FindChildTraverse("RecentPurchaseCostDivider");z(b,"#d8d0c088");b=c.g.FindChildTraverse("ModCost");let n=c.g.FindChildTraverse("goldIcon");b&&(d?(k(b,"color","#d64259"),k(n,"washColor","#d64259")):(k(b,"color","#66ffd9"),k(n,"washColor","#66ffd9")));let l=d?"Need "+m+" more for "+(c.name||"item"):"";f&&(g>0?f._lastChatMsg!==l&&(f._lastChatMsg=
l,f.SetPanelEvent("onactivate",()=>H(l))):f._lastChatMsg&&(f._lastChatMsg=null,f.SetPanelEvent("onactivate",()=>{})))}}function A(a){for(;a?.GetParent?.();)a=a.GetParent();return a}function H(a){var b=Date.now();if(!(b-B<1E3)&&(B=b,a)){var e=String(a).replace(/["\r\n;]/g," ").trim();if(e){try{$.DispatchEvent("CitadelConCommand","say_chat_team")}catch{}$.Schedule(p[0],()=>x(e,0,0))}}}function x(a,b,e){var c=I(),g=J();if(K(c,g))if(e<1&&b<p.length-1)$.Schedule(p[b+1],()=>x(a,b+1,e+1));else{try{c.text=
a;$.DispatchEvent("CitadelChatInputSubmitted",c);c.text="";var d=!0}catch{d=!1}d?C(c):L(c,a)}else b>=p.length-1||$.Schedule(p[b+1],()=>x(a,b+1,0))}function K(a,b){return a?.IsValid?.()&&b?.IsValid?.()?(a=String(b.text||"").trim())&&a!=="#citadel_chat_placeholder"?a!=="To (ALL):"&&a.indexOf("(ALL)")===-1:!1:!1}function L(a,b){try{$.DispatchEvent("SetInputFocus",a)}catch{}try{a.text=b,$.DispatchEvent("CitadelChatInputSubmitted",a),a.text=""}finally{C(a)}}function C(a){var b=D();try{$.DispatchEvent("CitadelChatInputBlur",
a)}catch{}try{$.DispatchEvent("DropInputFocus",a)}catch{}if(b?.IsValid?.()){try{$.DispatchEvent("CitadelChatInputBlur",b)}catch{}try{$.DispatchEvent("DropInputFocus",b)}catch{}}$.Schedule(0,()=>{try{$.DispatchEvent("CitadelChatInputBlur",a)}catch{}})}function D(){if(h.g?.IsValid?.())return h.g;var a=A($.GetContextPanel());if(!a?.IsValid?.())return null;a=a.FindChildTraverse("Chat");return a?.IsValid?.()?h.g=a:null}function I(){if(h.input?.IsValid?.())return h.input;var a=A($.GetContextPanel());if(!a?.IsValid?.())return null;
var b=h.g?.IsValid?.()?h.g:a.FindChildTraverse("Chat");if(b?.IsValid?.()){let e=b.FindChildTraverse("ChatControls")?.FindChildTraverse?.("ChatInput")||b.FindChildTraverse("ChatInput");if(e?.IsValid?.())return h.g=b,h.input=e}a=a.FindChildTraverse("ChatInput");return a?.IsValid?.()?h.input=a:null}function J(){if(h.i?.IsValid?.())return h.i;var a=h.g?.IsValid?.()?h.g:D();if(!a?.IsValid?.())return null;a=a.FindChildTraverse("ChatControls")?.FindChildTraverse?.("ChatTargetLabel")||a.FindChildTraverse("ChatTargetLabel");
return a?.IsValid?.()?h.i=a:null}function E(){var a=$.GetContextPanel();if(a&&(q&&q.IsValid()||(q=a.FindChildTraverse("RecentPurchaseTotalCostLabel")),r&&r.IsValid()||(r=a.FindChildTraverse("QuickbuyQueue")),t&&t.IsValid()||(t=a.FindChildTraverse("QuickbuySellQueue")),q)){var b=[];if(r)for(a=[r];a.length;){var e=a.pop();if(e.BHasClass&&e.BHasClass("QuickbuyItem")){var c=e.FindChildTraverse("ModCost"),g=e.FindChildTraverse("ModName");b.push({g:e,key:v(g?g.text:""),name:g?g.text:"",j:w(c?c.text:"")});
continue}c=e.GetChildCount();for(--c;c>=0;c--)a.push(e.GetChild(c))}a=b;b:{for(b=$.GetContextPanel();b;){if(e=b.FindChildTraverse("CurrentGoldAmount")){b=e;break b}if(!b.GetParent)break;b=b.GetParent()}b=null}b=b?(b=b.FindChildTraverse("hudCurGoldLabel"))?w(b.text):0:0;g=b;e=0;if(t)for(b=[t];b.length;){c=b.pop();if(c.BHasClass&&c.BHasClass("QuickbuyItem")){c=c.FindChildTraverse("ModCost");e+=Math.floor(w(c?c.text:"")/2);continue}var d=c.GetChildCount();for(--d;d>=0;d--)b.push(c.GetChild(d))}b=e;c=
{};e=0;g+=b;for(d=0;d<a.length;d++){var f=a[d];f.h=f.j;f.key&&(c[f.key]||(c[f.key]=[])).push({o:d,m:f.j,l:!1})}for(d=0;d<a.length;d++)if(f=F[a[d].key])for(let m=0;m<f.length;m++){let n=c[f[m]];if(n)for(let l=0;l<n.length;l++){let u=n[l];if(!(u.l||u.o>=d)){a[d].h-=u.m;u.l=!0;break}}}c=g;for(g=0;g<a.length;g++)d=a[g],d.h<0&&(d.h=0),e+=d.h,c>=d.h?(d.rem=0,c-=d.h):(d.rem=d.h-c,c=0);b=e-b;q.text=String(b<0?0:b);G(a)}$.Schedule(.05,E)}var y={"Arcane Surge":["Extra Stamina"],"Arctic Blast":["Cold Front"],
"Armor Piercing Rounds":["High Velocity Rounds"],"Boundless Spirit":["Improved Spirit"],"Burst Fire":["Rapid Rounds"],Capacitor:["Tesla Bullets"],Colossus:["Extra Health"],"Crippling Headshot":["Weakening Headshot"],"Crushing Fists":["Melee Charge"],"Cultist Sacrifice":["Monster Rounds"],"Disarming Hex":["Rusted Barrel"],"Divine Barrier":["Guardian Ward"],"Enduring Speed":["Sprint Boots"],"Escalating Exposure":["Mystic Vulnerability"],"Escalating Resilience":["Extended Magazine"],"Express Shot":["High Velocity Rounds"],
"Focus Lens":["Spirit Sap"],Fortitude:["Extra Health"],"Fury Trance":["Bullet Lifesteal"],"Greater Expansion":["Mystic Expansion"],Headhunter:["Headshot Booster"],"Healing Booster":["Extra Regen"],"Healing Nova":["Healing Rite"],"Healing Tempo":["Healing Booster"],"Improved Spirit":["Extra Spirit"],Infuser:["Spirit Lifesteal"],Juggernaut:["Enduring Speed"],"Kinetic Dash":["Extra Stamina"],Leech:["Bullet Lifesteal","Spirit Lifesteal"],Lifestrike:["Melee Lifesteal"],"Lightning Scroll":["Mystic Slow"],
"Mercurial Magnum":["Quicksilver Reload"],"Point Blank":["Close Quarters"],"Radiant Regeneration":["Mystic Regeneration"],"Rapid Recharge":["Extra Charge"],"Rescue Beam":["Healing Rite"],Sharpshooter:["Long Range"],Spellbreaker:["Debuff Reducer"],"Spirit Rend":["Spirit Shredder Bullets"],"Spirit Snatch":["Spirit Strike"],"Stamina Mastery":["Extra Stamina"],"Superior Cooldown":["Compress Cooldown"],"Superior Duration":["Duration Extender"],"Surge of Power":["Extra Spirit"],"Swift Striker":["Rapid Rounds"],
Tankbuster:["Mystic Burst"],"Titanic Magazine":["Extended Magazine"],"Transcendent Cooldown":["Superior Cooldown"],"Trophy Collector":["Sprint Boots"],Unstoppable:["Debuff Reducer"],"Vampiric Burst":["Bullet Lifesteal"],"Vortex Web":["Slowing Hex"],"Weighted Shots":["Slowing Bullets"]},F={},B=0,h={g:null,input:null,i:null},p=[0,.008,.012,.016,.032],q=null,r=null,t=null;(function(){for(let a in y)y.hasOwnProperty(a)&&(F[v(a)]=y[a].map(v))})();$.Schedule(0,E)})();
